### ISSUE TITLE
Problems with transaction in Execute.WithConnection

### ISSUE THREAD

**Issue by rhegner** [fluentmigrator/fluentmigrator#1001]
I tried the following for reading data from the database during a migration:

    Execute.WithConnection((connection, transaction) => {
        using (var cmd = connection.CreateCommand())
        {
            cmd.Transaction = transaction;
            cmd.CommandText = "...";
            using (var reader = cmd.ExecuteReader())
            {
                while (reader.Read())
                    // do something with the data
            }
        }
    });

With this code, `ExecuteReader()` fails with the following exception:

> System.InvalidOperationException: 'The transaction associated with this command is not the connection's active transaction; see https://fl.vu/mysql-trans'
 
Note that I'm using [MySqlConnector](https://mysql-net.github.io/MySqlConnector/) which, according to the link in the error message, requires the transaction to be set explicitly on the command. As you can see in the code, I do set the transaction, but the transaction I get from fluentmigrator turns out to be null.

Next, I tried to create my own transaction which I can provide to the command, like this:

    Execute.WithConnection((connection, transaction) => {
        using (var tr = connection.BeginTransaction())
        using (var cmd = connection.CreateCommand())
        {
            cmd.Transaction = tr;
            cmd.CommandText = "...";
            using (var reader = cmd.ExecuteReader())
            {
                while (reader.Read())
                    // do something with the data
            }
            tr.Commit();
        }
    });

This doesn't work either - `BeginTransaction()` fails with:

> System.InvalidOperationException: 'Transactions may not be nested.'

So... apparently, there is an active transaction already, but fluentmigrator does not make it available to me (`transaction` parameter is null). It looks to me like this is a problem in fluentmigrator.

**Comment by rhegner** [comment]
Note that MySqlConnector offers a `IgnoreCommandTransaction=true` option as a workaround. But this does not work in our case, because customer does provide the connection string to our software. So we need to have a solution which does not involve modifying the connection string.

I came up with the following workaround, which seems to work. In the `WithConnection` action I do the following:

    if ((transaction == null) && (connection is MySqlConnection))
    {
        var property = typeof(MySqlConnection).GetProperty("CurrentTransaction", BindingFlags.NonPublic | BindingFlags.Instance);
        transaction = (IDbTransaction)property.GetValue(connection);
    }

This is really ugly, and I hope there will be a better solution (FluentMigrator providing access to the current transaction) before we release the next version of our software.

**Comment by fubar-coder** [comment]
This sounds indeed like a bug. How did you configure the migration runner?

You can use the following `MigrationAttribute` as workaround:

```csharp
[Migration(1234, TransactionBehavior.None)]
```

This disables FluentMigrators own transaction for this migration and you can use your own transaction.

**Comment by rhegner** [comment]
Thanks for your quick response. Your workaround is much cleaner, and it works fine.

Here's how I configure the migration runner:

    var migrationServiceProvider = new ServiceCollection()
        .AddFluentMigratorCore()
        .ConfigureRunner(rb => {
            dbProvider.AddMigrationProcessor(rb);
            rb.WithGlobalConnectionString(connectionString);
            rb.ScanIn(typeof(IDatabaseProvider).Assembly).For.Migrations().For.VersionTableMetaData();
        })
        .AddLogging(lb => lb.AddNLog())
        .BuildServiceProvider(false);
    using (migrationServiceProvider)
    using (var scope = migrationServiceProvider.CreateScope())
    {
        var runner = migrationServiceProvider.GetRequiredService<IMigrationRunner>();
        runner.MigrateUp();
    }

**Comment by fubar-coder** [comment]
Ok, so it's nothing special and therefore most likely a bug I have to resolve.

**Comment by jzabroski** [comment]
As a thought, maybe we can move to using docker to run individual database regression suites.  With buildkit, overhead should be minimal.  Estimated time to achieve: 6 months to 1 year.  Most of the time would be learning.

**Comment by fubar-coder** [comment]
@jzabroski That would be a good idea.
