### ISSUE TITLE
Postgres JSON support

### ISSUE THREAD

**Issue by desmondgc** [fluentmigrator/fluentmigrator#1007]
Postgres supports JSON type since version 9.2. Can we add support in PostgresTypeMap.SetupTypeMaps?

```
SetTypeMap(DbType.Object, "json");
```

I assume this means we first need to add a new identifier e.g. Postgres vs Postgres92?

Maybe mapping DbType.Object is an abuse? NpgsqlDbType defines Json explicitly but we don't want to introduce concrete provider dependencies.

**Comment by bard83** [comment]
Is "json" the default mapping? is there a chance to support "jsonb" as well?

**Comment by fubar-coder** [comment]
Yes, `json` is the default mapping.

You can always use `.AsCustom("jsonb")` for PostgreSQL or replace the type map for the Postgres runner, which would change it globally.
