### ISSUE TITLE
AsBinary(Int32.Max) causes an exception for MySQL

### ISSUE THREAD

**Issue by x3ntrix** [fluentmigrator/fluentmigrator#1008]
`AsBinary(Int32.Max)` causes a NotSupportedException (Unsupported DbType 'Binary') for MySQL which is irritating because MySQL supports blobs. We have assumed that the column will become a LONGBLOB.

Our code targets MySQL and SQL Server. Is the only possible workaround to use `IfDatabase` and duplicate the complete create table statement or does FluentMigrator provide another way to check which database is used to just decide which `AsBinary` statement should be used? Something like:
```csharp
var table = Create.Table(...)....WithColumn("Image");

if (isMySQL)
    table.AsBinary();
else
    table.AsBinary(Int32.Max);
```

**Comment by fubar-coder** [comment]
You can always use dependency injection to inject a configuration object (or something similar) to determine the targeted database server.
