### ISSUE TITLE
In-process migrator - log sql

### ISSUE THREAD

**Issue by ambujs** [fluentmigrator/fluentmigrator#1011]
Hello, is there a way of logging the SQL and not executing it when using the in-process migrator? 

I'm aware that you can do this using dotnet-fm but I can't use that as I'm referencing external Nuget assemblies.

**Comment by fubar-coder** [comment]
Hi, the dotnet-fm tool uses the in-process migration runner, so almost all configuration options of `dotnet-fm` are available for you. The most important parts to achieve this are:

- Create your own (temporary?) `IServiceCollection` and register the FluentMigrator services as you would to update your database
- Set `ProcessorOptions.PreviewOnly` to avoid execution of the SQL statements
- Registering `SqlScriptFluentMigratorLoggerProvider` as singleton while passing a `TextWriter` as parameter

Now when you execute the migrations, they aren't applied to the database and the SQL statements are written to the text writer your passed to your `SqlScriptFluentMigratorLoggerProvider` singleton instance.

**Comment by ambujs** [comment]
Sorry to bother again but I have tried this but nothing is being logged into three.sql:
```
var serviceProvider = services
                .AddFluentMigratorCore()
                .ConfigureRunner(rb => rb
                    .AddPostgres() // add postgres support
                    .WithGlobalConnectionString(configuration.GetSection(nameof(ConnectionStrings))["AdventureWorks"]) // provide the connection string to database
                    .ScanIn(typeof(InitialDatabaseCreation).Assembly).For.Migrations()) // which assembly to look in for migrations
                    .AddLogging(builder =>
                    {
                        builder.AddNLog(new NLogProviderOptions
                        {
                            CaptureMessageTemplates = true,
                            CaptureMessageProperties = true
                        });
                    })
                .Configure<RunnerOptions>(opt => { opt.Tags = tags.Count > 0 ? tags.ToArray() : null; })
                .Configure<ProcessorOptions>(opt => opt.PreviewOnly = true)
                .BuildServiceProvider(false);

            var output = new StreamWriter("c:\\temp\\three.sql");
            services
                .AddSingleton<ILoggerProvider>(new SqlScriptFluentMigratorLoggerProvider(output));
```

**Comment by fubar-coder** [comment]
You have to build the service provider **after** you've added the singleton.

**Comment by ambujs** [comment]
That worked great, thanks a lot! Exactly what I needed.
