### ISSUE TITLE
FluentMigrator.DotNet.Cli install error

### ISSUE THREAD

**Issue by JayanthKumarS** [fluentmigrator/fluentmigrator#1020]
Getting below error when i am trying to intsall via NuGet Package Manager
Package 'FluentMigrator.DotNet.Cli 3.2.1' has a package type 'DotnetTool' that is not supported by project 'XXXX'

Application :  netcoreapp2.2
.

**Comment by sariyandath** [comment]
1.	Open “Command Prompt” window as “Run as administrator”.
2.	Navigate to the library (dll - your application) folder.
3.	Execute this command : dotnet tool install --global FluentMigrator.DotNet.Cli --version 3.2.1
4.	Execute migration: dotnet fm migrate -p sqlserver-c "SQLConnection" -a dllLibraryFileName.dll

For more Info: https://fluentmigrator.github.io/articles/runners/dotnet-fm.html
