### ISSUE TITLE
How to add a CHECK constraint using fluentmigrator?

### ISSUE THREAD

**Issue by sariyandath** [fluentmigrator/fluentmigrator#1021]
Hi, 
I couldn't find out a way to add a CHECK constraint using fluentmigrator. Is there any solution available to solve the below mentioned scenario?

```
ALTER TABLE  [dbo].[TableName]
    ADD CONSTRAINT [ColumnName record should be formatted as JSON]
                   CHECK (ISJSON(ColumnName)=1)
```

**Comment by fubar-coder** [comment]
Check constraints aren't supported yet, because some databases don't support them. It might be useful to implement this as an extension for the databases that support them or just have them ignored where it's not supported.

**Comment by jzabroski** [comment]
@sariyandath  You can implement it as an extension method using the `Execute.Sql` helper.

```csharp
public static class AlterTableExtensions
{
  public static void AddConstraint(this Migration migration, string schemaName, string tableName, string checkConstraintName, string checkConstraintFunction)
  {
    migration.Execute.Sql($@"
ALTER TABLE  [{schemaName}].[{tableName}]
    ADD CONSTRAINT [{checkConstraintName}]
                   CHECK ({checkConstraintFunction})".Trim());
  }
}
```

**Comment by jhardin-accumula** [comment]
@jzabroski - can you provide an example of how to use that extension in a migration?

The `AlterTableExtensions` class name suggests this should be used like:

`Alter.Table("mumble").AddConstraint("ck_name", "colname > 0");`

...which would be perfect, but that doesn't appear to work - IntelliSense does not offer `AddConstraint()` as an option for `Table()`, just the base `AddColumn()`, `AlterColumn()`, `ToSchema()` and `WithDescription()`.

n.b. I'm using Postgres via Postgres11_0 and I've made appropriate changes to the DDL in the method.

Thanks!

**Comment by jzabroski** [comment]
The AlterTableExtensions is something you would copy paste into your migration assembly. It's not part of the core project.

**Comment by jhardin-accumula** [comment]
I apologize for not making clear in my initial post that I did exactly that.

It is not clear what to do next, though. How would I code the migration to actually use that extension to create a check constraint?

**Comment by jzabroski** [comment]
this.AddConstraint will get you Intellisense

**Comment by jhardin-accumula** [comment]
OK, I apparently was not including that snippet in the assembly properly, I do see it now. 👍 

Unfortunately I cannot provide a schema name as a parameter. How would I get that from the migration runner's configured default schema?

**Comment by jzabroski** [comment]
See my answer. I would inject the tenant via a tenant service. This likely means creating an in-process runner instead of using Fluentmigrator.DotNet.Cli, such that you can loop over each tenant and inject it into the migration, or have a ITenantService with a ListAllTenantSchemas method that you could call within the migration. Which approach makes more sense depends on peculiarity of yiur deployment model I can't help you with.
