### ISSUE TITLE
How to set a database schema

### ISSUE THREAD

**Issue by quicoli** [fluentmigrator/fluentmigrator#1024]
Hello, 

I could not find an example of how to setup a global schema, actually I'm doing that including in all my migrations the ".InSchema(SchemaName);". 
I saw some commits on #290 suggesting there's a easier way, but I couldn't figure out how to use.

Any tip?

**Comment by fubar-coder** [comment]
Example:

```csharp
var defaultSchemaName = "myschema";
var services = new ServiceCollection()
    .AddSingleton<IConventionSet>(new DefaultConventionSet(defaultSchemaName, null))
    // other services (like FluentMigrator)
```
