### ISSUE TITLE
You must add a reference to assembly 'netstandard, Version=2.0.0.0

### ISSUE THREAD

**Issue by cpistiner** [fluentmigrator/fluentmigrator#1025]
I just updated (via NUGET) the version of FluentMigrator from 1.6.2 to 3.2.1 and well in my local environment I have no problems (beyond the necessary adaptations for the version change) when integrating the changes to the server I am receiving the message:

> The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

I have tried many solutions but the error persist.

I'm not sure it's a specific Fluent problem, but if you have any ideas, it's welcome.

Regards,
César

**Comment by jzabroski** [comment]
In https://github.com/dotnet/standard/issues/542 there are two suggestions:

- [ ] Check your Visual Studio version.  Visual Studio 2017 15.4.4 contained a bug that was fixed in later versions - the code would work fine if you had the right MSBuild tool and SDK installed, but Visual Studio would fail
- [ ] Add the following in your csproj:
    ```xml
    <ItemGroup>
      <Reference Include="netstandard" />
    </ItemGroup>
    ```

Separately, as suggested:
- [ ] Report what csproj file format you are using
- [ ] Report what dotnet runtime you are building against
  - [ ] Is the runtime Core or Framework?
  - [ ] What version number for the given Core or Framework runtime?

**Comment by cpistiner** [comment]
> MSBuild

Hi @jzabroski !

Thanks for your reply.

In localhost i have MSBuild 15.0 but the app is running in Windos Server 2012 and builds with MSBuil 14.0.

**Comment by cpistiner** [comment]
> Also, what .NET Framework version or .NET Core Runtime are you running locally vs. on your server?
> 
> For .NET Core Runtime, not sure if you're aware, but it's easy to see which versions of .NET Core are installed on our machine.

4.6.1

**Comment by jzabroski** [comment]
This footnote / warning in the MS Docs might help you:

> <sup>2</sup> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

Source: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by cpistiner** [comment]
> In [dotnet/standard#542](https://github.com/dotnet/standard/issues/542) there are two suggestions:
> 
> * [ ]  Check your Visual Studio version.  Visual Studio 2017 15.4.4 contained a bug that was fixed in later versions - the code would work fine if you had the right MSBuild tool and SDK installed, but Visual Studio would fail
> * [ ]  Add the following in your csproj:
>   ```
>   <ItemGroup>
>     <Reference Include="netstandard" />
>   </ItemGroup>
>   ```
> 
> Separately, as suggested:
> 
> * [ ]  Report what csproj file format you are using
> * [ ]  Report what dotnet runtime you are building against
>   
>   * [ ]  Is the runtime Core or Framework?
>   * [ ]  What version number for the given Core or Framework runtime?

At this moment i have Visual Stuidio Community 2019.

csproj file format? This?
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

The solution is running with NET Framework 4.6.1.

I already tried that but unfortunately it did not work
<ItemGroup>
  <Reference Include="netstandard" />
</ItemGroup>

I thank you very much for the help, I hope that with this information we will find the solution.

Regards,
César

**Comment by cpistiner** [comment]
> This footnote / warning in the MS Docs might help you:
> 
> > 2 The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.
> 
> Source: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

Excelent this, I migrated to 4.7.2 and commented how it was!!

Thank you very much!

**Comment by jzabroski** [comment]
> > MSBuild
> 
> Hi @jzabroski !
> 
> Thanks for your reply.
> 
> In localhost i have MSBuild 15.0 but the app is running in Windos Server 2012 and builds with MSBuil 14.0.

MSBuild 14.0 likely does not support _metapackages_, or does not support metapackages at the same level as MSBuild 15.0 - I think you need to upgrade your build server, but first take a VM snapshot before following such destructive suggestions, so that if it fails, you can just rollback the snapshot.
