### ISSUE TITLE
Add Processor for Snowflake DB

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1030]
I wonder if we should just have a plain ANSI SQL processor with "bring your own ODBC driver"?

**Comment by fubar-coder** [comment]
I've always seen the FluentMigrator expressions as something similar as the ODBC API with the processors being the DB-specific ODBC drivers.

**Comment by jzabroski** [comment]
Oh, SWEET.

I'm hoping to run my load test suite I wrote in FM against Snowflake.  This really makes my life so much easier. Thanks Mark!

**Comment by ikudjoi** [comment]
Did you know that the development version of FluentMigrator supports Snowflake natively?
Available via MyGet feed, we have been using it for half a year already.
