### ISSUE TITLE
Transaction Per Session Not Work - I'm Using Mariadb

### ISSUE THREAD

**Issue by dsanchezc24** [fluentmigrator/fluentmigrator#1031]
Hi, i got 2 transaction files, in the second file i throw an ArgumentException, 
I would expect no table to be created, but all the ones in the first file were created
![1Migration](https://user-images.githubusercontent.com/31042767/59158771-28b8e480-8a85-11e9-8794-ec29dc86cdba.png)
![2Migration](https://user-images.githubusercontent.com/31042767/59158774-2eaec580-8a85-11e9-84d5-9cf11f0937b5.png)

Mi code:

```
        private static IServiceProvider CreateServices(SC.Data.DbConfiguration dbConf)
        {
            var lstAss = new System.Reflection.Assembly[] {
                typeof(Security.Local.Migrations.Versions.V_2016.V20160606T1303).Assembly,
                typeof(POS.Local.Migrations.Versions.V_2019.V20190212T1651).Assembly
            };
            string connectionString;
                    connectionString = SC.Data.ConnectionStringsH.MakeConnectionString(dbConf);
                    return new ServiceCollection()
                    .AddFluentMigratorCore()
                    .ConfigureRunner(rb => rb
                        .AddMySql5()
                        .WithGlobalConnectionString(connectionString)
                        .ScanIn(lstAss).For.Migrations())
                    .AddLogging(lb => lb.AddFluentMigratorConsole())
                    .Configure<RunnerOptions>(opt => { opt.TransactionPerSession = true; })
                    .BuildServiceProvider(false);

        }

```        
```
        private static void UpDatabase(IServiceProvider serviceProvider)
        {
            // Instantiate the runner
            var runner = serviceProvider.GetRequiredService<IMigrationRunner>();
            runner.MigrateUp();
        }

```

**Comment by jzabroski** [comment]
@dsanchezc24 It looks like the issue is that MariaDB does not support Transactional DDL.  Please look at this documentation and tell me if you agree: https://mariadb.com/kb/en/library/start-transaction/#ddl-statements

It would be helpful if you provided a ODBC-only repro demonstrating that MariaDB does support Transactional DDL.  However, based on how I read the language (see below, **emphasis mine**), it does not seem possible.

> **DDL statements** (CREATE, ALTER, DROP) **and administrative statements** (FLUSH, RESET, OPTIMIZE, ANALYZE, CHECK,  REPAIR, CACHE INDEX), and LOAD DATA INFILE, **cause an implicit COMMIT and start a new transaction.** An exception to this rule are the DDL that operate on temporary tables: you can CREATE, ALTER and DROP them without causing any COMMIT, but those actions cannot be rolled back. This means that if you call ROLLBACK, the temporary tables you created in the transaction will remain, while the rest of the transaction will be rolled back.

**Comment by dsanchezc24** [comment]
Ok, apparently it is not an issue of FluentMigrator, it is that mariadb does not support for some actions that FluentMigrator needs.
thank you.
If you know in any other way that I can do to make everything work as I hope I would like to send me an example.

Thank you.

**Comment by jzabroski** [comment]
My suggestion is probably going to be: Use Snowflake DB.  I have not used it yet on a project, but the more and more I look at it, the more I think it solves problems I have today on very large database systems, and would likely make FluentMigrator even more powerful.

Note: I consider myself a SQL Server _EXPERT_, so when I say I am thinking of switching stacks, it's a bit of an identity crisis moment: Do I want to be a technology expert, or do I want to use what I think is the best tool for the job?
