### ISSUE TITLE
Add explanation for Obsolete interfaces

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1037]
Forward users to FM docs on obsoleting `ApplicationContext` and `MigrationAssemblies` in IMigrationContext.

e.g., something like the following but also with hyperlinks to FM docs explaining how to remove obsolete code.

```csharp
        /// <summary>
        /// Gets or sets the collection of migration assemblies
        /// </summary>
        [Obsolete("Migration assemblies are now per-runner, not per-context")]
        [CanBeNull]
        IAssemblyCollection MigrationAssemblies { get; set; }

        /// <summary>
        /// Gets or sets the arbitrary application context passed to the task runner
        /// </summary>
        [Obsolete("Use dependency injection to access 'application state'.")]
        object ApplicationContext { get; set; }
```

There is a lot of stuff that is Obsolete, but these are probably two of the big ones.

**Comment by jzabroski** [comment]
Similarly, `RunnerContext` and its interface `IRunnerContext` are obsolete.  The major interfaces replacing it are in FluentMigrator.Runner.Core.csproj, under the Initialization folder, in particular `RunnerOptions`.

The one troublesome feature is ApplicationContext, which is no longer needed because you can now use dependency injection to inject such "state" into your migrations.  In OO, this "state" injection into a workflow is called a "Saga pattern".  (TODO: Link issue where I requested such feature and @fubar-coder  recommended I use DI instead...)

IRunnerContext.WorkingDirectory is now ideally configured via an IConventionSet.RoothpathConvention.  The name WorkingDirectory was never a "great" name, in the sense that it is not clear what the WorkingDirectory is supposed to be used for (it's really supposed to help locate *.sql scripts to run via Execute.SqlScript - right @fubar-coder ?)

Small progress here trying to make sure we don't lose/upset users moving from 3.0 to 4.0 upcoming release :)

**Comment by fubar-coder** [comment]
@jzabroski It seems that you're right regarding the `WorkingDirectory`. I tried to keep most of the stuff as-is to minimize hassles for upgrades between major versions.

**Comment by jzabroski** [comment]
@fubar-coder Going through making some changes to this.  This message covers just ApplicationContext.  All obsoletes have the same message: `"Use dependency injection to access 'application state'."`  Ideally, the docs will be updated with a migration guide for how to use DI instead of ApplicationContext.

- `IRunnerContext.ApplicationContext` / `RunnerContext.ApplicationContext` is not marked as obsolete
    - This is probably because `IRunnerContext` / `RunnerContext` themselves are marked as obsolete, but I think as a book keeping principle we should mark this as obsolete, too, so that when we write the migration guide, we have a good checklist of what "entrypoints" we have to make sure have a clear upgrade guide for.
- Places I've gone through so far and fixed in my local
    - `IVersionTableMetaData.ApplicationContext`
    - `ObsoleteMigrationRunnerTests.CanPassApplicaitonContext()` / `ObsoleteVersionLoaderTests.CanSetupApplicationContext` - was marked as obsolete at the class level, but not the method level with explanation as to why.
    - `TestVersionTableMetaData.ApplicationContext`
    - `VersionLoaderTests.CanSetupApplicationContext`

Places it's not immediately clear what to do:
- `MigratorConsole.ApplicationContext` - not clear b/c this is a command line interface entrypoint.
  -  ❓ How were you planning to remove this in FluentMigrator 4.0?  If someone passes in "ApplicationContext" on the command line in 4.0, what is the migration path? 
  - I marked it as obsolete, anyway.
  - Similarly, marked `ConnectionCommand.Context` / `MigratorOptions.Context` as obsolete.

**Comment by fubar-coder** [comment]
The only solution for the external runners is to output a warning. The option should probably be kept for 4.0, but the runner should exit with an error.

**Comment by fubar-coder** [comment]
I don't know yet what a good replacement might look like.

**Comment by jzabroski** [comment]
Considering this done; we should review the PR and finish it off for  now.
