### ISSUE TITLE
ASP.NET Core - "Could not find a resource" in Execute.EmbeddedScript() 

### ISSUE THREAD

**Issue by kistva** [fluentmigrator/fluentmigrator#1041]
I am using this good migrator in ASP.NET Core v. 3.2.1.
But I have some issues in using Execute.EmbeddedScript()
I have a script placed in a folder /scripts/myscript.sql
And I have set the "Build Action" property as Embedded Resource.

But when it comes to the
_Execute.EmbeddedScript("myscript.sql");_ 
Then the error is "Could not find a resource with one of the following names "myscript.sql"

I have also tried with the "Namespace.DirectoryName.Filename" that gives the same error.
Namespace "Api.Migrations"

_Execute.EmbeddedScript("Api.Migrations.Scripts.myscript.sql");_ 

I haven't been able to make EmbeddedScript work. 
Any other having that problem?

**Comment by fubar-coder** [comment]
Did you enable scanning for embedded resources in the configuration?

Example:

```csharp
var services = new ServiceCollection()
    .AddFluentMigratorCore()
    .ConfigureRunner(rb => rb
        .ScanIn(typeof(YourType).Assembly)
            .For.Migrations()
            .For.EmbeddedResources());
```

**Comment by kistva** [comment]
That did the job :-)
I was missing the 3 last lines
        .ScanIn(typeof(YourType).Assembly)
            .For.Migrations()
            .For.EmbeddedResources());
Thanks a lot
