### ISSUE TITLE
Unable to open database file with Sqlite e UNC path. I fixed in Version 2, how to do in Version 3?

### ISSUE THREAD

**Issue by Rowandish** [fluentmigrator/fluentmigrator#1043]
I'd like to migrate a Sqlite database in a network UNC path, for example:

`\\foo\bar\database.db`

Following [this answer](https://stackoverflow.com/a/18506097/2965109) I'd like to call `SQLiteConnection` constructor with true as second argument.
I fixed the problem in version 2 of `FluentMigrator` as following:

```
var factory = new SQLiteProcessorFactoryParseViaFramework();
using (var processor = factory.Create(connectionString, announcer, options))
{
    var runner = new MigrationRunner(assembly, migrationContext, processor);
    runner.MigrateUp();
}

public class SQLiteProcessorFactoryParseViaFramework : SQLiteProcessorFactory
{
    public override IMigrationProcessor Create(string connectionString, IAnnouncer announcer,
        IMigrationProcessorOptions options)
    {
        var factory = new SQLiteDbFactory();
        var connection = new SQLiteConnection(connectionString, true); // Here is the fix
        return new SQLiteProcessor(connection, new SQLiteGenerator(), announcer, options, factory);
    }
}
```

Now I'd like to do the same in Version 3.
I saw that `IMigrationProcessorFactory` is obsolete and that the registered services provide everything that they need for their configuration.
But how to override the `SQLiteConnection` call in order to pass true as second parameter?

Thanks.

**Comment by jzabroski** [comment]
This is simply a terrible idea.

Don't do it.  You _will_ corrupt your database.

**Comment by jzabroski** [comment]
@Rowandish  Please see: https://www.sqlite.org/howtocorrupt.html
