### ISSUE TITLE
[Question] How is the best way to set all names to snake_case?

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [fluentmigrator/fluentmigrator#1045]
I have some migrations classes and want to use `C#` class casing like `MyTableName`, `MyColumn`
but on batabase migrationg i want to use `snake_case` names.
How is the best way to translate `CamalCase` names to `snake_case`?
It there some hooks or any place where it can be handled?

**Comment by fubar-coder** [comment]
This is typically done by the O/R mapper. FluentMigrator just takes the names as you write them.
