### ISSUE TITLE
SQL Views not managed ?

### ISSUE THREAD

**Issue by kilroyFR** [fluentmigrator/fluentmigrator#1046]
hey there, just started using FluentMigrator.

Just noticed there is no embedded script to create Views ? execute Stored procedure.

Seems very restricting ! a database is not only made of tables.

**Comment by jzabroski** [comment]
You can save views to a text file and call this.Execute.EmbeddedSql

```c#
  Execute.EmbeddedScript("Database.Migrations.201607150000_ERPDomainDB_Initial.sql");
```

You can also then create an extension method on Migration class that takes a partial path.

Someone in the FM gitter channel recently suggested adding this into the project as proper extensions.  We're happy to discuss what that API should look like and take a PR.

**Comment by lszczygielek** [comment]
@jzabroski what is a status of `Create.View` proposition? This issue is marked as answered, but it's not clear if idea is dropped or is planned for future. Can you add info?

**Comment by jzabroski** [comment]
I have my own extension methods at one client for AlterView, DropView. They don't subclass from ICreateExpressionRoot but are simply extension methods on Migration class. DropView detects if the embedded resources exist, and if it does, throws an exception saying to delete the embedded resource.

I do the same thing for function, trigger and stored procedure objects.
