### ISSUE TITLE
One to many and many to many with complex properties

### ISSUE THREAD

**Issue by sekulicb** [fluentmigrator/fluentmigrator#1056]
Hi. Thanks for this amazing library. I wanted to ask you, are there any examples when you have complex properties of another type, such as Enumerable TClass, what would be the best practice for writing Migrations. For example when you have Person class, but property Address inside Person class is not just plain string but List of Address-es, where each Address is type on its own and could have City, State, Zip etc...that would be one to many example, but also examples for many to many relationship. Thanks.

**Comment by jzabroski** [comment]
@sekulicb I think I need an idea on how you are using the library today.  There are downstream FluentMigrator collaborations that take Plain Old C# Objects and automatically generate database schema migrations from the POCOs.  However, there is nothing in the library today that takes a c# class and generates a table and/or schema.

Please see: https://github.com/fluentmigrator/fluentmigrator#third-party-contributions--fluentmigrator-ecosystem for EasyMigrator.
