### ISSUE TITLE
.config file is not valid XML

### ISSUE THREAD

**Issue by eivinskr** [fluentmigrator/fluentmigrator#1058]
Octopus Deploy complains about [`Sap.Data.Hana.v4.5.dll.config` ](https://github.com/fluentmigrator/fluentmigrator/blob/master/lib/Hana/ado.net/v4.5/Sap.Data.Hana.v4.5.dll.config) when parsing config files as it is not valid XML. 

Not sure how to fix it and ensure that the config still works. 

It seems like the less than- and greater than-sign on line 11 and 12 should be replaced by their character entity reference so that the XML processor does not interpret the symbols incorrectly (https://stackoverflow.com/questions/29398950/is-there-a-way-to-include-greater-than-or-less-than-signs-in-an-xml-file/29398983).

**Comment by fubar-coder** [comment]
Try deleting the file. It seems that it's just garbage.

**Comment by jzabroski** [comment]
@eivinskr  To elaborate on @fubar-coder 's "just garbage" comment:

That config file is only needed if you have an application plug-in which expects a different version of Sap.Data.Hana.v4.5.dll.  Ahem, think about that for a second.  The very fact that the dll includes a version number pretty much precludes this from EVER happening.

**Comment by eivinskr** [comment]
Ok, do you want a pull request to delete it from the fluentmigrator repo? 

Deleted it locally with a pre-deployment PowerShell script in Octopus

```
# config-file is not valid XML
Remove-Item "path/to/Sap.Data.Hana.v4.5.dll.config"
```

**Comment by fubar-coder** [comment]
I guess that it wouldn't hurt to delete this file. Nobody in his right mind would ever use those DLLs as a reference for their own projects. They're just there to be used by the external migration runners.

**Comment by jzabroski** [comment]
@eivinskr A PR would be great.  But, as a thought, maybe we can use the new .NET Common Project System and exclude files matching a pattern of "*Sap.Data.Hana.v*.*.dll.config"
