### ISSUE TITLE
Execute scripts in dependence

### ISSUE THREAD

**Issue by heikar** [fluentmigrator/fluentmigrator#1080]
Hi,

i have an application with multiple migration scripts (files wit create table and create pk/fk statements) in multiple assemblies. The assemblies can be from different developers (addin system). Now my question is whether it is possible to collect all statements from all assemblies in groups

- all create table and alter table statements
- all create pk statements
- all create fk statements

and execute in this order? So the migration tool from my application can be sure, that all tables and all pks are created before the fks be built.

Many thanks in advance
heikar

**Comment by BigYellowHammer** [comment]
If you are willing to run FM multiple times - you can tag migration
https://fluentmigrator.github.io/articles/migration/migration-filter-tags.html?tabs=runner-internal
And execute FPM to only run migrations with certain tags on them.

**Comment by heikar** [comment]
That sounds good. Tank you :)
I will try it.

**Comment by jzabroski** [comment]
I don't think it's a good idea to let addins alter tables. 

If this is truly your architecture, each addin should own it's own schema and you should consider executing Migrations per assembly  with the connection string changing to use that schema owners credentials. 

You don't want to tie your addins into all supporting the same service level agreements, as additional columns on a table may impact reports.
