### ISSUE TITLE
Configure dependabot

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1083]
Dependabot is a cool GitHub bot that automatically monitors your project dependencies for upgrades and submits PRs automatically to have a global quasi-"build at head" style master branch.

**Comment by jzabroski** [comment]
@fubar-coder  I just gave this a shot today.  I think dependabot still has a way to go to be mature, but it looks extremely promising (while it lasts?)

I configured it for weekly updates.  It appears tied to my account right now, which is a bit unfortunate.  Below is a screenshot of what the settings look like.

.NET ecosystem is marked as in Beta right now - I hope that means the ecosystem and not referring to ".NET 5.0" ! :)

![image](https://user-images.githubusercontent.com/447485/66957679-ab097480-f034-11e9-9495-1cc5bc3ed40b.png)

**Comment by jzabroski** [comment]
@fubar-coder  It's nice that it supersedes previous pull requests for a dependency: https://github.com/fluentmigrator/fluentmigrator/pull/1092 was auto-closed when it detected a newer dependency.  I'm not confident the "monthly" configuration is working correctly, however, so I apologize for the spam.

**Comment by fubar-coder** [comment]
No problem. It was expected that not everything will work flawlessly from the start.
