### ISSUE TITLE
Configure connection dateformat when building migrator

### ISSUE THREAD

**Issue by eliezeralmeida** [fluentmigrator/fluentmigrator#1118]
### Problem

In this code example below an error occurs because the database dateformat is different from `ymd`, so I need to execute a `set dateformat ymd;` before sending the insert with the date.

```
Execute.WithConnection(con, tran => 
{
    var cmdTemplate = "insert into table(datetimeColumn) values('{0}')";
    
    var cmd = con.CreateCommand();
    cmd.Transaction = tran;
    cmd.CommandText = string.format(cmdTemplate, DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.000"));

    cmd.ExecuteNonQuery();

});
```

### Current resolution
```
Execute.WithConnection(con, tran => 
{
    var formatCmd = con.CreateCommand();

    formatCmd.Transaction = tran;
    formatCmd.CommandText = "set dateformat ymd";
    formatCmd.ExecuteNonQuery();

    var cmdTemplate = "insert into table(datetimeColumn) values('{0}')";
    
    var cmd = con.CreateCommand();
    cmd.Transaction = tran;
    cmd.CommandText = string.format(cmdTemplate, DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.000"));

    cmd.ExecuteNonQuery();

});
```

### Question

Is there any event a way to configure FluentMigrator so that when opening the database connection it already executes the `set dateformat ymd;` command to the database?

**Comment by eliezeralmeida** [comment]
I was able to include the language in the connection string.

[https://blogs.msdn.microsoft.com/azuresqlemea/2017/01/13/lesson-learned-16-how-to-change-the-default-language-of-azure-sql-database/](https://blogs.msdn.microsoft.com/azuresqlemea/2017/01/13/lesson-learned-16-how-to-change-the-default-language-of-azure-sql-database/)

**Comment by jzabroski** [comment]
Hi @eliezeralmeida - Thanks for contributing to our Q&A knowledge base!  Hope you're enjoying coding fluently!
