### ISSUE TITLE
Maintenance to run before profiles not working correctly?

### ISSUE THREAD

**Issue by gandarez** [fluentmigrator/fluentmigrator#1121]
I have a persistent mysql database and a profile for testing purposes that inflates the database with data. Because I am running the migrations in-process I could not find a way of deleting those data before shutting down. So I decided to create a Maintance class which runs before profiles at a specific tag. That class is responsible to `delete` all the data before actually running the `testing profile` again. As unexpected result I have been getting `duplicate key` what sounds for me that the Maintance is not being called correctly.

```C#
[Maintenance(MigrationStage.BeforeProfiles, TransactionBehavior.None)]
[Tags("Testing")]
public class PrepareForSeedingMigration : ForwardOnlyMigration
{
    public override void Up()
    {
        Delete.FromTable("Table1").AllRows();
        Delete.FromTable("Table2").AllRows();
        ...
    }
}

[Profile("Testing")]    
public class SeedForTestingMigration : Migration
{
    public override void Up()
    {
        /* Insert data */
    }

    public override void Down()
    {
        /* Delete data */
    }
}
```

**Comment by jzabroski** [comment]
If you change your Profile into a regular migration, does it work?  Just for testing purposes and troubleshooting.

**Comment by gandarez** [comment]
It will work because changing to a regular migration says to the migrator that it has to be controlled by the `VersionInfo` table and then I do not need to be aware of running `BeforeProfiles` to drop some data. The initial problem is the `Profiles`  do not have a migration under `VersionInfo` table and the migrator has no way to check if the `Profile` has already been run or not. I think it is a concept for `FluentMigratior`.

**Comment by jzabroski** [comment]
I'm not asking if it will work - I am asking if you've confirmed it will work. :)

I think one blind spot is I dont have a MySQL environment set-up for me to debug these problems.  Definitely a TODO for me.  I think improving the MySQL runner is desirable, as there seem to be some edge cases people are running into.

**Comment by jzabroski** [comment]
I will try running it in SQL Server to see if its a general flow control issue.  I suspect it has more to do with transaciton isolation, though.

**Comment by gandarez** [comment]
As I said it works perfect because is using a regular migration instead of a single `Profile` setup.

**Comment by jzabroski** [comment]
Do you have zero regular migrations in your solution?

**Comment by gandarez** [comment]
Do you mean if I have any migration that sets version to zero? If that is the question, I'd say No, I don't.

**Comment by jzabroski** [comment]
Yes, that is the question.  There is a known bug/limitation around requiring at least one regular migration in a project.  The workaround is to create a dummy migration with a Version you'd never choose, like 0 or int.MinValue.

**Comment by jzabroski** [comment]
@gandarez  This is the issue I was thinking of 1017
