### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by gandarez** [fluentmigrator/fluentmigrator#1122]
I have a class library let's say `MyAssembly.DbMigration` that references `MyAssembly.Data` which contains all the entities. When running a migration through the command line it throws an exception.

```C#
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Dapper.Contrib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

**Comment by jzabroski** [comment]
In this scenario, you may want to use an In Process Runner which will allow the C# compiler / MSBuild to generate a deps.json file which can find the assembly for you.  See #1016

**Comment by gandarez** [comment]
As a workaround I exchanged some classes between libraries and the error has gone. But it's frustrating and I know it's not a specific problem for this library.

**Comment by jzabroski** [comment]
Yeah, I am working on a proposal to the .NET Infrastructure to make this user story easier for developers, but the problem is most developers I talk to look at me like I have six heads when I say this is a real problem... because they don't run into it. (Or, if they do, they don't realize it.)
