### ISSUE TITLE
Obsolete way to run migration on demand

### ISSUE THREAD

**Issue by Artur2** [fluentmigrator/fluentmigrator#1162]
Currently FluentMigrator scanning migrations on startup when using it in aspnet core project.
I found way to run migration on demand by calling for example action
Now I do that with RunnerContext which is obsolete
Any ways to do that not only at startup when configuring services ?

**Comment by jzabroski** [comment]
@Artur2 Thanks for your patience - was on vacation last week.

Artur, can you please post a code sample of what you're currently doing?  My understanding is you want to remove all Obsolete compiler warnings from your solution.  The best way, IMHO, for me to help you with that is to see a code example representative of what your solution is doing.  The other option is to follow the example in FluentMigrator samples directory and build an "In-Process Runner".

**Comment by Artur2** [comment]
@jzabroski Yep, sure
```C#
internal virtual void MigrateToLatestDatabaseVersion(string connectionString)
{
    var assembly = Assembly.GetExecutingAssembly();
	var logAnnouncer = new TextWriterAnnouncer(s => _logger.Debug(s));

	var migrationContext = new RunnerContext(logAnnouncer)
	{
		Namespace = "Logic.Dal.Migrations"
	};

	var options = new MigrationOptions();
	var factory = new SqlServer2012ProcessorFactory();

	using (var processor = factory.Create(connectionString, logAnnouncer, options))
	{
		var runner = new MigrationRunner(assembly, migrationContext, processor);
		runner.MigrateUp();
	}
}
```
`TextWriterAnnouncer` marked as `Obsolete` and other like `RunnerContext`, `SqlServer2012ProcessorFactory`, `MigrationRunner` with specified constructor

**Comment by jzabroski** [comment]
Got it.  I am releasing 3.2.2. hopefully tonight which contains so better warnings than just Obsolete.

TextWriterAnnouncer still exists, but the general Announcer abstraction has been replaced with the ability to log arbitrarily anything you want, and each logger can thus have their own output streams (so you can log things to a database, windows event log, file, cloud service like datadog, whatever).

Please look at: https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/samples/FluentMigrator.Example.Migrator/Program.DependencyInjection.cs

In particular, https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/samples/FluentMigrator.Example.Migrator/Program.DependencyInjection.cs#L31-L32

**Comment by jzabroski** [comment]
@Artur2  See this push just now: https://github.com/fluentmigrator/fluentmigrator/commit/69e1a267b7278d02f794d0a94d32054243f6f56c

**Comment by Artur2** [comment]
Thank you very much, that was helpful 😃
