### ISSUE TITLE
Why does the FluentMigrator.Console NuGet package include Microsoft.Extensions DLLs?

### ISSUE THREAD

**Issue by arfmach** [fluentmigrator/fluentmigrator#1163]
The **FluentMigrator.Console** NuGet package definition lists no dependencies, but the binaries include the DLLs for several Microsoft.Extensions.* packages. When adding those binaries to an artifact for deployment, those DLLs may conflict with newer versions required by other projects of the user's solution. If those references are really needed, they should be listed as dependencies for the NuGet package, so that the NuGet restore can resolve those version differences.

**Comment by jzabroski** [comment]
@arfmach Thanks for your patience - was on vacation last week.

To be honest, I don't understand how nuget.org lists dependencies.  I've seen StackOverflow's Marc Gravell and Nick Craver similarly perplexed.  If you know how that works, I'd appreciate an explanation.

As for why it's packaged the way it is, I can't say for sure, but I suspect that early .NET Core projects had incomplete support for "Framework Dependent Deployment".  In .NET Core 3.0, they fixed this by adding an official specification for "Framework Roll Forward", as well as improvements to the default MSBuild targets that interpret your csproj file XML elements as build instructions.  

> When adding those binaries to an artifact for deployment, those DLLs may conflict with newer versions required by other projects of the user's solution.

I mean, this is sort of a non-issue, right?  If you install any two arbitrary .NET programs in the same directory, you are going to have this issue.  Just trying to prioritize issues here, and where I spend time each week on FluentMigrator.  The confusion seems to arise from the fact FluentMigrator.Console is not a library, it's an actual executable.  nuget.org doesn't have a clean way to handle this use case and say "this is an executable, not a library for inclusion in VisualStudio", despite the fact many open source projects provide up to four common ways to use the open source project:

* MyProject.MSBuild.dll -- MSBuild tasks
* MyProject.Console.dll -- executable CLI Tool
* MyProject.DotNet.Cli.dll -- installable .NET Core CLI Tool
* MyProject.dll -- actual library useful for extensibility

**Comment by arfmach** [comment]
> FluentMigrator.Console is not a library, it's an actual executable.

Yes, I was too immersed in the problem and I didn't quickly realize that there was no link between my project's dependencies and FluentMigrator.Console's. In the end, we managed to isolate the responsibilities by copying FluentMigrator.Console in a dedicated subfolder for deployment.
Thank you.

**Comment by jzabroski** [comment]
Awesome, thanks for the feedback!  Happy migrating!
