### ISSUE TITLE
Fluent migration in Azure DevOps Pipeline

### ISSUE THREAD

**Issue by usamamalik75** [fluentmigrator/fluentmigrator#1167]
Hi,
How can I run the fluent migrations in Azure pipeline. can anyone guide me ?

Thanks

**Comment by jzabroski** [comment]
If you're using it in a build pipeline, can you just use FluentMigrator.MSBuild tasks?

**Comment by jzabroski** [comment]
@usamamalik75 I'm close this as its stale. Please re-open if you can respond to my question.  Thanks!
