### ISSUE TITLE
On Insert : "ORA-01704: string literal too long"

### ISSUE THREAD

**Issue by PhenX** [fluentmigrator/fluentmigrator#1171]
When inserting string via `Insert.Into` on Oracle, we are facing this issue when a string value is over 4000 chars : 
https://stackoverflow.com/questions/13945710/error-ora-01704-string-literal-too-long

**Comment by jzabroski** [comment]
@PhenX Thanks - I think this StackOverflow post ([oracle10g - How to insert/update larger size of data in Oracle tables](https://stackoverflow.com/a/8802397/1040437)) answered by Sathyajith Bhat better explains how we'll need to update the generated SQL.

In your link, I found these notes very helpful, too:

# Workaround 1: [concatenate sequences of 4000 byte literals using || concatenation operator](https://stackoverflow.com/a/30219281/1040437)
> ```sql
> Insert into table (clob_column) values ( to_clob( 'chunk 1' ) || to_clob( 'chunk 2' ) );
> ```

# Gotcha 1: [Handling Special Characters](https://stackoverflow.com/a/31794976/1040437)

> The split work until 4000 chars depending on the characters that you are inserting. If you are inserting special characters it can fail. The only secure way is to declare a variable.

My Note: I believe what this person is saying is that Workaround #1 works until you deal with special characters.

# Proposed Solution - [Combines Workaround 1 and Gotcha 1](https://stackoverflow.com/a/59469966/1040437)

> ```sql
> DECLARE
>   chunk1 CLOB; chunk2 CLOB; chunk3 CLOB;
> BEGIN
>   chunk1 := 'very long literal part 1';
>   chunk2 := 'very long literal part 2';
>   chunk3 := 'very long literal part 3';
> 
>   INSERT INTO table (MY_CLOB)
>   SELECT ( chunk1 || chunk2 || chunk3 ) FROM dual;
> END;
> ```

**Comment by fairking** [comment]
I have the same issie too. Waiting for the release. Appreciate your hard work guys.

**Comment by jzabroski** [comment]
@fairking I merged the fix , release coming this week.
