### ISSUE TITLE
Replace MyGet with Azure Artifacts feed

### ISSUE THREAD

**Issue by eloekset** [fluentmigrator/fluentmigrator#1180]
Ref #1101 we've concluded to remove the MyGet feed, which has been used for pre-releases up until now. That involves several tasks. From the top of my head:
* [x] Move all NuGet packages currently on the MyGet feed over to the Azure Artifacts feed
* [x] Update readme.md to show a badge for the latest release on the new feed and remove MyGet
* [x] Delete the Travis build script all together, or at least remove the part that depends on the MyGet feed
* [ ] Update any other documentation that may refer to the MyGet feed
* [ ] Finally actually delete the feed at myget.org

We shouldn't rush to do these steps. The most important step is to move all current packages so any project that depends on a previous prerelease can still get that package from the new feed.

**Comment by eloekset** [comment]
I don't know what's wrong with our MyGet feed, but it seems to be difficult get the first task done.
![image](https://user-images.githubusercontent.com/791721/75093616-b3922e80-5583-11ea-9a9b-a129a6ba55aa.png)

**Comment by jzabroski** [comment]
I like that you broke out deleting the myget feed as a separate step - that should help ease transitioning. I think we should also create a Sticky issue (which I will do now) here on GitHub notifying people MyGet is deprecated and will soon be obsolete.

Myget seems to support unlisting packages, but it is [not documented anywhere](https://www.google.com/search?q=inurl%3Adocs.myget.org+%22unlisted%22+package) except in one screenshot I found in their Package Retention documentation: https://docs.myget.org/docs/reference/package-retention

**Comment by jzabroski** [comment]
#1183 now tracks notification. I did this because some people come from Google Search directly to GitHub Issues and skip past the README. This adds an additional communication channel.

**Comment by eloekset** [comment]
The reason I didn't find any packages in the MyGet feed, is simply because I forgot to add the **-Prerelease** flag. 

I found a [PowerShell module that Microsoft has made](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/migrate-packages?view=azure-devops) to migrate from MyGet to Azure Artifacts. Exactly what we need to do this in just a few simple steps. No. It doesn't work. Of course... Will probably have to debug the PowerShell module, but before I do that I'll try running it on a Mac instead.

```
Move-MyGetNuGetPackages -SourceIndexUrl https://www.myget.org/F/fluent-migrator/api/v3/index.json -DestinationIndexUrl https://pkgs.dev.azure.com/fluentmigrator/fluentmigrator/_packaging/testmigrationfrommyget/nuget/v3/index.json -DestinationPAT <secret-value> -DestinationFeedName testmigrationfrommyget
```

The error messages that go over and over again for every package are:
```
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
At C:\Users\eivin\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:770 char:5
+     $process.Start() | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception

Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."
At C:\Users\eivin\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:771 char:5
+     $process.WaitForExit()
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

You cannot call a method on a null-valued expression.
At C:\Users\eivin\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:773 char:5
+     $return = [pscustomobject]@{
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
         
```

**Comment by eloekset** [comment]
No, same thing on a Mac with PowerShell 7. There I had to specify `-TempFilePath`, but the result is the same. And someone else got the same set of error messages and gave up: https://github.com/microsoft/azure-artifacts-migration/issues/4

**Comment by eloekset** [comment]
I finally found some time (at night) to make some progress on this migration from MyGet to Azure Artifacts. After tracking down the issue with the PowerShell module (https://github.com/microsoft/azure-artifacts-migration/issues/8), it seems like I'm able to migrate all packages - it's still running though, so I have to verify that everything is moved before I check the first checkbox of this issue. But so far it looks good. These are all migrated from MyGet now:
![image](https://user-images.githubusercontent.com/791721/88236205-c0bf6080-cc7c-11ea-85a0-bbfcf38859f9.png)

**Comment by eloekset** [comment]
The next thing is to change the badge on the readme.md front page. But we've got an issue there. Seems like we have to use promoting to the **Prerelease** view to get the correct badge, because now we only get the latest version that is not a prerelease, and when I try to switch to the Prerelease view it gives me a warning that we haven't got any packages there yet.

![image](https://user-images.githubusercontent.com/791721/88236378-26135180-cc7d-11ea-8c73-243829e28ee8.png)
![image](https://user-images.githubusercontent.com/791721/88236383-2c093280-cc7d-11ea-8f48-0869d6233b1b.png)

So we can manually promote all the prerelease packages that we've got so far. But preferably this should be automated somehow - I'm just not sure exactly how we're going to do that in the release pipeline, because it has to identify a prerelease. On branch maybe...?

**Comment by eloekset** [comment]
Hurray! I've checked the first checkbox. All packages are migrated. I know because I saw the count to be migrated was 191 when I debugged the PowerShell module.
![image](https://user-images.githubusercontent.com/791721/88236825-3677fc00-cc7e-11ea-8d62-707681242ba2.png)

**Comment by jzabroski** [comment]
Great

**Comment by eloekset** [comment]
I tried to promote a prerelase to the **Prerelease** view, but it won't help us getting the badge that we want for readme.md, because Azure Artifacts requires that we *don't* use the standard NuGet prerelease naming convention that has been working all time...
![image](https://user-images.githubusercontent.com/791721/88237136-ddf52e80-cc7e-11ea-841e-663717a2bd76.png)

I hope Microsoft can just fix this issue for us - as I don't see why we should not follow the naming convention of NuGet prereleases. If we don't follow the convention, it makes a mess for everyone consuming packages from our feed like I tested thoroughly and documented in the attachment named **Test of views in Azure Artifacts** in this comment: https://github.com/fluentmigrator/fluentmigrator/issues/1101#issuecomment-568888232

**Comment by eloekset** [comment]
I'll just leave this screenshot here, since I will use this GitHub issue as reference for a feature request to Azure Artifacts.
![image](https://user-images.githubusercontent.com/791721/88266140-f5f49e80-ccce-11ea-8ada-15cfd6ad1519.png)

What we need is this:
![image](https://user-images.githubusercontent.com/791721/88266378-6d2a3280-cccf-11ea-8549-2b9c68c3598f.png)

Because that's what works in Visual Studio:
![image](https://user-images.githubusercontent.com/791721/88266439-8337f300-cccf-11ea-8ee1-1faaf9d94fd9.png)

**Comment by eloekset** [comment]
I think we need upvotes to this suggestion to get this feature: https://developercommunity.visualstudio.com/idea/703726/generate-badge-without-version-restrictions.html

**Comment by jzabroski** [comment]
Closing this and moving the remainder work to a new issue.

**Comment by jzabroski** [comment]
BTW, I dont think we should bother deleting the myget feed.  If people rely on it, let them continue to do so.  Its obviously not affecting them
