### ISSUE TITLE
net core 3.x works but randomly doesn't execute certain migration when --self-contained

### ISSUE THREAD

**Issue by srad** [fluentmigrator/fluentmigrator#1185]
I'm not up to date if FM runs on net core 3.1, however I tried it and it works.
However when I deploy the migrations and run them in-process on the production server with:
```
dotnet publish -r linux-x64 -c Release --self-contained 
```
The runner asserts that a table that has already has been created can't be created because it exists (on an empty database).

journalctrl log output:
```
...
-------------------------------------------------------------------------------
501: AddTasksTable migrating
-------------------------------------------------------------------------------
Beginning Transaction
CreateTable tasks
!!! Table 'tasks' already exists
Rolling back transaction
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'tasks' already exists
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
```
Running it locally or during debugging everything works fine. Here are my migrations:
 
https://github.com/srad/eTaskAdvisor.WebApi/blob/master/Migrations/FluentMigrator

**Comment by srad** [comment]
This behavior seems database specific and too strange, I don't this it can have anything to do with the runner, for now I'm closing this.

**Comment by jzabroski** [comment]
@srad Hi Sam, Which version of FluentMigrator are you using? 3.x or 4.x?

I think you're conflating the dotnet.exe --self-contained flag with the fact MySQL treats Schemas as unique databases.  To "fully self contain" a fluentmigrator deployment, you need to 👍 

1. Have unique FM connection credentials per self-contained database (this will prevent FM from in the middle of a migration talking to another database)
2. Create a unique database and be careful about using "schemas".
