### ISSUE TITLE
dealing with multiple database

### ISSUE THREAD

**Issue by Do-flamingo** [fluentmigrator/fluentmigrator#1186]
Hello,
i have added fluentmigration to execute migration with my sql script :

services.AddFluentMigratorCore()
                    .ConfigureRunner(
                        builder => builder
                               .AddSqlServer()
                               .WithGlobalConnectionString(Configuration["ConnectionStrings:StarNet"])
                               .ScanIn(typeof(AjouterColonneMFI_MNT).Assembly).For.Migrations().For.EmbeddedResources());

But when i have added a script that reference different database i have got an error :
System.Exception
  HResult=0x80131500
  Message=An error occured executing the following sql:
  INSERT INTO [dbo].[VersionInfo] ([Version], [AppliedOn], [Description]) VALUES (20200226120430, '2020- 
  02-27T13:27:34', N'TestDatabase')
   The error was object name 'dbo.VersionInfo' invalid.

here is my script :

USE [DEV_SHIVA]
GO

 

CREATE SYNONYM [dbo].[SYN_OFFICE_DN_ACADOMIA_GetInterventionByIntervenantId] FOR [DEV_OFFICE].[dbo].[DN_ACADOMIA_GetInterventionByIntervenantId]
GO                                         

 

CREATE PROCEDURE [dbo].[DN_OFFICE_GetInterventionByIntervenantId]
       @INTERVENANT_BO_ID int
AS
BEGIN
       SET NOCOUNT ON;

 

       DECLARE @TB_OFFICE_InterventionIntervenant table ( [INTERVENTION_ID] [int] NOT NULL,
                                                  [CLIENT_NOM] [varchar](101) NULL,
                                                  [PRODUIT_LIB] [varchar](100) NOT NULL,
                                                  [DATEDEB] [varchar](27) NULL,
                                                  [DATEFIN] [varchar](27) NULL,
                                                  [INTERVENTION_DUREE] [int] NULL,
                                                  [INTERVENTION_DUREE_HEURE] [decimal](17, 0) NULL,
                                                  [INTERVENTION_TARIF_HOR] [decimal](6, 2) NULL,
                                                  [INTERVENTION_SAL_NET_HOR] [decimal](6, 2) NULL,
                                                  [INTERVENTION_INDIC_URSSAF] [char](1) NULL,
                                                  [EVENEMENT] [varchar](50) NULL,
                                                  [INTERVENTION_CREEQUAND] [varchar](10) NULL,
                                                  [TOTAL_MINUTE] [int] NULL,
                                                  [TOTAL_TEMPS] [varchar](20) NULL,
                                                  [TYPEINTERVENTION_ID] [tinyint] NOT NULL,
                                                  [TYPEINTERVENTION_LIB] [varchar](50) NULL,
                                                  [BENEFICIAIRE_NOM] [varchar](101) NULL)

 

       
       insert into @TB_OFFICE_InterventionIntervenant EXEC SYN_OFFICE_DN_ACADOMIA_GetInterventionByIntervenantId @INTERVENANT_BO_ID

 

       SELECT
             id=INTERVENTION_ID,
             client_nom=CLIENT_NOM,
             produit_libelle=PRODUIT_LIB,
             date_debut=DATEDEB,
             date_fin=DATEFIN,
             duree=INTERVENTION_DUREE,
              duree_heure=INTERVENTION_DUREE_HEURE,
             tarif_horaire=INTERVENTION_TARIF_HOR,
             salaire_net_horaire=INTERVENTION_SAL_NET_HOR,
             indic_urssaf=INTERVENTION_INDIC_URSSAF,
              evenement=EVENEMENT,
             date_creation=INTERVENTION_CREEQUAND,
             total_minute=TOTAL_MINUTE,
             total_temps=TOTAL_TEMPS,
             type_intervention_id=TYPEINTERVENTION_ID,
             type_intervention_libelle=TYPEINTERVENTION_LIB,
             beneficiaire_nom=BENEFICIAIRE_NOM
       FROM
             @TB_OFFICE_InterventionIntervenant

 

END
GO

 

USE [DEV_OFFICE]
GO

 

GRANT EXECUTE ON [dbo].[DN_ACADOMIA_GetInterventionByIntervenantId] TO [DOMIAGROUP\StarNet]
GO
GRANT EXECUTE ON [dbo].[DN_ACADOMIA_GetInterventionByIntervenantId] TO [StarNet]
GO

How can i do migration when i have multiple database schema?

**Comment by jzabroski** [comment]
Did you accidentally somehow deploy VersionInfo table into a different database, like master?

Or, did you remove the step in the sample that creates the VersionInfo table?

**Comment by Do-flamingo** [comment]
no i have execute one migration before and this table was created automaticaly, and i didn't touch this table

**Comment by jzabroski** [comment]
I don't have enough information to figure out what the problem is.  Without a good repro, I'm just making wild guesses.

Here's my last wild guess: Maybe consider not executing scripts with use statements:

```sql
USE [DEV_SHIVA]
GO
```

Going forward, I need more repro steps.

**Comment by jzabroski** [comment]
I don't have enough information to figure out what the problem is.  Without a good repro, I'm just making wild guesses.

Here's my last wild guess: Maybe consider not executing scripts with use statements:

```sql
USE [DEV_SHIVA]
GO
```

Going forward, I need more repro steps.

**Comment by Do-flamingo** [comment]
CAN i separate my script and into dev_shiva and dev_office and add tow times fluentmigrator wiht different connection string and then create tags for every connection strings

**Comment by jzabroski** [comment]
Create two separate runners.  There is currently no automatic support to sequence migrations across databases, especially if they have different schemas that have to be kept in sync, as that is highly idiosyncratic and based on the end users judgment.  My advice is to follow some convention around how you do releases.
