### ISSUE TITLE
How to get settings from EF Core DBBuilder?

### ISSUE THREAD

**Issue by Sellec** [fluentmigrator/fluentmigrator#1191]
We are using EF core 3.1 and fluentmigrator in one project and have similar settings for both - UseSqlServer(connStr)/AddSqlServer().WithGlobalConnectionString(connStr).
Is there any way to tell "FluentMigrator, this it the dboptionsbuilder/commonserviceprovider, you need to take settings from this"?

**Comment by jzabroski** [comment]
Lift the configuration up a level, inject it into both.  Problem solved.
