### ISSUE TITLE
public class in migration project cause exception

### ISSUE THREAD

**Issue by Saborion** [fluentmigrator/fluentmigrator#1212]
Don't know if this is expected behavior, but doubt it; didn't encounter this kind of issue when working on non-Core projects using a command line migrator.

Steps to reproduce:
1. Create .NET Core 3.1 library project
2. Add migration class with some random setup (hopefully that'll work)
3. Build project
4. Use the dotnet tool and run the following command (exchange name of database and dll):
    "dotnet fm migrate -p SqlServer2016 -c "server=.;Integrated Security=true;database=test" -a ".\bin\Debug\netcoreapp3.1\test.dll"
5. See how everything **works fine**
6. Add an empty class to project and make the class public
7. Rebuild project
8. Recreate database
9. Run command from step 4
10. Encounter "_Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified._"

**Comment by jzabroski** [comment]
It's a known issue.  The fix is described in #1178
