### ISSUE TITLE
GitVersion task fails to generate correct version number from tags

### ISSUE THREAD

**Issue by eloekset** [fluentmigrator/fluentmigrator#1213]
Part of #1061 moving to a different CI/CD service, the GitVersion task is automatically updated to use the latest 5.X version of GitVersion. According to [their release log](https://github.com/GitTools/GitVersion/releases), several bugs have been fixed in version 5.2.X, but the last version used in our pipeline that actually works correctly is version 5.1.3, so we'll have to update our build pipelines to use that specific version while we figure out how to keep using the latest version and still get the build number we want. 

In the following image, version 5.2.4 of GitVersion was used in the left build log. It incorrectly concluded to use base version 3.2.0 and ended up creating version number **3.3.0-tags-v3-2-5.1+89** for what should actually be version number **3.2.5**.
![image](https://user-images.githubusercontent.com/791721/79045896-f086b300-7c0d-11ea-9961-f978cdb7a3a6.png)

The right part of the image used version 5.1.3 of GitVersion. It correctly concluded to use base version **3.2.4** from our tags.

**Comment by jzabroski** [comment]
@eloekset I am manually deploying to nuget.org.  I think you set this up correctly as it gives us a chance to test the packages in AzureDevOps before pushing (in)directly to nuget.org.

As for GitVersion, what I read up on yesterday is the new approach is to create a GitVersion.yml (must by GitVersion.yaml and not GitVersion.y**a**ml) and create a `tag-prefix: '[vV]'` entry.  The GitVersion.yml approach looks extremely powerful, but very under-documented.

I suggest we add a build step using PowerShell to dump `GitVersion.exe /showconfig` as a build step.  It does not even need to be part of the same pipeline.  We can have a proxy pipeline called `FluentMigrator WhatIf` that doesn't build anything.  Basically, I'm trying to think of better ways to integration test changes to a cloud-based CI / CD server, as I'm used to on-premise where if I make a mistake, I can just delete my mistakes. Thoughts?

**Comment by jzabroski** [comment]
@eloekset It almost worked correctly - the issue was the nuget task was configured with the wrong wildcards, because we copy the artifacts in a folder called "drop" as part of our build pipeline.

![image](https://user-images.githubusercontent.com/447485/79048730-20718e80-7bed-11ea-9e16-5d2a1259b195.png)

I can see in the [build logs](https://dev.azure.com/fluentmigrator/fluentmigrator/_releaseProgress?_a=release-environment-logs&releaseId=38&environmentId=149) that this is the exact version of NugetCommand@2 we used (logging this for posterity sake in case they break something in the future):

```
2020-04-11T16:03:15.9818358Z Downloading task: NuGetCommand (2.167.5)
```

Next, for some reason NugetCommand 2.167.5 uses Nuget 4.1 (again, merely good to know):

```
020-04-11T16:03:32.8878068Z Caching tool: NuGet 4.1.0 x64
2020-04-11T16:03:32.8972985Z Found tool in cache: NuGet 4.1.0 x64
2020-04-11T16:03:32.9027616Z Resolved from tool cache: 4.1.0
2020-04-11T16:03:32.9028178Z Using version: 4.1.0
2020-04-11T16:03:32.9029832Z Found tool in cache: NuGet 4.1.0 x64
```

What's strange is `nuget.exe push` doesn't support a `--what-if` flag to do verification.

**Comment by eloekset** [comment]
Yes, there was something wrong with the path to the .nupkg files. The first stage uses $(System.DefaultWorkingDirectory), while the second stage used $(Build.ArtifactStagingDirectory). It's changed now, so it should work for the next release. Although not automatically, but that's by intention. It waits for approval from someone in the Release Administrators group, so we don't accidently push things to nuget.org unintentionally.

Regarding the issue with GitVersion, it sounds interesting to use a GitVersion.yml file. I'll read the documentation about that. The problem is that it's so difficult to test things, since it all depends on so many things and we have to commit to master and tag new versions to actually see the results. I can try it out in my own fork to avoid making too much noise in here.

**Comment by jzabroski** [comment]
@eloekset Yes, I agree with this:

> The problem is that it's so difficult to test things, since it all depends on so many things and we have to commit to master and tag new versions to actually see the results. I can try it out in my own fork to avoid making too much noise in here.

I discussed very briefly with CEO of GitHub Nat Friedman on Twitter, and asked him why GitHub doesn't support "deep forking", where if you clone the repository, you can also clone the GitHub Actions workflows associated with it.  He said, "Uh, it does".  This makes me second guess the decision to use AzureDevOps, but I think GitHub Actions and AzureDevOps pipelines will likely merge into a single product at some point.

To be honest, I don't even know if "deep forking" is the industry-standard term to describe what I want, but I hope the idea is self-explanatory: When you click Fork on GitHub, you not only fork the code, but also all the workflows, and therefore get your own CI/CD environment.

That said, AzureDevOps builds things very fast, and has a lot of user friendly features once you set it up correctly.  It's just configuring it that is a huge pain.

Anyway, I don't think we could've done a lot better than we did.  We dove head-first and figured it out as best as we could.

**Comment by jzabroski** [comment]
BTW, I found this very helpful: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/NuGetCommandV2/task.json

Reading the task.json for various tasks is actually better than reading the documentation, for some reason.

**Comment by jzabroski** [comment]
And here is the GitVersion.yml documentation: https://gitversion.net/docs/configuration

PRO TIP:  You can call gitversion /showconfig to effectively dump the in-memory configuration model to yaml!  This will save us a lot of time, as we just have to dump and save it to version control and it's a lock like a nuget lock assets file!

**Comment by jzabroski** [comment]
> It's changed now, so it should work for the next release.

I clicked redeploy based on your comments that its updated now.  Heading for a jog to get some exercise amids this quasi-lockdown situation.  Will check back in about an hour or so.
https://dev.azure.com/fluentmigrator/fluentmigrator/_releaseProgress?releaseId=38&_a=release-pipeline-progress  

I'm not sure if your edit applies only to the next release.  With Octopus Deploy, there is an option to "Update Variables" on a failed release and re-deploy to fix an issue (vs. deleting the release and re-creating it).  I'm not sure if this approach works with AzureDevOps or if we need a whole new build.

**Comment by jzabroski** [comment]
@eloekset it worked!

**Comment by eloekset** [comment]
Interesting.... Previously you'd have to create a new release (but not build) after editing the release pipeline. But I can see from the [run history of Release-38](https://dev.azure.com/fluentmigrator/fluentmigrator/_releaseProgress?releaseId=38&_a=release-environment-logs&environmentId=149) that the changes was applied when doing a redeploy. That's an improvement to Azure DevOps that's happened quite recently.

**Comment by jzabroski** [comment]
Yes. Octopus Deploy only added Update Variables about 16 months ago
