### ISSUE TITLE
EOL: SQL Server Compact Edition / SAP SQL Anywhere

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1229]
# SQL Server Compact Edition
SQL Sever Compact Edition is EOL in 14 months (July 2021).  Next version of FluentMigrator should warn users that we'll eventually drop support for this runner.

https://en.wikipedia.org/wiki/SQL_Server_Compact

⚠️ Users needing an upgrade path from SQL Server Compact Edition should look at SQL Server Express Edition for commercial use.  Developers using SQL Server Express Edition can develop solutions locally using [SQL Server Express LocalDB](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15), which is useful if you're a startup and trying to save licensing costs (however, LocalDB does not support network connections, so its not suitable for commercial usage).  However, I am not a software licensing expert, so you should have someone in your organization review any material licensing differences between SQL Server Compact Edition and SQL Server Express Edition. ⚠️ 

# SAP SQL Anywhere

SAP does not publish an official nuget package for SQL Anywhere.  Also, they have not updated the drivers for a very long time, and have not published any .NET Core support.  As a result, we are dropping support for SAP SQL Anywhere.

**Comment by jzabroski** [comment]
I tried installing SAP SQL Anywhere 17 today, on Windows 11.  While going through the installation, I got the following error:

![image](https://user-images.githubusercontent.com/447485/216781760-3d4a3961-487e-49da-8ba7-929004ecce8f.png)

I chose to "Install using compatibility settings".

I then got a Windows Defender access control prompt.

This brought me back through the SAP SQL Anywhere 17 InstallShield, where I selected Repair installation. Afterwards, I was asked:

![image](https://user-images.githubusercontent.com/447485/216781867-ca6f942d-0a0e-42be-9643-42db1e62e414.png)

I selected Yes, because I am not sure how to verify.

Additionally:

- When I go to http://sqlanywhere-forum.sap.com, in Chrome, I obviously get redirected to the https url, and it forwards me to https://130.214.205.148/ - I then get a privacy error, NET::ERR_CERT_COMMON_NAME_INVALID, indicating the common name on the SSL certificate is invalid.
- https://help.sap.com/viewer/product/SAP_SQL_Anywhere/17.0/en-US works correctly
- README is important. Indicates there is a Windows hotfix (KB 2719306) that must be installed if the database server hangs.

I created a test database via:

```cmd
dbinit -z "1252LATIN1" -zn "UCA" -i -dba "test","test" -mpl 4 -t "D:\source\GitHub\fluentmigrator\test\SqlAnywhereTestDatabase\test.log" "D:\source\GitHub\fluentmigrator\test\SqlAnywhereTestDatabase\test.db"
```

I was able to then successfully create a table foo:

```c#
using System.Data.Odbc;
// See https://aka.ms/new-console-template for more information

var connStringBuilder = new OdbcConnectionStringBuilder();
connStringBuilder.Dsn = "SQL Anywhere 17 test";
using var conn = new OdbcConnection(connStringBuilder.ConnectionString);
using var cmd = conn.CreateCommand();
cmd.CommandText = "CREATE TABLE foo (id int not null)";
conn.Open();
cmd.ExecuteNonQuery();
conn.Close();
Console.WriteLine("Created table foo!");
```

![image](https://user-images.githubusercontent.com/447485/216784395-cbd4b59d-fb1f-4f76-aa15-fa5397c24e19.png)

**Comment by eloekset** [comment]
Sorry for this SQLAnywhere issue. I was previously working for a company that insisted in using this abandoned DB. However, I can't see why you should spend time dealing with it anymore. If someone needs FluentMigrator for SQLAnywhere, they can use an old version.

I wish there was statistics for the usage of each provider, because my guess is that no-one is actually using FluentMigrator for SQLAnywhere anymore.

**Comment by jzabroski** [comment]
OK, noted. I will delete it

**Comment by jzabroski** [comment]
@eloekset And now Compact Edition is gone as well.

**Comment by jzabroski** [comment]
As an update here, I am almost done merging in Snowflake changes from the Develop branch as well as a few other things mentioned in the code merge Google Spreadsheet.  I have 37 failing tests, mostly around additional column name descriptions.  Sqlite BatchParserTests.cs is failing due to a mock that isn't being called but is expected to be called.

Get through these issues and 4.0 should be in the bag.
