### ISSUE TITLE
Use Execute.Script() come out "!!! Illegal characters in path" for no reason

### ISSUE THREAD

**Issue by Jason6809** [fluentmigrator/fluentmigrator#1237]
**Describe the question**
Use `Execute.Script()` come out 

> !!! Illegal characters in path

 error in PowerShell. Multiple time checked, the error come out for no reason
Tried absolute path also come out same error.

The Migration Code
```
using FluentMigrator;

namespace WPF_SQLite
{
    [Migration(20200428022647)]
    public class RenameColumnIdFromTablePersonToPersonId : Migration
    {
        public override void Up()
        {
            Execute.Script(@"Migrations\Scripts\20200428022647_RenameColumnIdFromTablePersonToPersonId.sql");
        }

        public override void Down()
        {
            Execute.Script(@"Migrations\Scripts\20200428022647_RenameColumnIdFromTablePersonToPersonId_Down.sql");
        }
    }
}
```
The PowerShell Command
` .\packages\FluentMigrator.Console.3.2.6\tools\net461\any\Migrate.exe -t:migrate -db Sqlite -configPath "D:\Jason Tam\Desktop\Playground\WPF (.NET Framework)\WPF_SQLite_Solution\WPF_SQLite\bin\Debug\WPF_SQLite.exe.config" -c "Data Source=.\WPF_SQLite\bin\Debug\Application.db" -a "D:\Jason Tam\Desktop\Playground\WPF (.NET Framework)\WPF_SQLite_Solution\WPF_SQLite\bin\Debug\WPF_SQLite.exe" -wd "D:\Jason Tam\Desktop\Playground\WPF (.NET Framework)\WPF_SQLite_Solution\WPF_SQLite\bin\Debug\" -verbose "TRUE"`

**Documentation Pages You've Read So Far**
Everything

**Expected benefit**
1. I'm still learning to use this framework and also new in WPF. Hoping someone professional can explain the error behind this problems and provide solution. Thank very much.

**Information (please complete the following information):**
 - OS: [ Windows 10 ]
 - Platform [ .NET Framework 4.7.2 ]
 - FluentMigrator version [ 3.2.6 ]
 - FluentMigrator runner  [ FluentMigrator.Console.3.2.6 ]
 - Database Management System [ SQLite ]
 - Database Management System Version [ SQLite Version 3 ]

**Additional context**
I used Alt.FluentMigrator.VStudio package to auto generate the migrations file and SQL script.

**Comment by jzabroski** [comment]
How familiar are you with PowerShell?

To avoid issues with PowerShell trying to handle parameters starting with `-` as special, it's best to construct all arguments as a PSObject and pass those to the executable you want to call via Start-Process.

I hate PowerShell. I'm ten times to hundreds times more productive in C#.

**Comment by jzabroski** [comment]
The other possibility is to use Shane Ray Visual Studio Whitespace Invisible Character plugin to see if you have a Unicode non printing character in the Script path in your C#

**Comment by jzabroski** [comment]
@Jason6809 Any update here?

**Comment by Jason6809** [comment]
@jzabroski 

Thanks very much for the suggestions. I will try it update here.
I also not very familiar with PowerShell and still learning on it.

I tested Execute.EmbeddedScript() method to run the SQL scripts, and it run flawlessly. 
I also tested Execute.Sql(), it run perfectly as well.
Only Execute.Script() will resulting error.

**Comment by jzabroski** [comment]
@Jason6809  Did you ever figure out how to execute this with PowerShell?  Thanks

**Comment by jzabroski** [comment]
@Jason6809  Hi - I am going to close this issue. Please re-open if you have renewed interest in getting help.
