### ISSUE TITLE
Included column in a unique index added as part of the unique constraint instead

### ISSUE THREAD

**Issue by anderslyman** [fluentmigrator/fluentmigrator#1250]
**To Reproduce**
Use the following:
```
Create.Index("IX_Foo").OnTable("Bar")
    .OnColumn("ID").Ascending()
    .WithOptions().Unique()
    .WithOptions().NonClustered()
    .Include("Baz");
```

It creates the index like this:
```
CREATE UNIQUE NONCLUSTERED INDEX [IX_Foo] ON [dbo].[Bar]
(
    [Baz] ASC
    [ID] ASC
)
```

**Expected behavior**
I would expect this to create an index with an included column, like so:
```
CREATE UNIQUE NONCLUSTERED INDEX [IX_Foo] ON [dbo].[Bar]
(
    [ID] ASC
)
INCLUDE([Baz])
```

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Standard 2.0
 - FluentMigrator version: 3.2.6
 - FluentMigrator runner: IMigrationRunner
 - Database Management System: SQLServer
 - Database Management System Version: Microsoft SQL Server 2012 (SP4-GDR) (KB4057116) - 11.0.7462.6 (X64)
--

**Comment by anderslyman** [comment]
Looking at this a little more - we have some tables where the index is created correctly, and others where it isn't (in the same database).

I'm trying to track down the difference between the tables...

**Comment by anderslyman** [comment]
Found the issue... This is our fault, and not a bug in FluentMigrator (although I may have a feature request now around being able to target file groups).
We have some custom code to move indices from the `Primary` file group to our `Index` file group, and apparently the drop/recreate involved in said moves is not considering "included" columns.

**Comment by jzabroski** [comment]
@anderslyman Note, one area for improvement is the fact that there are _**two ways for SQL Server engineers**_ to create unique constraints:

```c#
Create.UniqueConstraint("IX_Foo").OnTable("Bar")
                .Columns("ID", "Baz") // doesn't allow Included columns, but allows compound key
                .NonClustered();
```
and, arguably the nicer way as follows (nicer as in it is easier for programmatic manipulation):

```c#
Create.Index("IX_Foo").OnTable("Bar")
    // doesn't allow specifying multiple columns, but allows specifying sort direction
    .OnColumn("ID").Ascending() 
    .WithOptions().Unique()
    .WithOptions().NonClustered()
    .Include("Baz"); // allows Included column
```

As far as file groups go, there was somebody who was interested in adding support for #967 (see also #667)
