### ISSUE TITLE
Better Console logging

### ISSUE THREAD

**Issue by YeskaNova** [fluentmigrator/fluentmigrator#1252]
Console.WriteLine is polluting the console and there is no way to disable it ( in my stress tests, it prints hundreds of time exceptions that are well handled in my user code ). It could be better if we move that to proper Microsoft.Extensions.Logging.Console .

ex: https://github.com/fluentmigrator/fluentmigrator/blob/24df4a710481182388a5dcd5306a6231b24146d8/src/FluentMigrator.Runner.SqlServer/Processors/SqlServer/SqlServerProcessor.cs#L149

**Comment by jzabroski** [comment]
Resolved in 3.2.7. @YeskaNova  Please provide any feedback if you find further aspects of logging that need improvement.
