### ISSUE TITLE
VersionInfo table doesn't work in SQL Azure because no clustered index

### ISSUE THREAD

**Issue by jtreuting** [fluentmigrator/fluentmigrator#126]
http://blogs.msdn.com/b/sqlazure/archive/2010/04/29/10004618.aspx

SQL Azure requires all tables to have a clustered index.  It will let it be created but then the first time FM tries to insert a Version into it, it errors out so no migrations will run.  Right now you have to create that table manually yourself with a clustered index on the Version column.

**Comment by stilettk** [comment]
The pull request have been reverted and this problem is still there. Is there any solution or workaround is still needed?

**Comment by stilettk** [comment]
> I have merged in @AndyBareWeb 's pull request so this should be fixed now (#175).

@daniellee can we look at this again since #175 has been reverted and the problem is still there? I still have to use this workaround

**Comment by jzabroski** [comment]
It looks like it does get clustered, here: https://github.com/fluentmigrator/fluentmigrator/blob/f137ca71f5f6ecee49b061f1722ce4d7a31925d9/src/FluentMigrator.Runner.Core/Versioning/VersionMigration.cs#L82

Can you please check?
