### ISSUE TITLE
Naming conventions not working

### ISSUE THREAD

**Issue by KrisPetkov** [fluentmigrator/fluentmigrator#1264]
**Describe the bug**
After following the example provided by @fubar-coder for custom naming conventions as described here: https://github.com/fluentmigrator/fluentmigrator/issues/814#issuecomment-409585968 I'm facing two different issues:

1. My naming convention has not been applied at all
2. Getting "A circular dependency was detected for the service of type..." exception

* The above two depends whether I'm going to register it like this (for `1.` problem):

```csharp
services.AddSingleton<IConventionSet, NamingConventionSet>();

services.AddFluentMigratorCore()                 
                 .ConfigureRunner(rb => rb
                    .AddPostgres()
                    .WithGlobalConnectionString(connectionString)
                    .ScanIn(Assembly.GetExecutingAssembly()).For.Migrations());

services.AddScoped<IMigrationManager, MigrationManager>();
``` 

* Or like this (for `2.` problem):

```csharp
services.AddFluentMigratorCore()
                 .AddSingleton<IConventionSet, NamingConventionSet>()
                 .ConfigureRunner(rb => rb
                    .AddPostgres()
                    .WithGlobalConnectionString(connectionString)
                    .ScanIn(Assembly.GetExecutingAssembly()).For.Migrations());

services.AddScoped<IMigrationManager, MigrationManager>();
```

This is my IConventionSet implmentation:

```csharp
public class NamingConventionSet : IConventionSet
    {
        public NamingConventionSet()
            : this(new DefaultConventionSet(), new ForeignKeyNameConvention(), new IndexNameConvention())
        {
        }

        public NamingConventionSet(IConventionSet innerConventionSet, ForeignKeyNameConvention foreignKeyConvention, IndexNameConvention indexConvention)
        {
            ForeignKeyConventions = new List<IForeignKeyConvention>()
            {
                foreignKeyConvention,
                innerConventionSet.SchemaConvention,
            };

            IndexConventions = new List<IIndexConvention>
            {
                indexConvention
            };

            ColumnsConventions = innerConventionSet.ColumnsConventions;
            ConstraintConventions = innerConventionSet.ConstraintConventions;            
            SequenceConventions = innerConventionSet.SequenceConventions;
            AutoNameConventions = innerConventionSet.AutoNameConventions;
            SchemaConvention = innerConventionSet.SchemaConvention;
            RootPathConvention = innerConventionSet.RootPathConvention;
        }

        public IRootPathConvention RootPathConvention { get; }

        public DefaultSchemaConvention SchemaConvention { get; }

        public IList<IColumnsConvention> ColumnsConventions { get; }

        public IList<IConstraintConvention> ConstraintConventions { get; }

        public IList<IForeignKeyConvention> ForeignKeyConventions { get; }

        public IList<IIndexConvention> IndexConventions { get; }

        public IList<ISequenceConvention> SequenceConventions { get; }

        public IList<IAutoNameConvention> AutoNameConventions { get; }
    }
}
```

This is my IForeignKeyConvention implementation:

```csharp
public class ForeignKeyNameConvention : IForeignKeyConvention
    {
        public IForeignKeyExpression Apply(IForeignKeyExpression expression)
        {
            expression.ForeignKey.Name = GetForeignKeyName(expression.ForeignKey);

            return expression;
        }

        private string GetForeignKeyName(ForeignKeyDefinition foreignKey)
        {
            var fCol = string.Join('_', foreignKey.ForeignColumns);
            var pCol = string.Join('_', foreignKey.PrimaryColumns);

            var keyName = $"FK2_{foreignKey.ForeignTable}_{fCol }_{foreignKey.PrimaryTable}_{pCol }";

            return keyName;
        }
    }
```

**To Reproduce**
Run migration

**Expected behavior**
Custom naming convention to be applied without getting any errors

**Information (please complete the following information):**
 - OS: Windows 10 Pro
 - Platform .NET Core 3.1
 - FluentMigrator version: 3.2.6
 - FluentMigrator runner: "in-process runner"
 - Database Management System: PostgreSQL
 - Database Management System Version: 12.2

**Additional context**

I'm also having a migration manager (Unfortunately I can share only small part of it - its constructor). 

```csharp
public class MigrationManager
    {
        private readonly IFilteringMigrationSource _filteringMigrationSource;
        private readonly IMigrationRunner _migrationRunner;
        private readonly IMigrationRunnerConventions _migrationRunnerConventions;
        private readonly IMigrationContext _migrationContext;

        public MigrationManager(
            IFilteringMigrationSource filteringMigrationSource,
            IMigrationRunner migrationRunner,
            IMigrationRunnerConventions migrationRunnerConventions,
            IMigrationContext migrationContext)
        {
            _filteringMigrationSource = filteringMigrationSource;
            _migrationRunner = migrationRunner;
            _migrationRunnerConventions = migrationRunnerConventions;
            _migrationContext = migrationContext;
        }
}
```

I'm sharing this part because when I get the circular error this class is mentioned in the stack trace. I'm providing the detailed exception message: [Exception link](https://pastebin.com/tSkLaAhC)

**Workaround**
The workaround I have managed to find and to make everything works is to make the second constructor (the one that has argument) to be `private`

**Comment by jzabroski** [comment]
Off-topic comment:
A `MigrationManager` is effectively what #1208 seeks to achieve, although I think calling it `FluentMigratorApplication` is more likely.  Currently, the closest thing we have to this concept is `TaskExecutor` class.

Thanks for mentioning NopCommerce in the other thread (#1038), as it demonstrates people are effectively writing their own redundant `FluentMigratorApplication` class.

**Comment by jzabroski** [comment]
> I'm sharing this part because when I get the circular error this class is mentioned in the stack trace. I'm providing the detailed exception message: [Exception link](https://pastebin.com/tSkLaAhC)

So, I finally got a chance to grok what your issue is about.  The program is your MigrationManager class is creating a circular dependency.  I have not traced the graph myself, but I would guess passing in both an IMigrationRunner and IMigrationRunnerConventions to the same constructor is the root cause.  Please look at TaskExecutor in the source code to see how it is done there.  Note: I am not endorsing how that code is written, but it does avoid this problem.  I'd ideally like to refactor how that logic is done, but its nowhere near my top priority.

**Comment by KrisPetkov** [comment]
@jzabroski Thank you! I will have a look
