### ISSUE TITLE
Can't create a unique filtered index with included columns.

### ISSUE THREAD

**Issue by Powerz** [fluentmigrator/fluentmigrator#1278]
**Describe the bug**
FluentMigrator generates invalid SQL for a unique filtered index with included columns.

**To Reproduce**
```
Create.Index("IndexName")
    .OnTable("TableName")
    .OnColumn("Column1").Ascending()
    .OnColumn("Column2").Ascending()
    .WithOptions()
    .Unique()
    .WithOptions()
    .Include("Column3")
    .Filter("Column2 = 1");
```

This will result in the following SQL:
```
CREATE UNIQUE INDEX [IndexName]
    ON [dbo].[TableName] ([Column1] ASC, [Column2] ASC)    
    WHERE Column1 = 1
    INCLUDE ([Column3])
```

**Expected behavior**
```
CREATE UNIQUE INDEX [IndexName]
    ON [dbo].[TableName] ([Column1] ASC, [Column2] ASC)    
    INCLUDE ([Column3])
    WHERE Column1 = 1
```
The `WHERE` has to go right after `INCLUDE`.

**Information (please complete the following information):**
 - OS: MacOS Catalina 10.15.5.
 - Platform .net core 3.1
 - FluentMigrator version 3.2.7
 - FluentMigrator runner: in-process runner
 - Database Management System SQL Server
 - Database Management System Version: Microsoft SQL Server 2017 (RTM-CU10) (KB4342123) - 14.0.3037.1 (X64) 
	Jul 27 2018 09:40:27 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)

**Comment by jzabroski** [comment]
N.B. @gliljas .  I hope to get a chance to fix this weekend, unless you want to jump ahead of me.

**Comment by Powerz** [comment]
Hi guys, did you have a chance to take a look? No rush, just asking :)

Btw, thank you for working on this awesome project.
