### ISSUE TITLE
[Runner] VersionInfo not generated with -no--connection option

### ISSUE THREAD

**Issue by SebaVDP** [fluentmigrator/fluentmigrator#1284]
I don't have access to the database, so I am generating my script with -no--connection and --preview options.
When I don't define an --start-version or I put it on 0, no VersionInfo table is created in the generated script. 

I would like to have a way where the generated script also includes the VersionInfo Table.
For example by adding an specific option on the runner
Or by setting the option --start-version to 'i', 'initial' or '-1'.

Context:
I am using dotnet fm migrate ....
fluentmigrator.dotnet.cli      3.2.7        dotnet-fm

**Comment by jzabroski** [comment]
See: #1226
While that only mentions ConnectionlessVersionLoader and creating the initial VersionInfo table, it's the general way connectionless journaling is handled that needs improvement.
