### ISSUE TITLE
SQLite Rename Column

### ISSUE THREAD

**Issue by Chandler-Davidson** [fluentmigrator/fluentmigrator#1290]
SQLite previously did not support column renaming; however, since 2018-09-15 (v. 3.25.0), SQLite has supported it via the ALTER command. See: https://www.sqlite.org/changes.html

We should update the existing RenameColumn generator for SQLite to use the command. I'm unsure how we support versioning of databases, please let me know!

**Comment by jzabroski** [comment]
The way we support versioning is not super-modular, so it makes sense you wouldn't know how we do it.  The most common way is to recurse on the existing Generator by subclassing it and then overriding the virtual method that adds the incremental functionality.  Each new Generator in turn needs a new Processor and ProcessorId (see fluentmigrator.github.io for list of ids).

It would, in many ways, be ideal to allow metadata to be passed around and each individual piece to dispatch on the available metadata.  The downside to doing the metadata approach is then people have to step through more lines of code.

**Comment by southernprogrammer** [comment]
👍

**Comment by fairking** [comment]
[dotnet](https://www.nuget.org/packages/Microsoft.Data.Sqlite.Core/6.0.0-preview.3.21201.2) is considering to update the version of sqlite: https://github.com/dotnet/efcore/issues/24834
Also the [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core/) will be updated very soon: https://system.data.sqlite.org/index.html/doc/trunk/www/news.wiki
