### ISSUE TITLE
Use Nuget Installer task in AzureDevOps

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1306]
@eloekset  this will allow us to control what version of Nuget we use.

The default uses 4.x, which is rather odd.  I hard-coded it to use 5.4, as that has lots of bells and whistles.

![image](https://user-images.githubusercontent.com/447485/88239216-c2276380-cc51-11ea-9063-608ed8ee0008.png)

**Comment by eloekset** [comment]
oh, great! 👍
