### ISSUE TITLE
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found

### ISSUE THREAD

**Issue by vijayganeshpk** [fluentmigrator/fluentmigrator#1317]
**Describe the bug**]
Unable to run out of process migration on MacOS Catalina

When trying to run `dotnet-fm` getting error

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.6 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=osx.10.15-x64
```

**To Reproduce**
1. Install global tool `dotnet tool install -g FluentMigrator.DotNet.Cli`
2. Try to execute the tool even without any parameters `dotnet-fm`

**Expected behavior**
Get an help text

**Information (please complete the following information):**
 - OS: `MacOS Catalina 10.15.6`
 - Platform [.NET Framework 4.x / .NET Core 2.x , etc]: `.NET Core 3.1.302`
 - FluentMigrator version [ e.g 3.2.1 ]: `3.2.8`
 - FluentMigrator runner [ FluentMigrator.MSBuild, FluentMigrator.Console, FluentMigrator.DotNet.Cli, or "in-process runner" ]: `FluentMigrator.DotNet.Cli`
 - Database Management System [ SQLServer, SQLite, Mysql, Postgres, Firebird, Oracle, Redshift, DB2, DB2 ISeries, SAP Hana, SAP SQL Anywhere ]: `Postgres`
 - Database Management System Version [ e.g., "SQL Server 2019 Enterprise Edition", "Oracle 18xe", etc ]

**Additional context**
I am not even getting the initial help text message from `dotnet-fm`

**Comment by jzabroski** [comment]
Hi @vijayganeshpk Thanks for reporting this.  Unfortunately, this is not a bug - it is exactly what the message indicates.  When you run dotnet-fm, what you are actually running is dotnet.exe, so the error message you get is before dotnet-fm even executes.

The solution for now is to install .NET Core 2.1.  We're working on #1178
