### ISSUE TITLE
Create NuGet FluentMigrator.Runner.Common for remove dependencies to DB package from FluentMigrator.Runner

### ISSUE THREAD

**Issue by pippolino** [fluentmigrator/fluentmigrator#1327]
When the "FluentMigrator.Runner" package is included as a dependency, all packages from the various DB implementations are also included as they are called dependencies. Example: "**FluentMigrator.Runner.Db2**" or "**FluentMigrator.Runner.Oracle**"

It would be convenient to have a package just for "**FluentMigrator.Runner.dll**" by calling it "**FluentMigrator.Runner.Common**" and add this dependency to all packages related to DB implementations.

**Comment by jzabroski** [comment]
@pippolino Yes, that is under consideration.  I am guessing you closed this because you found the related issue.

**Comment by pippolino** [comment]
> 
> 
> @pippolino Yes, that is under consideration. I am guessing you closed this because you found the related issue.

Yes ... 👍
