### ISSUE TITLE
Can not able to run fluentmigrator's migration using command line with net core app 3.1 

### ISSUE THREAD

**Issue by ParthiKarnan** [fluentmigrator/fluentmigrator#1333]
I'm building .NET Core 3.1 application projects with PostgreSQL Databases. I'm trying to migrate all the tables to PostgreSQL database using fluentmigrator package from command line by using the below command. 

> "C:\Users\kpart\.nuget\packages\FluentMigrator\1.6.2\tools\migrate.exe" --assembly ".\src\EFCodeFirst\bin\Debug\netcoreapp3.1\EFCodeFirst.dll" --provider postgres --connectionString "User ID =postgres;Password=KzQMd384FVNc5Yh;Server=localhost;Port=5432;Database=EFCodeDB;Pooling=true;" --task migrate:up

When I run the above command I'm getting the below error.

-------------------------------------------------------------------------------
=============================== FluentMigrator ================================
-------------------------------------------------------------------------------
Source Code:
  http://github.com/schambers/fluentmigrator
Ask For Help:
  http://groups.google.com/group/fluentmigrator-google-group
-------------------------------------------------------------------------------
[+] Using Database postgres and Connection String User ID =postgres;Password=********;Server=localhost;Port=5432;Database=EFCodeDB;Pooling=true;
**!!! Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.** 

Correct me If I did anything wrong here.

Kindly let me know is there any solution to resolve this problem?

Kind regards,
Parthiban.

**Comment by jzabroski** [comment]
@ParthiKarnan It looks like you're using an ancient version of the FluentMigrator runner.  Can you please upgrade to the latest version?

> ```
> "C:\Users\kpart.nuget\packages\FluentMigrator\1.6.2\tools\migrate.exe" 
>                                                                               ^^^----- ANCIENT VERSION
> ```

**Comment by jasonsultana** [comment]
I'm actually getting this same problem, using the `dotnet fm` tool on OSX.

```
dotnet tool update -g FluentMigrator.DotNet.Cli
Tool 'fluentmigrator.dotnet.cli' was reinstalled with the latest stable version (version '3.2.10').
dotnet fm list migrations -p MySQL5 -a "./bin/Debug/netcoreapp3.1/ClassNotes.Data.dll"

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

What's very curious is that I can't even find version 4.2.2 of System.Runtime on Nuget at https://www.nuget.org/packages/System.Runtime/. 

Any ideas?

**Comment by jzabroski** [comment]
@jasonsultana This is a very different issue. Your problem is with computing the transitive closure of dependencies at startup when your Migrations reference a system assembly from netcoreapp3.1 or higher.

**Comment by jzabroski** [comment]
The workaround is to create an in process runner
