### ISSUE TITLE
Ignore Attribute

### ISSUE THREAD

**Issue by mtugnoli** [fluentmigrator/fluentmigrator#1344]
In my class I have a field that doesn't exist on the database, is there a function to ignore it?

**Comment by jzabroski** [comment]
@mtugnoli Thanks for your question, but I'm not sure what you are asking. FluentMigrator doesn't directly use class properties. Can you please upload some sample code or rephrase your question?

**Comment by mtugnoli** [comment]
Sorry, you are right !, I was studing a project, but is my error !!
Thank you anyway !
