### ISSUE TITLE
Add support for PgSQL partial indexes

### ISSUE THREAD

**Issue by ig-sinicyn** [fluentmigrator/fluentmigrator#1367]
Fluent migrator does support filtered index creation for SQL Server. It will be nice to have same feature for PG SQL.

As a real-world use case, we need to add unique constraint for nullable columns treating null as unique value.
There're [some solutions on stackoverflow](https://stackoverflow.com/questions/8289100/create-unique-constraint-with-null-columns) but no one can be easily made via FluentMigrator api.

**Is this a feature you'd like to submit a PR for?**
No

**Comment by jzabroski** [comment]
@lillo42 Can I assign this to you?

**Comment by lillo42** [comment]
@jzabroski  sure, no problem

**Comment by jzabroski** [comment]
This is the last feature for 3.2.10.  Release notes are already drafted, I just need @lillo42 to fix merge conflicts and for me to click merge.
