### ISSUE TITLE
Rollback not working when get error in migration up

### ISSUE THREAD

**Issue by seanmars** [fluentmigrator/fluentmigrator#1377]
**Describe the bug**
When migration up, if get error the rollback not working properly.

**To Reproduce**
1. Create a Migration class like below

```csharp
[Migration(1)]
public class CreateUserTable : Migration
{
	public override void Up()
	{
		Create.Table("test");
			.WithColumn("id").AsInt32().PrimaryKey()
			.WithColumn("value").AsInt32();

		Create.Index("ix_value")
			.OnTable("test")
			.OnColumn("wrong_column");
	}

	public override void Down()
	{
		Delete.Table("test");
	}
}
```

2. Use this class to do migration up
3. It will get error "!!! Key column 'wrong_column' doesn't exist in table"
4. After it, it still get the `test` table in database

**Expected behavior**
I think in this migration it will rollback all action in `Up` function. The `test` table should not be exist in database.

**Information (please complete the following information):**
 - OS: [ Windows 10 ]
 - Platform [ .NET core 3.1 ]
 - FluentMigrator version [ 3.2.9 ]
 - FluentMigrator runner [ "in-process runner" ]
 - Database Management System [ MySQL ]
 - Database Management System Version [ 5.7 / 8.0 ]

**Additional context**

**Comment by jzabroski** [comment]
@seanmars I think this is because MySQL does not support transactional DDL like SQL Server.

**Comment by seanmars** [comment]
> @seanmars I think this is because MySQL does not support transactional DDL like SQL Server.

Ok, I see, I found some information of it. You are right, MySQL does not support transactional DDL.

Sorry I am new here.
