### ISSUE TITLE
Check constraint is not created in Azure Database

### ISSUE THREAD

**Issue by RodionM** [fluentmigrator/fluentmigrator#1378]
I have a migration that creates CHECK constraint for a table.
Examples:
Simple example
`alter table [TableName] add constraint [C_ConstraintName] check (not ([IsDefault] = 1 and dbo.IntScalarFunction() > 1));`

Example of SQL server generated script for needed constraint
```
ALTER TABLE [dbo].[TableName]  WITH CHECK ADD  CONSTRAINT [C_ConstraintName] CHECK  ((NOT ([IsDefault]=(1) AND [dbo].[IntScalarFunction]()>(1))))
GO
ALTER TABLE [dbo].[TableName] CHECK CONSTRAINT [C_ConstraintName]
GO
```

Examples were run in migration as raw SQL via Execute.Sql method.

When I run this migration against default MS SQL database all works fine, constraint is being created.
When I run this migration against Azure hosted database all looks fine, there are no errors, migration is reported as executed one but constraint is not created.
When I run raw SQL script against Azure hosted database all works fine, constraint is being created.

Does anyone have any experience with creation of CHECK constraints using migrations in Azure database?

**Comment by jzabroski** [comment]
Hi @RodionM

This all looks good to me.

If you have a typo you can create extensions methods on Migration class to avoid typos as much as possible
