### ISSUE TITLE
Relative ConnectionStringConfigPath does not work

### ISSUE THREAD

**Issue by enemysik** [fluentmigrator/fluentmigrator#1388]
ConnectionStringConfigPath arguments does not work at a case of relative value. 
For example:
I run a command from powershell like:
`C:\git\tmp> C:\Git\exmaple\Aso.Web\bin\Migrate\Migrate.exe -a "..\Aso.DataAccess.dll" -db:SqlServer2014 -profile "SeedDebug" -conn "DataContext" --connectionStringConfigPath "..\Aso.Web.dll.config"` it ends with error (console output below)

In case i run it directly from from directory where Migrator.exe is:
`C:\Git\exmaple\Aso.Web\bin\Migrate> .\Migrate.exe -a "..\Aso.DataAccess.dll" -db:SqlServer2014 -profile "SeedDebug" -conn "DataContext" --connectionStringConfigPath "..\Aso.Web.dll.config"`
it work normally.

With absolute path 
`C:\git\tmp> C:\Git\exmaple\Aso.Web\bin\Migrate\Migrate.exe -a "..\Aso.DataAccess.dll" -db:SqlServer2014 -profile "SeedDebug" -conn "DataContext" --connectionStringConfigPath "C:\Git\exmaple\Aso.Web\bin\Aso.Web.dll.config"`
it also works normally.

Output from console:
```
-------------------------------------------------------------------------------
=============================== FluentMigrator ================================
-------------------------------------------------------------------------------
Source Code:
  https://github.com/fluentmigrator/fluentmigrator
Ask For Help:
  https://gitter.im/FluentMigrator/fluentmigrator
-------------------------------------------------------------------------------
!!! Specified configuration file path does not exist
Parameter name: path
```
**Information (please complete the following information):**
 - OS: Windows 10 Enterprise 
 - Platform .NET Framework 4.7.2
 - FluentMigrator version 3.2.1
 - FluentMigrator runner, FluentMigrator.Console
 - Database Management System SQLServer

**Additional context**

**Comment by fubar-coder** [comment]
A relative path is relative to the current directory - not relative to the location of the executable.

**Comment by fubar-coder** [comment]
I misread the issue.

**Comment by fubar-coder** [comment]
It's somewhat confusing, but it seems that DLLs are loaded relative to the path of the external runner while the configuration file is loaded relative to the current path.

**Comment by enemysik** [comment]
Ok if everything works as intended, I close the issue

**Comment by jzabroski** [comment]
Probably worth updating docs

**Comment by jzabroski** [comment]
Added link to document this.  Thanks for bringing this up, @enemysik
