### ISSUE TITLE
Warning when building with `AutoGenerateBindingRedirects` (Found conflicts between different versions of ...)

### ISSUE THREAD

**Issue by Socolin** [fluentmigrator/fluentmigrator#1392]
**Describe the bug**
When building with flag AutoGenerateBindingRedirects to true we get warnings

```
PS D:\temp\ReproFluentMigrator> dotnet build
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored D:\temp\ReproFluentMigrator\Repro.csproj (in 199 ms).
C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "System.Data.SqlClient" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\temp\ReproFluentMigrator\Repro.csproj]
C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "System.Security.AccessControl" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\temp\ReproFluentMigrator\Repro.csproj]
C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "System.Security.Permissions" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\temp\ReproFluentMigrator\Repro.csproj]
C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "System.Security.Principal.Windows" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\temp\ReproFluentMigrator\Repro.csproj]
  Repro -> D:\temp\ReproFluentMigrator\bin\Debug\netcoreapp3.1\Repro.dll

Build succeeded.

C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "System.Data.SqlClient" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\temp\ReproFluentMigrator\Repro.csproj]
C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "System.Security.AccessControl" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\temp\ReproFluentMigrator\Repro.csproj]
C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "System.Security.Permissions" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\temp\ReproFluentMigrator\Repro.csproj]
C:\Program Files\dotnet\sdk\5.0.101\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3277: Found conflicts between different versions of "System.Security.Principal.Windows" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\temp\ReproFluentMigrator\Repro.csproj]
    4 Warning(s)
    0 Error(s)
```

**To Reproduce**

Just run `dotnet build` with the following `Repro.csproj` and `Program.cs`

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FluentMigrator.Runner" Version="3.2.9" />
	</ItemGroup>
</Project>
```

Program.cs
```c#
namespace Repro
{
	public class Program
	{
		static void Main(string[] args)
		{
		}
	}
}
```

**Expected behavior**
No warning

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Core 3.1
 - FluentMigrator version 3.2.9

**Additional context**
`dotnet info`

```
PS D:\temp\ReproFluentMigrator> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.103 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
````

**Workaround**
```
		<PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
		<PackageReference Include="System.Security.Permissions" Version="4.7.0" />
```

**Comment by jzabroski** [comment]
I am pretty sure you can't use AutoGenerateBindingRedirects in .NET Core apps.  I asked Microsoft to confirm, since the documentation doesn't explicitly say you can't... or what the behavior is.

https://github.com/dotnet/project-system/issues/3677

**Comment by Socolin** [comment]
> I am pretty sure you can't use AutoGenerateBindingRedirects in .NET Core apps. I asked Microsoft to confirm, since the documentation doesn't explicitly say you can't... or what the behavior is.
> 
> [dotnet/project-system#3677](https://github.com/dotnet/project-system/issues/3677)

I don't know, I just upgraded from net472, I don't have this problem on any other projects.

If this has no effect in .NET Core I would expect the flag to be ignored or better, to get a warning about removing this.

When I build with this flag, I get a `<runtime>` section in the <Assembly>.dll.config. I don't know if this has any effects, I'll do some testings.

**Comment by jzabroski** [comment]
You can run the following in cmd to enable host tracing:

```
setx CORE_HOSTTRACE 1
```

I dont recommend running this in pwsh (PowerShell), because PowerShell 7 is itself a .NET Core app, and you will get a lot of confusing messages from POwerShell's own host tracing.

**Comment by jzabroski** [comment]
> I don't know, I just upgraded from net472, I don't have this problem on any other projects.

Just wondering - how did you upgrade?  Make sure you clean the whole solution manually, by deleting all bin and obj directories (recommend you do it manually or after you check in your changes to source control to avoid accidentally deleting wrong files).

Basically, the workflow is:

1. git reset . --hard
2. git status # ensure no changes
3. rm --recurse --force **/bin/* && rm --recurse --force **/obj/*
4. update csproj (you can use https://github.com/hvanbakel/CsprojToVs2017 or similar tools)
5. dotnet restore
6. dotnet build

This will take care of various things that might get cached in your obj file, which the SDK uses as a cache.

**Comment by Socolin** [comment]
I tried what I reported you into a new directory so there is no cache problem possible. (2 file into a new directory then `dotnet build`)

The `runtime` section is present in the .dll.config so `dotnet build` still generate it

**Comment by jzabroski** [comment]
OK.  But I don't think it does anything, as https://github.com/dotnet/project-system/issues/3677 mentions it's a bug to generate an app.config (which is no different than a .dll.config).  It's possible they only fixed the app.config scenario and not .dll.config scenario.  But there is no commit on that issue, so it's hard to know how they resolved it.  I just know the auto binding redirect generation docs dont mention .NET Core or .NET 5.

**Comment by jzabroski** [comment]
@Socolin Can you open a new issue in the dotnet/project-system repo.  I am fairly certain this is a bug.  It appears they handled it for app.config but not dll.config.

**Comment by jzabroski** [comment]
To elaborate, .NET Core generates a deps.json file which dotnet.exe uses to pass to the runtime a list of all assemblies it has to load.  It does this in conjunctton with a runtimeHosts.json (or however you spell it).  The "new" binding redirect is `<RollForward>Major</RollForward>` but it doesn't work great.  You can smooth out some issues as long as the EXE isn't referencing obsolete APIs that no longer exist in the new runtime's FrameworkReference.  The idea of a FrameworkReference is it basically specifies a set of "in-box" nuget packages as a "meta-package" that encapsulates all Base Class Libraries and things that used to ship into the GAC.  Then, rather than assume all customers want a GAC, .NET Core takes the stance of by default allowing customers to do a "framework-dependent deployment".  Prior to .NET Core 2.1, this meant that your executable/binary copied all BCL dlls into your deployment directory.  Later, they added FrameworkReference so that instead you could pull in these dependencies from a global cache, and control how "far forward" you are willing to take upgrades/hotfixes.  Major RollForward means you will allow infinitely high runtime versions, but there is a very high chance you will hit missing APIs if someting is obsolete (as Entity Framework, ASP.NET and other "out-of-box" nuget packages are prone to do.  Minor RollForward was nice in theory, but dumb in practice.  As an example, .netcoreapp3.0 is LTS and .netcoreapp3.1 is not, but since the default is Minor RollForward, you end up rolling forward to the 3.1 runtime if it is installed.  Most open source developers recommend LatestFeature RollForward because it most closely aligns with SemVer 2.0 guarantees about no breaking changes.

This is a 120 second tutorial to bring you up to speed.

**Comment by Socolin** [comment]
Ok, Thanks a lot for the explanation

I thought it was working same way as before, I'll do some research to understand this in details when I found some time.

I removed all `AutoGenerateBindingRedirects` from my project and it works, so I suppose I can close this issue.
