### ISSUE TITLE
Missing documentation and examples on relationships

### ISSUE THREAD

**Issue by SergejSachs** [fluentmigrator/fluentmigrator#1415]
There are missing examples how fluent migrator works with .net core entity mapping on relations.

Creating one table is pretty simple. 
One to many is little bit more complicated. 

Many to Many is just try and error without a documentation on every new project im working on without accessing the old codebase.

**Comment by jzabroski** [comment]
@SergejSachs There is no concept of many to many in FluentMigrator.  Just primary keys and foreign keys.  Can you please elaborate what you're looking for?  I get the sense you're looking for EntityFramework code-first migrations.  How did you find out about FluentMigrator?  Thanks.

**Comment by SergejSachs** [comment]
Yes its about the relation between entity framework and fluent migrators default behaviours.
Would be nice to have just an example documentation on that because that's probably the way to go in .NET Core.
