### ISSUE TITLE
InSchema vs WithSchema

### ISSUE THREAD

**Issue by KiLLeRRaT** [fluentmigrator/fluentmigrator#1420]
**Describe the question**
In most cases, when using Fluent Syntax you will use `InSchema(...)` but when you say, create a UniqueConstraint, you have to use `WithSchema(...)`.

e.g.:
```
Alter.Table("ObjectService").InSchema("SCH")...
```
vs

```
Create.UniqueConstraint("UC_Object_ObjectID_ServiceType").OnTable("ObjectService").WithSchema("SCH");
```

Why is that? Why not have it `InSchema` across the board?

Sorry if this is a silly question, but I couldn't find a clear answer anywhere.

Cheers,

EDIT: Just found this inconsistency while writing the `Down()`

```
Create.UniqueConstraint("UC_Object_ObjectID_ServiceType").OnTable("ObjectService").**WithSchema**("SCH");
```
vs
```
Delete.UniqueConstraint("UC_Object_ObjectID_ServiceType").FromTable("ObjectService").**InSchema**("SCH");
```

**Comment by jzabroski** [comment]
I think a lot of these small inconsistencies are due to being an open source project and perhaps less than perfect review process.

**Comment by jzabroski** [comment]
https://www.strathweb.com/2018/12/using-roslyn-c-completion-service-programmatically/

Actually looking like it might be possible!
