### ISSUE TITLE
Can't run migrations, Could not load file or assembly 'System.Runtime, Version=4.2.2.0'

### ISSUE THREAD

**Issue by bionanek** [fluentmigrator/fluentmigrator#1428]
**Describe the question**
Hey everyone. 
I've written few migrations in my project. It's a .NET Core Class Library project. 
I've added FluentMigrator 3.2.15 and FluentMigrator.Runner 3.1.15 nugget packages to it. 
When I'm trying to run these migrations using dotnet cli like so: 

```
dotnet fm migrate -p sqlserver -c "data source=localhost;initial catalog=MyDb;persist security info=True;Integrated Security=SSPI" -a ".\bin\Debug\netcoreapp3.1\myProject.DB.dll"
```

it builds VersionInfo table, but when it starts running one of my migrations it throws an error:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

Not sure if this is a bug or i am doing something wrong... 

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform: .NET 5, .NET Core 3.x
 - FluentMigrator version: 3.2.15
 - Database Management System: MsSQL
 - Database Management System Version: 2018

**Comment by jzabroski** [comment]
Did you look at the release notes

**Comment by bionanek** [comment]
Not really, only docs on your documentation website.

**Comment by jzabroski** [comment]
Please see: https://github.com/fluentmigrator/fluentmigrator/releases/tag/v3.2.15

Use --allowDirtyAssemblies

We need to update https://github.com/fluentmigrator/documentation to mention this flag.  Come to think of it, we probably should catch unhandled exceptions and see if it's an exception of this type `System.IO.FileNotFoundException` where Message starts with `"Could not load file or assembly 'System.Runtime"` - if you'd like to add a PR for that, that would be great!  The unhandled exception handler should throw once it prints a message communicating to consider using this workaround.

**Comment by jzabroski** [comment]
Created doc issue https://github.com/fluentmigrator/documentation/issues/42

**Comment by fubar-coder** [comment]
Looking for the text `Could not load file or assembly` will most likely only on systems with an english locale.

**Comment by jzabroski** [comment]
@fubar-coder Good point.  Is there any other thing we filter we could use that is locale neutral?  I guess we could check for just "`System.Runtime`".  But, this issue can also happen with out-of-box dependencies like System.ComponentModel.DataAnnotations, so maybe we shouldn't bother filtering at all?

**Comment by bionanek** [comment]
Hey guys! Thanks, @jzabroski, your solution helped and saved me a lot of time.
I will consider preparing PR for that but can't really right now, so don't promise ;)

**Comment by rom5jp** [comment]
I'm facing the same issue but on .NET 6.

I'm trying to run the following command: 
`.\Migrate.exe migrate --allowDirtyAssemblies --conn "Server=xxx;Port=xxx;Database=xxx;user=xxx;password=xxx;" --provider mysql --assembly "C:\...\bin\Debug\net6.0\myproject.dll" --task rollback --output --outputFilename output.sql`

When running that I receive the follow message: **!!! Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.**

Any help with .NET 6?
