### ISSUE TITLE
Postgres Identity column does not work

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [fluentmigrator/fluentmigrator#1445]
**Describe the bug**
The identity option, as well the the default sequential id value do not work with postgres

**To Reproduce**
```
            services.AddFluentMigratorCore()
                .ConfigureRunner(fluentMigratorBuilder => fluentMigratorBuilder
                    .AddPostgres()
                    .WithGlobalConnectionString(connectionString)
                    .ScanIn(AssemblyWithMigrations).For.Migrations()
                )
                .AddLogging(lb => lb.AddFluentMigratorConsole());
```

With the uuid-ossp installed as an extension on my postgres database the following migration results in an integer primary key:
```
Create.Table("Players")
.WithColumn("Id").AsGuid().NotNullable().PrimaryKey().Identity()
.WithColumn("FirstName").AsString()
```

This results in a PK uuid which seems promising:
```
Create.Table("Players")
.WithColumn("Id").AsGuid().NotNullable().PrimaryKey().WithDefault(SystemMethods.NewSequentialId)
.WithColumn("FirstName").AsString()
```

however when I attempt the following query:
`insert into "Players" VALUES ('George')`

I get the following error
```
ERROR:  invalid input syntax for type uuid: "George"
LINE 1: insert into "Players" VALUES ('George')

```
It seems then that I cannot have an auto generating uuid.

an int identity also doesnt work:
```
Create.Table("Players")
                .WithColumn("Id").AsInt32().NotNullable().PrimaryKey().Identity()
                .WithColumn("FirstName").AsString().NotNullable();
```

results in a primary key but not an identity column.
```
ERROR:  invalid input syntax for type integer: "George"
LINE 1: insert into "Players" VALUES ('George')
```

**Expected behavior**
An identity column should be generated

**Information (please complete the following information):**
 - OS: [ Windows 10 ]
 - Platform [.Net Core 5 / PostgreSQL 13]
 - FluentMigrator version [  3.2.15 ]
 - FluentMigrator runner [ "in-process runner" ]
 - Database Management System [ Postgres ]
 - Database Management System Version [ "pgAdmin 4" ]

**Comment by jzabroski** [comment]
@lillo42 can you please look

**Comment by CraigComeOnThisNameCantBeTaken** [comment]
Reproduced on mac os with postgres 13 as well.

**Comment by lillo42** [comment]
@CraigComeOnThisNameCantBeTaken the problem is your insert query.

The correct query:
```sql
insert into "Players" ("FirstName") VALUES ('George') 
```

When you create a table with default, that means if you don't pass a value Postgres will use the default value, and in your query you don't explicit the column, so PostgreSQL is assuming  you need to pass all column.

About this part:

```c#
Create.Table("Players")
    .WithColumn("Id").AsGuid().NotNullable().PrimaryKey().Identity()
```
doesn't make sense you use AsGuid and Identity together because Identity is for int or long only.

**Comment by lillo42** [comment]
@CraigComeOnThisNameCantBeTaken the problem is your insert query.

The correct query:
```sql
insert into "Players" ("FirstName") VALUES ('George') 
```

When you create a table with default, that means if you don't pass a value Postgres will use the default value, also in your query you don't explicit the column, so PostgreSQL is assuming  you are going to pass all column.

About this part:

```c#
Create.Table("Players")
    .WithColumn("Id").AsGuid().NotNullable().PrimaryKey().Identity()
```

It doesn't make sense you use AsGuid and Identity together because Identity is for int or long only.

And about this:

```c#
Create.Table("Players")
                .WithColumn("Id").AsInt32().NotNullable().PrimaryKey().Identity()
                .WithColumn("FirstName").AsString().NotNullable();
```
We generated this query:

```sql
create table "Players"
(
    "Id" serial not null primary key,
    "FirstName" text not null
);
```

Postgres translate it for:

```sql
create table "Players" (
    "Id" integer NOT NULL DEFAULT nextval('Players_id_seq'),
    "FirstName" text not null
);
```

So you need to specific the column too. 

For insert query the best thing is use explicit column,  I always do it.

**Comment by CraigComeOnThisNameCantBeTaken** [comment]
> @CraigComeOnThisNameCantBeTaken the problem is your insert query.
> 
> The correct query:
> 
> ```sql
> insert into "Players" ("FirstName") VALUES ('George') 
> ```
> 
> When you create a table with default, that means if you don't pass a value Postgres will use the default value, also in your query you don't explicit the column, so PostgreSQL is assuming you are going to pass all column.
> 
> About this part:
> 
> ```cs
> Create.Table("Players")
>     .WithColumn("Id").AsGuid().NotNullable().PrimaryKey().Identity()
> ```
> 
> It doesn't make sense you use AsGuid and Identity together because Identity is for int or long only.
> 
> And about this:
> 
> ```cs
> Create.Table("Players")
>                 .WithColumn("Id").AsInt32().NotNullable().PrimaryKey().Identity()
>                 .WithColumn("FirstName").AsString().NotNullable();
> ```
> 
> We generated this query:
> 
> ```sql
> create table "Players"
> (
>     "Id" serial not null primary key,
>     "FirstName" text not null
> );
> ```
> 
> Postgres translate it for:
> 
> ```sql
> create table "Players" (
>     "Id" integer NOT NULL DEFAULT nextval('Players_id_seq'),
>     "FirstName" text not null
> );
> ```
> 
> So you need to specific the column too.
> 
> For insert query the best thing is use explicit column, I always do it.

Im very sorry! Im sorry I wasted your time and thanks for the help. This was 10/10 stupid.
