### ISSUE TITLE
Add documentation on running tests with in-memory databases

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [fluentmigrator/fluentmigrator#1446]
**Is your feature request related to a problem? Please describe.**
There is no documentation on how to use fluentmigrator with inmemory tests in the same style as EF.

**Describe the solution you'd like**
Documentation should be added.

**Additional context**
I have implemented this myself. Details for which can be found in my answer on stackoverflow here:
https://stackoverflow.com/questions/53282474/how-to-test-fluent-migrations-with-an-in-process-migration-runner-and-a-in-memor/66926940#66926940

**Is this a feature you'd like to submit a PR for?**
I can if this proves a popular idea.

**Comment by schambers** [comment]
Created new issue on documentation repo here: https://github.com/fluentmigrator/documentation/issues/73
