### ISSUE TITLE
Fluent Migrator 3.2.1 Timeout occurring when running sql script that runs long

### ISSUE THREAD

**Issue by josephbaggettgainsco** [fluentmigrator/fluentmigrator#1471]
How do I change the timeout on the migration runner to handle sql scripts that take too long to execute but are completely valid going through FluentMigrator 3.2.1?

        /// <summary>
        /// Configure the dependency injection services
        /// </summary>
        private static IServiceProvider CreateServices()
        {
            return new ServiceCollection()
             // Add common FluentMigrator services
             .AddFluentMigratorCore()
             .Configure<RunnerOptions>(cfg =>
              {
                  cfg.Profile = !String.IsNullOrEmpty(profile) ? profile : string.Empty; 
              })
             .ConfigureRunner(rb => rb
                 // Add SQLite support to FluentMigrator
                 .AddSqlServer2016()
                 // Set the connection string
                 .WithGlobalConnectionString(GetConnectionString())
                 
                 // Define the assembly containing the migrations
                 .ScanIn(typeof(EmptyDatabaseMigration).Assembly).For.Migrations())

             // Enable logging to console in the FluentMigrator way
             .AddLogging(lb => lb.AddFluentMigratorConsole())
             // Add AssemblySourceItem to run VersionTableInfo updates
             .AddSingleton<IAssemblySourceItem>(new AssemblySourceItem(Assembly.GetAssembly(typeof(EmptyDatabaseMigration))))
             // Build the service provider
             .BuildServiceProvider(false);

        }

        /// <summary>
        /// Update the database
        /// </summary>
        private static void UpdateDatabase(IServiceProvider serviceProvider)
        {

            // Instantiate the runner
            var runner = serviceProvider.GetRequiredService<IMigrationRunner>();

            // will create testdata
            if (allowDatabaseToBeRebuilt)
            {
                runner.MigrateDown(0);
            }

            if (migrationRollbackNumber.HasValue)
            {
                runner.MigrateDown(migrationRollbackNumber.Value);
            }
            else
            {
                //runner.RunnerContext.Timeout = 0;
                // Execute the migrations
                runner.MigrateUp();
            }
        }

I tried to set the RunnerContext.Timeout to 0, but it is not fixing the issue.  I can run these sql statements manually and they simply just run.

Joseph

**Comment by fubar-coder** [comment]
Did you try a timeout value of `-1`? IIRC, [Timeout.Infinite](https://docs.microsoft.com/en-us/dotnet/api/system.threading.timeout.infinite?view=net-5.0) (for example) is defined as `-1`.
