### ISSUE TITLE
Password to sql server is logged as plain text, when connection string contains whitespace around equality mark

### ISSUE THREAD

**Issue by wiciok** [fluentmigrator/fluentmigrator#1479]
**Describe the bug**
Password to sql server is logged as plain text, when connection string contains whitespace around equality mark, ex.  `'Password = examplepassword'`

**To Reproduce**
Use FluentMigrator with SQL Server connection string, that contains whitespace around equality mark, ex. 
`Server = 127.0.0.1;Database = FluentMigrator;Password = pass@123;User Id = MyUser`

**Expected behavior**
Password should be logged in masked form, regardless of whitespace in connection string

**Additional context**
I've opened PR with fix: #1478

**Comment by jzabroski** [comment]
I will try to release 3.2.16 today  CC @lillo42 as well - sorry this has been delayed.  Still getting my energy levels up after recovering from COVID-19.
