### ISSUE TITLE
Get "FileNotFound" error when running migration through dotnet-fm

### ISSUE THREAD

**Issue by Lopopix** [fluentmigrator/fluentmigrator#1481]
**Problem**
For a new project I installed the latest version of FluentMigrator (3.2.15) and everything needed to build my script with dotnet-fm.
When I launch the command, I get a "FileNotFound" error, saying it can not load FluentMigrator.dll

After downgrading of packages to a version used in another project (v3.2.1), it works (without any other change). Is it possible that something has change since v3.2.1 ?

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform: .NET Framework 4.6..2

**Comment by fubar-coder** [comment]
Maybe it's a version mismatch (wrong assembly binding redirect)?

**Comment by jzabroski** [comment]
In your test environment, if you use the flag to allow dirty assemblies, does is still work?

**Comment by schambers** [comment]
In an effort to organize existing issues and due to age, this ticket is being closed. If you feel like the issue still applies, please open a new ticket and we'll review for future addition. Thank you!
