### ISSUE TITLE
FluentMigrator.DotNet.Cli does not work with .Net Standard 2.1 or .Net 5 projects

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [fluentmigrator/fluentmigrator#1491]
**Describe the bug**
If the project which holds the migrations is not .Net Standard 2.0 and you attempt to run migrations using the dotnet-fm migration runner you will experience a Sytem.Runtime missing exception.

**To Reproduce**
Create a new .Net Standard 2.1 OR .NET 5 library
Install FluentMigrator from nuget
Globally (or locally) install FluentMigrator.DotNet.Cli
Run a migration command using dotnet-fm

**Expected behavior**
The migration should work

**Information (please complete the following information):**
 - OS: [Windows 10 ]
 - Platform [.NET Standard 2.1 OR .NET 5]
 - FluentMigrator version [ e.g 3.2.7 ]
 - FluentMigrator runner [FluentMigrator.DotNet.Cli]
 - Database Management System [ Postgres ]

**Additional context**
It would be good if this restriction was documented somewhere for now

**Comment by jzabroski** [comment]
@CraigComeOnThisNameCantBeTaken Yes, the workaround for now is to run the FluentMigrator.DotNet.Cli with the flag `--allowDirtyAssemblies`.  This workaround needs to be documented on the github.io page.  It would be great if you could update that and add a section to the FAQ.  The docs are available at http://github.com/fluentmigrator/documentation - I love when people help contribute documentation!

The two pages are:
1. https://fluentmigrator.github.io/articles/runners/dotnet-fm.html
2. https://fluentmigrator.github.io/articles/faq.html

Also, it looks like the link to the FAQ from the main landing page is broken/incorrect.  It should be https://fluentmigrator.github.io/articles/faq.html  But it is resolving to xref:faq.md - ugh.

**Comment by jzabroski** [comment]
Also, `--allowDirtyAssemblies` I believe was added in 3.2.15 , so if you are on 3.2.7 like your issue says, then recommendation is to upgrade.

I am hoping to finally push my branch for .net 5 out very soon - recovering from COVID-19 took much longer than anticipated, and I was pretty much useless for 10-12 weeks.

**Comment by CraigComeOnThisNameCantBeTaken** [comment]
> @CraigComeOnThisNameCantBeTaken Yes, the workaround for now is to run the FluentMigrator.DotNet.Cli with the flag `--allowDirtyAssemblies`. This workaround needs to be documented on the github.io page. It would be great if you could update that and add a section to the FAQ. The docs are available at [http://github.com/fluentmigrator/documentation](https://github.com/fluentmigrator/documentation) - I love when people help contribute documentation!
> 
> The two pages are:
> 
> 1. https://fluentmigrator.github.io/articles/runners/dotnet-fm.html
> 2. https://fluentmigrator.github.io/articles/faq.html
> 
> Also, it looks like the link to the FAQ from the main landing page is broken/incorrect. It should be https://fluentmigrator.github.io/articles/faq.html But it is resolving to xref:faq.md - ugh.

Sure - happy to :). Ill have a look tonight (uk time)

P.S. I am on 3.2.17 - typo.

**Comment by jzabroski** [comment]
@CraigComeOnThisNameCantBeTaken How did this work for you?

**Comment by jzabroski** [comment]
I updated the docs btw

**Comment by jzabroski** [comment]
Documents here: https://fluentmigrator.github.io/articles/runners/dotnet-fm.html#net-runtime-related-switches

Also updated the faq.

**Comment by CraigComeOnThisNameCantBeTaken** [comment]
> @CraigComeOnThisNameCantBeTaken How did this work for you?

Havent tested yet (I previously broke my migrations into a dedicated project to make them work) but Im sure it will.

Sorry I didnt get around to the docs PR - night got away from me.
