### ISSUE TITLE
SAP Hana - incorrect default type for boolean column

### ISSUE THREAD

**Issue by yavorsp** [fluentmigrator/fluentmigrator#1506]
**Describe the bug**
Followup of issue #1447 The issue with mapping of boolean to SAP Hana SQL column type is fixed in v3.2.17, however default initialization still uses integer type.

**To Reproduce**
Create.Table("NODE").WithColumn("ACL").AsBoolean().NotNullable().WithDefaultValue(true);
results in following SQL code:
CREATE COLUMN TABLE "NODE" ("ACL" BOOLEAN DEFAULT 1);
Correct should be
CREATE COLUMN TABLE "NODE" ("ACL" BOOLEAN DEFAULT TRUE);

**Expected behavior**
Ability to set default value for boolean type.

**Information (please complete the following information):**
 - OS: SAP Cloud Foundry
 - Platform: .NET Core 2.x
 - FluentMigrator version: 3.2.17
 - FluentMigrator runner: "in-process runner"
 - Database Management System: SAP Hana
 - Database Management System Version SAP HANA Schemas & HDI Containers

**Additional context**
NA

**Comment by jzabroski** [comment]
This will be fixed in 6.0.0
