### ISSUE TITLE
Runner for json file

### ISSUE THREAD

**Issue by MiroslavMikus** [fluentmigrator/fluentmigrator#1508]
**Describe the question**
We often change our C# classes and stored values and would need to reflect this in our JSON files. At best in some maintainable and automatic manner. So here am I searching for some C# gems -_^. 

Can be this framework used/extended to migrate JSON (or any text) files?

**Documentation Pages You've Read So Far**
Could not find any...

**Expected benefit**
We don't want to reinvent the wheel! 
Disclaimer: I have never used this framework yet.
So some guess here: If we could get something Newtonsoft Runner / Text-File Runner, developers could reuse a lot of the fluentmigrator functionality and migrate theirs JSON files. 

**Information (please complete the following information):**
 - OS: Win 10 
 - Platform .Net 5

Thanks in advice

**Comment by jzabroski** [comment]
@MiroslavMikus I dont know what this request means.  I dont understand what migrating a json file means.  I would probably suggest looking into Simon Cropp's DiffEngine for snapshot testing.
