### ISSUE TITLE
Add support for NullsDistinct() / NullsNotDistinct() for Postgre uinque indexes

### ISSUE THREAD

**Issue by ig-sinicyn** [fluentmigrator/fluentmigrator#1525]
We have a migration for Postgres that creates an index over two columns, one of them is non-nullable.
We want to mimic MsSql behavior (nulls are treated as the same value) and to forbid duplicates like this:
```
 Name     OwnerId
------- ----------
 User1       NULL
 User1       NULL
```

There're NullsDistinct() / NullsNotDistinct() extension methods for MsSql server (actually, it does in reverse, allowing nulls to be treated as a distinct values), but there are no such helpers for Postgres.

[There are](https://stackoverflow.com/q/8289100) two well-known approaches In PgSql

1. Create a secondary index with `WHERE OwnerId IS NULL` filter. Generally it is not a good solution as its nontrivial to apply if you have more than one nullable column in unique index.
2. Wrap column with `Coalesce(OwnerId, '00000000-0000-0000-0000-000000000000')` expression.

I'd prefer to have a helper for the second approach, or, at least, a way to set a custom expression for `.OnColumn()` calls.

**Is this a feature you'd like to submit a PR for?**
No :(

**Comment by jzabroski** [comment]
```c#
Create.Index
                .OnTable(GeneratorTestHelper.TestTableName1)
                .OnColumn(GeneratorTestHelper.TestColumnName1).Ascending().NullsDistinct()
                .OnColumn(GeneratorTestHelper.TestColumnName2).Descending()
                .WithOptions().UniqueNullsNotDistinct();
```

**Comment by jzabroski** [comment]
@lillo42 Is this something you're interested in adding?

**Comment by lillo42** [comment]
@ig-sinicyn I think postgres doesn't have this functions, so you need to do this manually with filter:

```c#
Create.Index()
                .OnTable("")
                .OnColumn("").Ascending()
                .WithOptions()
                .Filter("Column IS NOT NULL");
```

@jzabroski what do you think? since Postgres doesn't have `NULL DISTINCT` should we add it and handle multi-column manually and filter? (I think this can be a bit complicated, specially when we are going to multi-column as null or null distinct and some filter)

**Comment by ig-sinicyn** [comment]
@lillo42 
Hi!

MS SQL does not have built-in option to manage null comparison, too. The NullsDistinct() / NullsNotDistinct() helpers [do something similar](https://github.com/fluentmigrator/fluentmigrator/blob/9c87d698b161b3a1bb596a5624c02891a64459c5/src/FluentMigrator.Runner.SqlServer/Generators/SqlServer/SqlServer2008Generator.cs#L98-L100) to what you've proposed.

**Comment by jzabroski** [comment]
@lillo42 This tutorial is probably the explanation you are looking for: https://www.enterprisedb.com/postgres-tutorials/postgresql-unique-constraint-null-allowing-only-one-null

**Comment by jzabroski** [comment]
@lillo42 See previous reply. I assigned it to you. Feel free to un-assign yourself if you're not that interested.
