### ISSUE TITLE
.Net 6 Support

### ISSUE THREAD

**Issue by WajahatAliAbid** [fluentmigrator/fluentmigrator#1544]
The new .net 6 LTS was released last month. However there is no support for it with Fluent Migrator CLI. Is it expected to be released soon?

**Comment by lszczygielek** [comment]
In dependencies section https://www.nuget.org/packages/FluentMigrator/ you can see that FluentMigrator is .NETStandard2.0, so it should work with .NET 6 without issues.

**Comment by jzabroski** [comment]
@lszczygielek Sort of.  You would need to enable the allow dirty assembly resolve flag.

I am hoping to get a chance to work on FluentMigrator again very soon.  I got delayed this year due to some Long Covid symptoms, but am past that now and just been catching up on life.

**Comment by Pikachews** [comment]
Do I still need to install .NET 5 in order to run dotnet-fm with .NET 6?
I get an error saying that .NET 5 is missing when I try to run it with .NET 6 as my only SDK installed, and it doesn't appear that `--allowDirtyAssembly` helps. Is there a way around that?

I'm trying to avoid having to install .NET 5 (since I'm running on M1 and trying to avoid having to install Rosetta), but if that's the only way then so be it, although that leads me to wonder what `--allowDirtyAssembly` does if I'm still required to have .NET 5 installed to run it.

**Comment by jzabroski** [comment]
Short term, yes.  I am hoping to get to .NET 6 support this week.  The stupid SAP stuff is holding us back.

**Comment by gwin003** [comment]
Came across this issue while trying to upgrade our projects to .NET 6. Has there been any progress made on this lately? 

I decided to throw together a docker image that has both .NET 5 and .NET 6 installed so we can use it in our Bitbucket Pipeline, but still getting an error when running `dotnet-fm`.

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at FluentMigrator.Runner.Initialization.AssemblySourceMigrationRunnerConventionsAccessor.<>c.<.ctor>b__1_1(Assembly a) in D:\a\1\s\src\FluentMigrator.Runner.Core\Initialization\AssemblySourceMigrationRunnerConventionsAccessor.cs:line 50
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at FluentMigrator.Runner.Initialization.AssemblySourceMigrationRunnerConventionsAccessor.<>c__DisplayClass1_0.<.ctor>b__0() in D:\a\1\s\src\FluentMigrator.Runner.Core\Initialization\AssemblySourceMigrationRunnerConventionsAccessor.cs:line 50`

**Comment by Pikachews** [comment]
> Came across this issue while trying to upgrade our projects to .NET 6. Has there been any progress made on this lately?
> 
> I decided to throw together a docker image that has both .NET 5 and .NET 6 installed so we can use it in our Bitbucket Pipeline, but still getting an error when running `dotnet-fm`.
> 
> ```
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
>    at System.Reflection.RuntimeAssembly.GetExportedTypes()
>    at FluentMigrator.Runner.Initialization.AssemblySourceMigrationRunnerConventionsAccessor.<>c.<.ctor>b__1_1(Assembly a) in D:\a\1\s\src\FluentMigrator.Runner.Core\Initialization\AssemblySourceMigrationRunnerConventionsAccessor.cs:line 50
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator 2.MoveNext()
>    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable 1 source, Func 2 predicate, Boolean& found)
>    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at FluentMigrator.Runner.Initialization.AssemblySourceMigrationRunnerConventionsAccessor.<>c__DisplayClass1_0.<.ctor>b__0() in D:\a\1\s\src\FluentMigrator.Runner.Core\Initialization\AssemblySourceMigrationRunnerConventionsAccessor.cs:line 50
> ```

Did you add the `--allowDirtyAssemblies` switch? I believe that should fix your issue.

**Comment by gwin003** [comment]
@Pikachews Yes I have that switch in place. Here's the command I'm running.

```
dotnet-fm 
    migrate 
    -a NET6Project.Database/bin/Debug/net6.0/NET6Project.Database.dll 
    -p MySql5 
    --allowDirtyAssemblies
    --tag $DB_TAG 
    -c "SERVER=127.0.0.1;UID=$DB_MYSQL_USER;PWD=$DB_MYSQL_PASSWORD;Database=$DB_MYSQL_DATABASE;AllowUserVariables=True"
```

**Comment by fwhenin** [comment]
Are there any updates to supporting .NET 6?

**Comment by jzabroski** [comment]
I'm making progress but only have so many free hours.

**Comment by juanchavezlive** [comment]
Any update about this issue ? :(

**Comment by jseekamp** [comment]
I would love to help out with this, but I want to make sure my efforts would be in the correct place. Is https://github.com/fluentmigrator/fluentmigrator/pull/1451 where the work is being done?

**Comment by jzabroski** [comment]
Hi @jseekamp 
I had prototyped something for .NET 3.1 awhile ago - see #1178 - I got sick with long covid and never finished it up. Doing better now but lost a lot of life time healing up.

**Comment by jseekamp** [comment]
@jzabroski Really sorry to hear that. Hope you fully recover soon. Would it make more sense to drop #1178 in favor of #1451 and jump directly to .net 6?

**Comment by crimcol** [comment]
Stuck on same issue. I want to use Migrate.exe instead of dotnet-fm to support both .net framework and .net 6.

**Comment by jseekamp** [comment]
My issue is that I can't run migrate at all since I'm on a Macbook Pro M1. .net 5 doesn't support ARM based CPUs.

**Comment by jzabroski** [comment]
> My issue is that I can't run migrate at all since I'm on a Macbook Pro M1. .net 5 doesn't support ARM based CPUs.

@jseekamp Initially, your comment reads as off-topic. Did you mean to additionally say, ".NET 6 support resolves this problem, because [.NET 6 is the first release that supports ARM-based CPUs](https://devblogs.microsoft.com/dotnet/announcing-net-6/)"?

**Comment by jzabroski** [comment]
I'm actually very close to shipping .NET 6 support.  I got Covid (again) 3 weeks ago, so it delayed things a bit again.

**Comment by jake-carpenter** [comment]
> My issue is that I can't run migrate at all since I'm on a Macbook Pro M1. .net 5 doesn't support ARM based CPUs.

@jseekamp You can get .NET 5 installed using Rosetta, but it will be a separate binary and (I believe, correct me if I'm wrong) it has to be run from a terminal that is also using Rosetta.

I have the same issue, but don't use the .NET 5 binary because I'm in a situation where I need cross-platform support and have reverted to building my migration projects as an EXE in the meantime.


> I'm actually very close to shipping .NET 6 support. I got Covid (again) 3 weeks ago, so it delayed things a bit again.

Very sorry to hear about the health issues. Hope you stay healthy. I'm excited to hear it's getting close though.

**Comment by jseekamp** [comment]
> > My issue is that I can't run migrate at all since I'm on a Macbook Pro M1. .net 5 doesn't support ARM based CPUs.
> 
> @jseekamp Initially, your comment reads as off-topic. Did you mean to additionally say, ".NET 6 support resolves this problem, because [.NET 6 is the first release that supports ARM-based CPUs](https://devblogs.microsoft.com/dotnet/announcing-net-6/)"?

Yes, sorry this exactly what I meant to say.

**Comment by Andrioden** [comment]
Any news on this? @jzabroski , would be great to get rid of .net 5 workaround that we have to place in our dockerfiles and build scripts in .net 6 projects.

**Comment by NatMarchand** [comment]
Hi there!
Although it'd be great to have net6 supported, you can totally run dotnet-fm having just net6. The key is to allow roll forward for dotnet with an environment variable (DOTNET_ROLL_FORWARD).

```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS builder

RUN dotnet tool install FluentMigrator.DotNet.Cli --tool-path /fm

FROM mcr.microsoft.com/dotnet/runtime:6.0

RUN useradd -ms /bin/bash app

WORKDIR /fm

COPY --from=builder --chown=app:app /fm .

COPY --chown=app:app . .

ENV DOTNET_ROLL_FORWARD=LatestMajor

ENTRYPOINT [\
    "/fm/dotnet-fm", "migrate",\
    "--processor", "${FM_PROCESSOR}",\
    "--assembly", "${FM_ASSEMBLY}",\
    "--connection", "\"${FM_CONNECTION_STRING}\"",\
    "up"\
]

```

**Comment by gwin003** [comment]
@jzabroski Any updates on this? Anything we can do to move this issue along?

**Comment by jzabroski** [comment]
@gwin003 
> Anything we can do to move this issue along?

Sure!
I wanted to:

1. merge in the Snowflake connector from the [v4.0.0-dev](https://github.com/fluentmigrator/fluentmigrator/tree/v4.0.0-dev) branch 
2. move the SAP SqlAnywhere processor to use regular ADO.NET OdbcConnection https://learn.microsoft.com/en-us/dotnet/api/system.data.odbc.odbcconnection?view=dotnet-plat-ext-7.0
3. Sunset SQL Server Compact Edition support - it should just go away and people should use LocalDB if they need something similar, or use SQLite going forward since its designed for embedded use cases.

The latter 2 issues are covered here: https://github.com/fluentmigrator/fluentmigrator/issues/1229

**Comment by johannessorheim** [comment]
@jzabroski Would it be possible to make the following change and create a new release, so we are able to run dotnet-fm on net6.0 om Mac M1 processor?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/8747772/213822028-c38fbd61-01cb-4603-9a3f-6dcad2f54760.png">

**Comment by vmandic** [comment]
a big +1 for @johannessorheim suggestion, now also with `net7.0` actually?

**Comment by hcasado** [comment]
@jzabroski i have time to help you refactoring/coding/testing what you need for get .Net 6 Support working.

**Comment by hcasado** [comment]
> Hi there! Although it'd be great to have net6 supported, you can totally run dotnet-fm having just net6. The key is to allow roll forward for dotnet with an environment variable (DOTNET_ROLL_FORWARD).
> 
> ```
> FROM mcr.microsoft.com/dotnet/sdk:6.0 AS builder
> 
> RUN dotnet tool install FluentMigrator.DotNet.Cli --tool-path /fm
> 
> FROM mcr.microsoft.com/dotnet/runtime:6.0
> 
> RUN useradd -ms /bin/bash app
> 
> WORKDIR /fm
> 
> COPY --from=builder --chown=app:app /fm .
> 
> COPY --chown=app:app . .
> 
> ENV DOTNET_ROLL_FORWARD=LatestMajor
> 
> ENTRYPOINT [\
>     "/fm/dotnet-fm", "migrate",\
>     "--processor", "${FM_PROCESSOR}",\
>     "--assembly", "${FM_ASSEMBLY}",\
>     "--connection", "\"${FM_CONNECTION_STRING}\"",\
>     "up"\
> ]
> ```

Thanks for that, you give me a chance to think diferent about what I need in my project.

FluentMigrator is realy a great tool, for several reason all here know.

I use version from nuget, I dont want to compile my own version of FM

Right now there is a dependency to Microsoft.Extensions.DependencyInjection 2.0.0, but I want to keep updated with new delivered versions.

So finally, I divided my app in 3 diferent solutions:
1. WebApp for UI
2. WebApi for Microservices
3. Last but not least, a microservice for only apply migrations

Larga vida a FluentMigrator !

**Comment by jzabroski** [comment]
Thanks.  Sorry for the lack of follow-up.  I got pretty sick recently and am better now.  I welcome your help if you still have time.

**Comment by robertcoltheart** [comment]
I got tired of waiting and made this: https://www.nuget.org/packages/FluentMigratorBridge which lets you use just a single database runner instead of referencing them all.

**Comment by cryptoswarm** [comment]
Any news on this? @jzabroski

**Comment by jzabroski** [comment]
Done. 4.0.0 will ship shortly.
