### ISSUE TITLE
Postgres10_0 / Postgress11_0: When altering column, migrator ignores collation.

### ISSUE THREAD

**Issue by maxkornev** [fluentmigrator/fluentmigrator#1545]
Trying to update column collation using Postgres11 generator. But result SQL script doesn't contain a collation change statement.

The bug can be reproduced by the following test in FluentMigrator.Tests project:

```
[Test]
        public void CanAlterColumnWithCollation()
        {
            var expression = GeneratorTestHelper.GetAlterColumnExpressionWithCollation();

            var result = Generator.Generate(expression);

            result.ShouldBe(@"ALTER TABLE ""public"".""TestTable1"" ALTER ""TestColumn1"" TYPE varchar(20) COLLATE " + GeneratorTestHelper.TestColumnCollationName + @", ALTER ""TestColumn1"" SET NOT NULL;");
        }
```

Expected result: ALTER TABLE "public"."TestTable1" ALTER "TestColumn1" TYPE varchar(20) COLLATE Latin1_General_CS_AS, ALTER "TestColumn1" SET NOT NULL;
Actual result: ALTER TABLE "public"."TestTable1" ALTER "TestColumn1" TYPE varchar(20), ALTER "TestColumn1" SET NOT NULL;

**Comment by jzabroski** [comment]
@maxkornev Would you like to submit a PR to fix it?  Can publish right away.  CanAlterColumnWithCollation is currently only tested on SQL Server....  It looks like the base Postgres*Tests class should have this logic, similar to how SQL Server 2005 tests contain this logic and other processors inherit it.

**Comment by jzabroski** [comment]
@maxkornev I see that what you're saying is the method `SqlServer2005GeneratorTests.CanAlterColumnWithCollation` should also apply to the Postgres generator:

https://github.com/fluentmigrator/fluentmigrator/blob/9c87d698b161b3a1bb596a5624c02891a64459c5/test/FluentMigrator.Tests/Unit/Generators/SqlServer2005/SqlServer2005GeneratorTests.cs#L387-L395

but the logic should be:

```
        [Test]
        public void CanAlterColumnWithCollation()
        {
            var expression = GeneratorTestHelper.GetAlterColumnExpressionWithCollation();

            var result = Generator.Generate(expression);

            result.ShouldBe(@"ALTER TABLE ""public"".""TestTable1"" ALTER ""TestColumn1"" TYPE varchar(20) COLLATE " + GeneratorTestHelper.TestColumnCollationName + @", ALTER ""TestColumn1"" SET NOT NULL;");
        }
```

I'm not sure why you're expecting Postgres to have Latin1_General_CS_AS collation.  That's a SQL Server defined collation, I believe.

What do you see when you run:

```sql
SELECT * 
FROM pg_collation;
```

Thanks

**Comment by jzabroski** [comment]
@lillo42 Any interest in looking at this bug?

**Comment by jzabroski** [comment]
@maxkornev Based on the Postgres docs: https://www.postgresql.org/docs/current/sql-altertable.html

```
where action is one of:

    ADD [ COLUMN ] [ IF NOT EXISTS ] column_name data_type [ COLLATE collation ] [ column_constraint [ ... ] ]
    DROP [ COLUMN ] [ IF EXISTS ] column_name [ RESTRICT | CASCADE ]
    ALTER [ COLUMN ] column_name [ SET DATA ] TYPE data_type [ COLLATE collation ] [ USING expression ]
```

It appears Postgres is somewhat unique in that collation should be done as part of specifying the data type.
