### ISSUE TITLE
Getting error "The certificate chain was issued by an authority that is not trusted"

### ISSUE THREAD

**Issue by henebb** [fluentmigrator/fluentmigrator#1565]
Not sure where to put this, but not really a bug. But perhaps something worth clearifying somewhere? If not already clarified? I tried to look, but couldn't find anything. I might have searched poorly, and then you can just delete this question :)

But, since the release of v3.3.2 of FluentMigrator (where System.Data.SqlClient was replaced with Microsoft.Data.SqlClient) we started getting exceptions when connecting to our SQL Servers (2019). We're running on .NET Framework (v4.7.2).
The exception message we got was `A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)`
According to this [blog post by Rick Strahl](https://weblog.west-wind.com/posts/2021/Dec/07/Connection-Failures-with-MicrosoftDataSqlClient-4-and-later); v4 of Microsoft.Data.SqlClient has started encrypt data by default. And this is why we got the exception. It was fixed by adding `Encrypt=False` to the connection string. Of course, we should fix the certificate. So not an error in FluentMigrator. But perhaps this could be mentioned somewhere? If others are getting the same error?

**Comment by henebb** [comment]
Created a PR for this: https://github.com/fluentmigrator/documentation/pull/53 Not sure how to link to that PR in a more appropriate way 😄

**Comment by jzabroski** [comment]
Thank you.  Merged it already.
