### ISSUE TITLE
fluentmigrator   sqlite   BUG  ArgumentException

### ISSUE THREAD

**Issue by icetech233** [fluentmigrator/fluentmigrator#1570]
sqlite 

bool a  = this.Schema.Table("plu").Column("price_his").Exists();

System.ArgumentException:“Type of value has a mismatch with column typeCouldn't store <0> in dflt_value Column.  Expected type is Byte[].”

**Comment by icetech233** [comment]
i find fluentmigrator  bug and  fix  it

**Comment by mattbrailsford** [comment]
Can close this issue as was resolved in #1580
