### ISSUE TITLE
FluentMigrator.Console and FluentMigrator.DotNet.Cli cannot apply migrations to MariaDB 10.6+

### ISSUE THREAD

**Issue by braveyp** [fluentmigrator/fluentmigrator#1574]
**Describe the bug**
FluentMigrator.Console gives a cryptic error if you try to apply any migrations to a MariaDB 10.6 or later database:

!!! The given key was not present in the dictionary.

FluentMigrator.DotNet.Cli gives a slightly different error:

Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '28265' was not present in the dictionary.

**To Reproduce**

Attempt to apply one or more migrations against a database on MariaDB 10.6 using either migrate.exe or dotnet-fm.

**Expected behavior**
It should run the migrations....

**Information (please complete the following information):**
 - OS: Windows
 - Platform: cli tools
 - FluentMigrator version [ e.g 3.2.1 ] 3.3.2
 - FluentMigrator runner FluentMigrator.Console, FluentMigrator.DotNet.Cli
 - Database Management System: MariaDB
 - Database Management System Version 10.6 or 10.7

**Additional context**
MariaDB changed the way it handles utf8 in 10.6 and now returns results in utf8mb3. MySql.Data.8.0.11, which the current released tools depends on, doesn't support utf8mb3 which is why the command line tools fail as soon as it tries to check for the existence of the VersionInfo table. The fix is to update the tools to use MySql.Data.8.0.28 which is when Oracle added support for utf8mb3.

**Comment by jzabroski** [comment]
Will publish 4.0 soonish. No exact ETA. @mattbrailsford is helping modernize our Sqlite stack.
