### ISSUE TITLE
Issue with Maintenance Migrations (BeforeAll and AfterAll)

### ISSUE THREAD

**Issue by dorlandode** [fluentmigrator/fluentmigrator#1591]
**Describe the question**
I am having issues getting the Maintenance migrations to run.  I trying to run the BeforeAll and AfterAll MigrationStages, but they will not execute.
I have several migrations that run successfully, but the BeforeAll and AfterAll are not working as I would expect.

Example code:
```
[Maintenance(MigrationStage.BeforeAll, TransactionBehavior.Default)]
public class MigrationBeforeAll : Migration
{
    public override void Up()
    {
    }
    public override void Down()
    {
    }
}
```

```
[Maintenance(MigrationStage.AfterAll, TransactionBehavior.None)]
public class MigrationAfterAll : Migration
{
    public override void Up()
    {
    }
    public override void Down()
    {
    }
}
```

From the Startup.cs
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    var runner = app.ApplicationServices.GetRequiredService<IMigrationRunner>();
    runner.MigrateUp();
    ...
}
```
webapi csproj file:
```
<PackageReference Include="FluentMigrator.Runner" Version="3.3.2" />
<PackageReference Include="FluentMigrator.Runner.Postgres" Version="3.3.2" />
```

As a work-around I found that if I call my Maintenance Migrations from the startup like this it works, but my understanding is that this is not expected.
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    var runner = app.ApplicationServices.GetRequiredService<IMigrationRunner>();
    runner.Up(new MigrationBeforeAll());
    runner.MigrateUp();
    runner.Up(new MigrationAfterAll());
    ...
}
```

**Documentation Pages You've Read So Far**
https://fluentmigrator.github.io/articles/faq.html

I have also been reviewing the source code.  Specifically the following classes:
FluentMigrator.Runner.MigrationRunner
FluentMigrator.Tests.Unit.Runners.MaintenanceLoaderTests

**Expected benefit**
I expect the MigrationStage.BeforeAll and AfterAll to run before all migrations and after all migrations respectively.

**Information (please complete the following information):**
 - OS: Windows 11
 - Platform: .NET Core 3.1.x
 - FluentMigrator:  3.3.2
 - FluentMigrator runner: Running from the Startup.cs file.
 - Database Management System: Postgres
 - Database Management System Version: 14.2

**Comment by jzabroski** [comment]
I don't think there is enough information here to reproduce your issue, because it sounds like a configuration issue where you're using an in-process runner in a Website  hosting context.

That said, your maintenance migrations are empty - so how are you determining they aren't being run?

I'd recommend adding at least a Windows Event Pipe log message so you can verify. - Note, you are using Windows 11, so Windows Event Log Viewer should be there in your environment, assuming your Information section above is accurate.

**Comment by dorlandode** [comment]
I emptied them out, for posting on here, but I set a break point, which was never hit in debug.  I was attempting to do an advisory lock.

**Comment by jzabroski** [comment]
There is one other thing to check, which is that you are scanning the assembly that contains maintenance migrations.  The current Scanner syntax needs improvement. See #1231

**Comment by tboothman** [comment]
I have the same issue. I have pretty much the quickstart code and a postgres db lock I made using the code from https://fluentmigrator.github.io/articles/faq.html#database-dependent-application-locking

Code from program.cs:
```csharp
using (ServiceProvider serviceProvider = new ServiceCollection()
    // Add common FluentMigrator services
    .AddFluentMigratorCore()
    .ConfigureRunner(rb => rb
        // Add SQLite support to FluentMigrator
        .AddPostgres()
        // Set the connection string
        .WithGlobalConnectionString(timescaleCs)
        .WithGlobalCommandTimeout(TimeSpan.FromMinutes(5))
        // Define the assembly containing the migrations
        .ScanIn(typeof(DbMigrationUnlockBefore).Assembly).For.Migrations())
    // Enable logging to console in the FluentMigrator way
    .AddLogging(lb => lb.AddFluentMigratorConsole())
    .Configure<RunnerOptions>(opt => {
        // Run all the untagged migrations and the dev only ones if in dev
        if (app.Environment.IsDevelopment())
        {
            opt.Tags = new[] { "Development" };
        }
    })
    // Build the service provider
    .BuildServiceProvider(false))
using (IServiceScope scope = serviceProvider.CreateScope())
{
    // Put the database update into a scope to ensure
    // that all resources will be disposed.
    IMigrationRunner runner = scope.ServiceProvider.GetRequiredService<IMigrationRunner>();

    // Execute the migrations
    // runner.Up(new DbMigrationUnlockBefore()); -- This does run the migration and causes the db lock
    runner.MigrateUp();
    // runner.Up(new DbMigrationUnlockAfter());
}
```

DBMigrationLockbefore.cs
```csharp
using FluentMigrator;

[Maintenance(MigrationStage.BeforeAll, TransactionBehavior.None)]
public class DbMigrationUnlockBefore : Migration
{
    public override void Down()
    {
        throw new NotImplementedException("Down migrations are not run for BeforeAll");
    }

    public override void Up()
    {
        Console.WriteLine("Before migrations lock");
        Execute.Sql("SELECT pg_advisory_lock(1)");
    }
}
````

DBMigrationLockAfter.cs
```csharp
using FluentMigrator;

[Maintenance(MigrationStage.AfterAll, TransactionBehavior.None)]
public class DbMigrationUnlockAfter : Migration
{
    public override void Down()
    {
        throw new NotImplementedException("Down migrations are not run for AfterAll");
    }

    public override void Up()
    {
        Execute.Sql("SELECT pg_advisory_unlock(1)");
    }
}
```

Whatever.cs - a migration
```csharp
using FluentMigrator;

[Migration(202308101601)]
public class Whatever : Migration
{
    public override void Up()
    {
        Console.WriteLine("up");
    }

    public override void Down()
    {
    }
}
```

**Comment by GopalanHarish** [comment]
This still doesn't work and I am using v5.2.0.

**Comment by jzabroski** [comment]
@GopalanHarish did you read https://github.com/fluentmigrator/fluentmigrator/issues/1689 and check your RunnnerOptions

**Comment by jzabroski** [comment]
@GopalanHarish Would be great to hear back from you and confirm you just needed to set your RunnerOptions accordingly.
