### ISSUE TITLE
Add STRICT Tables for SQLite

### ISSUE THREAD

**Issue by dittodhole** [fluentmigrator/fluentmigrator#1618]
With SQLite 3.37.0 the [type affinity](https://www.sqlite.org/datatype3.html) of SQLite got enhanced by [STRICT Tables](https://www.sqlite.org/stricttables.html).

Any chance to opt-in?

**Comment by jzabroski** [comment]
1. This should use FluentMigrator.Infrastructure.ISupportAdditionalFeatures.
2. There is no way currently to specify table-level options. There needs to be a new `ICreateTableWithOptionOrWithColumnOrSchemaSyntax`. This new interface needs to implement ICreateTableWithColumnOrSchemaSyntax.  This should probably look like:
  ```c#
  public interface ICreateTableOptionsSyntax : IFluentSyntax
  {
    /// <summary>
    /// Defines the table as having a tablespace (partitions).
    /// </summary>
    /// <returns>Defines the column or schema for the table</returns>
    ICreateTableWithColumnOrSchemaSyntax Tablespace(); // <-- this doesn't exist yet, but it could...
  }
  ```
  and `CreateTableExpressionBuilder` should implement `ICreateTableOptionsSyntax`
  ```c#
        /// <inheritdoc />
        ICreateTableOptionsSyntax WithOptions()
        {
            return this;
        }
  ```
3. Need to update SQLiteGenerator `public override string Generate(CreateTableExpression expression)` to support appending this if it is set & update SQLiteGeneratorTests to test both scenarios.

The SQLiteGenerator should then be customized accordingly to use the value.:
```c#
private static readonly HashSet<string> _supportedAdditionalFeatures = new HashSet<string>
{
    SQLiteExtensions.StrictTable,
};
```
Recommend features are organized via a Extensions file:

```c#
public static partial class SQLiteExtensions
{
   public const string StrictTable = "SQLiteStrictTable";

  private static TNext SetStrict<TNext, TNextFk>(ITableOptionSyntax<TNext, TNextFk> expression, PostgresGenerationType? generation, PostgresIdentityModificationType modificationType, ISupportAdditionalFeatures castColumn)
    where TNext : IFluentSyntax
    where TNextFk : IFluentSyntax
{
    if (generation.HasValue)
        castColumn.AdditionalFeatures[IdentityGeneration] = generation;

    castColumn.AdditionalFeatures[IdentityModificationType] = modificationType;

    return expression.Identity();
}
}
```

**Comment by jzabroski** [comment]
I'm going to complete this, probably this week.  The solution will require all tables in the database to be strict or not strict.  Mixing and matching is likely to cause too many support requests for me to handle right now.

**Comment by jzabroski** [comment]
This is effectively resolved in #1754 - you will have to have the whole database use strict tables or not, viz a viz SQLiteTypeMap constructor.

We could still annotate SQLite tables as being STRICT, but it would clash with the aforementioned SQLiteTypeMap setting. There's no way to assign a type map per table, and we have no plans to support that level of customization. Frankly, that SQLite does it that way is rather odd to me. If you want to use FluentMigrator with SQLite, all your tables need to be strict or not.

**Comment by kpietraszko** [comment]
Would you consider re-opening this? I think marking tables as STRICT would still be useful, even if it's a manual call in the migration. It would help catch some bugs, especially when inserting columns manually through an external management tool.

**Comment by jzabroski** [comment]
@kpietraszko Sorry, what is the ask? The feature should work - you just can't opt into doing it for some tables but not others. You have to commit to doing it across your whole database. Most SQLite schemas I see in the wild are pretty small, so I think this is a very reasonable assumption/request of users of this library, especially as it only helps them.

**Comment by kpietraszko** [comment]
@jzabroski Maybe I'm misunderstanding. When you set `useStrictTables` to `true`, and use `Create.Table("name")`, FluentMigrator doesn't append `STRICT` to the `CREATE TABLE` command in the generated SQL. At least as far as I've observed - let me know if I'm wrong.  
So the ask is to make creating STRICT tables possible, either automatically or manually.

**Comment by jzabroski** [comment]
Got it. I missed that in my examples. I think that I never implemented the `SetStrict` API I mentioned here: https://github.com/fluentmigrator/fluentmigrator/issues/1618#issuecomment-1849114709 - let's open a new issue.
