### ISSUE TITLE
Maintenance Migrations without tags aren't executed by the .NET Framework Console Runner when the -tag option is set

### ISSUE THREAD

**Issue by pmarflee** [fluentmigrator/fluentmigrator#1622]
**Describe the bug**
I have a number of maintenance migrations in my project. These migrations do not have tags specified against them. The .NET Framework Console Runner does not execute these migrations when the _-tag_ option is set.

**To Reproduce**
1. Get a copy of the following Github repo: (https://github.com/pmarflee/MaintenanceMigration)
2. Create a new Service-based database named **Migrations.mdf** in the project root folder (Project -> Add New Item -> Service-based Database)
3. Build the project
4. Execute the following command from the Windows console: `{ProjectRootFolder}\packages\FluentMigrator.Console.3.3.2\net461\any\migrate.exe  -c="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename={ProjectRootFolder}\Migrations.mdf;Integrated Security=True" -db=sqlserver2016 --target={ProjectRootFolder}\bin\Debug\maintenancemigration.dll  -t=migrate -o -tag=MyTag`

**Expected behavior**
The migrations 'Migration1' and 'Migration2' should be executed (working as expected)
The maintenance migration 'MaintenanceMigration' should be executed (not working as expected).

**Information (please complete the following information):**
 - OS: Windows 10 Pro
 - Platform .NET Framework 4.7.2
 - FluentMigrator version 3.3.2
 - FluentMigrator runner FluentMigrator.Console
 - Database Management System SQLServer
 - Database Management System Version Local SQLServer DB

**Additional context**

**Comment by pmarflee** [comment]
After reading through the source code, I see that there is a `--include-untagged:` switch that allows untagged migrations and/or maintenance migrations to be run when tags are provided. Once I added this switch to my PS build script, my untagged migrations were executed regardless of whether any tag values were provided to the runner.

It would be a good idea to add details of this switch to the online documentation at https://fluentmigrator.github.io/articles/runners/runner-console.html.

**Comment by jzabroski** [comment]
@pmarflee Sorry that you wasted time on this.

The documentation repo is at github.com/fluentmigrator/documentation - PRs welcome to fix this.

**Comment by jzabroski** [comment]
Fixed doc
