### ISSUE TITLE
AnnouncerFluentMigratorLogger FluentMigrator v2 Porting to v3 Help Request

### ISSUE THREAD

**Issue by jbrierley** [fluentmigrator/fluentmigrator#1623]
I have an implementation in v2 that I am upgrading to the latest v3.x and now have several obsolete entries giving me problems. I used an announcer to forward the logging to an even which I control the logging. 

the rough code I am using is this:
                    var announcer = new TextWriterAnnouncer(message => Log(logs, message));
                    var processorFactory = new SqlServerProcessorFactory();
                    var migrationProcessorOptions = new ProcessorOptions();
                    using (var processor = processorFactory.Create(migrationDTO.ConnectionString, announcer, migrationProcessorOptions)) {
                        var runnerContext = new RunnerContext(announcer);
                        var runner = new MigrationRunner(migrationDTO.Assembly, runnerContext, processor);
                        runner.RunnerContext.ApplicationContext = migrationDTO;

Now all of the classes (pretty much) are giving me obsolete warnings. I can replace most of this with the new dependency injection but the TextWriterAnnouner is now obsolete and so is the AnnounceFluentMigratorLogger, so my question is what replaces this to have the loggin forwarded to an event ? All the logging I have read so far in the documentation of v3 indicates logging to files or streams. I want an EVENT not a stream

If I get the answer to my question I will actually be able to perform the logging without having to re-invent the wheel on simple logging mechanics. 

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Framework 4.7.2
 - FluentMigrator version 3.3.2 
 - FluentMigrator runner : In process I think. I an running this within a custom tool and not command line 
 - Database Management System SQLServer
 - Database Management System Version Multiple versions of sql have tp be support, from 2012 up to the latest.

**Comment by jzabroski** [comment]
@jbrierley Here is the 2.0 to 3.0 upgrade guide, bookmarked to the spot where we cover announcers: https://fluentmigrator.github.io/articles/guides/upgrades/guide-2.0-to-3.0.html#iannouncer

  I will close this issue for now.  If you find there is something specifically missing in this guide, please open a new issue to address either (1) missing docs (2) possible missing features.
