### ISSUE TITLE
The DI example does not call Dispose() on ServiceProvider

### ISSUE THREAD

**Issue by Anhil-111** [fluentmigrator/fluentmigrator#1638]
**Describe the bug**
The DI example from your documentation does not call `Dispose()` on `ServiceProvider` even though it implements `IDisposable`.

Not calling `Dispose()` on the `ServiceProvider` means it won't be called on registered singletons. I experienced issues in the past where Ctrl+C wouldn't terminate the process because of this.

**To Reproduce**
Pretty much follow the steps outlined here: https://fluentmigrator.github.io/articles/quickstart.html#running-your-first-migration

**Expected behavior**
`Dispose()` needs to be called. May I suggest the following changes:
```diff
     {
         static void Main(string[] args)
         {
-            var serviceProvider = CreateServices();
-
-            // Put the database update into a scope to ensure
-            // that all resources will be disposed.
+            using (var serviceProvider = CreateServices())
             using (var scope = serviceProvider.CreateScope())
             {
+                // Put the database update into a scope to ensure
+                // that all resources will be disposed.
                 UpdateDatabase(scope.ServiceProvider);
             }
         }
@@ -25,7 +24,7 @@
         /// <summary>
         /// Configure the dependency injection services
         /// </summary>
-        private static IServiceProvider CreateServices()
+        private static ServiceProvider CreateServices()
         {
             return new ServiceCollection()
                 // Add common FluentMigrator services
```

**Comment by jzabroski** [comment]
Resolved in fluentmigrator/documentation project.

**Comment by jzabroski** [comment]
I suppose this should be updated too?

https://github.com/fluentmigrator/fluentmigrator/blob/ef8ceae368a5b4ff9fd7d9b692d003279ffe9930/src/FluentMigrator.DotNet.Cli/Commands/BaseCommand.cs#L27-L33

**Comment by Anhil-111** [comment]
Oops, didn't realize you had a different repository for documentation, sorry.

> I suppose this should be updated too?

Actually yes, it should be.

**Comment by jzabroski** [comment]
A good Oops altogether, as I think this may resolve a couple issues independently reported by others.  So, a great contribution.  Would you like to get credit with a PR?

**Comment by schambers** [comment]
This is stale and likely can be closed

**Comment by jzabroski** [comment]
@schambers This actually still requires fixing - and should be an easy way for you to contribute if interested/if you can build on your Mac OSX m1 machine:

The following code:

https://github.com/fluentmigrator/fluentmigrator/blob/ef8ceae368a5b4ff9fd7d9b692d003279ffe9930/src/FluentMigrator.DotNet.Cli/Commands/BaseCommand.cs#L27-L33

should likely say something like:

```c#
 protected int ExecuteMigrations(MigratorOptions options, IConsole console) 
 { 
     using (var serviceProvider = Setup.BuildServiceProvider(options, console))
     {
         var executor = serviceProvider.GetRequiredService<TaskExecutor>(); 
         executor.Execute(); 
         return 0;
     } 
 } 
```
Needs testing of course.
