### ISSUE TITLE
`IMigrationRunner` doesn't exist in `FluentMigrator.Runner.Core` package

### ISSUE THREAD

**Issue by TETYYS** [fluentmigrator/fluentmigrator#1639]
**Describe the bug**
`IMigrationRunner` doesn't exist in `FluentMigrator.Runner.Core` package, it exists only in `FluentMigrator.Runner`. `FluentMigrator.Runner` however adds dependencies to every flavor of database runner, which is something one expect to avoid.

**To Reproduce**
With `FluentMigrator.Runner.Core`: https://dotnetfiddle.net/txN4d4
With `FluentMigrator.Runner`: https://dotnetfiddle.net/xXu057

**Expected behavior**
`IMigrationRunner` to exist in `FluentMigrator.Runner.Core`, as well as such methods as `AddFluentMigratorCore`

**Information (please complete the following information):**
 - OS: windows
 - Platform: .NET 6
 - FluentMigrator version: 3.3.2

**Comment by jzabroski** [comment]
It's resolved in the main branch. Just need to finalize some stuff for 4.0.0 release.
Maybe I should not try to do so much for 4.0.0

**Comment by TETYYS** [comment]
Thanks
