### ISSUE TITLE
I need to create a column with the FILESTREAM attribute

### ISSUE THREAD

**Issue by sherifr212** [fluentmigrator/fluentmigrator#1649]
**Describe the question**
Dear All, I am trying to create a table that contains a VARBINARY(MAX) column with the FILESTREAM attribute. I don't know how to achieve that. Can you please help.

**Documentation Pages You've Read So Far**
Microsoft documentation:
https://learn.microsoft.com/en-us/sql/relational-databases/blob/create-a-table-for-storing-filestream-data?view=sql-server-ver16

**Comment by jzabroski** [comment]
Use `AsCustom("VARBINARY(MAX) FILESTREAM NULL")`
