### ISSUE TITLE
Datatype compatibility between databases (SQLite & SqlServer)

### ISSUE THREAD

**Issue by maddinthegreat** [fluentmigrator/fluentmigrator#1651]
Hello guys,

AsDouble() or AsDecimal() is not compatible between databases (in my case SQLite and SqlServer) together with Dapper.

Selecting and inserting data from SQLite to SqlServer with Dapper results in:

**InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Double]'** from SQLite to SqlServer.

FluentMigrator uses for both datatypes INT64 & REAL -> NUMERIC. That's imprecise. Should be fixed as:

**AsDouble() , AsFloat() , AsDecimal() -> REAL
integral types -> INTEGER**

for SQLite.

Regards
Martin

**Comment by jzabroski** [comment]
This does not sound like a FluentMigrator issue.  It sounds like a coding issue where you are trying to cast in C# from `long` to `double?`. You mentioned Dapper twice, so I wonder if its really a Dapper issue.  I'm not sure what code you wrote to achieve this exception, so I am closing this issue as not reproducible.

**Comment by jzabroski** [comment]
If you want to customize data types per database, one workaround would be to use the IfDatabase clause to customize logic per database tag.

**Comment by maddinthegreat** [comment]
I do something like this:

`                    using var trans = await dest.BeginTransactionAsync(tks.Token);
                    await dest.DeleteAllAsync<Asset>(trans);

                    var copied = await dest.InsertAsync(await source.GetAllAsync<Asset>(), trans);
                    await trans.CommitAsync(tks.Token);`

**Comment by maddinthegreat** [comment]
Just looked into https://github.com/fluentmigrator/fluentmigrator/blob/a292999ca5b4e3a462e5db0340d3cfee4883b9a0/src/FluentMigrator.Runner.SQLite/Generators/SQLite/SQLiteTypeMap.cs

Used is indeed a REAL, but why is standing there a NUMERIC?

Hm...
