### ISSUE TITLE
fluentmigrator.dotnet.cli requires dotnet 5.x even when newer versions are installed

### ISSUE THREAD

**Issue by Darkmace** [fluentmigrator/fluentmigrator#1655]
**Describe the bug**
The fluentmigrator.dotnet.cli seems to require dotnet 5.x even when newer versions are installed. When attempting to run the cli in an environment without dotnet 5.x it will simply refuse to even start. This is the output from encountering this bug in Azure DevOps:

```
You can invoke the tool using the following command: dotnet-fm
Tool 'fluentmigrator.dotnet.cli' (version '3.3.2') was successfully installed.
You must install or update .NET to run this application.

App: C:\Users\VssAdministrator\.dotnet\tools\dotnet-fm.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  3.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  3.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  3.1.32 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64
##[error]Cmd.exe exited with code '-2147450730'.
```
I was also able to replicate the behaviour locally after uninstalling dotnet 5.x

**To Reproduce**
Simply run dotnet-fm in any environment without dotnet 5.x installed, such as an Azure DevOps hosted agent.

**Expected behavior**
I expected fluentmigrator.dotnet.cli to only be dependent on having any version of dotnet installed.

**Information (please complete the following information):**
 - OS: Windows 10/11
 - Platform: dotnet 6.0/7.0
 - FluentMigrator version: 3.2.2
 - FluentMigrator runner: FluentMigrator.DotNet.Cli
 - Database Management System: Any
 - Database Management System Version: Any

**Additional context**
This issue was encountered when attempting to run fluentmigrator migrations as part of a Azure DevOps pipeline on their hosted agents, as none of them have dotnet 5.x installed anymore, so even though fluentmigrator.dotnet.cli is successfully installed it just refuses to run any dotnet-fm commands due to the missing dotnet 5.x version.

**Comment by johannessorheim** [comment]
This PR should fix it, but it has been very little activity in this project lately. Previous release was october 2021, even if some PRs have been merged since then. I am considering other solutions for our migrations.

A workaround for me is to use unit tests or a custom console application for migrations as an alternative to the FluentMigrator.DotNet.Cli tool.

I am using Mac M1 where dotnet 5 is not supported.

https://github.com/fluentmigrator/fluentmigrator/pull/1650

**Comment by aivarasatk** [comment]
Is the nuget expected to have a new version anytime soon? What about .NET7, 8, ...?

**Comment by Andrioden** [comment]
Soon 18 months since last release : S

Some more info here btw: https://github.com/fluentmigrator/fluentmigrator/issues/1544

**Comment by PeteW** [comment]
Reviving the topic.
If the maintainer is not around we need a successor to keep this project up to date with the cadence of the runtimes.

**Comment by jzabroski** [comment]
I'm open to help and I have a clear idea of what the next steps would be.

**Comment by franckyj** [comment]
I just had the same issue, same error message

```
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: C:\Program Files\dotnet\
...
```

I found out that by settings this env. variable `$Env:DOTNET_ROLL_FORWARD="LatestMajor"` I was able to run the command "properly" (quotes are intended) without error. Of course you open yourself up to issues if the behavior between the 2 SDK versions are different, but I think it's unlikely.

Here is [the documentation about the setting.](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_roll_forward)

**Comment by SpiridonovAlexMoeDelo** [comment]
so annoying issue...

is this project already dead or still alive?

@jzabroski can you give us any info or plans about new releases?

may be we can help you somehow with this?

**Comment by jzabroski** [comment]
It's not dead. I just keep underestimating how much time I dedicate week to week to being a sad, husband and other things.

If you want to help, that would be great.

**Comment by SpiridonovAlexMoeDelo** [comment]
how we can help you with release of a new version of the fm's nuget package?

what kind of tasks must to be done for it?

**Comment by slang25** [comment]
I would like to help too, perhaps you could select a few people into a temporary team and we could coordinate some actions to get some of the priorities cleared down.

**Comment by jzabroski** [comment]
The main thing I wanted to do was merge some of the old "4.0" (develop branch) contributions into main. In particular, the Snowflake one is a big one that I would love to have added.

In terms of this issue in particular, I do think the "right approach" for many is to not use FluentMigrator.DotNet.Cli directly but rather expose its entrypoint as a FluentMigratorApplicationBase base class, as that would completely solve issues with upgrading. The only downside would be that it would lock people into the Nate McMaster Command Line Utils and would not solve for people who run the migration framework directly on ASP.Net Core. But based on my experience answering issues and discussions here, the people who know how to and want to run this on ASP.Net Core would rather continue with their own approach and don't care for an "on rails" approach. This Base class would also address the fact that Microsoft stance on CLI tools is dev only, and thus to run FluentMigrator.DotNet.Cli on a production box today effectively requires installing the SDK, which is rather nasty thing to ask System Administrators to do VS. deploy a regular .Net executable. EF Core team approach is to generate "bundles" but I think has a limited usefulness. 

I'm open to not doing the Base class thing, but it's my view that would solve half of all requests people have. In terms of why I have wanted it for 4.0, if I push it and other things, I need to reorganize a bunch of Github milestones.

I do want to note, even though we have not done a release in a while, I have spent time cleaning up the FluentMigrator/Documentation repo and there is really only one active issue there now.

**Comment by slang25** [comment]
I completely agree with what you're saying about the .NET tool approach, it's caused many issues at my place of work.

I've been telling people to use this sort of approach:
<img width="1101" alt="image" src="https://github.com/fluentmigrator/fluentmigrator/assets/1341446/31d628b4-0f7c-4323-8a7e-eb857d789ca7">

<img width="725" alt="image" src="https://github.com/fluentmigrator/fluentmigrator/assets/1341446/135ebdf2-f732-4098-8938-80e1b38e362d">

^ with this approach you are then leaning on MSBuild and ResolveAssemblyReferences to sort out all of your issues, and building an app that has a consistent mechanism to automate deployment updates and rollbacks.

Having a preferred and recommended approach like this would be fantastic.

**Comment by jzabroski** [comment]
We can have a side chat on WhatsApp if you want. 

It's not been a problem where I consult but it just takes so much effort on here helping beginners out. Even many senior developers struggle with this on my other project, Razor Light. 

I had created https://github.com/jzabroski/Home/issues/5 to discuss how to improve dependency loading in .net.

This stuff pulls my hair out because I can't seem to get a good conversation going with Microsoft on this and I run two projects with like 25 million downloads, lol. I get that in their view, I'm likely some niche customer, but the total lack of acknowledgement there are still problems with loading dependencies in .net is frustrating. When I spoke to a PM about this Pre .net 5, the only color I got was they would improve it. But Microsoft never defined "the problem" and so, as best as I can tell, "the solution" was to kill off ".net standard" (as in, release no more new iterations of it, since the unstated view was it creates diamond dependencies that are awful to deal with and intractable to do tree shaking on to minify libraries dll size) and to move the most popular Microsoft "out of box" nuget packages to "inbox" and shut down framework level nuget packages. It was totally an improvement but it didn't solve my problems.

**Comment by KarsonAlford** [comment]
For Docker images you can use multistage builds to build the code in one intermediate image and then copy into a .NET 5 runtime image where it can be ran.

This example builds .NET 6 code then copies it into the final image which has the .NET 5 runtime.

```
# We must run the application in 5 because that is what FluentMigrator uses.
FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["src/Data.csproj", "src/Data/"]

RUN dotnet restore "src/Data/Data.csproj"

RUN dotnet tool install -g FluentMigrator.DotNet.Cli

RUN dotnet build "Data.csproj" -c Release -o /app/build

FROM base AS final
WORKDIR /app
# Copy Data.Dll files
COPY --from=build /app/build .
# Copy FluentMigrator (so we don't have to use an sdk image)
COPY --from=build /root/.dotnet/tools/ /opt/bin
ENV PATH="/opt/bin:${PATH}"

CMD dotnet-fm migrate -a /app/Data.dll -p SqlServer --allowDirtyAssemblies -c "${CONNECTIONSTRING}"

```

**Comment by jzabroski** [comment]
Resolved. 4.0.0 will be shipped soon. net5.0 support dropped.
