### ISSUE TITLE
SQLite: Support binary GUIDs

### ISSUE THREAD

**Issue by lrobin136** [fluentmigrator/fluentmigrator#1657]
We're using the FluentMigrator 3.3.2. System.data.sqlite.core 1.0.113.7 allows us to store guids as binary data with the connection string option "BinaryGuid=True". 

If we use in our migrations: 

``` 
Insert.IntoTable("Table").Row(new { GUID_= Guid.NewGuid() } )
```

a guid is inserted as text string because of the [GenericQuoter](https://github.com/fluentmigrator/fluentmigrator/blob/65f79eb7353d2db8fab0aed48311d4bc87ac04d8/src/FluentMigrator.Runner.Core/Generators/Generic/GenericQuoter.cs#L132):

```
        public virtual string FormatGuid(Guid value)
        {
            return ValueQuote + value.ToString() + ValueQuote;
        }
```

We would like to have a SQLiteQuoter that optionally formats guids directly as hexadecimal string values:

```
        public override string FormatGuid(Guid value) 
        {
            return "x'" + value.ToString("N", CultureInfo.InvariantCulture) + "'"; 
        }
```
Would it be possible to implement this missing feature? 

Right now, we have a workaround that inserts our own SQLiteQuoter implementation into the [SQLiteProcessor](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Runner.SQLite/Processors/SQLite/SQLiteProcessor.cs), but the quoter is not passed on to the [SQLiteColumn](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Runner.SQLite/Generators/SQLite/SQLiteColumn.cs) and the solution is not entirely satisfactory.

**Comment by lrobin136** [comment]
Would you be interested if we submitted a PR to support binary guids with SQLite?

**Comment by jzabroski** [comment]
Hi @lrobin136 . Thanks for your patience. Yes, absolutely. 4.0.0 branch is basically in the bag, we could ship it as 4.1.0 feature.

**Comment by jzabroski** [comment]
@lrobin136 As this depends on the caller to know the convention set by the connection string, I will implement this as:

```c#
        public bool BinaryGuid { get; set; } = false;

        /// <inheritdoc />
        public override string FormatGuid(Guid value)
        {
            if (BinaryGuid)
                return "x'" + value.ToString("N", CultureInfo.InvariantCulture) + "'";
            return base.FormatGuid(value);
        }
```

Let me know if you disagree with this approach.  I would still appreciate the PR, so that (a) you get credit (b) the tests are maintained accordingly. (c) an active SQLite user regression tests this.

**Comment by lrobin136** [comment]
Hi @jzabroski, Thanks for your feedback. The approach sounds good with me. We'll try to submit a PR in the next few weeks.

**Comment by lrobin136** [comment]
Hi @jzabroski, we submitted a minimal PR to inject the quoter into the [SQLiteColumn](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Runner.SQLite/Generators/SQLite/SQLiteColumn.cs). This change solves our initial issue as well, because a user can inject a user-specific quoter for SQLite, that is used in the column as well.

**Comment by jzabroski** [comment]
I commented on the PR.  It solves _your_ initial issue for your team, but does not solve it for _this project_.  I can't accept the PR in this state, as it clearly does not address this issue.
