### ISSUE TITLE
SerenityFramework net6 project template incompatible with FluentMigrator 3.3.2

### ISSUE THREAD

**Issue by elenaaralla** [fluentmigrator/fluentmigrator#1666]
**Describe the bug**
When I run the command:
`dotnet-fm list migrations -p sqlserver -a "my assembly path" --allowDirtyAssemblies`

I got this error:

```
 dotnet-fm list migrations -p sqlserver -a "D:\WORKING\PecDownloaderAdmin\PecDownloaderAdmin.Web\bin\Debug\net6.0\PecDownloaderAdmin.Web.dll" --allowDirtyAssemblies
// Wrong assembly binding redirects for System.Runtime, loading it from disk anyway. C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.4\System.Runtime.dll
dotnet-fm : Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=6.0.0.0, 

```

**To Reproduce**
simply run the command
`dotnet-fm list migrations -p sqlserver -a "my assembly path" --allowDirtyAssemblies`

**Expected behavior**
I expect to see the list of migrations

**Information (please complete the following information):**
 - OS: Windows 10 Pro
 - Platform: .NET 6.0
 - FluentMigrator version : 3.3.2
 - FluentMigrator runner: FluentMigrator.DotNet.Cli
 - Database Management System: SQLServer
 - Database Management System Version: Microsoft SQL Server Express (64-bit)

**Additional context**
I created the project with serenity framework

**Comment by jzabroski** [comment]
What is Serenity Framework

**Comment by elenaaralla** [comment]
https://serenity.is/ 

Its destination framework is net6.0  and FluentMigrator.DotNet.Cli 3.3.2 does not support net6.0 :(

Bye

**Comment by jzabroski** [comment]
I don't know what to do with this - I don't support random third party libraries - so I am closing it as I don't see a way to make forward progress.  FluentMigrator.DotNet.Cli 4.0.0 (published soon) will support .net 6.0.
