### ISSUE TITLE
ConnectionlessProcessor NotImplementedException should state method name not supported

### ISSUE THREAD

**Issue by GevorDanielyan** [fluentmigrator/fluentmigrator#1672]
I have API where I used FluentMigrator. Now, when I try to run built  **.exe** from bin folder, there is the exception:

```
2023-08-10 09:46:17.242 [INF] 1: _1_InitialMigration migrating
!!! Method is not supported by the connectionless processor
2023-08-10 09:46:17.252 [FTL] Fatal error
System.NotImplementedException: Method is not supported by the connectionless pr
ocessor
```

Why it happens and how to fix if it's really problem in fluent migrator usage?

Thanks in advance.

**Comment by jzabroski** [comment]
This error message should be better, I agree.  If you searched the code, though, you would find which place it could be in:

https://github.com/fluentmigrator/fluentmigrator/blob/5fa7ce26d943159f90ae164660a8d5d8f5edf17f/src/FluentMigrator.Runner.Core/Processors/ConnectionlessProcessor.cs#L117-L130

Do you want to submit a PR?
