### ISSUE TITLE
Need to change the TAGS filter of MigrationRunner at runtime

### ISSUE THREAD

**Issue by sweco-dkdakn** [fluentmigrator/fluentmigrator#1673]
I'm trying to maintain a multi-tenant-database with Fluent Migrator.
The setup consists of a single database with multiple customer schemas and a shared schema. While all customer schemas have the same design, the shared schema looks different.
I tag all migrations with something like `[Tags("Customer")]` and `[Tags("Shared")]`.
If I put a tag filter in the configuration of the .net core project, I can make it doing the right choice. With `builder.Configuration["MigrationTarget"]` I can bind the filter to a setting, so I can switch the filter inside appsetting.json. But that requires to restart the project to switch between customer schemas and shared schema.

To show the current status I include my startup configuration:
```
// Add FluentMigrator.
builder.Services.AddSingleton<FluentMigratorConnectionStringProvider>();
builder.Services.AddSingleton<IConnectionStringReader>(
    sp => sp.GetRequiredService<FluentMigratorConnectionStringProvider>());
builder.Services.AddScoped<MigrationHandler>();
builder.Services
    .AddLogging(c => c.AddFluentMigratorConsole())
    .AddFluentMigratorCore()
    .Configure<RunnerOptions>(x => x
        .Tags = new string[] { builder.Configuration["MigrationTarget"] ?? "Shared" }
    )
    .ConfigureRunner(options => options
        .AddPostgres11_0()
        .WithVersionTable<VersionTableAccessor>()
        .ScanIn(typeof(FluentMigrationAttribute).Assembly).For.Migrations()
    );
```

**Documentation Pages I've Read So Far**
I was reading tons of documentation and googling for the problem. I came across the "What's new" of the latest or second latest release and could see you announced changes in handling IoC to create more runtime flexibility. Unfortunately there are no details to find for me, but at least that makes me hope there is a way to get it solved. As you can see from above code snipped, I'm already following your advice to change database connection during runtime and I managed to switch schema for versioninfo table by using VersionTableAccessor.

**Expected benefit**
If you can provide a solution to my problem, we'd be able to apply different migrations to our 2 different types of database schemas (customer schemas, shared schema) without tweaking appsettings and restarting the application. As we aim for a final solution running as a website, restarting wouldn't really work!

**Information:**
 - OS: Windows Server 2019 (or newer if needed)
 - Platform .NET Core 7 (C# - WebAPI)
 - FluentMigrator version 3.3.2
 - FluentMigrator runner: "in-process runner"
 - Database Management System: Postgres
 - Database Management System Version: 14

**Comment by jzabroski** [comment]
Create a factory wrapper and the object context for the Factory Make(object context) method be the tags, and configure Microsoft DI to resolve a unique Migration Runner per Factory Make request.
