### ISSUE TITLE
Build pipeline broken by UseGitVersion task

### ISSUE THREAD

**Issue by eloekset** [fluentmigrator/fluentmigrator#1677]
**Describe the bug**
Build breaks after changing the .NET versions supported by the library. It looks like UseGitVersion task depends on .NET Core 3.1.

**To Reproduce**
See [build run 20230924.1](https://dev.azure.com/fluentmigrator/fluentmigrator/_build/results?buildId=700&view=results)

**Expected behavior**
The build should continue successfully after automatically deciding the version to be used for the build.

**Information (please complete the following information):**
Looks like UseGitVersion should be replaced by GitTools: https://github.com/GitTools/GitVersion/issues/2162#issuecomment-597973891

**Comment by eloekset** [comment]
I opened this issue, but @jzabroski fixed it before I even tried 💯

**Comment by jzabroski** [comment]
Almost at 4.0.  Just need the babysitter to come on a weekend again.
