### ISSUE TITLE
[MariaDb] Invalid default value for 

### ISSUE THREAD

**Issue by MeikelLP** [fluentmigrator/fluentmigrator#1686]
**Describe the bug**
I'm unable to rename a datetime column in MariaDB: `Invalid default value for 'CreatedAt_old'`

**To Reproduce**
```sql
create table account.accounts
(
    CreatedAt  datetime         default current_timestamp() not null
);
```

```cs
// migration
Rename.Column("CreatedAt").OnTable("accounts").To("CreatedAt_old")
```

**Expected behavior**
Column gets renamed

**Information (please complete the following information):**
 - Windows 64 Bit
 - .NET 7
 - FluentMigrator version 3.2.17
 - FluentMigrator runner MySQL 3.3.2
 - mariadb:10.10

My theory: `MySqlProcessor` generates wrong SQL:

```sql
ALTER TABLE `accounts` CHANGE `CreatedAt` `CreatedAt_old` datetime NOT NULL DEFAULT 'current_timestamp()'
```

but should be:

```sql
ALTER TABLE `accounts` CHANGE `CreatedAt` `CreatedAt_old` datetime DEFAULT current_timestamp() NOT NULL;
```

I don't know about the quotes but the order of `not null` looks important to me. I'm not a mysql pro

**Comment by jzabroski** [comment]
Should be fixed thanks to #1678
