### ISSUE TITLE
BREAKING CHANGE: RunnerOptions.IncludeUntaggedMaintenanceMigratrions will now default to true

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1689]
**Is your feature request related to a problem? Please describe.**
See #1062, #1607, #1591

**Describe the solution you'd like**
To make the default behavior of fluent migrator to include untagged maintenance migrations, consistent with untagged migrations. This legacy behavior has caused a lot of confusion.

**Comment by rhegner** [comment]
Could you please provide an example of such an "untagged maintenance migration"?

I've been using fluentmigrator for a long time, but based on this pretty short description I'm not sure if/how this breaking change is affecting my codebase.

**Comment by rhegner** [comment]
Thanks for the quick response (and for this great library)!
It is clear now.
