### ISSUE TITLE
FluentMigrator 5.0.0 and SQLite - Column Type Defining as TEXT Instead of DATETIME 

### ISSUE THREAD

**Issue by Rowandish** [fluentmigrator/fluentmigrator#1724]
## Problem Description
Since version 5.0.0 of FluentMigrator, when defining a column using `AsDateTime()` in migrations, the column is created as type TEXT instead of DATETIME in SQLite. The same code works correctly with FluentMigrator version 3.2.2.

## Steps to Reproduce
Define a migration that defines a column using `AsDateTime()`. When this migration is run with FluentMigrator 5.0.0, the column is created as TEXT instead of DateTime in SQlite.

## Expected Behavior
The column should be created as type DATETIME when using `AsDateTime()`.

## Actual Behavior
The column is created as type TEXT instead of DATETIME with FluentMigrator 5.0.0.

## Environment
* FluentMigrator Version: 5.0.0
* System.Data.SQLite Version: 1.0.118
* Operating System: Windows 11
* Database: SQLite
* .NET Version: .NET8

## Console Application
I have attached a self-contained single-file console application that reproduces the issue for clarity.

```csharp
using System.Data.SQLite;
using FluentMigrator;
using FluentMigrator.Runner;
using Microsoft.Extensions.DependencyInjection;

class Program
{
    static void Main()
    {
        const string dbName = @".\mydatabase.db";
        const string connectionString = $"Data Source={dbName};Version=3;";
        File.Delete(dbName);

        var serviceProvider = new ServiceCollection()
            .AddFluentMigratorCore()
            .ConfigureRunner(rb =>
            {
                rb.AddSQLite()
                  .WithGlobalConnectionString(connectionString)
                  .ScanIn(typeof(Program).Assembly).For.Migrations();
            })
            .BuildServiceProvider(false);
        var runner = serviceProvider.GetRequiredService<IMigrationRunner>();
        runner.MigrateUp();

        var realColType = VerifyColumnType(connectionString);
        if (realColType != "DATETIME")
            throw new Exception();
    }

    private static string VerifyColumnType(string connectionString)
    {
        using var connection = new SQLiteConnection(connectionString);
        connection.Open();

        using var command = new SQLiteCommand("SELECT type FROM PRAGMA_TABLE_INFO(\"MyTable\") WHERE name = \"MyColumn\"", connection);
        return (string) command.ExecuteScalar();
    }
}

[Migration(42)]
public class DateTimeMigration : Migration
{
    public override void Up()
    {
        Create.Table("MyTable").WithColumn("MyColumn").AsDateTime();
    }

    public override void Down()
    {
    }
}
```

Thank you for your attention to this matter. Let me know if additional information is needed.

**Comment by workgroupengineering** [comment]
Duplicate? #1722

**Comment by jzabroski** [comment]
@mattbrailsford Just a heads up, but your proposal to enforce strict caused a slight problem for clients not in strict mode. In hindsight, I should have caught this when reviewing your PR.  My plan is to add a flag that determines whether column types are serialized using strict mode or use type affinity.

@Rowandish and @workgroupengineering - One detail I do not understand in how type affinity works, per the SQLite docs, is guid mentioned in #1722 - uniqueidentifer isn't listed as a type, so how does SQLite know what to coerce it to?

**Comment by workgroupengineering** [comment]
> @mattbrailsford Just a heads up, but your proposal to enforce strict caused a slight problem for clients not in strict mode. In hindsight, I should have caught this when reviewing your PR. My plan is to add a flag that determines whether column types are serialized using strict mode or use type affinity.
> 
> @Rowandish and @workgroupengineering - One detail I do not understand in how type affinity works, per the SQLite docs, is guid mentioned in #1722 - uniqueidentifer isn't listed as a type, so how does SQLite know what to coerce it to?

I do not remember. The biggest problem I have with version 5 is that all DECIMAL(12,6) fields are recognized as TEXT.

**Comment by jzabroski** [comment]
https://stackoverflow.com/a/18954383/1040437 - this is the explanation I was looking for:

> SQLite itself does not support GUID as internal type.

> 
> Except that, it does! (sort of). Remember, in SQLite any string can be used as type name, and that includes `GUID` or `UUID` (read more about [SQLite datatypes](http://www.sqlite.org/datatype3.html)).

> 
> According to those rules, `GUID` type has affinity `NONE`, which is the same as for `BLOB` fields.

**Comment by jzabroski** [comment]
One last update here.  Ugh.  The SQLite docs suck.  

For your particular test case, you are using DATETIME... and I think what is happening is under a different section of the SQLite datatypes docs:

> 2.2. Date and Time Datatype
> SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in [Date And Time Functions](https://www.sqlite.org/lang_datefunc.html) of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values:

> 
> * TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").
> * REAL as Julian day numbers, the number of days since noon in Greenwich on November 24, 4714 B.C. according to the proleptic Gregorian calendar.
> * INTEGER as Unix Time, the number of seconds since 1970-01-01 00:00:00 UTC.
> 
> **Applications can choose to store dates and times in any of these formats** and freely convert between formats using the built-in [date and time functions](https://www.sqlite.org/lang_datefunc.html).

That last bit, Applications can choose to store dates and times in any of [text, real, integer] formats, is the key.  What's weird is that your type affinity must be DATETIME, right?  So, technically, that means you are storing text data as a blob somehow, and that is actually unsupported, and so I think the Fluent Migrator pre-5.0 behavior was probably undefined.  Does that make sense?  To be clear I want to fix this asap.

**Comment by jzabroski** [comment]
I think the fix should be to add a boolean flag to SQLiteTypeMap called UseStrictTables with default to false.  There may need to be some additional dependencies configured to allow people to use @mattbrailsford 's PR #1581, but I think that is the simplest fix.

**Comment by workgroupengineering** [comment]
I would like SQLite Column to be injectable.  And using like this

```c#
public sealed SQLiteTypeMap 
{
  public static ITypeMap Strict => ...
  public static ITypeMap UnStrict => ...
}
```

```c#
                services
                    .AddFluentMigratorCore()
                    .ConfigureRunner(rb =>
                        _ = rb
                            .AddSQLite(SQLiteTypeMap.UnStrict)
                            .WithGlobalConnectionString(settings.DataSource)
                        );

                using var serviceProvider = services.BuildServiceProvider();
                using var scope = serviceProvider.CreateScope();
                var runner = scope.ServiceProvider.GetRequiredService<IMigrationRunner>();
                runner.MigrateUp();
``` 

or

```c#
                services
                    .AddFluentMigratorCore()
                    .AddKeyedScoped<ITypeMap>("sqlite", _ => SQLiteTypeMap.UnStrict)
                    .ConfigureRunner(rb =>
                        _ = rb
                            .AddSQLite()
                            .WithGlobalConnectionString(settings.DataSource)
                        );

                using var serviceProvider = services.BuildServiceProvider();
                using var scope = serviceProvider.CreateScope();
                var runner = scope.ServiceProvider.GetRequiredService<IMigrationRunner>();
                runner.MigrateUp();
```

**Comment by jzabroski** [comment]
@Rowandish Finally finished a large PR that addresses this problem and more.
