### ISSUE TITLE
Get rid of Microsoft.NETCore.App 2.1 dependency on dotnet-fm

### ISSUE THREAD

**Issue by allexey312** [fluentmigrator/fluentmigrator#1727]
Even latest (5.0.0) release of dotnet-fm tool still depends on Microsoft.NETCore.App 2.1 (which was deprecated 1.5 years ago) to run.

**Comment by jzabroski** [comment]
Thanks for reporting.  I missed this while merging.

**Comment by schambers** [comment]
Where does this need to be correct @jzabroski? I dont see a reference in FluentMigrator.DotNet.Cli csproj

**Comment by jzabroski** [comment]
I may have fixed it in 5.1.0 or it was never a problem. The right way to check is to use Visual Studio by right clicking on the solution root and opening the package manager and looking for warnings. Not at my computer right now.

**Comment by schambers** [comment]
I'm using vscode and haven't found where to see nuget packages in the GUI, but the `dotnet list package` command doesnt seem to have any references to this assembly any longer (which I think is the same list as vs package manager):

```dotnet list package | grep "Microsoft.NET"                                                          schambers@Seans-MacBook-Pro
   > Microsoft.NETFramework.ReferenceAssemblies        (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NET.Test.Sdk                                       17.8.0      17.8.0
   > Microsoft.NETFramework.ReferenceAssemblies             (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies        (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   > Microsoft.NETFramework.ReferenceAssemblies   (A)   [1.0.3, )   1.0.3
   ```

**Comment by jzabroski** [comment]
@allexey312  ? Can you comment and reopen if you feel this is closed incorrectly.

I loaded the latest sln in Visual Studio and dont see the problem you described 

![image](https://github.com/fluentmigrator/fluentmigrator/assets/447485/d04e7e06-b36c-45b7-ae46-16da4e01679a)

**Comment by allexey312** [comment]
Sorry for long silence.
The way I see it now (as of dotnet-fm v.6.2.0) and it did not change since previous post, when I launch it I just receive such message:

C:\Users\me\Desktop\migration-test>dotnet-fm migrate -p SqlServer2016 -c "Data Source=.;Database=32;Integrated Security=true;Encrypt=false;" -a migrations.dll
You must install or update .NET to run this application.

App: C:\Program Files\dotnet\tools\dotnet-fm.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '2.1.0' (x64)
.NET location: C:\Program Files\dotnet

The following frameworks were found:
  3.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  5.0.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  8.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win-x64&os=win10

**Comment by jzabroski** [comment]
@allexey312 This is probably because you installed dotnet-fm as a global tool and never uninstalled it, but you uninstalled the sdk on your machine for 2.1. The error message Microsoft provides is not great, I'll admit, but i have no say in that. You can open a ticket and possibly a PR to improve the message.

I recommend you install it as a "local tool" (or you can also use a "path specific tool" instead if you don't like Microsoft putting a .config directory alongside your repository code.)

As a best practice, if you are installing a "path specific tool," I strongly recommend specifying the -version and -framework parameters to force it to pick a specific tool version and target framework to install. In this way, if you set-up an InitialTargets in a msbuild targets file, you can check if its already installed and only install the tool if you need it, and also clearly document your dependencies (version info and tfm are implicit dependencies)
