### ISSUE TITLE
Table rename in custom schema

### ISSUE THREAD

**Issue by vmato** [fluentmigrator/fluentmigrator#1746]
Sample code:

`Rename.Table("myschema.mytable").To("myschema.newname");`

Actual result:

```
!!! An error occurred executing the following sql:
ALTER TABLE "public"."myschema.mytable" RENAME TO "myschema.newname";
The error was 42P01: relation "public.myschema.mytable" does not exist
```

Why "public"? How do I specify database schema?

**Comment by schambers** [comment]
@vmato can you please provide the following information?

**Information (please complete the following information):**
 - OS: [ e.g Ubuntu 16.04, Windows Server 2016, etc ]
 - Platform [.NET Framework 4.x / .NET Core 2.x , etc]
 - FluentMigrator version [ e.g 3.2.1 ]
 - FluentMigrator runner [ FluentMigrator.MSBuild, FluentMigrator.Console, FluentMigrator.DotNet.Cli, or "in-process runner" ]
 - Database Management System [ SQLServer, SQLite, Mysql, Postgres, Firebird, Oracle, Redshift, DB2, DB2 ISeries, SAP Hana, SAP SQL Anywhere ]
 - Database Management System Version [ e.g., "SQL Server 2019 Enterprise Edition", "Oracle 18xe", etc ]

**Comment by jzabroski** [comment]
Rename.Table("table").InSchema("public").To("tableOld");

**Comment by vmato** [comment]
InSchema() works good. Thank you!
