### ISSUE TITLE
Still no migrations found using the fm tool. 

### ISSUE THREAD

**Issue by crimsonhawk47** [fluentmigrator/fluentmigrator#1760]
I have `FluentMigrator`, `FluentMigrator.Runner`, and `FluentMigrator.Runner.Postgres` installed. Here is my migration file and the command I run. I'm on dotnet 8. 

`dotnet fm migrate -p postgres -a ./bin/Debug/net8.0/Migrations.dll -c "Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=example;"`

```c#
using FluentMigrator;

namespace test
{
    [Migration(20180430121800)]
    public class AddLogTable : Migration
    {
        public override void Up()
        {
            Create.Table("Log")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("Text").AsString();
        }

        public override void Down()
        {
            Delete.Table("Log");
        }
    }
}
```

**Comment by jzabroski** [comment]
Can you please follow the issue template. This is not a full bug report.
