### ISSUE TITLE
How to determine the current runner default schema from within a migration?

### ISSUE THREAD

**Issue by jhardin-accumula** [fluentmigrator/fluentmigrator#1762]
Folks:

I am building a multitenant .Net 8 API hosted on Postgres 16, using the tenant-per-schema model where each tenant (account) schema has the same table structure. I want to use FluentMigrator 5.1.0 to maintain the table structure in each schema independently and automatically.

The dynamic scoped-default-schema approach is working so far for directing the fluent migration runner to work within a specific schema.

Due to limitations in FM I am forced to also use `Execute.Sql()` to run some non-fluent DDL - specifically, to create table check constraints.

This fails because `ALTER TABLE mumble ADD ...` doesn't find the table. Apparently the FM runner doesn't do something like `SET SCHEMA 'configured_default_schema';` before executing the migration on Postgres, so I need to add the current default schema explicitly into the DDL.

So as a general question _not specifically related to check constraints_:

**How do I determine within the migration what the current runner's configured default schema is?**

I don't see any promising properties on the `Migration` base class, and I haven't found any examples illustrating how to retrieve the runner's default schema within the migration code. All I'm finding is how to specify the schema for a fluent operation, like `Create.Table("mumble").InSchema("mumble")`, when the migration already knows the target schema. That is not suitable here.

I would hope to be able to do something like:
```
public override void Up()
{
    var curSchema = Schema.GetCurrentDefault();
    Execute.Sql($"ALTER TABLE {curSchema}.mumble ADD ...");
    ...
```

What is the proper way to do this, if it can be done in 5.1.0?

Thanks!

**Comment by jzabroski** [comment]
I would suggest using dependency injection and inject the tenant schema name into every migration through some kind of Tenant service. I'm not supporting something like this out of the box.  I think it's easy enough for you to build it yourself.

**Comment by jhardin-accumula** [comment]
Okay, as I am using the dynamic default schema approach suggested [here](https://github.com/fluentmigrator/fluentmigrator/discussions/1509) I tried doing this:

```
    public class InitialTenantSchema : Migration
    {
        private readonly IConventionSet _runnerConventions;

        public InitialTenantSchema(IConventionSet runnerConventions)
        {
            _runnerConventions = runnerConventions;
        }
```

This part works great, I get the `DefaultConventionSet` object with the desired target schema name that I created for the runner, no other custom infrastructure is needed.

Unfortunately the `DefaultSchemaConvention` class returned by `DefaultConventionSet.SchemaConvention` gives no public way to see what default schema name it is carrying.

Would you support _this_ change to `DefaultSchemaConvention`?

```
--- a/src/FluentMigrator.Runner.Core/Conventions/DefaultSchemaConvention.cs
+++ b/src/FluentMigrator.Runner.Core/Conventions/DefaultSchemaConvention.cs
@@ -65,7 +65,7 @@ namespace FluentMigrator.Runner.Conventions
         /// default schema name is null or empty and returns the new default
         /// schema name when the <paramref name="originalSchemaName"/> is null
         /// or empty</returns>
-        string GetSchemaName(string originalSchemaName)
+        public string GetSchemaName(string originalSchemaName)
         {
             return _defaultSchemaNameConvention.GetSchemaName(originalSchemaName);
         }
```


With that change, I assume I could do this in my migrations:

`var schemaName = _runnerConventions.SchemaConvention.GetSchemaName(null);`

**Comment by jzabroski** [comment]
That's not what I'm suggesting.

I'm suggesting you can inject into every migration a tenant service and you can ask your tenant what it's schema is. Why tightly couple this to Fluentmigrator? Having a higher order abstraction you control allows you to do way more things while using Fluentmigrator as the mechanism for various tenants policies.

I think the only part I didn't think through in my initial reply is how you would manage VersionInfo table. In that sense, you probably need a custom convention set that also injects your tenants service.

I really think this is the way. Fluentmigrator already has all the hooks you need.

**Comment by jzabroski** [comment]
If you omit InSchema today, it will use whatever injected DefaultSchemaConvention you injected. You don't need to query it, except to write Execute.Sql scripts parameterized by tenants schema.

It might make sense to support template variables like {DefaultSchema} to make Execute.Sql as friendly as the rest of the API. Then you would not need to inject anything so your migration code will read more like a conversation with your database about up and down migration and less about technical plumbing like dependency injection. No explicit constructors, no private variables to house dependencies.

Is there some feature I'm missing this idea would not cover?

**Comment by jhardin-accumula** [comment]
I'm not using `InSchema()` at all, I'm relying on the default schema provided to the runner.

> You don't need to query it, except to write Execute.Sql scripts parameterized by tenants schema.

Which is exactly the problem I'm trying to solve.

> It might make sense to support template variables like {DefaultSchema} to make Execute.Sql as friendly as the rest of the API.

I was indeed contemplating that as a possibility but omitted it from my initial question for simplicity's sake. Supporting template variables / token substitution in `Execute.Sql()` with a predefined list of useful tokens, permitting something like `Execute.Sql("ALTER TABLE $(DefaultSchema).mumble ADD ...");`, would _absolutely_ cover this need. 👍 

Are template variables / substitution tokens already supported in `Execute.Sql()`? Perhaps related to [this](https://github.com/fluentmigrator/fluentmigrator/issues/625) or [this](https://fluentmigrator.github.io/api/v3.x/FluentMigrator.SqlScriptTokenReplacer.html)?

If so, using that capability is not well documented. Also, it's not useful for this if the migration itself has to define all of the substitutions - there would _still_ need to be some mechanism for the migration to retrieve the default schema name to include in the substitution map. The token replacer would need to reserve some predefined tokens like `DefaultSchema` and populate them from FM hidden data and any replacement map the migration provided would be in addition to that.

**Comment by jzabroski** [comment]
Remind me, as a short term solution, why can't you inject IDefaultSchemaNameConvention https://github.com/fluentmigrator/fluentmigrator/blob/main/src%2FFluentMigrator.Runner.Core%2FConventions%2FDefaultSchemaNameConvention.cs ?

I don't think you need any changes.

With regards to documentation, PR to fluentmigrator/documentation on best practices standing up a tenant per schema solution would be welcome


It looks like PR #643 to add tokens never got the logic merged into main so it was lost with time and forgotten about.

**Comment by jhardin-accumula** [comment]
I'll try that and see what happens, thanks.

**Comment by jhardin-accumula** [comment]
Yeah, I will likely make a base class for that to neaten things up, but long term I would still _much_ rather see the default schema name available natively via FM.

**Comment by jzabroski** [comment]
Hi! @jhardin-accumula How did you end up wiring this up? 

I have #2298 open currently and it makes sense to stack it with built-in token variables that are shortcuts to various *Convention state, like DefaultSchema.

Perhaps built-in tokens should be injectable so that at least initially there's no breaking changes, and a Roslyn Analyzer warns if code references a reserved variable name and additionally throws with a useful runtime exception directly explaining the duplicate variable issue.

**Comment by jhardin-accumula** [comment]
I didn't take it any further than the DI I described above on Apr 03, and extensions to encapsulate schema-specific SQL like:

```
this.SetCollation(_schemaName, "products", "category", "global_ci_ai");
```

**Comment by jzabroski** [comment]
OK. I plan to do the following:
IMigrationRunnerConventionsAccessor -> IMigrationRunnerConventions -> Nothing. Could be expanded in the future to provide helper functions that rather than returning true/false, returning matching information.
IConventionSetAccessor -> IRootPathExpression -> IFileSystemExpression --> RootPath --> Nothing. Could return the root path in the future.
IConventionSetAccessor -> DefaultSchemaConvention -> GetSchemaName(null)

The remaining question is how to scope FluentMigrator reserved variables. They could have a namespace like `$[FM-DefaultSchema]` but that feels heavy. I think we will probably just go with $[DefaultSchema]

https://www.nuget.org/packages/Jinja2.NET and other templating engines could be used to let people decouple the syntax from the variable passing altogether. Jinja2 is what dbt uses in the Python world So it would potentially make it easier for Python data engineers to work in the .NET ecosystem.
