### ISSUE TITLE
AsBoolean() creates INTEGER column instead of Boolean/BIT on SQLite

### ISSUE THREAD

**Issue by vmato** [fluentmigrator/fluentmigrator#1798]
**Describe the bug**
AsBoolean() creates INTEGER column instead of Boolean/BIT on SQLite

**To Reproduce**
```
        public override void Up()
        {
            Create.Table("Test")
                .WithColumn("B")
                    .AsBoolean()
                    .NotNullable();
        }
```

**Current behavior**
INTEGER column created

**Expected behavior**
Boolean/BIT column is expected

**Information (please complete the following information):**
 - OS: Windows 10/11
 - .NET 8
 - FluentMigrator 5.2.0, "in-process runner"
 - SQLite

**Comment by jzabroski** [comment]
Please read the release notes.  Are you using strict tables mode or not?

**Comment by vmato** [comment]
> Are you using strict tables mode or not?

Not yet (we have a lot of legacy)

> Please read the release notes

If you mean #1581 I should notice the following

* Data types should not to be confused with storage classes

* SQLite does support boolean data type: https://www.sqlite.org/datatype3.html#boolean_datatype

* For compatibility there are SQL standards. Boolean type if a part of SQL99
https://en.wikipedia.org/wiki/SQL:1999#Boolean_data_types

**Comment by vmato** [comment]
> Are you using strict tables mode or not?

Not yet (we have a lot of legacy). But our software relies on database data types

> Please read the release notes

If you mean #1581 I should notice the following

* Data types should not to be confused with storage classes

* SQLite does support boolean data type: https://www.sqlite.org/datatype3.html#boolean_datatype

* For compatibility there are SQL standards. Boolean type is a part of SQL99
https://en.wikipedia.org/wiki/SQL:1999#Boolean_data_types

**Comment by jzabroski** [comment]
I agree that storage classes and data types are different but Sqlite definitely has a strict mode for tables. Also, it took me several times reading through to understand that there actually is no such thing as a boolean data type in Sqlite and it's type domain is based on its type affinity to its storage class, and that the type is just suggestive.

Let me know if disabling strict mode meets your needs.

**Comment by vmato** [comment]
> there actually is no such thing as a boolean data type in Sqlite

Following this logic there is also no datetime date type cause datetimes are stored as other types ([near same link](https://www.sqlite.org/datatype3.html#date_and_time_datatype)). But migrator's AsDateTime() nevertheless creates DATETIME field (which I consider correct)

> Let me know if disabling strict mode meets your needs.

As of us, db "boolean" data type is mapped to CLR bool, and db "integer" mapped to CLR long automatically. So we need to distinguish these types in database.

But I'd like this topic to be **not** about someone's particular needs

**Comment by jzabroski** [comment]
Sorry, we may be talking past each other. Whether we send Datetime depends on the strict mode configured in Fluentmigrator dependency injection. Not your Sqlite DB file. The two should ideally be in synch, tho.

**Comment by vmato** [comment]
Yes, I've actually thought about SQLite engine mode first.

Now I've experimented with AddSQLite()'s parameter useStrictTables. AsBoolean() created integer column regardless of the useStrictTables value

**Comment by jzabroski** [comment]
Yes, and section 3.1 of the Sqlite documentation says:

If the declared type contains the string "INT" then it is assigned INTEGER affinity.

There is no explicit rules for boolean.

**Comment by jzabroski** [comment]
After reviewing the code, Fluentmigrator has always worked this way. Confirmed by reading the git history of SQLiteTypeMap.cs

**Comment by vmato** [comment]
Scared bug?

**Comment by jzabroski** [comment]
Sorry, I don't understand. Are you saying you think it's still a bug even though it's been working this way for a very long time? I suppose it's possible. I can't find any examples anywhere where Sqlite expects a type of bit in a create table statement.

**Comment by vmato** [comment]
> I can't find any examples anywhere where Sqlite expects a type of bit in a create table statement.

Are there examples where any RDBMS expects certain type from user?

**Comment by jzabroski** [comment]
Hey, sorry but this isn't a productive question. I've linked to the documentation explaining Sqlite doesn't mention bit or bool or boolean data types. Sqlite does support literals true and false, as type constructors, but they are saved in integer columns per the standard.

If you don't like this answer, please address it with the Sqlite team, not this project, thank you.

**Comment by vmato** [comment]
> this isn't a productive question
Well, it depends... From this you may know the databases are to provide/support, not to expect

And yes, some bugs can live many years. You don't even need to go far for examples )

**Comment by vmato** [comment]
> this isn't a productive question

Well, it depends... From this you may know the databases are to provide/support, not to expect

And yes, some bugs can live many years. You don't even need to go far for examples )

**Comment by jzabroski** [comment]
Hey, sorry. I generally don't lock threads but you're wasting my time with opinions not facts.

I will remind you one last time, Sqlite documentation [literally says](https://www.sqlite.org/datatype3.html):

> SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).
> 
> SQLite recognizes the keywords "TRUE" and "FALSE", as of version 3.23.0 (2018-04-02) but those keywords are really just alternative spellings for the integer literals 1 and 0 respectively.

This is a warning. You will be banned if you continue to insist this is a bug, because it's wasting time.
