### ISSUE TITLE
The test method "CanCreateIndexWithVacuumCleanupIndexScaleFactor" fails in the master branch

### ISSUE THREAD

**Issue by TheSquidCombatant** [fluentmigrator/fluentmigrator#1804]
The test fails in the current master branch. I mean test `FluentMigrator.Tests.Unit.Generators.Postgres11_0.Postgres11_0IndexTests.CanCreateIndexWithVacuumCleanupIndexScaleFactor`.

**Comment by jzabroski** [comment]
Sorry, but can you provide more details?  We have an automated ci suite that runs on every commit, and it is passing.  Can you close this and open a new issue, and follow the issue template to provide more details?
