### ISSUE TITLE
RawSql.Insert cannot be used as entire Where clause or Set clause in UpdateDataExpression/DeleteDataExpression

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1827]
**Describe the bug**
RawSql.Insert cannot be used as entire Where clause or Set clause in UpdateDataExpression/DeleteDataExpression

**To Reproduce**
```c#
    [Migration(202406181031, "Testing RawSql.Insert behavior")]
    public class TestMigration : ForwardOnlyMigration
    {
        public override void Up()
        {
            Update.Table("Foo").InSchema("dbo")
                .Set(RawSql.Insert("Baz = CASE WHEN Bar = 1 THEN 2 ELSE 0 END"))
                .Where(RawSql.Insert("Baz IS NULL"));
        }
    }
```

generates the following invalid SQL expression:
```sql
UPDATE [dbo].[Foo] SET [Value] = N'Baz = CASE WHEN Bar = 1 THEN 2 ELSE 0 END' WHERE [Value] = N'Baz IS NULL'
```

**Expected behavior**
RawSql should be... raw sql :)

**Information (please complete the following information):**
 - FluentMigrator version 5.2.0

**Additional context**
Workaround is to use Execute.Sql syntax instead:

```c#
    [Migration(202406181031, "Testing RawSql.Insert behavior")]
    public class TestMigration : ForwardOnlyMigration
    {
        public override void Up()
        {
            Execute.Sql(@"UPDATE dbo.Foo
SET Baz = CASE WHEN Bar = 1 THEN 2 ELSE 0 END
WHERE Baz IS NULL");
        }
    }
```

**Comment by PhenX** [comment]
Is it acceptable with such a syntax ?

```
Update.Table("Foo").InSchema("dbo")
    .Set(new
    {
        Baz = RawSql.Insert("CASE WHEN Bar = 1 THEN 2 ELSE 0 END")
    })
    .Where(new
    {
        Baz = RawSql.Insert("IS NULL")
    });
```

**Comment by jzabroski** [comment]
I did not consider that. What does it generate?

**Comment by PhenX** [comment]
Well for now it's a little bit better but not what we want because of the "=" on the WHERE part

```sql
UPDATE "dbo"."Foo" SET "Baz" = CASE WHEN Bar = 1 THEN 2 ELSE 0 END WHERE "Baz" = IS NULL
```

the fix is very simple though.

By the way, while talking about this, why don't we simply consider this simplified syntax, passing directly the raw expression as a string (I think the fix would be nearly the same as with RawSql)

```sql
Update.Table("Foo").InSchema("dbo")
    .Set("Baz = CASE WHEN Bar = 1 THEN 2 ELSE 0 END")
    .Where("Baz IS NULL");
```

**Comment by jzabroski** [comment]
I had looked at what Linq2Db does, as they implement a more modern approach to RawSql.Insert using the new formatted strings feature.

**Comment by PhenX** [comment]
@jzabroski I think this issue is adressed now, and [this pull request](https://github.com/fluentmigrator/documentation/pull/77/files) is now obsolete

**Comment by jzabroski** [comment]
thanks
