### ISSUE TITLE
Registering custom IVersionTableMetaData must be done after AddFluentMigratorCore

### ISSUE THREAD

**Issue by warappa** [fluentmigrator/fluentmigrator#1836]
**Describe the bug**
I had to use a custom version info table, so I registered it like this:
```csharp
services.AddScoped<IVersionTableMetaData, CustomVersionTableMetaData>();
```
Previously it worked, but after I refactored my code (just moving registrations around) it broke.

The reason:
Previously, I _first_ called `AddFluentMigratorCore(...)` and _after_ that `services.AddScoped<IVersionTableMetaData, CustomVersionTableMetaData>()`. While refactoring the order changed.

**To Reproduce**
This version works (pseudo code):
```csharp
services.AddScoped<IVersionTableMetaData, CustomVersionTableMetaData>();
services.AddFluentMigratorCore(..);
```
this doesn't:
```csharp
services.AddFluentMigratorCore(..);
services.AddScoped<IVersionTableMetaData, CustomVersionTableMetaData>();
```

**Expected behavior**
The order of the registration should not cause the custom migration to be ignored/missed.
I consider this a very suptle but hard to spot and therefore serious bug, despite the workarounds being pretty straight forward.

**Investigation**
Usually, in a library this is caused by using `services.AddScoped<...>()` instead of `services.TryAddScoped<...>()` which overrides user registrations, but I couldn't find something like that.
As I did not register a `AssemblyVersionTableMetaDataSourceItem` with `ScanIn(...).For.VersionTableMetaData()`, this returns `null` for `VersionTableMetaData` property (debugged this).

**Workarounds**
- Call `AddScoped<IVersionTableMetaData, CustomVersionTableMetaData>();` after `AddFluentMigratorCore(...)`
- Use `ScanIn(...).For.VersionTableMetaData()`
- Use `WithVersionTable(new CustomVersionTableMetaData())`

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET 8
 - FluentMigrator version 5.2.0
 - FluentMigrator runner "in-process runner"
 - Database Management System Oracle
 - Database Management System Version "Oracle 19c

**Comment by jzabroski** [comment]
> The order of the registration should not cause the custom migration to be ignored/missed.

This doesn't seem like a bug to me.  I don't know what you actually want to be done.

> I consider this a very suptle but hard to spot and therefore serious bug, despite the workarounds being pretty straight forward.

Hard to spot, as in, you ran migrations without testing them / validating them?  If people don't test their code, then that is not this project's problem to solve?  I don't think this is a serious bug.

> **Investigation**
> Usually, in a library this is caused by using `services.AddScoped<...>()` instead of `services.TryAddScoped<...>()` which overrides user registrations, but I couldn't find something like that.

If you need to Replace a core dependency, call [Replace](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.extensions.servicecollectiondescriptorextensions.replace?view=net-8.0)?

**Comment by warappa** [comment]
> This doesn't seem like a bug to me. I don't know what you actually want to be done.

Well, OK, then I try to detail my issue further and also rephase it a bit.

FluentMigrator supports resolving a custom `IVersionTableMetaData` via the **service provider**. My example is literally taken from the sample shown in the **[official docs](https://fluentmigrator.github.io/articles/version-table-metadata.html)**.

> In the same assembly that your migrations are located, create a new class (it must be public) that implements the [IVersionTableMetaData](xref:FluentMigrator.Runner.VersionTableInfo.IVersionTableMetaData) interface and decorate the class with the [VersionTableMetaDataAttribute](xref:FluentMigrator.Runner.VersionTableInfo.VersionTableMetaDataAttribute). FluentMigrator will automatically find this and use it instead of the default settings.
> ...
> Finally, register it via Microsoft Dependency Injection:
> `serviceCollection.AddScoped(typeof(IVersionTableMetaData), typeof(CustomVersionTableMetaData));`

This way is supported since a long time (3.x?) and worked well in my projects.

This stopped working due to an undocumented implicitly required registration order (see original description).

> Hard to spot, as in, you ran migrations without testing them / validating them? If people don't test their code, then that is not this project's problem to solve? I don't think this is a serious bug.

This issue has nothing to do with presence or absence of testing, nor does it question the importance of testing.

As I have shown, messing up the order of registrations leads to a hard-to-understand unexpected behavior (as the docs does not state anything about registration order).
I consider this a bug of _some_ form - **in code and/or in documentation**.

> If you need to Replace a core dependency, call [Replace](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.extensions.servicecollectiondescriptorextensions.replace?view=net-8.0)?

Yes, but then you have to already know what's going on (and deviate from the documentation's sample code).

**So, what do I want to be done?**
I want other devs to succeed using this library and not being deterred by such a mishap. Therefore, I would appreciate if you would reopen this issue, update the documentation and/or investigate and hopefully fix the registration order issue.

**Meta**
I know it's hard maintaining an open source project especially of this size and for this long time. This project is a very, very valuable one that helped me tremendously.  Thanks for maintaining it and providing support!

But I have one wish: If you - as you stated - don't know what the issue creator wants, please don't just quick-comment and close it without giving an opportunity to respond before doing so, but leaving it open to clear up misunderstandings and hopefully further enhance this library.

**Comment by jzabroski** [comment]
> This way is supported since a long time (3.x?) and worked well in my projects.
> 
> This stopped working due to an undocumented implicitly required registration order (see original description).

Can you provide a quick repro of it working on 3.x?

Trying to understand what could have broken it, there have not been many changes to this pipeline.

https://github.com/fluentmigrator/fluentmigrator/commit/a1b3df583f294cd6e2a4b85d3f7469f2c64aa0ca#diff-aa658122553fb65d54ffada31f932395515ef4781648ef1cdd6375c354e2cc30R79

and 

https://github.com/fluentmigrator/fluentmigrator/commit/a1b3df583f294cd6e2a4b85d3f7469f2c64aa0ca#diff-b0b30aa167ca75759da8f2cb0b8bbf7e083519a66fc077355c917acc1536f7a8L233-R233

and 

https://github.com/fluentmigrator/fluentmigrator/commit/d68a4f77f01bd7792c424f909c19ee2d90e7ba87

> > If you need to Replace a core dependency, call [Replace](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.extensions.servicecollectiondescriptorextensions.replace?view=net-8.0)?
> 
> Yes, but then you have to already know what's going on (and deviate from the documentation's sample code).

I think, what you're saying doesn't match my experience using Microsoft DI.  You do have to know what is in your type universe and calling Replace is the way you address overriding a type in your universe.

What solution would you propose if not having users call Replace?

**Comment by jzabroski** [comment]
There is also this commit that changed how OracleRunnerBuilderExtensions works, by making TypeMap injectable, but it's not clear why it would break your experience: https://github.com/fluentmigrator/fluentmigrator/commit/a5b1bf9203817f1d13010e20418e9f7cbf74087f#diff-7765c1da745dcbb27449c6678354e024a20847624bb79a5d9c0763057a614a28

**Comment by warappa** [comment]
Here's the repo:
https://github.com/warappa/FluentMigrator-1836

Running the program, you get asked if you want to register the `IVersionTableMetaData` class **too early**. Press **'y' or 'n'** to register too early or just right.
The output will tell you what version tables are actually generated (the previous SQLite database file is deleted on every start).
Maybe this helps debugging the different code paths taken in FluentMigrator.

Additionally, I included a TryAddScoped demo to demonstrate what I meant about the registration (giving user registrations priority). I hope this clears up what I meant previously (under "Investigation" in original description).

I hope this helps!

**Comment by jzabroski** [comment]
In your sample, you are using FluentMigrator 3.3.2 with net8.0.  I was not expecting that but since it is using netstandard2.0 , it is theoretically allowed.  I will debug.

**Comment by warappa** [comment]
### Fixing the Order Dependency
I checked out the current FluentMigrator source and added my repo project.

A quasi one-liner can add support for pre- or post-AddFluentMigratorCore registration.

This lines

https://github.com/fluentmigrator/fluentmigrator/blob/214345132f8b599ce72fdd21bf966baf894aae2d/src/FluentMigrator.Runner.Core/FluentMigratorServiceCollectionExtensions.cs#L112-L117

needs to be replaced by 
```csharp
 // Configure the default version table metadata 
 .TryAddScoped(sp => sp.GetRequiredService<IVersionTableMetaDataAccessor>().VersionTableMetaData ?? ActivatorUtilities.CreateInstance<DefaultVersionTableMetaData>(sp));

services.
 // Configure the migration information loader 
 .AddScoped<IMigrationInformationLoader, DefaultMigrationInformationLoader>() 
```

Just using the TryAddScoped here make the difference.

### MS DI Behavior Investigation
I did an investigation about registration order and how MS DI container deals with getting a single service if multiple registrations are found.

- If only 1 service is registered for example `IVersionTableMetaData`, it is easy: Just return this configured implementation.
- If **_more than_** 1 services are registered for this interface, it will pick the **_last_ registered** implementation.

Regarding this issue, this is the reason it always worked to just register a custom `IVersionTableMetaData` **_after_** `AddFluentMigratorCore()`. FluentMigrator _still registers_ `DefaultVersionTableMetaData`, but as the user implementation is registered afterwards, it is the last registration and therefore it wins.

I updated my repo (and pushed 😉) to also demonstrate this MS DI behavior.

**Comment by warappa** [comment]
Hi @jzabroski,
as you can see, I added a PR with tests. This fixes the issue and should not break anything (see 2nd test).

> [!TIP]
> I didn't look into this more deeply, but maybe some other registrations in `FluentMigratorServiceCollectionExtensions` could benefit from using the `Try...` variant. But this would be part of another issue.

**Comment by jzabroski** [comment]
We should probably convert everything to use TryAddScoped and note the breaking change in the 6.0.0 release notes. Interested in doing that?
