### ISSUE TITLE
Some tests fail if culture is different from en-US

### ISSUE THREAD

**Issue by warappa** [fluentmigrator/fluentmigrator#1848]
**Describe the bug**
Running the tests in german culture yields 5 errors. These are all releated to differences in culture ("," instead of ".", localized error messages instead of the english ones).

**To Reproduce**
Run the tests with a German culture
- A) German WIndows
- B) Setting `System.Globalization.CultureInfo.CurrentCulture`/`System.Globalization.CultureInfo.CurrentUICulture` to German culture before any tests executes (untested)

**Expected behavior**
Tests should not vary because of culture of operating system.

**Information (please complete the following information):**
 - OS: Windows 11
 - Platform .NET 8
 - FluentMigrator version 5.2.0/source

**Comment by warappa** [comment]
Examples:
"Wrong" because localized error message:
![grafik](https://github.com/user-attachments/assets/3762b470-6be2-4a1d-85cf-90e9e44eb73d)

Actually wrong generation with `PostgresExtensions`:
![grafik](https://github.com/user-attachments/assets/87945536-1b9f-40e1-acf7-158f8da9faad)

**Comment by warappa** [comment]
In the PR there is an actual bugfix (`PostgresGenerator`), so this is not just about test. If this should be it's own ticket/PR then I'll be happy to do so.

**Comment by jzabroski** [comment]
> In the PR there is an actual bugfix (`PostgresGenerator`), so this is not just about test. If this should be it's own ticket/PR then I'll be happy to do so.

Not necessary. This comment here is enough. The issue is that the vacuum index cleanup factor has to be in en-US decimal notation, yes?

**Comment by warappa** [comment]
Yes, this seems to be the case judging from the [documentation](https://www.postgresql.org/docs/12/runtime-config-client.html#GUC-VACUUM-CLEANUP-INDEX-SCALE-FACTOR) and the pre-existing FluentMigrator test.

I fixed it in this PR with `ToString(CultureInfo.InvariantCulture)` which is [more-or-less `en-US`](https://stackoverflow.com/a/2329317/516071) behind the scenes.
`CultureInfo.InvariantCulture` is also used e.g. in `GenericQuoter` for parsing numbers so I think this should be fine.

**Comment by jzabroski** [comment]
@warappa One comment. You can use SetCulture("").  string.Empty is how the CultureInfo constructor designates the Invariant Culture. https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.-ctor?view=net-8.0#system-globalization-cultureinfo-ctor(system-string)

### From "Remarks" on CultureInfo string constructor
> If name is [String.Empty](https://learn.microsoft.com/en-us/dotnet/api/system.string.empty?view=net-8.0#system-string-empty), the constructor creates an instance of the invariant culture; this is equivalent to retrieving the value of the [InvariantCulture](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=net-8.0) property.

**Comment by jzabroski** [comment]
Sorry, SetUICulture("") as you pointed out.
