### ISSUE TITLE
My Project implemented a sharding strategy, how can I use fluentmigrator to upgrade the database

### ISSUE THREAD

**Issue by weiyan2012** [fluentmigrator/fluentmigrator#1861]
How to synchronize and update all tenant databases under Saas architecture

**Comment by jzabroski** [comment]
@weiyan2012 Closing - I did not hear back from you.  It is hard to give advice about an unusual ci/cd process without insight into how you would address your "sharding strategy" without FluentMigrator.  If you could describe that process, then figuring out how to write code to accomodate it is the easy part.
