### ISSUE TITLE
Ability to pass parameters to Execute root sub-command Sql (feature parity with Script/EmbeddedScript)

### ISSUE THREAD

**Issue by jzabroski** [fluentmigrator/fluentmigrator#1870]
Resurrecting logic proposed by @zendever in https://github.com/fluentmigrator/fluentmigrator/pull/643

Ideally, the Parameters collection would come pre-seeded with certain special macros for things like DefaultSchema, plumbed in via the convention set.

**Comment by PhenX** [comment]
Hello, @jzabroski it looks like it already exists except for the Sql sub command https://github.com/fluentmigrator/fluentmigrator/blob/main/src/FluentMigrator.Abstractions/Builders/Execute/IExecuteExpressionRoot.cs

Or is it something else that you want ?

**Comment by jzabroski** [comment]
See this commit: https://github.com/fluentmigrator/fluentmigrator/pull/643/commits/cacd140a19946ade4c9217b9bf84f7ca2fafbce5

I forget what conversation I had with someone recently about this, but they wanted the ability to have a macro that said CurrentDatabase() or DefaultSchema().  DefaultSchema() would come from the convention set injected into the process.

**Comment by jzabroski** [comment]
Wait, sorry, I misread your response.  Yes, it exists for Execute.Script and Execute.EmbeddedScript.  It does not exist for Execute.Sql, which I imagine is probably one of the more popular approaches.

https://github.com/fluentmigrator/fluentmigrator/blob/9ef860f126de98512df1665ca875d4e19f26bb46/src/FluentMigrator.Abstractions/Builders/Execute/IExecuteExpressionRoot.cs#L50-L55

https://github.com/fluentmigrator/fluentmigrator/blob/9ef860f126de98512df1665ca875d4e19f26bb46/src/FluentMigrator.Abstractions/Builders/Execute/IExecuteExpressionRoot.cs#L69-L74

**Comment by jzabroski** [comment]
Updated the ticket title and original issue to include the note about the DefaultSchema macro.

**Comment by PhenX** [comment]
Ok so the fix should not be very hard, I'll make a pull request for this
