### ISSUE TITLE
PostgreSQL Error 55000 if database level replication is enabled

### ISSUE THREAD

**Issue by vmato** [fluentmigrator/fluentmigrator#1872]
**Describe the bug**
`The error was 55000: cannot delete from table "VersionInfo" because it does not have a replica identity and publishes deletes`

**To Reproduce**
Run migration on postgresql with replica publication enabled

**Expected behavior**
Migrator runs without errors

**Information (please complete the following information):**
 - OS: Windows
 - Platform .NET Framework 4.x
 - "in-process runner"
 - PostgreSQL

**Comment by jzabroski** [comment]
I need more information as I don't work in an environment where we use Postgres replication.

For example,
* what command is being run on Postgres that generates this error?
* why can't you add replication to the VersionInfo table?

**Comment by jzabroski** [comment]
Closing. @vmato I did not hear back from you. I need more details when you submit these issues for it to be something I can look into.

**Comment by jzabroski** [comment]
Sorry, I don't know how to help here.
