### ISSUE TITLE
Add support for non-clustered primary key

### ISSUE THREAD

**Issue by IlyaGrebnov** [fluentmigrator/fluentmigrator#335]
Add support for non-clustered primary key, like Create.Table("User").WithColumn("Id_User").AsInt32().Identity().PrimaryKey().NonClustered()

**Comment by igorgatis** [comment]
#340 does not really fix the issue, IMHO. The line @IlyaGrebnov posted could be used on a `WithGuidIdColumn` extension to enforce best practices of "Guid as Primary Keys"[1]:

        public static ICreateTableColumnOptionOrWithColumnSyntax WithGuidIdColumn(
            this ICreateTableWithColumnSyntax table)
        {
            return table
                .WithColumn("Guid").AsGuid().WithDefault(SystemMethods.NewSequentialId)
                .PrimaryKey().NonClustered();
        }

In the example above, `.PrimaryKey()` returns a `ICreateTableColumnOptionOrWithColumnSyntax` which does not support `.NonClustered()`.

[1] http://www.sqlskills.com/blogs/kimberly/guids-as-primary-keys-andor-the-clustering-key/

**Comment by 0xorial** [comment]
Is this currently supported? I do not have .NonClustered() after .PrimaryKey()...

**Comment by jzabroski** [comment]
Please don't comment on 8 year old issues. The maintainers are different now, and the major version increased from 1 to 3. Please open a new issue with a link to old ones.
