### ISSUE TITLE
Add support for indexes with included columns

### ISSUE THREAD

**Issue by IlyaGrebnov** [fluentmigrator/fluentmigrator#336]
SQL Example:

CREATE NONCLUSTERED INDEX 
     IX_Address_PostalCode
ON 
    Person.Address (PostalCode)
INCLUDE 
    (
      AddressLine1,
      AddressLine2,
     City,
     StateProvinceID
);

**Comment by TPedersenDataFinch** [comment]
Was the Include option for indexes included in the May 25th 2013 release? I seem to be unable to find the option in the latest nuget 1.6.2 package released a few days after the merge.

**Comment by TPedersenDataFinch** [comment]
Never mind - I had not linked the right runner.dll and not added the "using FluentMigrator.Runner.Extensions;".

All good now.
