### ISSUE TITLE
Can't migrate set of tables in a given Database

### ISSUE THREAD

**Issue by ghost** [fluentmigrator/fluentmigrator#361]
This issue is the same as the #106 and looks like it wasn't solved despite a tentative contribution from the #106 issuer.

To recap the need: I have a framework made of several modules which are all evolving separately, but I want to store their tables in the same database.

Let's say I have
- Module1 with tables A, B, C
- Module2 with tables D, E

I want to define a set of migration classes for Module1 and another for Module2.
I came up with a combination of Tags and Migration like:

Module1:

``` csharp
[Tags("Module1")]
[Migration(1)]
class Module1Initial {}

[Tags("Module1")]
[Migration(2)]
class Module1Upgrade {}
```

Module2:

``` csharp
[Tags("Module2")]
[Migration(1)]
class Module2Initial {}

[Tags("Module2")]
[Migration(2)]
class Module2Upgrade {}
```

Unfortunately the VersionInfo table doesn't not support the Tags when stored the highest updated version number, which totally disables migrations of Module2 after I've made a migration of Module1.

I believe the issue #219 doesn't solve this as it is stated in the discussion of the #106.

Any help would be appreciated, I can try to solve the issue myself, but let me know how you guys would like me to proceed. 

From my "noob of FM" perspective an additional column in VersionInfo to store a given Tags sequence would be enough to handle this scenario. 

Then if migration is based on Tags, find the Migration classes with these tags and when adding the line in VersionInfo store the given Tags sequence. 

Then also modify the method that returns the current highest version, but based on a Tags sequence (which can be none, of course).

**Comment by schambers** [comment]
In an effort to organize the backlog and close out extremely old tickets, this ticket is being closed. If you feel like the issue still applies, please open a new ticket and we'll review for future addition. Thank you!å
