### ISSUE TITLE
Schema support for ForeignKey

### ISSUE THREAD

**Issue by palfrey** [fluentmigrator/fluentmigrator#365]
It would be nice to be able to detect foreign keys in the same manner as we can currently do Schema.Table("blah").Exists()

**Comment by fubar-coder** [comment]
Will be covered by idempotent migrations.

**Comment by schambers** [comment]
In an effort to organize the backlog and close out extremely old tickets, this ticket is being closed. If you feel like the issue still applies, please open a new ticket and we'll review for future addition. Thank you!
