### ISSUE TITLE
IfDatabase runs scripts targeted for SqlServer on SqlServerCE

### ISSUE THREAD

**Issue by matt-richardson** [fluentmigrator/fluentmigrator#387]
The current implementation of IfDatabase in IfDatabaseExpressionRoot uses "StartsWith" and strings rather than an enum. This means that you cannot target SqlServer (ie, 2000/2005/2008/2012) separately to SqlServerCE (unless you target "SqlServer2").

Commit 3c0504e157224b952c54edebb6fdd76341c5ec46 changed the signature from an enum to a string - not entirely sure why. However, the previous implementation would've had the same issue.

Before I make a fix and send a pull request, I would like to know a bit of background of this change and why the enum was removed.

**Comment by fubar-coder** [comment]
The current behavior is by design. You can now use the syntax from issue #683 to check by equality:

```
IfDatabase(x => x == "SqlServer" || x == "SqlServer2014")
```
