### ISSUE TITLE
FluentMigrator should use SQL Compact Edition NuGet package instead of including files itself

### ISSUE THREAD

**Issue by Athari** [fluentmigrator/fluentmigrator#389]
Microsoft provides [NuGet package for SqlCe](http://nuget.org/packages/Microsoft.SqlServer.Compact/), however FluentMigrator relies on files included in its solution. It causes multiple problems:
1. If FluentMigrator is included in the project (necessary to access from the code), SqlCe files are always copied into the output directory. If NuGet package is used, files are copied two times.
2. Version of SqlCe is fixed and never updated. It's hard to update files included with FluentMigrator.
3. Including binary files in a Git repository for code is generally a bad idea, as it makes it slow and large, especially if files are frequently updated.

NuGet package is a private deployment, so it's pretty close to "manual" private deployment currently used, however it doesn't have these drawbacks.

**Comment by tommarien** [comment]
I totally agree on this but to be able to this we need a lot of effort in moving to a new model for fluentmigrator. We need to be able to run in the context of the migration assembly and need to create different provider nugets, so if you just use sql server you don't need to install sqlce nuget etc

**Comment by fubar-coder** [comment]
We should use it for .NET Framework, but provide our own for .NET Standard.
