### ISSUE TITLE
Mapping Int64 to Sqlite BigInt

### ISSUE THREAD

**Issue by markswiatek** [fluentmigrator/fluentmigrator#391]
I have an Int64 value that I'm trying to store in a Sqlite column defined AsInt64(). Currently that maps as follows:
              SetTypeMap(DbType.Int64, "INTEGER");
Is there a reason this isn't mapped to BIGINT.

When I try to insert ticks into this column, I end up with a 0. If I change the column to BIGINT, my value is inserted.

**Comment by fubar-coder** [comment]
`BIGINT` is `INTEGER` internally, but the `AUTOINCREMENT` syntax requires it being `INTEGER`. There is no disadvantage in keeping `INTEGER`.
