### ISSUE TITLE
Alter Table set primary key.

### ISSUE THREAD

**Issue by ghost** [fluentmigrator/fluentmigrator#393]
Hi, Think I've just stumbled upon a issue while attempting to make a column on my table a primary key.  I did the following migration:

```
Alter.Table("tableName")
    .AlterColumn("Id").AsInt64().NotNullable().PrimaryKey();
```

And the SQL generated looks like this:

ALTER TABLE [dbo].[tableName] ALTER COLUMN [Id] BIGINT NOT NULL

Runing MS SQL 2008 on framework version 4.5.

**Comment by fniwes** [comment]
Even when there is a workaround, the operation should not be permitted or generate a error.
