### ISSUE TITLE
No information about not existent namespace in RunnerContext 

### ISSUE THREAD

**Issue by Xunrel** [fluentmigrator/fluentmigrator#431]
For a current project I'm using the fluentmigrator again and I found something unpleasant.

I'm using the RunnerContext and setting the namespace to my migrations, because I have to maintain two seperate databases with different table definitions, which worked great.
After a while I had to refactor my solution which ended up in a different namespace for my migrations and the previous namespace I used for the RunnerContext didn't exist anymore.

So after about an hour of searching the bug I realized that the namespace string for the RunnerContext does not give me any information that he did not found any migrations.

After fixing the namespace it worked again and I found a better approach for finding the correct namespace I need (in short: I'm searching the namespace through the DefinedTypes of the Assembly I'm using for the MigrationRunner).
But would it be possible to throw an exception or give any information from the RunnerContext if it did not find andy migrations?

**Comment by fubar-coder** [comment]
An exception is now (in 2.0.0) thrown when no migration could be found in the given namespace/assembly.
