### ISSUE TITLE
Migrate allows non-reversable auto-reversable migrations

### ISSUE THREAD

**Issue by mirhagk** [fluentmigrator/fluentmigrator#439]
Using auto-migrate is a very handy tool, however the auto-reversing migration class still allows many non-reversible methods. Ideally these should not be included in the class, or should throw errors when migrating, or at least warnings in the code, but they do not.

Rather what happens is I rollback a change and I get an error then. I should not be allowed to migrate something that does not have a down method IMO

**Comment by Caltor** [comment]
`Rename` is the one that always catches me out! Has that been fixed now so a warning is provided?

**Comment by fubar-coder** [comment]
Auto-reversing migrations is something that definitely needs an overhaul, but is nothing that can be done on a single weekend. It's on my todo list, but it's not done yet.
