### ISSUE TITLE
SqlServer2000Processor strips new lines from data.

### ISSUE THREAD

**Issue by mmiller678** [fluentmigrator/fluentmigrator#442]
I have a some data that is being read in from resource files and added to the database using FM.  I noticed that when there were multiple new lines in the data  they replaced with a single \n when the INSERT statements were being generated.  This only seemed to occur some of the time which was confusing.  I found some code in ExecuteBatchNonQuery that looks for the word 'go' and if its found it splits the SQL by line with the option to remove empty entries (StringSplitOptions.RemoveEmptyEntries).

This is fine if its just new lines between SQL statements, but in the case where the new lines are part of the data it results in a different data being acted upon.  In some cases my data had the word GO in it so I was seeing this behavior - in other cases the data did not contain the word go so the behavior was not seen.

I think the simple fix is to not remove empty entries and to change the replacement that happens to use Environment.NewLine rather than \n.  

A better improvement would be to have the logic to decide to use the ExecuteBatchNonQuery method would look for GO statement on its own line rather than using contains as it would be a better indicator.

The work around for now is to generate your own SQL statements and use Migration.Execute.

**Comment by fubar-coder** [comment]
This happens, because we're using `sql.Split(new[] { "\n", "\r" }, StringSplitOptions.RemoveEmptyEntries)`. This may affect other processors too.

**Comment by fubar-coder** [comment]
I'm currently trying to implement an [SQL batch parser](https://github.com/fluentmigrator/batch-parser) which should solve this problem.

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0
