### ISSUE TITLE
Remove the VersionTableMetaData Attribute

### ISSUE THREAD

**Issue by nfplee** [fluentmigrator/fluentmigrator#469]
Without looking at the code could you not simply say the following to get the type that implements IVersionTableMetaData within the assembly:

assembly.GetExportedTypes().SingleOrDefault(t => typeof(IVersionTableMetaData).IsAssignableFrom(t) && !t.IsAbstract)

**Comment by tommarien** [comment]
@nfplee I would be possible yes, but still we need the attribute for backwords compatibility. Do i smell a pull  ?

**Comment by fubar-coder** [comment]
This problem should be obsolete with the development of a new migrator.
