### ISSUE TITLE
Simplify options by combining migrate:up / down and rollback?

### ISSUE THREAD

**Issue by thomaseyde** [fluentmigrator/fluentmigrator#479]
Hi,

I'm using FluentMigrator in my auto-deployment setup and have stumbled into an issue regarding rollback. When I deploy the next version and something goes wrong, I want to rollback to the previous working version. I also want to use the same workflow in both cases.

And here is the catch: Migrate.exe has different arguments for migrating up and down, which doesn't work for me. When I deploy a certain version, I don't know which way I'm migrating, only the expected version.

Why is it we can't have simple options like:
--migrate, which migrates to latest version
--migrate --version, which migrates to the given version

I'm probably missing something, but I don't understand the need for migrate:down and the various rollback options. Wouldn't a --migrate --version cover all those?

**Comment by tommarien** [comment]
@thomaseyde Not really then you would need to know the version always for instance rollback will only rollback the last applied version

**Comment by fubar-coder** [comment]
This is (IMHO) not in the scope of the project as it implies some kind of intelligent logic, which (almost) always produces unexpected results.
