### ISSUE TITLE
Tags / Namespace selection not working as required for software components.

### ISSUE THREAD

**Issue by tohagan** [fluentmigrator/fluentmigrator#481]
When you execute a runnner with Tags="FeatureA,FeatureB" only migration 4 will run.
What I expected was that all would run except migration 6.  

Changing the current Tags behavior would be a breaking change.  So what I'd recommend is for the Runners to use a different delimiter to indicate an OR rather than an AND condition on the tags.  e.g.  Tags="FeatureA|FeatureB". Note that for an OR condition, I think tag filtering should only be applied to migrations that have a Tag attribute (so in this case migration 1 should still run). This makes it easy to support "core component" migrations (no tags) + component specific migrations (tag per component) + complex cases involving integration like foreign keys between multiple components (multiple tags on a migration).

I'm trying to select a complete set of migrations that will run as part of a single transaction (TransactionPerSession == true) but currently can't see a way to do this. 

I had also hoped to be able to run all migrations in sub namespaces but currently can only select a single namespace per session. I'm using the Tags and namespace features in combination (for complex reasons).

```
[Migration(1)]
public class BaseComponent: Migration
{
}

[Tags("FeatureA")]
[Migration(2)]
public class ComponentA: Migration
{
}

[Tags("FeatureB")]
[Migration(3)]
public class ComponentB: Migration
{
}

[Tags("FeatureA","FeatureB")]
[Migration(4)]
public class BothABComponents: Migration
{
}

[Tags("FeatureA")]
[Tags("FeatureB")]
[Migration(5)]
public class EitherABComponents: Migration
{
}

[Tags("FeatureC")]
[Migration(6)]
public class ComponentC: Migration
{
}
```

FYI ... The code generator I'm working on will support this pattern by allowing you to select subsets of tables that corresponding to a component and then emit generated migrations tagged by component ID. You can also control the migration numbers it generates to ensure the correct migration sequence.

**Comment by fubar-coder** [comment]
This requires a completely new runner/version table design.

**Comment by fubar-coder** [comment]
You can use the following solution:

- Using multiple version tables (for every component)
- Specify the `TagsAttribute.Behavior` as `RequireAny`

**Comment by tohagan** [comment]
Thanks!
