### ISSUE TITLE
Feature request: Being able to retrieve a version number from a database table

### ISSUE THREAD

**Issue by brunzefb** [fluentmigrator/fluentmigrator#52]
Hi,

One thing I am missing is the ability to read a version number from an arbitrary table to make decisions if you need to upgrade:

public override Up()
{
   int majorVersion;
   int minorVersion;
    Execute.ReadVersion("SELECT Major, Minor FROM ApplicationVersionTable WHERE AppID='MyApp'", out majorVersion, out minorVersion);
   if(majorVersion > 3 && minorVersion >1)
   {
      // do schema changes etc....
   }

}

Now maybe there is a way to do this already, but a quick glance at the code shows that this may be missing.

Currently, we implement this with a simple ADO.NET SQL query, but it would be nice to have this as part of the fluentmigrator toolset.

Friedrich

**Comment by fubar-coder** [comment]
Superseded by issues #838 and #839
