### ISSUE TITLE
Exposing custom configuration through migration

### ISSUE THREAD

**Issue by mwpowellhtx** [fluentmigrator/fluentmigrator#534]
Hello,

Having gotten my feet wet with FM a bit, doing both fluent as well as SQL-backed migration, I am interested in a use case involving a user configuration, potentially.

Specifically, migrating towards SQL Server, FILESTREAM, FILEGROUP(s), etc, identifying those directory path(s) at the moment of migration. Once configured in the database, the rest is pretty well straightforward altering tables, adding/altering columns, connecting with defined files, filegroups, etc.

We could hard-code the paths depending on build configuration, but a better option seems like exposing a custom-configuration-section through the app- and/or web-config, and allowing the end-user to configure that approaching delivering, into dev, into test, into production, etc. The configuration approach would work and allow us to either identify which configs to include, transform, etc.

In my mind's eye, I don't see why this would be a problem combining the two technologies, but I'd like to get a second opinion from authoritative FM folks.

Thank you...

**Comment by tommarien** [comment]
@mwpowellhtx You could add your environment to applicationcontext and use that environment in your migrations to get necessary configuration from config files

**Comment by fubar-coder** [comment]
The application context is the way to go.
