### ISSUE TITLE
SQLite for Mono supported?

### ISSUE THREAD

**Issue by haf** [fluentmigrator/fluentmigrator#556]
It seems there's no obvious nuget package from `sqlite.org` for Mono, and mono has its `Mono.Data.SQLite` assembly that implements the ADO.Net interface itself. The system.data.SQLite.org guys think it's a good idea to not ship a compiled package for mono, but that has to be compiled for yourself from a little-used SCM called fossil, on Windows.

So I guess my question is how well Linux/OS X is supported? It would be nice to be able to use FluentMigrator when I'm used to it, even on Mono for SQLite.

**Comment by tommarien** [comment]
@haf I have no experience on mono what so ever maybe @daniellee knows?

**Comment by haf** [comment]
I talked to the SQLite guys and they welcome PRs and help to get mono officially supported. I can't get engaged in even more OSS projects myself, right now though.

**Comment by dealproc** [comment]
I'm wondering if we need to use [this](http://www.mono-project.com/docs/database-access/providers/sqlite/) package, instead of `System.Data.SQLite`... Just running into this issue myself.  Maybe I'll update and see what happens.

**Comment by dealproc** [comment]
First issue that I'm running into is that the .net framework stack is still on 3.5 for the base project.  I'm wondering if at this point in the game, if it isn't advisable to roll to .net 4.0 or 4.5/4.6, as it would provide the capability to use `Mono.Data.Sqlite`.

I'm working on a fork of the repo right now, and am going to upgrade the project to .net 4.5 and see what happens.  @tommarien, realizing this is the Christmas holiday, when you're back on the computer, if you wouldn't mind letting me know if folks are game to look at upgrading the dependency of .net 3.5 for FluentMigrator or not.

**Comment by dealproc** [comment]
Here's what I wound up with:

https://github.com/dealproc/fluentmigrator/tree/sqlite-mono

Going to build a custom set of *.dlls, add them to a project I'm working on right now that is using FluentMigrator, and see what happens.  If anyone sees anything blaring, let me know.  The changes were near damn 1-1, so I don't see (outside of dropping the .net 3.5 dependency) how this would hurt folks.

**Comment by tommarien** [comment]
@dealproc To be honest i think we have to move fluentmigrator to v2 (which would be .net 4.5.1 only) this would enable a lot of possibilities

* Oracle Managed only support
* Extendability of providers etc
* Lazy, etc

Future of this project is getting uncertain because we have enough ideas with almost nobody to execute them. My initial plan was to move fluentmigrator towards a more modularised approach see the discussion group for this.

**Comment by fubar-coder** [comment]
System.Data.SQLite works now on mono

**Comment by dealproc** [comment]
sweet.  thanks for this @fubar-coder
