### ISSUE TITLE
SQLite and multi column constrains on Create.Table(..)

### ISSUE THREAD

**Issue by karaaie** [fluentmigrator/fluentmigrator#598]
Hello! 

Since SQLite does not allow for creation of constrains after a table has been created, I'd like to create the constraint at table creation time instead. However I can only find how to do this by calling .Unique() on the column. I could not find a way of doing this for many columns at the same time, have I missed something?

**Comment by tommarien** [comment]
@karaaie I don't think you have, normally you can do this with a Create.Index expression. But that is not option for sqllite.

**Comment by scaredfinger** [comment]
Hi guys!! I really need this feature as I use to create unit tests over in memory sqlite db, when my actual will be another one (most likely mysql).

**Comment by tommarien** [comment]
@scaredfinger I would love to help you out but as alter table etc is not allowed on sqllite i guess we are stuck until someone finds a way around it.

IMHO: I would strongly rethink your strategy as the differences between mysql and sqllite are just to big. Maybe use mysql local installed for integration tests, i am sure it is fast enough ;)

**Comment by scaredfinger** [comment]
Thanks a lot.

I work myself around.

Cheers!!!
