### ISSUE TITLE
Oracle 11g migration fails to create a table

### ISSUE THREAD

**Issue by xumix** [fluentmigrator/fluentmigrator#603]
The code is pretty easy:

```
Create.Table("DOU.MailQueue").WithDescription("Очередь почтовых сообщений")
                  .WithColumn("Id").AsGuid().NotNullable().PrimaryKey().WithDefault(SystemMethods.NewGuid)
                  .WithColumn("Subject").AsString(400).NotNullable().Indexed()
                  .WithColumn("Body").AsString(int.MaxValue).NotNullable()
                  .WithColumn("Attached").AsBinary(int.MaxValue).Nullable()
                  .WithColumn("From").AsString(400).NotNullable().Indexed()
                  .WithColumn("To").AsString(400).NotNullable().Indexed()
                  .WithColumn("IsSent").AsBoolean().NotNullable().Indexed().WithDefaultValue(0)
                  .WithColumn("AddedDate").AsDateTime().NotNullable().WithDefault(SystemMethods.CurrentDateTime);
```

```
BEGIN
   EXECUTE IMMEDIATE
      'CREATE TABLE DOU.MailQueue (Id RAW(16) DEFAULT sys_guid() NOT NULL, Subject NVARCHAR2(400) NOT NULL, Body NCLOB NOT NULL, Attached BLOB, From NVARCHAR2(400) NOT NULL, To NVARCHAR2(400) NOT NULL, IsSent NUMBER(1,0) DEFAULT 0 NOT NULL, AddedDate TIMESTAMP(4) DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_DOU.MailQueue PRIMARY KEY (Id))';

   EXECUTE IMMEDIATE
      'COMMENT ON TABLE DOU.MailQueue IS ''Очередь почтовых сообщений''';
END;
```

This sql is actually invalid. All the identifiers must be escaped with double quotes including constraint, column and index names.

**Comment by tommarien** [comment]
@xumix Have you tried using quoted identifiers ? https://github.com/schambers/fluentmigrator/wiki/Command-Line-Runner-Options#--providerswitchesvalue

**Comment by xumix** [comment]
@tommarien I've looked into --help but missed that switch. Why is is not always enabled by default?

**Comment by tommarien** [comment]
@xumix Because quoting promotes case sensitivity on most db's. You tried with the quoted indentifiers option ? (did it work ?)

**Comment by xumix** [comment]
@tommarien Why is case sensitivity is an issue? Looks like it is just the desired behavior

**Comment by tommarien** [comment]
@xumix Well i tend to agree on that statement but some will disagree, this gives the option to opt-in for the behavior ;)

**Comment by xumix** [comment]
@tommarien Ok, I've tried the option:
```
[+] Using Database oracle and Connection String data source=192.168.2.116:1521/orcl;password=********;persist security info=True;user id=***
SELECT 1 FROM USER_TABLES WHERE upper(TABLE_NAME) = 'VERSIONINFO'
SELECT 1 FROM USER_TAB_COLUMNS WHERE upper(TABLE_NAME) = 'VERSIONINFO' AND upper(COLUMN_NAME) = 'APPLIEDON'
SELECT 1 FROM USER_TAB_COLUMNS WHERE upper(TABLE_NAME) = 'VERSIONINFO' AND upper(COLUMN_NAME) = 'DESCRIPTION'
SELECT 1 FROM USER_TABLES WHERE upper(TABLE_NAME) = 'VERSIONINFO'
!!! ORA-00942: table or view does not exist
```

If I remove the option - it works OK

**Comment by tommarien** [comment]
@xumix on a clean db ?

**Comment by xumix** [comment]
Nope, of course it is not clean already, since I used migration many times.

**Comment by tommarien** [comment]
@xumix Was there any specific IVersionTableMetaData override done ?

**Comment by xumix** [comment]
@tommarien nope, no customizations at all

**Comment by tommarien** [comment]
@xumix are you still in a position to remove the versioninfotable ? (I'm guessing that's where it goes wrong)

**Comment by tommarien** [comment]
@xumix Any update ?

**Comment by xumix** [comment]
I just can't remove it since I use it in production and can't just drop all the history.

**Comment by fubar-coder** [comment]
Closed due to inactivity.

**Comment by a-jamil-idware** [comment]
How can I enable Quoted Identifer for Oracle DB?

**Comment by jzabroski** [comment]
@a-jamil-idware That would be a feature request.
