### ISSUE TITLE
Token replacement for scripts

### ISSUE THREAD

**Issue by zendever** [fluentmigrator/fluentmigrator#625]
Not 100% sure the best approach here, or if there was some sort of mechanism for passing parameters to Execute.Script, but it would certainly be nice if scripts could be tokenized (maybe using $(token) or something, and then as an optional parameter, you could pass in a Dictionary<string, string> that would replace token values.

For data in scripts that may require the token format, they could be "escaped" by using something like $$((token)) which would set it back to what it would be in the data.

I've already forked this and updated, so let me know if you want a pull request.

**Comment by tommarien** [comment]
@zendever Can you give me some clear use case explaining examples ?

**Comment by zendever** [comment]
It's mainly for simplicity...yes, you could embed all scripts into Execute.Sql statements, thus giving you access to config/build specific parameters, but it's much easier to model and then export database creation/alter scripts.

Given property "Config" is the environment-specific app.config and "create.sql" looks something like:

```sql
CREATE DATABASE [$(Catalog)]
	CONTAINMENT = NONE
	ON PRIMARY (NAME = N'$(Catalog)', FILENAME = N'$(FileGroupLocation)\$(Catalog).mdf', SIZE = 4096KB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
	LOG ON (NAME = N'$(Catalog)_log', FILENAME = N'$(FileGroupLocation)\$(Catalog)_log.ldf', SIZE = 1024KB, MAXSIZE = 2048GB, FILEGROWTH = 10%)
GO

ALTER DATABASE [$(Catalog)] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
	EXEC [$(Catalog)].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [$(Catalog)] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [$(Catalog)] SET ANSI_NULLS OFF 
GO
....
INSERT INTO dbo.tblTemplateData (SomeTemplateData) VALUES('Catalog = $$((Catalog))')
...
```

Usage would be something like: 

```c#
Execute.Script("create.sql", new Dictionary<string, string> { {"Catalog", Config.AppSettings.Settings["Catalog"].Value }, { "FileGroupLocation", Config.AppSettings.Settings["FileGroupLocation"].Value } });
```

and the generated SQL would be:

```sql
CREATE DATABASE [MyDatabase]
	CONTAINMENT = NONE
	ON PRIMARY (NAME = N'MyDatabase', FILENAME = N'C:\DATA\MyDatabase.mdf', SIZE = 4096KB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
	LOG ON (NAME = N'MyDatabase_log', FILENAME = N'C:\DATA\MyDatabase_log.ldf', SIZE = 1024KB, MAXSIZE = 2048GB, FILEGROWTH = 10%)
GO

ALTER DATABASE [MyDatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
	EXEC [MyDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

ALTER DATABASE [MyDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyDatabase] SET ANSI_NULLS OFF 
GO
...
INSERT INTO dbo.tblTemplateData (SomeTemplateData) VALUES('Catalog = $(Catalog)')
...
```

This would give you the ability to generate environment specific scripts without having to alter the base script which may be completely appropriate for any environment, save for a few main pieces of data. So, maybe the production database is located in a different file location on the server, or the database name is something like "MyDatabase_Prod".

I was able to get this working fine in my fork, and it's handy for creating base scripts from previous models and then moving them to a migration project and then having other developers get quickly spun up from scratch while having machine specific locations/names.

Some caveats for migrating from creation scripts is that the default Catalog has to be set to "master"...but then again, it may only be relevant to run the script in specific tagged environments, or the build process would have grants to create/alter databases anyway.

**Comment by zendever** [comment]
@tommarien ... I was wondering if you had an opportunity to review this enhancement request. I have this coded up and ready to go, although I'll probably add some unit tests. The usefulness comes in to play when dealing with modifications to the database itself. In particular, this has enhancement has been somewhat crucial in our development path as it allows developers to easily stand up databases in both local and development environments on shared servers.

While the same thing could be achieved by using something like profiles or tags and duplicating migrations and/or scripts, it's a bit of extra work attached to the migration product.

I understand it may not be a high priority enhancement, but it's an enhancement I'm willing to contribute to as long as the semantics and use are to your liking.

**Comment by tommarien** [comment]
@zendever Could you share some code with us ?

I am guessing that you allow on 

Execute.Embeddedscript, Execute.sql etc where you can pass a dictionary or a dynamic object ?

**Comment by zendever** [comment]
@tommarien ... EXACTLY as you stated above, I added a dictionary parameter that associates the token to the value.

I added this function to the IExecuteExpressionRoot tree:

```c#
void Script(string pathToSqlScript, IDictionary<string, string> tokenDictionary);
```

Below is my updated version of the ExecuteScriptExpression.

```c#
public class ExecuteSqlScriptExpression : MigrationExpressionBase
{
	public string SqlScript { get; set; }

	public IDictionary<string, string> Parameters { get; set; }

	public override void ExecuteWith(IMigrationProcessor processor)
	{
		string sqlText;
		using (var reader = File.OpenText(SqlScript))
			sqlText = reader.ReadToEnd();

		// since all the Processors are using String.Format() in their Execute method
		//	1) we need to escape the brackets with double brackets or else it throws an incorrect format error on the String.Format call
		//	2) we need to replace tokens
		//	3) we need to replace escaped tokens
		sqlText = Regex.Replace(
			Regex.Replace(
				sqlText.Replace("{", "{{").Replace("}", "}}"),
				@"\$\((?<token>\w+)\)",
				m => ((Parameters != null) && Parameters.ContainsKey(m.Groups["token"].Value))
					? Parameters[m.Groups["token"].Value]
					: ""),
			@"\${2}\({2}(?<token>\w+)\){2}",
			m => string.Format("$({0})", m.Groups["token"]));

		// adding ability to pass parameters to execute function
		processor.Execute(sqlText);
	}

	public override void ApplyConventions(IMigrationConventions conventions)
	{
		SqlScript = Path.Combine(conventions.GetWorkingDirectory(), SqlScript);
	}

	public override void CollectValidationErrors(ICollection<string> errors)
	{
		if (string.IsNullOrEmpty(SqlScript))
			errors.Add(ErrorMessages.SqlScriptCannotBeNullOrEmpty);
	}

	public override string ToString()
	{
		return base.ToString() + SqlScript;
	}
}
```

**Comment by tommarien** [comment]
@zendever i would go for the double mustaches (like mustache is doing) and start from your dictionary keys likes this

```c#
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApplication22
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            string sql = @"CREATE DATABASE [{{MyDatabase}}]
    CONTAINMENT = NONE
    ON PRIMARY (NAME = N'MyDatabase', FILENAME = N'C:\DATA\MyDatabase.mdf', SIZE = 4096KB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
    LOG ON (NAME = N'MyDatabase_log', FILENAME = N'C:\DATA\MyDatabase_log.ldf', SIZE = 1024KB, MAXSIZE = 2048GB, FILEGROWTH = 10%)
GO

ALTER DATABASE [{{MyDatabase}}] SET COMPATIBILITY_LEVEL = 110
GO";

            var dictionary = new Dictionary<string, string>
            {
                {"MyDatabase", "DBNAME"}
            };

            dictionary.Keys
                .ToList()
                .ForEach(key => { sql = sql.Replace(string.Format("{{{{{0}}}}}", key), dictionary[key]); });


            Console.WriteLine(sql);
            Console.ReadLine();
        }
    }
```

But i am sure you can make this code more optimal and faster ;)

**Comment by zendever** [comment]
@tommarien ... Hey, I apologize for not responding to this sooner. So, I purposely chose $(token) as the format because it follows exactly the format for T-SQL scripts being passed into the command line with parameter injection. Not that it matters, but it makes the upgrade path for T-SQL fairly benign as existing scripts wouldn't have to be modified...again...this is hardly a "requirement".

That said, this is YOUR vision, just confirm that you want me to use double-braces and I'll do that instead. I just want to be absolutely sure before I change anything.

**Comment by zendever** [comment]
@tommarien ...I finally had a little time to update the pull request that adds the token dictionary functionality.

I think this would be a nice improvement to the code base.

**Comment by fubar-coder** [comment]
Should be fixed with PR #666

**Comment by fubar-coder** [comment]
I'll look into it again.

**Comment by fubar-coder** [comment]
Ah, it was mixed into the PR #643. I kept that part out yet, sorry for the confusion.
