### ISSUE TITLE
Default to Unicode strings

### ISSUE THREAD

**Issue by vgrigoriu** [fluentmigrator/fluentmigrator#636]
Would it be possible, when inserting data, to default to Unicode strings? That is, instead of having to use `ExplicitUnicodeString`, to force people to use `ExplicitNonUnicodeString` when they don't want Unicode? I realize this might be a breaking change, but it seems like the right thing to do. Am I missing something that makes this a bad idea?

**Comment by tommarien** [comment]
@vgrigoriu I guess it all depends on the use case, i never liked the naming though UnicodeString should have been better as a class name.

What you could do and has less side effects is keeping the code as is but

* Add Ansistring in same way as we now have ExplicitUnicode
* Add overload option to insert update etc which is by default false threatallstringsasunicode (expect the ones explicitly using a type like ansistring or unicodestring)

What do you think about this ?

**Comment by vgrigoriu** [comment]
I don't think there's any use case in which defaulting to ANSI strings is correct. Either you only use ASCII characters, so you don't care, or you use accented characters, in which case clearly what you want is an Unicode string. If we make Unicode strings the default and someone's code behavior changes then it was almost certainly a bug.

I think the right thing to do would be:
- deprecate ExplicitUnicodeString
- add AnsiString, as you suggested
- default to formatting normal .NET strings as Unicode SQL strings.

If you agree, I'll try to send a PR this weekend.

cc @Ashthos who originally introduced `ExplicitUnicodeString`.

**Comment by fubar-coder** [comment]
Fixed in 2.0.0

**Comment by vgrigoriu** [comment]
Wow 😄 

Thanks for finally getting this in!

**Comment by fubar-coder** [comment]
It was a rough ride. 1 month of work went into the 2.0 release.
