### ISSUE TITLE
DateTime2 support

### ISSUE THREAD

**Issue by krillgar** [fluentmigrator/fluentmigrator#637]
The project that I'm currently working on requires DateTime2 support. Is there reasons why that and the other date types from SQL Server 2008+ haven't been implemented yet? I started a fork, but didn't want to go too far into it in case there was some conscious decision that was made.

**Comment by immeraufdemhund** [comment]
https://github.com/schambers/fluentmigrator/blob/master/src/FluentMigrator.Runner/Generators/SqlServer/SqlServer2008TypeMap.cs

Looks like it is implemented to me (unless I'm reading the code incorrectly)

**Comment by krillgar** [comment]
I added the AsDateTime2() method to [IColumnTypeSyntax](https://github.com/krillgar/fluentmigrator/commit/9ce6b31e30677cff400eaf6cd5b4ccfa6b030560). 

Does the SqlServer2008TypeMap allow me to actually create a column with those types, or does it just enable its use?

**Comment by immeraufdemhund** [comment]
Well using the fluent api I tried all the date variants (as I'm sure you did as well) and couldn't get it to generate a datetime2. I see DateTime2 in a few of the Unit Tests, but it must not be hooked up. I did however get it to work by using AsCustom("DateTime2") and that made the DateTime2 column

**Comment by rasmuschristensen** [comment]
Thanks @immeraufdemhund .Works on sql azure, but not sqlexpress. Needed to change it manually afterwards

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0
