### ISSUE TITLE
Migrate.exe tasks silient failures

### ISSUE THREAD

**Issue by Horusiath** [fluentmigrator/fluentmigrator#655]
While working with Migrate.exe tool I've found following issue - after running any task, console returns completed notification, but no work is actually done, none result has been returned and no failures info has been displayed. Example:

> ./packages/FluentMigrator.1.5.0.0/tools/Migrate.exe  -connection "**connection_string**" -target "./**migration_dll**.dll" -provider sqlserver -task listmigrations -verbose true

Output: 

```
-------------------------------------------------------------------------------
=============================== FluentMigrator ================================
-------------------------------------------------------------------------------
Source Code:
  http://github.com/schambers/fluentmigrator
Ask For Help:
  http://groups.google.com/group/fluentmigrator-google-group
-------------------------------------------------------------------------------
[+] Using Database sqlserver and Connection String **connection string**
-------------------------------------------------------------------------------
Migrations
-------------------------------------------------------------------------------
[+] Task completed.
```

As output shows, there are no migrations displayed, while in fact few dozens of them should be listed. Connection string and path to dll are correct. Similar result is returned with basically any other task requested.

**[EDIT]** After some time spent I've finally managed to find a source of the problem. Dll was compiled against FluentMigrator version 1.3, while Migrate.exe came from nuget version 1.5. Nonetheless tool should inform about assembly version mismatch for the sanity of future devs ;)

**Comment by tommarien** [comment]
@Horusiath Ok, never tried this myself. Do you have any clue why it does not work? As looking at the changes from 1.3 to 1.5 i can see nothing that could explain this behavior

**Comment by fubar-coder** [comment]
Not easy to handle this case.
