### ISSUE TITLE
Custom metadata for VersionInfo table is not detected

### ISSUE THREAD

**Issue by danehnert** [fluentmigrator/fluentmigrator#656]
I have created my custom class implementing the IVersionTableMetaData interface (including the VersionTableMetaData attribute). Unfortunately the migration runner doesn't detect my custom implemention (it used to work in a previous release). I also tried to inherit from the DefaultVersionTableMetaData class, but without luck.

I'm using a custom migration runner, which is embedded in our custom maintenance tool. The code executing the runner looks like this:

``` csharp
private MigrationRunner GetMigrationRunner(IAnnouncer announcer, bool previewOnly)
{
            Assembly assembly = Assembly.GetExecutingAssembly();

            RunnerContext migrationContext = new RunnerContext(announcer)
            {
                Namespace = "xxx.xxx.DbTool.Migrator.Migrations"               
            };            

            MigrationOptions migrationOptions = new MigrationOptions();
            migrationOptions.PreviewOnly = previewOnly;
            migrationOptions.Timeout = 60;           

            SqlServer2005ProcessorFactory factory = new SqlServer2005ProcessorFactory();
            IMigrationProcessor processor = factory.Create(_connectionString, announcer, migrationOptions);    

            return new MigrationRunner(assembly, migrationContext, processor);               
}
```

**Comment by tommarien** [comment]
@danehnert Ok tracked it down to this commit

https://github.com/schambers/fluentmigrator/commit/0382e5333c8880bc01c65c7cf86fd031689cf96c

It changes the way types are found but also for the versionmetadata

**Comment by eloekset** [comment]
@istaheev @tommarien, should VersonLoader simply not filter by namespace? It changed again in commit 525e4330, but is still filtering by namespace.

**Comment by fubar-coder** [comment]
The namespace should be respected too to enable different namespaces for different databases.
