### ISSUE TITLE
No sqlite autoindex with unique

### ISSUE THREAD

**Issue by STVM** [fluentmigrator/fluentmigrator#662]
When I create a column with Unique(), it doesn't have the word 'UNIQUE' in the creating table query. An index is created but in SQLite with UNIQUE an autoindex should be created.

What is the différence between Index() and Unique() on a column ? The 2 methods create a new index.

**Comment by fubar-coder** [comment]
Might be related to #753 . Can you provide unit tests with the expected results?

**Comment by fubar-coder** [comment]
SQLite doesn't know named constraints, so named INDEXes are used instead. A more thorough explanation can be found in #753.

**Comment by schambers** [comment]
In an effort to organize the backlog and close out extremely old tickets, this ticket is being closed. If you feel like the issue still applies, please open a new ticket and we'll review for future addition. Thank you!
