### ISSUE TITLE
Oracle: define tablespace when creating an index.

### ISSUE THREAD

**Issue by barser** [fluentmigrator/fluentmigrator#667]
Oracle: define tablespace when creating an index.

As far as I know, the separate tablespace containing all indices data is well-known solution for performance improvements. It would be helpful to add an opportunity for defining tablespace with fluent syntax.

**Comment by fubar-coder** [comment]
Canj you provide more detailed information?

**Comment by jzabroski** [comment]
Duplicate of #967 - @barser  This is absolutely on the roadmap to try to add this year.
