### ISSUE TITLE
Access to context from root expressions

### ISSUE THREAD

**Issue by rbwamsley** [fluentmigrator/fluentmigrator#668]
I'm creating an extension class for my application and am trying to keep my code fluent.

Example. Delete.ApplicationRole(34)

We have a stored procedure to delete application roles which follows the FK references all the way down through the table chain. I want to call this stored proc from my extension method. The problem is that I cannot access the context off DeleteExpressionRoot to create an ExecuteExpressionRoot to call my stored proc.

Is there another way of doing this?

public static class ApplicationRoleExtensions
{
        public static IDeleteExpressionRoot ApplicationRole(this IDeleteExpressionRoot root, long roleId)
        {
            IExecuteExpressionRoot exec = new ExecuteExpressionRoot(???);
        }
}

**Comment by fubar-coder** [comment]
Note FM related
