### ISSUE TITLE
Fluentmigrator reports success when trying to migrate an assembly without any migrationscripts in it.

### ISSUE THREAD

**Issue by ulven77** [fluentmigrator/fluentmigrator#670]
FluentMigrator returns success when I try to migrate an assembly without any migrationscripts in it. Please save me from myself :)
## =============================== FluentMigrator ================================

Source Code:
  http://github.com/schambers/fluentmigrator
Ask For Help:
##   http://groups.google.com/group/fluentmigrator-google-group

[+] Using Database sqlserver and Connection String Data Source=***
; Initial Catalog=**_; User Id=**_;Password=********;
[+] Task completed.

**Comment by tommarien** [comment]
@ulven77 For me this how it should react. It eases the pain when starting from scratch in development and already wanted to have fluentmigrator in your pipeline. What is your oppinion on this and why do you think it's wrong ?

**Comment by ulven77** [comment]
@tommarien I can see your point but for me as a new user I want to be told when Im doing something potentially, wrong like trying to migrate an assembly with no migrations in it.

**Comment by fubar-coder** [comment]
Maybe we should add a warning?
