### ISSUE TITLE
Add categories for all tests

### ISSUE THREAD

**Issue by eloekset** [fluentmigrator/fluentmigrator#671]
Visual Studio Test Explorer makes it easy to run tests by category. To run only tests for a specific database type or various types of generator tests I suggest that we add four categories to all tests:
1. General database type, i.e. SQLServer, Firebird, Hana etc
2. Specific database type, i.e. SQLServer2005, SQLServer2014 etc
3. Type of unit test, i.e. Generator, Builder etc
4. Detailed type of unit test, i.e. Table, Index etc for Generator tests and Alter, Create etc for Builder tests.

An example for an SQL Anywhere 16 Generator test for Index statements:
[Category("SQLAnywhere"), Category("SQLAnywhere16"), Category("Generator"), Category("Index")]
![2015-11-10_1553](https://cloud.githubusercontent.com/assets/791721/11065370/3e2611b2-87c3-11e5-9bd8-fddef797f10e.png)

**Comment by fubar-coder** [comment]
Fixed in develop
