### ISSUE TITLE
Firebird: AlterColumnSetNullable not working any more since 3.0

### ISSUE THREAD

**Issue by fubar-coder** [fluentmigrator/fluentmigrator#673]
Meta data changes aren't allowed since 3.0.

**Comment by tommarien** [comment]
@fubar-coder 3.0 is still in release canditate, from what i could see is that added the following

ALTER TABLE <table name> ALTER <field name> [NOT] NULL

Regards

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0
