### ISSUE TITLE
Logging from within the migration

### ISSUE THREAD

**Issue by LSTANCZYK** [fluentmigrator/fluentmigrator#680]
I would like to be able to log information from inside of the migration. This should be included in the output log. Is this currently possible and if not, please consider it as a feature request.

**Comment by ROIInstitute** [comment]
I would also like to know this.

**Comment by sjorsmiltenburg** [comment]
I would also like to know this..

**Comment by eloekset** [comment]
I don't think it's possible. I've been using Console.WriteLine() from within my migrations, but that obviously works when run in a console runner only.

**Comment by sjorsmiltenburg** [comment]
what I did was create a custom announcer which writes to log4net.

`public class Log4netAnnouncer : Announcer
	{
		private static readonly log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

		public override void Write(string message, bool escaped)
		{
			Log.Debug(message);
		}

		public override void Error(Exception exception)
		{
			base.Error(exception);
			Log.Error(exception);
		}
	}`

**Comment by fubar-coder** [comment]
I think about using Microsoft.Extensions.Logging. This would allow log message filtering and would at least a partial solution for this problem.

**Comment by fubar-coder** [comment]
Fixed in develop branch
