### ISSUE TITLE
Provide ability to override quoter on RunnerContext

### ISSUE THREAD

**Issue by volkanceylan** [fluentmigrator/fluentmigrator#687]
First of all, thanks for this awesome tool, it changed the way i'm thinking about database versioning, and i'm using in it my business app platform, [Serenity](https://github.com/volkanceylan/serenity).

Considering a table created with this simple migration:

``` cs
Create.Table("Users")
```

If you run this migration in SQL server, it quotes with brackets, and in PostgreSQL it uses double quotes, nothing seems wrong so far.

But later, when you wanted to execute a very simple query:

``` sql
SELECT * FROM Users
```

This works in SQL Server, but not PostgreSQL.

``` sql
SELECT * FROM users
```

Again this works in SQL Server, but not PostgreSQL.

In PostgreSQL, if you put double quotes in tablename, while creating a table, not only it becomes case sensitive, you must also use double quotes while querying it, even if you use the exact same case. I don't want to question their reasons. They probably had a very bright idea while designing this.

But i didn't put double quotes myself, PostgreSQLQuoter did this, and i have no option to turn it off.

I just want to be able to write database-independent SQL queries (with dapper etc) at least for very simple ones, without having to quote everything.

I don't ask you to change defaults, maybe some people are depending on this feature, but please provide a way to override default quoter of the generator. I think it should be a parameter on RunnerContext. I'll subclass quoter, and assign it before running migrations.

**Comment by fubar-coder** [comment]
We probably need a way to enforce quoting, but it should't be enabled by default, because this would cause problems for databases like Firebird. Maybe configuration over DI would be an option too.

**Comment by fubar-coder** [comment]
With 3.0, you're able to create a new class, derived from `PostgresQuoter` and add it via dependency injection:

```
services
    .AddScoped<PostgresQuoter, YourDerivedPostgresQuoter>();
```

Whenever the `PostgresQuoter` is queries, your implementation will be used instead. You can do the same with the `SqlServer2008Quoter` (or 2005 or 2000).

Just override the `ShouldQuote` function and always return `true`.

**Comment by a-jamil-idware** [comment]
@fubar-coder 
Can I do that for Oracle as well using "OracleQuoter" class?

**Comment by jzabroski** [comment]
@a-jamil-idware Yes, you can look at where PostgresQuoter is used and add similar support for an OracleQuoter.  Happy to accept a PR and get it merged quickly (within one week turnaround usually).

**Comment by jzabroski** [comment]
Related comment: https://github.com/fluentmigrator/fluentmigrator/issues/603#issuecomment-94649803 explains why by default we wouldn't quote.  Although, I am a bit skeptical that quoting really does force case sensitivity of variable names

**Comment by a-jamil-idware** [comment]
I understand quoting does force case sensitivity, I would have created a PR for that but I am extremely busy and I have temporarily used character escape. I think there should be a proper way for that and I have added a feature request for this [Enable Quoted Identifier functionality for Oracle](https://github.com/fluentmigrator/fluentmigrator/issues/1365)

**Comment by a-jamil-idware** [comment]
@jzabroski  I will create a PR for the above mentioned feature request.
