### ISSUE TITLE
Oracle Script Migrator works locally, fails on server.

### ISSUE THREAD

**Issue by cletisgipson** [fluentmigrator/fluentmigrator#688]
I have a scrip that runs fine locally, however when I copy the contents to a remote server, the script fails.

Here is the script.

CREATE OR REPLACE TRIGGER SEDD_HIST 
    before update on CORPS_SPECIAL_ED_DIRECTOR
    for each row
       begin
       insert into CORPS_SPECIAL_ED_DIRECTOR_HIST (
          SPECIAL_ED_DIRECTOR_HIST_ID,
          SPECIAL_ED_DIRECTOR_ID,
          SEDD_CORP_ID_CHAR,
          SPECIAL_ED_DIRECTOR_TYPE,
          SEDD_AUTHROIZER_NAME,
          SEDD_PLANNING_DISTRICT_NAME,
          SEDD_TITLE,
          SEDD_NAME_FIRST,
          SEDD_NAME_MIDDLE,
          SEDD_NAME_LAST,
          SEDD_EMAIL,
          SEDD_PHONE,
          SEDD_FAX,
          SEDD_ADDRESS,
          SEDD_CITY,
          SEDD_STATE,
          SEDD_ZIP,
          SEDD_LAST_UPDATE,
          SELD_TITLE,
          SELD_NAME_FIRST,
          SELD_NAME_MIDDLE,
          SELD_NAME_LAST,
          SELD_EMAIL,
          SELD_PHONE,
          SELD_FAX,
          SELD_ADDRESS,
          SELD_CITY,
          SELD_STATE,
          SELD_ZIP,
          SELD_LAST_UPDATE )
       values ( CORPS_SPL_ED_DIRECTOR_HIST_SEQ.NEXTVAL,
          :old.SPECIAL_ED_DIRECTOR_ID,
          :old.SEDD_CORP_ID_CHAR,
          :old.SPECIAL_ED_DIRECTOR_TYPE,
          :old.SEDD_AUTHROIZER_NAME,
          :old.SEDD_PLANNING_DISTRICT_NAME,
          :old.SEDD_TITLE,
          :old.SEDD_NAME_FIRST,
          :old.SEDD_NAME_MIDDLE,
          :old.SEDD_NAME_LAST,
          :old.SEDD_EMAIL,
          :old.SEDD_PHONE,
          :old.SEDD_FAX,
          :old.SEDD_ADDRESS,
          :old.SEDD_CITY,
          :old.SEDD_STATE,
          :old.SEDD_ZIP,
          :old.SEDD_LAST_UPDATE,
          :old.SELD_TITLE,
          :old.SELD_NAME_FIRST,
          :old.SELD_NAME_MIDDLE,
          :old.SELD_NAME_LAST,
          :old.SELD_EMAIL,
          :old.SELD_PHONE,
          :old.SELD_FAX,
          :old.SELD_ADDRESS,
          :old.SELD_CITY,
          :old.SELD_STATE,
          :old.SELD_ZIP,
          sysdate );
    end;

It runs fine locally, but gives the following error when i run it from a server.

[+] ExecuteEmbeddedSqlScript DOEOnline.Database.Oracle.Scripts.Script0005
te Trigger SEDD_HIST.sql
!!! ORA-06550: line 1, column 6:
PLS-00103: Encountered the symbol "" when expecting one of the following:

   begin case declare exit for goto if loop mod null pragma
   raise return select update while with <an identifier>
   <a double-quoted delimited-identifier> <a bind variable> <<
   close current delete fetch lock insert open rollback
   savepoint set sql execute commit forall merge pipe
The symbol "begin was inserted before "" to continue.
ORA-06550: line 67, column 8:
PLS-00103: Encountered the symbol "" when expecting one of the following:

   begin case declare end exception exit for goto if loop mod
   null pragma raise return select update while with
   <an identifier> <a double-quoted delimited-id
!!! ORA-06550: line 1, column 6:
PLS-00103: Encountered the symbol "" when expecting one of the following:

   begin case declare exit for goto if loop mod null pragma
   raise return select update while with <an identifier>
   <a double-quoted delimited-identifier> <a bind variable> <<
   close current delete fetch lock insert open rollback
   savepoint set sql execute commit forall merge pipe
The symbol "begin was inserted before "" to continue.
ORA-06550: line 67, column 8:
PLS-00103: Encountered the symbol "" when expecting one of the following:

   begin case declare end exception exit for goto if loop mod
   null pragma raise return select update while with
   <an identifier> <a double-quoted delimited-id

Any idea why this would be happening?

**Comment by fubar-coder** [comment]
Maybe a different Oracle version? Some missing updates?
