### ISSUE TITLE
Enum Support

### ISSUE THREAD

**Issue by farhadbheekoo** [fluentmigrator/fluentmigrator#693]
Hi

does anyone know how to handle enums or would that be a custom type? If it is a custom type, how does that work?

**Comment by eloekset** [comment]
Is this a specific issue to your migrations? I think the answer is to cast your enum values to int values, so your migrations would just be written for standard Int32 columns. There's a question about storing enums in an SQL DB at StackOverflow here: http://stackoverflow.com/a/1390704/1421847
