### ISSUE TITLE
Using FluentMigrator on existing database

### ISSUE THREAD

**Issue by charuhans** [fluentmigrator/fluentmigrator#696]
I am working with a project and would like to move it to use FluentMigrator. I exported the current schema using SQL Server Management Studio using the Generate Scripts functionality. It includes create table, alter table, stored procedures, views etc. 
I created an empty database I tried to run my first migration as:

```
[Migration(0)]
public class Baseline : Migration
{
    public override void Up()
    {
        this.Execute.Script("BaselineSetup.sql");
     }

    public override void Down()
    {
        this.Execute.Script("BaselineDown.sql");
    }
 }
```

When I run my migration, I get following error:

The error was ALTER DATABASE statement not allowed within multi-statement transaction.
!!! ALTER DATABASE statement not allowed within multi-statement transaction.

In order to fix the error, I tried to run migration with:

```
[Migration(0, TransactionBehavior.None)]
```

I was able to run the script, but I got a following error:

INSERT INTO [xyz].[VersionInfo]([Version], [AppliedOn], [Description]) VALUES (1, '2016-01-25T15:56:35', 'Baseline')
The error was Invalid object name 'xyz.VersionInfo'.

**Comment by jarz** [comment]
FluentMigrator tracks the applied migrations using the VersionInfo table. Can you see if the table was created in a different schema (perhaps dbo)?

**Comment by charuhans** [comment]
Hi Jarz,

Thank you for your reply. 

I did change default schema for Version table:

    [VersionTableMetaData]
    public class VersionTable : DefaultVersionTableMetaData
    {
        public override string SchemaName => "xyz";
    }

It still gives me same error.

**Comment by marcrocny** [comment]
As a side note, it might be a good idea to pull the `ALTER DATABASE` statement out into it's own transaction-free migration, and let the rest run within a transaction.  Just a thought.
