### ISSUE TITLE
TaskExecutor HasMigrationsToApply method

### ISSUE THREAD

**Issue by eloekset** [fluentmigrator/fluentmigrator#700]
When migrations are run automatically on startup of an application, it should be possible to make a database backup before TaskExecutor.Execute() is called. However the backup is not necessary unless any migrations will actually be executed. 

This functionality could be implemented in a subclass of TaskExecutor, but to make it easier to decide whether or not to do a backup, the TaskExecutor can instead provide a public method HasMigrationsToApply() that any custom runner can call.

```
if (executor.HasMigrationsToApply())
    BackupDatabase();

executor.Execute();
```

**Comment by fubar-coder** [comment]
Fixed by #701
