### ISSUE TITLE
Expose the Connection String Name

### ISSUE THREAD

**Issue by jzielke** [fluentmigrator/fluentmigrator#703]
Would it be possible to exposed the original connection string name from the command line? 

The connection string in the object is the expanded connection string from the App.Config file. I would like to do some extra database logic and need the connection string name that is passed in.

I can get around this by specifying the connection string name on the command line as a ApplicationContext value since I am not using that today but I am adding the same information twice.  

So would it be possible to add a ConnectionName property or something like that?

**Comment by fubar-coder** [comment]
You can always use the application context to pass your data to the migrations.
