### ISSUE TITLE
preview mode output do not match exactly with executed sql (in MSSQL)

### ISSUE THREAD

**Issue by mnieto** [fluentmigrator/fluentmigrator#706]
Due to our deploy procedure, we must supply .sql scripts to the db admins, so we cannot use migrate.exe
- If I run `migrate --ouput --outfile script.sql` the generated output has plenty of batch separator (GO) between statements.
- If I run `migrate --ouput --outfile script.sql --preview` the generated file will execute with errors because it needs batch separator for certain statements.

I have found a related issue #292, but I think that the problem is not only specific to stored procedures.
Please, see the attached file showing the normal output (left) and the preview output (right)

![2016-03-14 16_15_19-winmerge - script sql - 01 migration sql](https://cloud.githubusercontent.com/assets/7962206/13749098/3dd7913c-ea00-11e5-832e-3d8f45fd6b9b.png)

**Comment by jarz** [comment]
+1. We noticed this on Oracle, but never had time to investigate. ¯\_(ツ)_/¯

**Comment by fubar-coder** [comment]
Seems to be fixed in the meantime
