### ISSUE TITLE
Upgrade projects to VS 2015 and C# 6

### ISSUE THREAD

**Issue by fubar-coder** [fluentmigrator/fluentmigrator#711]
I'd propose to update the projects to VS 2015 and C# 6. VS 2015 CE is available for (almost) everyone and C# 6 has some interesting features like exception filters, etc. while still being able to target .NET 4 (which has reached its EOL).
- [ ] Upgrade all projects
- [ ] Add projects to FluentMigrator.sln from FluentMigrator (2010).sln

@tommarien Did I miss something? Is there work to be done on/for the build server that I overlooked?

**Comment by tommarien** [comment]
@fubar-coder This means we drop 3.5 and mono support ?, seems like something for 2.0 version

**Comment by fubar-coder** [comment]
Latest mono (and Xamarin.*) can handle up to 4.6 just fine. Older mono versions should be able to support .NET up to 4.0, but we don't need to drop 3.5. We can use all (or just almost all?) C# 6 features for .NET 3.5. Example:

```csharp
class Program
{
    static void Main(string[] args)
    {
        try
        {
            try
            {
                throw new Exception("Test");
            }
            catch (Exception ex) when (Test(ex))
            {
                Debug.Assert(false, "Never executed");
            }
        }
        catch
        {
            Console.WriteLine("Should print this line");
        }
    }

    private static bool Test(Exception ex)
    {
        Console.WriteLine(ex.ToString());
        return false;
    }
}
```

**Comment by tommarien** [comment]
@fubar-coder i would go for a .net 4 (including mono) on next major then so fluent migrator v2

**Comment by abusby** [comment]
I agree this should be a 2.0 milestone request.  There is not real benefit for the upgrade at the moment and it is a breaking change.  

You have mentioned execption filtering, I am curious, have you got a specific feature use case in mind that you want to use them for?

If you need them personally why not create a 2.0 branch and then merge upstream changes.

**Comment by fubar-coder** [comment]
Done
