### ISSUE TITLE
Multiple tags are ignored

### ISSUE THREAD

**Issue by tharris29** [fluentmigrator/fluentmigrator#713]
When adding multiple tags to the command line it either ignores them both or takes the first one. I have tried the following

```
/tag MyTag /tag SecondTag
```

And

```
/tag MyTag SecondTag
```

**Comment by tharris29** [comment]
Found my issue. I thought the tags worked as a "OR" condition but it is an "AND"

**Comment by tharris29** [comment]
What I was trying to do is run items which are "ALL" or "Specific"

**Comment by tommarien** [comment]
@tharris29 anything we can do to help or can I close this ?

**Comment by fubar-coder** [comment]
Closed due to inactivity.
