### ISSUE TITLE
Dropping DefaultConstraint

### ISSUE THREAD

**Issue by lineker** [fluentmigrator/fluentmigrator#715]
Hi,

I'm trying to drop a column that has a default constraint.
I'm trying to drop the constraint before dropping the table but I get an error when using fluent migrator.

Delete.DefaultConstraint().OnTable("LicenseKeys").InSchema("licensing").OnColumn("isTrial");

a get the following error:
DECLARE @default sysname, @sql nvarchar(max);

-- get name of default constraint
SELECT @default = name
FROM sys.default_constraints
WHERE parent_object_id = object_id('[licensing].[LicenseKeys]')
AND type = 'D'
AND parent_column_id = (
SELECT column_id
FROM sys.columns
WHERE object_id = object_id('[licensing].[LicenseKeys]')
AND name = 'isTrial'
);

-- create alter table command to drop constraint as string and run it
SET @sql = N'ALTER TABLE [licensing].[LicenseKeys] DROP CONSTRAINT ' + @default;
EXEC sp_executesql @sql;
The error was Incorrect syntax near '.'.

ps: using MS Server 2012

**Comment by jarz** [comment]
If you run the SELECT query in SSMS, does it return the correct constraint
name?

**Comment by lineker** [comment]
Yes, it seems the problem is when "EXEC sp_executesql @sql;" gets executed.

**Comment by jarz** [comment]
Do you have the output/command that your migration attempts? (I mainly use
Oracle, but maybe me or someone else can identify the syntax issue.)

**Comment by lineker** [comment]
I gave the output already. Here it goes again:

`DECLARE @default sysname, @sql nvarchar(max);

-- get name of default constraint
SELECT @default = name
FROM sys.default_constraints
WHERE parent_object_id = object_id('[licensing].[LicenseKeys]')
AND type = 'D'
AND parent_column_id = (
SELECT column_id
FROM sys.columns
WHERE object_id = object_id('[licensing].[LicenseKeys]')
AND name = 'isTrial'
);

-- create alter table command to drop constraint as string and run it
SET @sql = N'ALTER TABLE [licensing].[LicenseKeys] DROP CONSTRAINT ' + @default;
EXEC sp_executesql @sql;
The error was Incorrect syntax near '.'.`

**Comment by tommarien** [comment]
What is the name of the default constraint ? So the result of the SELECT

**Comment by lineker** [comment]
ALTER TABLE [licensing].[LicenseKeys] DROP CONSTRAINT DF_licensing.LicenseKeys_isTrial

**Comment by cmaish** [comment]
I think I've run into a version of this issue as well - the SqlServer2005 Generator gets the constraint name but executes it unescaped.

In my case, the constraint was DF_Table_[Mandatory].  As constraints can be named pretty much anything, it looks like it could be possible to use this with a crafted database to execute any SQL.
