### ISSUE TITLE
Documentation about FluentMigrator.T4

### ISSUE THREAD

**Issue by Hilgo** [fluentmigrator/fluentmigrator#720]
I am not sure if this is the right place to report about the documentation but i went to wiki page of fluentmigrator, in [Guide to FluentMigrator.T4](https://github.com/schambers/fluentmigrator/wiki/Guide-to-FluentMigrator.T4), and it's incomplete.

Here's a screenshot to show how that wiki page looked like in the time i made this report.

![captura de tela 32](https://cloud.githubusercontent.com/assets/7366331/15247038/cda73af4-18e7-11e6-8281-220c23696e52.png)

**Comment by fubar-coder** [comment]
FluentMigrator.T4 isn't supported anymore
