### ISSUE TITLE
28000: no PostgreSQL user name specified in startup packet

### ISSUE THREAD

**Issue by Corstiaan84** [fluentmigrator/fluentmigrator#722]
This runs fine on my dev/local machine:

`mono packages/FluentMigrator.Tools.1.6.1/tools/AnyCPU/40/Migrate.exe -a Reflect.Web.v2.Migrations/bin/Debug/Reflect.Web.v2.Migrations.dll -db Postgres -conn "Server=localhost;Port=5432;Database=<redacted>;User Id=<redacted>;Password=<redacted>;CommandTimeout=20;" -profile "Debug"`

But when running this in production:

`mono /app/packages/FluentMigrator.Tools.1.6.1/tools/AnyCPU/40/Migrate.exe -a Reflect.Web.v2.Migrations.dll -db Postgres -conn "Server=dokku-postgres-reflectdb;Port=5432;Database=<redacted>;User Id=<redacted>;Password=<redacted>;CommandTimeout=20;" -profile "Release"`

It throws

`28000: no PostgreSQL user name specified in startup packet`

I tried adding a `username` param to the connection string, removing the `User Id` params, etc but to no avail.

Any ideas? :-)

Im using postgres...

**Comment by Corstiaan84** [comment]
I took a different approach: I ran Migrate.exe passing the name of the connection string in the app.config of the migrations project, instead of passing the connection string directly as a parameter, like this:

`Migrate.exe -a Reflect.Web.v2.Migrations.dll -db Postgres -conn "NameOfConnectionString" -profile "Release"`

This works.

**Comment by fubar-coder** [comment]
Might be a mono/npgsql version issue.
