### ISSUE TITLE
AsString() generates varchar column type instead of nvarchar column type in MySql database

### ISSUE THREAD

**Issue by hollisyao** [fluentmigrator/fluentmigrator#724]
In MySql database, AsString() should generate nvarchar column type.
The error source code is as follow:
Project: FluentMigrator.Runner
Path: Generators\MySql\MySqlTypeMap.cs
Code: line43 - 49
SetTypeMap(DbType.StringFixedLength, "CHAR(255)");
            SetTypeMap(DbType.StringFixedLength, "CHAR($size)", StringCapacity);
            SetTypeMap(DbType.StringFixedLength, "TEXT", TextCapacity);
            SetTypeMap(DbType.StringFixedLength, "MEDIUMTEXT", MediumTextCapacity);
            SetTypeMap(DbType.StringFixedLength, "LONGTEXT", LongTextCapacity);
            SetTypeMap(DbType.String, "VARCHAR(255)");
            SetTypeMap(DbType.String, "VARCHAR($size)", TextCapacity);

**Comment by intelbrainee** [comment]
I think you should use `AsCustom("NVARCHAR(n)");`

**Comment by Hollisyao** [comment]
No, i have read the source code, AsString() will always generate nvarchar() data type in Sql Sever, and AsAnsiString() is be mapped varchar() data type.

**Comment by intelbrainee** [comment]
Okay, didn't know you were referring to MS SQL Server, I use MySQL.

**Comment by Hollisyao** [comment]
maybe, i did not make it clearly.
I am using MySql, i have just found that FluentMigrator still generate **VARCHAR(50)** data type even if i specified **AsCustom("NVARCHAR(50)")**

**Comment by intelbrainee** [comment]
`nvarchar()` is not supported on MySQL so it defaults to `varchar()`.

**Comment by fubar-coder** [comment]
The better choice would be using something like `VARCHAR(n) CHARSET utf8`

**Comment by Hollisyao** [comment]
Thank you both very much.

**Comment by Hollisyao** [comment]
@fubar-coder how do i create a index for a TEXT column?

            Create.Index("IX_dbo.AbpUsers_IsDeleted_TenantId_EmailAddress").OnTable("dbo.AbpUsers")
                .OnColumn("IsDeleted").Ascending()
                .OnColumn("TenantId").Ascending()
               

>  .OnColumn("EmailAddress").Ascending() ??? length???

**Comment by Hollisyao** [comment]
and i found that VARCHAR(128) column should also be specify the length as a index.

**Comment by fubar-coder** [comment]
NVARCHAR support is available since MySQL 5 and is implemented in the release/2.0.0 branch
