### ISSUE TITLE
Execute.EmbeddedScript and multiple SQL instructions in Oracle

### ISSUE THREAD

**Issue by pittpasc** [fluentmigrator/fluentmigrator#729]
Hello,

I'm trying to use FluentMigrator with the function `Execute.EmbeddedScript(@"SQLtest.sql");`

But I can't load an SQL file with more than 1 SQL Instruction ! Everytime I put a ";" in the end of a sql statement, it generate an error with the migrate.exe runner. Here the command used :

`Migrate.exe --db "Oracle" --conn "mydatasource" --assembly  "myAssemblyMigrator.dll" --task "migrate:up"`

Did someone experience this and knows how to fix it ? Or maybe there's another way to write multiple SQL instructions in a file ?

Thanks for you help
Pitt

**Comment by barser** [comment]
Hello, check that in your sql script all ";" placed at beginning of new
lines.

Like so:

Insert....
;
Update....
;
Delete....
15.07.2016 12:54 пользователь "pittpasc" <notifications@github.com> написал:

**Comment by pittpasc** [comment]
It works ! A little bit tricky this workaround. It is because of Oracle ?
Thank you so much for the quick response
Kind Regards
Pitt

**Comment by barser** [comment]
I had similar issue with Oracle database also. I don't know about other
databases. By the way, if you have some packages, functions, trigger
declarations etc. in your sql embedded scripts you don't need to place ";"
at new line in these cases. The difference is in these cases semicolon is
the part of sql statement (not the separator between different sql
statements)...
18.07.2016 12:26 пользователь "pittpasc" <notifications@github.com> написал:

**Comment by fubar-coder** [comment]
Answered by @barser
