### ISSUE TITLE
Support for SqlServer2016 ?

### ISSUE THREAD

**Issue by amrithyerramilli** [fluentmigrator/fluentmigrator#732]
Hi,

I have been using FluentMigrator for our database migrations for a while now.
Recently, I shifted to Sql Server 2016 (specifically, Azure SQL Databse - whose compatibility matches sql server 2016).

Was wondering if and when support for this could be available.

**Comment by amrithyerramilli** [comment]
Bump?

**Comment by tommarien** [comment]
Hi, 

Any feature just want in particular, i remember that we added sql2014 which atm just inherits from sql2012

KR

**Comment by mstancombe** [comment]
For what it's worth, I have been using FM with Sql Azure dbs for over a year now, and haven't had any problems.

**Comment by grajdeanserghei** [comment]
Hi, 

I briefly checked the [SQL Server Database Engine Backward Compatibility](https://docs.microsoft.com/en-us/sql/database-engine/sql-server-database-engine-backward-compatibility) for 2016 & 2017 and din't find anything suspicious that can break functionality. 

@tommarien, I found the commit for SQL Server 2014  - [ae7d639](https://github.com/fluentmigrator/fluentmigrator/commit/ae7d63946c96c931ddbb72b811d887a58339adf8)

Can we do the same for 2016 and 2017?

**Comment by eloekset** [comment]
I added Generator and Processor for Sqlserver2016 in #763 but then made #788 since the feature implemented in the first PR appeared to have existed way back. I can make a new PR with only those commits that introduce the Generator and Processor.

**Comment by grajdeanserghei** [comment]
Yeah, having a separate PR with link to this issue would be very helpful because when you search in google for "FluentMigrator support Sql Server 2016" you get this page as first result and there is no evidence that it has been fixed. Maybe at least you can link this issue to your existing PR.

Thanks

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0
