### ISSUE TITLE
SetExistingRowsTo with SystemMethods produces incorrect sql script

### ISSUE THREAD

**Issue by govorovvs** [fluentmigrator/fluentmigrator#733]
I'he found that SetExistingRowsTo with SystemMethods produces incorrect UPDATE script.

Here is example migration
`Alter.Table("Table").InSchema("dbo")
.AddColumn("EditDate").AsDateTime().NotNullable().WithDefault(SystemMethods.CurrentUTCDateTime).SetExistingRowsTo(SystemMethods.CurrentUTCDateTime);`
and result script
`UPDATE [dbo].[Table] SET [EditDate] = 'CurrentUTCDateTime' WHERE 1 = 1`

**Comment by mstancombe** [comment]
Currently it doesn't support system methods, only fixed values, as under the hood it uses the same flow as the Update expression, eg, 

```
Update.Table("Table")
    .Set(new { EditDate = DateTime.Today })
    .AllRows()
```

In your case you can probably use
```
Alter.Table("Table").InSchema("dbo")
.AddColumn("EditDate").AsDateTime().NotNullable().WithDefault(SystemMethods.CurrentUTCDateTime)
.SetExistingRowsTo(Datetime.UtcNow);
```
If you really wanted to use the SystemMethods when populating existing rows, I think you would have to implement them in the UpdateDataExpression.
