### ISSUE TITLE
Listmigrations lists all migrations but does not show which has been applied in previous then current version

### ISSUE THREAD

**Issue by ArneHB** [fluentmigrator/fluentmigrator#749]
I can't find the documentation that specifies how this should exactly work and maybe this is more of a feature request. Currently it lists all Migrations and which is the current migration you're on. To me I would also think that all the listed migrations of previous then current version had been applied but that is not the case.

My request is that listmigrations would show migrations not applied with a [ - ] instead of [ + ] infront. Those migrations not implemented that is of previous version then current should perhaps also get a red or orange color so it's clear it hasn't been applied.

Example:
If two people work on same migration project, Foo checks in first, with migration version 3, and Bar checks in last, with migration version 2. Foo has already  run migration 1 and 3 then pulls down the latest code before he builds the project. He then runs <Migration.exe> -task listmigrations to see what migrations he's missing/version he's on. It will show him all 3 migrations and that he's on the latests (current) while which is true of the point is only to show in what version he's on. List migrations would give a lot more if it also showed him that version 2 hadn't been run.

Example 2:
(Those in red circle is migrations missing and hasn't been applied)
![image](https://cloud.githubusercontent.com/assets/3367106/20712124/22de859c-b643-11e6-8d7d-8e7ce3ebb161.png)
![image](https://cloud.githubusercontent.com/assets/3367106/20712160/447767a0-b643-11e6-9477-aaf2abefd3e2.png)

**Comment by fubar-coder** [comment]
Implemented by PR #750.
