### ISSUE TITLE
Move from IDbConnection to DbConnection

### ISSUE THREAD

**Issue by govorovvs** [fluentmigrator/fluentmigrator#760]
This is a part of #712. 
As _System.Data.IDbConnection_ isn't longer supported in netstandard, we have to move to _System.Data.Common.DbConnection_

**Comment by govorovvs** [comment]
I've created a pull request #761  assigned to this issue

**Comment by volkanceylan** [comment]
@govorovvs could you provide a link where it explains that DbConnection is supported in netstandard while IDbConnection not? I'm currently targeting netstandard1.6 and working with IDbConnection caused no problems. I searched net for this but couldn't find any info about that.

**Comment by eloekset** [comment]
IDbConnection was added in 1.0.0 RC2: https://github.com/dotnet/core/blob/master/release-notes/1.0/RC1-RC2_API_diff.md
April 2016: https://github.com/dotnet/corefx/releases/tag/v1.0.0-rc2

**Comment by fubar-coder** [comment]
Obsolete
