### ISSUE TITLE
Oracle: Script output should have delimiter ; 

### ISSUE THREAD

**Issue by ltvan** [fluentmigrator/fluentmigrator#765]
I use --output or --preview and the generated script file doesn't have delimiter between statements.

**Comment by eloekset** [comment]
For which database provider?

**Comment by fubar-coder** [comment]
You can achieve this by writing your own announcer. The next major release will have a dedicated "script output" feature.

**Comment by InfinityException** [comment]
> You can achieve this by writing your own announcer. The next major release will have a dedicated "script output" 

You can achieve this by writing your own announcer. The next major release will have a dedicated "script output" feature.

Could you provide a quick schematic Explanation how to create such an announcer for this issue. I couldn't get the trick with my researches.

**Comment by fubar-coder** [comment]
The announcers are now a thing of the past.  When you move to the [logger implementations](https://github.com/fluentmigrator/fluentmigrator/tree/master/src/FluentMigrator.Runner.Core/Logging), you can see several files, two of them being:

* [SqlScriptFluentMigratorLoggerProvider.cs](https://fluentmigrator.github.io/api/v3.x/FluentMigrator.Runner.Logging.SqlScriptFluentMigratorLoggerProvider.html): This instantiates an `ILogger` for a given category and is what gets registered in a `ILoggerFactory` or `ILoggingBuilder`.
* [SqlScriptFluentMigratorLogger.cs](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator.Runner.Core/Logging/SqlScriptFluentMigratorLogger.cs): This class implements the logging itself.

The way to provide your own output is to write your own logger derived from [FluentMigratorLogger](https://fluentmigrator.github.io/api/v3.x/FluentMigrator.Runner.Logging.FluentMigratorLogger.html) and reimplement both `SqlScriptFluentMigratorLoggerProvider` and `SqlScriptFluentMigratorLogger` where you append a semicolon `;` to every non-empty `sql` statement in the `WriteSql` function.

When you now add your logger provider to to `ILoggerFactory` or `ILoggingBuilder`, then you should be able to use your logger to create the correct SQL statements.

**Maybe** it's sufficient to add a configuration option to `SqlScriptFluentMigratorLoggerOptions` and modify `SqlScriptFluentMigratorLogger` to always append (depending on the configuration) a semicolon when it's missing? A pull request would be welcome 😄 . Every out-of-process runner has to be updated too to support this new option.

**Comment by InfinityException** [comment]
Thank you for your assistance! I will give this a try in time.
