### ISSUE TITLE
How add a new column in the "VersionInfo" table ???

### ISSUE THREAD

**Issue by yfrindel** [fluentmigrator/fluentmigrator#768]
How can I add a new column in the "VersionInfo" table ? (for example : author)
I saw this webpage : https://github.com/schambers/fluentmigrator/wiki/Create-custom-metadata-for-the-VersionInfo-table but I don't see any explanation about how to add a new column !
Is it possible ?

**Comment by reinaldocoelho** [comment]
Hi @yfrindel, I will try to help you on your question.

First, in this moment is not possible to improve VersionInfo table with new column by the lib.

Second, what information you need to add? 

"Author" for example I think would be better on the VCS (Version control system), like git, subversion and other in this case. This don´t solve your problem?

Sorry for a long time to answer.

**Comment by yfrindel** [comment]
Hi,

and thank you for your answer.

I resolved my problem by the creation of a new table (extra table) linked to the VersionInfo table.
So I can store now all information that I need.

regards.

**Comment by reinaldocoelho** [comment]
Perfect.

I will close this issue then.

Thanks.
