### ISSUE TITLE
Firebird column name, index names etc not quoted

### ISSUE THREAD

**Issue by fatalerrorx** [fluentmigrator/fluentmigrator#770]
In Firebird unquoted names are treated as all upper case. It is necessary to quote all names so that casing is preserved. Fluentmigrator unfortunately does not quote column and index names. 

Manually quoting seems to not work either. For example fluentmirgrator generates the following DROP INDEX "iUser_Name with the end quote is missing.

**Comment by fubar-coder** [comment]
Maybe a provider option is the way to go - just like for the Oracle provider?
