### ISSUE TITLE
SQL Server 2014: Inserting to NVARCHAR column

### ISSUE THREAD

**Issue by leevva** [fluentmigrator/fluentmigrator#786]
My table in SQL Server 2014 has structure:
```
CREATE TABLE [dbo].[some_table] (
    [some_table_id] INT            IDENTITY (1, 1) NOT NULL,
    [code]          VARCHAR (45)   NOT NULL,
    [name]          NVARCHAR (60)  NOT NULL,
    [description]   NVARCHAR (200) NULL,
    CONSTRAINT [PK_some_table] PRIMARY KEY CLUSTERED ([some_table_id] ASC)
);
```
When I insert row:
```
Insert.IntoTable("some_table").InSchema("dbo")
    .WithIdentityInsert()
    .Row(new
        {
            some_table_id = 15,
            code = "SomeCode",
            name = "Название"
    });

```
FluentMigrator generates Script:
`
SET IDENTITY_INSERT [dbo].[some_table] ON; INSERT INTO [dbo].[some_table] ([some_table_id], [code], [name]) VALUES (15, 'SomeCode', 'Название'); SET IDENTITY_INSERT [dbo].[some_table] OFF
`
But it should be 
... VALUES (15, 'SomeCode', **N**'Название') ...

How to properly insert into NVARCHAR column?

**Comment by fubar-coder** [comment]
You may want to try `ExplicitUnicodeString` as explained in the [Wiki page for SQL Server specific extensions](https://github.com/fluentmigrator/fluentmigrator/wiki/Sql-Server-Specific-Extensions).
