### ISSUE TITLE
Oracle Migration with Alter Table Add Column

### ISSUE THREAD

**Issue by Noobishness** [fluentmigrator/fluentmigrator#791]
Hi together,

currently the Oracle implementation does not consider the Schema passed to the CreateColumnExpression. In my opinion this should behave similar to the MSSQL Version which includes the Schema Name in the alter table query string

Best regards

**Comment by fubar-coder** [comment]
The schema handling of ORACLE (and other databses) was streamlined and this problem should be fixed in 2.0.0. Please leave a comment if the issue is still there after the 2.0 release.
