### ISSUE TITLE
Support identity columns for Oracle

### ISSUE THREAD

**Issue by hv2017** [fluentmigrator/fluentmigrator#799]
Currently, FluentMigrator throws an exception when an identity column is created in an Oracle database.
With the release of version 12c R1, identity columns are supported by Oracle ([link](https://oracle-base.com/articles/12c/identity-columns-in-oracle-12cr1#identity-columns)).
Can support for Oracle identity columns be added to FluentMigrator?

Kind regards,

**Comment by spindev** [comment]
I would like to have this contraint removed, too.

Thanks :)

**Comment by PhenX** [comment]
I've started to work on this. For now I simply copied a part of the Oracle generator classes, and added basic support identity.
I think the best way to achieve this change would be to like SqlServer, and add a "Oracle12c" generator.
I'll need to add extensions because of the "generated" type of Oracle (by default, always, on null).
What do you think ?

I'll use this page for reference https://oracle-base.com/articles/12c/identity-columns-in-oracle-12cr1

**Comment by fubar-coder** [comment]
@PhenX Sounds good to me. There are already some extensions for other databases (e.g. SQL Anywhere and SQL Server), so you may use them as starting point.

**Comment by PhenX** [comment]
Ok, thank you, I started here : https://github.com/am-creations/fluentmigrator/tree/oracle-identity

**Comment by mijaved** [comment]
Hi @PhenX what the status of your work on Identity support for  Oracle12c, Is your pull request accepted?
I need this feature urgently.

**Comment by arthurmmedeiros** [comment]
Hi @PhenX 
I'm facing the same issue with the identity column here. I usually use SQL Server, but I also need my application to run in Oracle database. Is there any workaround for this issue?

I didn't understand what you suggested here "I think the best way to achieve this change would be to like SqlServer, and add a "Oracle12c" generator."

**Comment by PhenX** [comment]
@mijaved @arthurmmedeiros #921 is merged into develop, but the NuGet package is not released yet.

**Comment by fubar-coder** [comment]
@arthurmmedeiros Thanks to the hard work of @PhenX , you can try the 4.0.0-alpha.144 nuget packages from [MyGet](https://www.myget.org/gallery/fluent-migrator). I hope to release a 3.2.0 as soon as I have some spare time.

**Comment by dfaruque** [comment]
I am getting the following error using 4.0.0-alpha.144 version

`Could not load file or assembly 'FluentMigrator.Runner, Version=4.0.0.0, Culture=neutral, PublicKeyToken=aacfc7de5acabf05'. The located assembly's manifest definition does not match the assembly reference`

at line `var serviceProvider = CreateServices();`

do you have any workaround?

**Comment by fubar-coder** [comment]
@dfaruque I guess that you have a mix-up of assemblies (some old and some new assembly versions). Updating the [Quickstart](https://fluentmigrator.github.io/articles/quickstart.html) exmple to the alpha package versions works doesn't cause this problem.

**Comment by dfaruque** [comment]
@fubar-coder  Thanks you very much for your attention.

`.AddOracleManaged()` , `.AddSQLite()` works but `.AddOracle12CManaged()` is not working.

Did you used `.AddOracle12CManaged()`?

**Comment by dfaruque** [comment]
@fubar-coder  Thank you very much for your attention.
Your guess is correct.

Now I have another issue using `.AddOracle12CManaged()`
`Unable to resolve service for type 'FluentMigrator.Runner.Generators.Oracle.OracleGenerator' while attempting to activate 'FluentMigrator.Runner.Processors.Oracle.OracleManagedProcessor'.`

`AddOracleManaged()` and `AddSQLite()` works.

**Comment by fubar-coder** [comment]
It seems that this is the same problem as reported in issue #934 .

**Comment by fubar-coder** [comment]
A new alpha version should be available soon. This is a blind fix, because I don't have access to an Oracle12c database here. The version will be `4.0.0-alpha.150`.

**Comment by dfaruque** [comment]
Thanks @fubar-coder ,
It is working now

**Comment by arthurmmedeiros** [comment]
Hi there,
I downloaded this alpha version 4.0.0-alpha.150 but I keep getting the same error. 
No matter what I try, I get the message below: 
_"Oracle does not support identity columns. Please use a SEQUENCE instead"_
I'm testing it on Oracle 12c, and I can make the same change when using oracle command line, therefore, I'm pretty sure this is not an oracle issue.
To make sure I am running the correct version of Fluent Migrator I created a new project.

**Comment by fubar-coder** [comment]
Did you select the Oracle12c database processor for FlientMigrator?

**Comment by arthurmmedeiros** [comment]
> Did you select the Oracle12c database processor for FlientMigrator?

Would you have an example setting this option in the project?

**Comment by arthurmmedeiros** [comment]
> > Did you select the Oracle12c database processor for FlientMigrator?
> 
> Would you have an example setting this option in the project?

I figured I needed to use "-db oracle12cManaged". It's working now!  :)

**Comment by fubar-coder** [comment]
Fixed by PR #921
