### ISSUE TITLE
SqlServer2005GeneratorTests use SqlServer2008Generator instead of 2005

### ISSUE THREAD

**Issue by eloekset** [fluentmigrator/fluentmigrator#802]
I noticed, when working on a PR for #801, that SqlServer2005GeneratorTests creates an instance of SqlServer2008Generator and not SqlServer2005Generator. It has always been like this since the test class was created in commit 0d00e840.

I'll fix it in a separate commit in the upcoming PR for #801.

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0
