### ISSUE TITLE
SQLite Nullable generates a NOT NULL column

### ISSUE THREAD

**Issue by aetaylor** [fluentmigrator/fluentmigrator#804]
I would expect the following to create a table with the "FirstName" column marked as _nullable_ ...

`           Create.Table("Contact")`
`                  .WithColumn("Id").AsInt32().NotNullable().PrimaryKey().Identity()`
`                  .WithColumn("FirstName").AsString(30).Nullable()`
`                  ......`

however, the following is generated...

`CREATE TABLE Contact`
`(`
`    Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,`
`    FirstName TEXT NOT NULL,`
`    .......`

I'm guessing that this would be a bug?

**Comment by fubar-coder** [comment]
Woah, this would be a huge bug. I'll take a look.

**Comment by aetaylor** [comment]
I was expecting the default behaviour to be _nullable_ anyway, but when that didn't happen I added the `Nullable()` call but it made no difference.
Am I correct in assuming that specifying neither `.Nullable()` nor `.NotNullable()` should result in the column being _nullable_?

**Comment by fubar-coder** [comment]
It should be dependent on the database/data type.
