### ISSUE TITLE
Allow --timeout=0 to mean infinite

### ISSUE THREAD

**Issue by jasondentler** [fluentmigrator/fluentmigrator#810]
This matches the behavior of SqlCommand.CommandTimeout, which the documentation references. 

Here's the offending code:

`
            if (RunnerContext.Timeout == 0)
            {
                RunnerContext.Timeout = 30; // Set default timeout for command
            }
`

**Comment by AdGalesso** [comment]
+1

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0
