### ISSUE TITLE
SQLite + Delete.Column(): table column still there after migration

### ISSUE THREAD

**Issue by rbarillec** [fluentmigrator/fluentmigrator#812]
This is very likely an issue with my usage, but I haven't found any indication as to why in the docs or on forums. I have an SQLite database and the following migration:

```csharp
[Migration(3)]
public class _003_add_surname_column : Migration
{
    public override void Up()
    {
        Rename.Column("name").OnTable("Test").To("forename");
        Alter.Table("Test").AddColumn("surname").AsString(50).Nullable();
    }

    public override void Down()
    {
        Delete.Column("surname").FromTable("Test");
        Rename.Column("forename").OnTable("Test").To("name");
    }
}
```

Migrating up works fine. Migrating down performs the column rename (from "forename" to "name"), but leaves the "surname" column in the table. I expected that column to be gone. Am I missing something? Or is that the intended behaviour?

Using FluentMigrator version 1.6.2, System.Data.SQLite.1.0.99.0, .NET 4.5.1.

Thanks!

**Comment by rbarillec** [comment]
OK, it looks like it is an issue with SQLite not supporting the deletion of columns.

https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite#8442173

This could be an issue for anyone trying to migrate down at some point and then later migrate up again, as the column cannot be added again (since it wasn't deleted on the way down, it still exists). 

it would be nice if FluentMigrator threw an exception in that situation or used a workaround (duplicate the table without the column). At the moment, it seems to just ignore the column deletion, which is a bit misleading.

**Comment by rbarillec** [comment]
Here is the output of the up migration. Migration 3 adds the column and Migration 4 removes it.

```
-------------------------------------------------------------------------------
3: _003_add_column migrating
-------------------------------------------------------------------------------
[+] RenameColumn Test name to forename
[+] AlterTable Test
[+] CreateColumn Test surname String
[+] 3: _003_add_column migrated
-------------------------------------------------------------------------------
4: _004_delete_surname_column migrating
-------------------------------------------------------------------------------
[+] DeleteColumn Test surname
[+] RenameColumn Test forename to name
[+] 4: _004_delete_surname_column migrated
[+] Task completed.
```

The `surname` table is still in the database post-migration and no error is reported.

Just for completeness, here is Migration 4:

```csharp
[Migration(4)]
public class _004_delete_surname_column : Migration
{
    public override void Up()
    {
        Delete.Column("surname").FromTable("Test");
        Rename.Column("forename").OnTable("Test").To("name");
    }

    public override void Down()
    {
        Rename.Column("name").OnTable("Test").To("forename");
        Alter.Table("Test").AddColumn("surname").AsString(50).Nullable();
    }
}
```

**Comment by rbarillec** [comment]
As expected, rollback then fails as we try and restore the non-deleted column:

```
-------------------------------------------------------------------------------
4: _004_delete_surname_column reverting
-------------------------------------------------------------------------------
[+] RenameColumn Test name to forename
[+] AlterTable Test
[+] CreateColumn Test surname String
!!! SQLite error
duplicate column name: surname
While Processing:
"ALTER TABLE "Test" ADD COLUMN "surname" TEXT"
!!! SQLite error
duplicate column name: surname
!!! SQLite error
duplicate column name: surname
While Processing:
"ALTER TABLE "Test" ADD COLUMN "surname" TEXT"
!!! SQLite error
duplicate column name: surname
```

Hope this helps. Let me know if you need any more info.

**Comment by escarls** [comment]
FluentMigrator doesn't generate SQL for renaming or deleting columns for SQLite.
Here is how the generated SQL looks like for me when I run against SQLite:
[Issue812.dll.sql.txt](https://github.com/fluentmigrator/fluentmigrator/files/1935932/Issue812.dll.sql.txt)
As you can see, no SQL generated for the rename in Migration 3:
```
/* Beginning Transaction */
/* RenameColumn Test name to forename */
/* No SQL statement executed. */
```
But it does generate SQL for adding the new column:
```
/* CreateColumn Test surname String */
ALTER TABLE "Test" ADD COLUMN "surname" TEXT
```
And then in Migration 4, neither the Delete or Rename is generated:
```
/* Beginning Transaction */
/* DeleteColumn Test surname */
/* No SQL statement executed. */

/* RenameColumn Test forename to name */
/* No SQL statement executed. */
```

**Comment by escarls** [comment]
I think for a start, FluentMigrator should probably throw and exception when an unsupported migration is run.
Then for later, look at if it's possible to do the workaround hacks with renaming table, create new table, copy data from old table.

**Comment by escarls** [comment]
@fubar-coder what do you think?
To throw the exception should be simple enough, but do the workaround, that will be pretty complex.

**Comment by fubar-coder** [comment]
I've seen in the project that there is an enum `CompatabilityMode`, which is set to LOOSE by default (constructor of `GenericGenerator`). It should throw an exception if the compatibility mode is set to STRICT.

I added a note to the 3.0 project board, because currently there is no way to set the compatibility mode from the external runners.

**Comment by PoLaKoSz** [comment]
I [implemented](https://github.com/PoLaKoSz/fluentmigrator/commit) the `Delete.Column(string columnName)` in hope maybe I can give something back to the community.
I am not an experienced developer but can I get some feedback about this? Is this ugly implementation?

Thanks!

**Comment by PoLaKoSz** [comment]
I want to say first that maybe I am the worst person for this job:
- beginner programmer
- I never used NUnit
- IoC is pretty new to me
- I only did basic CRUD operations in my whole life so I don't have a clear picture about indexes, views, etc.)

... but I hope when it actually get accepted as a solution, it will be the best possible solution.

A day ago [I produced the code](https://github.com/PoLaKoSz/fluentmigrator/commit/916fdd112b041753d71a2c687546f2003b9e8968) which bypass the `SQLiteGenerator` class and do everything in the `Process(DeleteColumnExpression expression)` of the `SQLiteProcessor` class. If I am correct it can't be tested in any way so I came up with a second solution.

I created a new Expression called `DeleteSQLiteColumnExpression` which is now contains the `DeleteColumnExpression` as a property called `GenericExpression` and holds every column name of the table which is populated in the `SQLiteProcessor` class `Process(DeleteColumnExpression expression)` method. This custom Expression now passed to the SQLiteGenerator Generate method this is where the SQL generation takes place.
I added an Obsolete attribute to the `Generate(DeleteColumnExpression expression)` but I waiting for You feedback!
I not implemented any Unit / Integration tests yet, because this library really advanced for me but I want to in the near future.

Thank You!
BTW the source code [can be find here](https://github.com/PoLaKoSz/fluentmigrator/commit/2df03ff666ede1f9ea72b9716b81d85c2570c98b).

**Comment by fubar-coder** [comment]
Ok, I made some tests and this is the way to go:

1. Disable foreign keys while no transaction is active (e.g. in an overridden `BeginTransaction` function)
2. Create a new table (with primary key, foreign key references, etc)
3. Copy its data (don't use `create table as select`, because this doesn't work with `primary key` columns and foreign key references)
4. Drop the old table
5. Rename the new table to the old tables name
6. Recreating the indexes
7. Enable foreign keys after transaction has been completed (either rollback or commit)

Some hints:

- Produce the code in the `SQLiteGenerator` and not in the `SQLiteProcessor`
- Don't forget to use the quoter (`Quoter` base class property usable from `SQLiteGenerator`)
- You can put multiple SQL statements into a single string, when you use a `;` after every statement
- The indexes have to be recreated on the table
- Views can be ignored
- Keep it simple 😀 

Here's my test program that you can use as a starting point. Some functions (e.g. reading into a `DataTable`/`DataSet` is already possible from the processor. You can see in the resulting database, that `primary key` was stripped from the `id` column of `test1`. `view1` keeps working and the foreign keys from `test2` to `test1` don't bug out.

```cs
using System;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.IO;
using System.Linq;

using Microsoft.Data.Sqlite;

namespace TestSqliteMultiCommand
{
    internal static class Program
    {
        private static void Main()
        {
            // Ensure a clean DB file
            var testDbFileName = Path.Combine(Path.GetTempPath(), "test.db");
            if (File.Exists(testDbFileName))
            {
                File.Delete(testDbFileName);
            }

            var cb = new SqliteConnectionStringBuilder()
            {
                DataSource = testDbFileName,
            };
            using (var conn = new SqliteConnection(cb.ConnectionString))
            {
                conn.Open();

                // Create tables
                CreateTestTables(conn);

                // Validate data
                EnsureDataExists(conn);

                // Turn off foreign keys
                using (EnsureDisabledForeignKeys(conn, null))
                {
                    // Simulate start of a per-migration transaction
                    using (var trans = conn.BeginTransaction())
                    {
                        // Some statement changing the database
                        ExecuteStatement(conn, trans, "insert into test1 (id, dummy) values (3, '3');");

                        // The "DROP COLUMN" replacement (no transaction passed to command)
                        ExecuteStatement(conn, null,
                            "create table _rename_target_of_test1 as select id, dummy2 from test1;" +
                            "drop table test1;" +
                            "alter table _rename_target_of_test1 rename to test1;");

                        trans.Commit();
                    }
                }
            }
        }

        /// <summary>
        /// Ensure that the tables were seeded
        /// </summary>
        /// <param name="conn">The database connection</param>
        private static void EnsureDataExists(DbConnection conn)
        {
            var tbl = ReadDataTable(conn, null, "select * from test2 order by id");
            Debug.Assert(tbl.Rows.Count == 2);
            Debug.Assert(Convert.ToInt32(tbl.Rows[0][0]) == 1);
            Debug.Assert(Convert.ToInt32(tbl.Rows[0][1]) == 1);
            Debug.Assert(Convert.ToInt32(tbl.Rows[1][0]) == 2);
            Debug.Assert(Convert.ToInt32(tbl.Rows[1][1]) == 2);
        }

        /// <summary>
        /// Create and seed the test tables
        /// </summary>
        /// <param name="conn">The database connection</param>
        private static void CreateTestTables(DbConnection conn)
        {
            using (var trans = conn.BeginTransaction())
            {
                ExecuteStatement(conn, trans, "create table test1 (id int primary key, dummy text, dummy2 text);");
                ExecuteStatement(conn, trans, "create index i1 on test1(dummy2);");
                ExecuteStatement(conn, trans, "create view view1(id, dummy2) as select id,dummy2 from test1;");
                ExecuteStatement(conn, trans, "create table test2 (id int primary key, test1id int references test1(id));");
                ExecuteStatement(conn, trans, "insert into test1 (id, dummy) values (1, '1');");
                ExecuteStatement(conn, trans, "insert into test1 (id, dummy) values (2, '2');");
                ExecuteStatement(conn, trans, "insert into test2 (id, test1id) values (1, 1); insert into test2 (id, test1id) values (2, 2);");
                //ExecuteStatement(conn, trans, "insert into test2 (id, test1id) values (2, 2);");
                trans.Commit();
            }
        }

        /// <summary>
        /// Execute an SQL statement
        /// </summary>
        /// <param name="connection">The database connection</param>
        /// <param name="transaction">The current transaction</param>
        /// <param name="sql">The SQL statement(s)</param>
        private static void ExecuteStatement(DbConnection connection, DbTransaction transaction, string sql)
        {
            using (var cmd = connection.CreateCommand())
            {
                if (transaction != null)
                {
                    cmd.Transaction = transaction;
                }

                cmd.CommandText = sql;
                cmd.ExecuteNonQuery();
            }
        }

        /// <summary>
        /// Executes an SQL statement and put the returning data into a DataTable
        /// </summary>
        /// <param name="connection">The database connection</param>
        /// <param name="transaction">The current transaction</param>
        /// <param name="sql">The SQL statement(s)</param>
        /// <returns>The data table (might be null if no data returned)</returns>
        private static DataTable ReadDataTable(DbConnection connection, DbTransaction transaction, string sql)
        {
            var set = ReadDataSet(connection, transaction, sql);
            return set.Tables.Cast<DataTable>().FirstOrDefault();
        }

        /// <summary>
        /// xecutes an SQL statement and put the returning data into a DataSet
        /// </summary>
        /// <param name="connection">The database connection</param>
        /// <param name="transaction">The current transaction</param>
        /// <param name="sql">The SQL statement(s)</param>
        /// <returns>The data set</returns>
        private static DataSet ReadDataSet(DbConnection connection, DbTransaction transaction, string sql)
        {
            using (var cmd = connection.CreateCommand())
            {
                if (transaction != null)
                {
                    cmd.Transaction = transaction;
                }

                var set = new DataSet();
                cmd.CommandText = sql;
                using (var reader = cmd.ExecuteReader())
                {
                    do
                    {
                        if (reader.Read())
                        {
                            var tbl = set.Tables.Add();
                            for (var i = 0; i != reader.FieldCount; ++i)
                            {
                                var colName = reader.GetName(i);
                                var colType = reader.GetFieldType(i);
                                tbl.Columns.Add(colName, colType ?? typeof(object));
                            }

                            do
                            {
                                var row = new object[reader.FieldCount];
                                reader.GetValues(row);
                                tbl.Rows.Add(row);
                            } while (reader.Read());
                        }
                    } while (reader.NextResult());
                }

                return set;
            }
        }

        /// <summary>
        /// A function that returns a disposable which restores foreign key handling
        /// to its current state after turning it off.
        /// </summary>
        /// <param name="connection">The database connection</param>
        /// <param name="transaction">The current transaction</param>
        /// <returns>The disposable object to restore the foreign key handling</returns>
        private static IDisposable EnsureDisabledForeignKeys(DbConnection connection, DbTransaction transaction)
        {
            return new ForeignKeyDisabler(connection, transaction);
        }

        /// <summary>
        /// A disposable implementation that turns off foreign key handling and restores it when disposing
        /// </summary>
        private class ForeignKeyDisabler : IDisposable
        {
            private readonly DbConnection _connection;
            private readonly DbTransaction _transaction;
            private readonly bool _mustReenable;

            /// <summary>
            /// Initializes a new instance of the <see cref="ForeignKeyDisabler"/> class.
            /// </summary>
            /// <param name="connection">The database connection</param>
            /// <param name="transaction">The current transaction</param>
            public ForeignKeyDisabler(DbConnection connection, DbTransaction transaction)
            {
                _connection = connection;
                _transaction = transaction;
                _mustReenable = IsForeignKeyEnabled() == true;
                if (_mustReenable)
                {
                    DisableForeignKeys();
                }
            }

            /// <summary>
            /// Restores the previous foreign key handling
            /// </summary>
            public void Dispose()
            {
                if (_mustReenable)
                {
                    EnableForeignKeys();
                }
            }

            /// <summary>
            /// Disable foreign key handling
            /// </summary>
            private void DisableForeignKeys()
            {
                EnableForeignKeys(false);
            }

            /// <summary>
            /// Enables foreign key handling
            /// </summary>
            /// <param name="enable"></param>
            private void EnableForeignKeys(bool enable = true)
            {
                using (var command = _connection.CreateCommand())
                {
                    if (_transaction != null)
                    {
                        command.Transaction = _transaction;
                    }

                    command.CommandText = $"PRAGMA foreign_keys = {(enable ? "ON" : "OFF")}";
                    command.ExecuteNonQuery();
                }
            }

            /// <summary>
            /// Returns if foreign keys are enabled.
            /// </summary>
            /// <returns><c>true</c> when foreign keys are enabled and <c>null</c> when SQLite is built without
            /// foreign key support</returns>
            private bool? IsForeignKeyEnabled()
            {
                using (var command = _connection.CreateCommand())
                {
                    if (_transaction != null)
                    {
                        command.Transaction = _transaction;
                    }

                    command.CommandText = "PRAGMA foreign_keys";
                    using (var reader = command.ExecuteReader())
                    {
                        // Should never return null, but better safe than sorry
                        if (reader.Read() && !reader.IsDBNull(0))
                        {
                            var isEnabled = reader.GetInt32(0) != 0;
                            return isEnabled;
                        }
                    }
                }

                // Foreign keys are not supported by SQLite!
                // https://www.sqlite.org/foreignkeys.html#fk_enable
                return null;
            }
        }
    }
}
```

**Comment by PoLaKoSz** [comment]
@fubar-coder  Thank You so much for your help! I will analyze this hopefully soon.

**Comment by fubar-coder** [comment]
You can do the following: Create a pull request starting with a "WIP: " in the title.

**Comment by eallende** [comment]
Hello, I have an issue with this solution. 
When you want to have more than one DeleteColumn expressions like this in the same migration: 
`Delete.Column("Col1").FromTable("TableName");` 
`Delete.Column("Col2").FromTable("TableName");`
When it tries to delete the second Column, it throws an error saying that Col1 is not a column. And that's right actually because I have deleted previously.
Any workaround for this that comes up?

**Comment by jzabroski** [comment]
If you use two separate migrations, does it still throw an error saying that Col1 is not a column?

**Comment by eallende** [comment]
No, no that way. But still I wanted to be able to have them on the same migration

**Comment by jzabroski** [comment]
I don't have the bandwidth right now to do a deep dive and figure out whether this is possible.  I'm sorry.  Just giving you proper notice that you're stuck with the separate migrations approach for now.

**Comment by fairking** [comment]
Looks like the support of `DROP TABLE` is introduced in sqlite version 3.35.0. (https://sqlite.org/changes.html#version_3_35_0).

Let me know guys if you managed to execute `Delete.Column("Col2").FromTable("TableName");` on the latest version of sqlite. And which sqlite nuget library you used.

**Comment by fairking** [comment]
[dotnet](https://www.nuget.org/packages/Microsoft.Data.Sqlite.Core/6.0.0-preview.3.21201.2) is considering to update the version of sqlite: https://github.com/dotnet/efcore/issues/24834
Also the [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core/) will be updated very soon: https://system.data.sqlite.org/index.html/doc/trunk/www/news.wiki

**Comment by jzabroski** [comment]
@mattbrailsford Any chance you can tackle this too?   I think this is and #1492 are the last two that would be nice to have before shipping 4.0

**Comment by mattbrailsford** [comment]
Sure. I’m gonna look through it all as there is a lot that appears to be missing. I’ll see what I can fill in 👍🏻

**Comment by GKannan1990** [comment]
Hi Team,

Try to execute Delete.Column("Col2").FromTable("TableName"); on the latest version of sqlite. But column still there after migration. Could you please let me know, delete column will support by fluentmigrant 3.3.2

**Comment by jzabroski** [comment]
This issue is tagged with a 4.0.0 milestone.

**Comment by GKannan1990** [comment]
> This issue is tagged with a 4.0.0 milestone.

Thank you Team... Could you please suggest any workaround....

**Comment by fairking** [comment]
> > This issue is tagged with a 4.0.0 milestone.
> 
> Thank you Team... Could you please suggest any workaround....

You can simply execute the following plain sql:
``` c#
IfDatabase("sqlite")
    .Execute.Sql("alter table Table1 drop column Col2");
```

**Comment by GKannan1990** [comment]
Tried Execute.Sql("alter table Table1 drop column Col2"); but getting below issue.
!!! SQLite Error 1: 'near "DROP": syntax error'.
While Processing:
"ALTER TABLE Table1  DROP COLUMN Col2"

**Comment by jzabroski** [comment]
DROP requires SQLite 3.35.0.

**Comment by GKannan1990** [comment]
Currently we are using SQlite 1.0.115.5. But still getting below issue
!! SQLite Error 1: 'near "DROP": syntax error'.
While Processing:
"ALTER TABLE Table1 DROP COLUMN Col2"

**Comment by jzabroski** [comment]
@GKannan1990 You don't understand what you are doing. Ask someone you work with who is senior for help. You are wasting our time and will likely make a big mistake until someone explains to you what the task is and how to proceed.
