### ISSUE TITLE
Can't run task from *.csproj

### ISSUE THREAD

**Issue by korenb** [fluentmigrator/fluentmigrator#813]
i have following lines in my csproj
`<UsingTask TaskName="FluentMigrator.MSBuild.Migrate" AssemblyFile="$(SolutionDir)\packages\FluentMigrator.1.6.2\tools\FluentMigrator.MSBuild.dll" />
  <Target Name="Migrate">
    <Message Text="SolutionDir=$(SolutionDir)" />
    <Migrate Database="SqlServer" Connection="$(ConnectionString)" Target="$(MSBuildProjectDirectory)/bin/Debug/LearnFluentMigrator.dll" Output="True" OutputFilename="generated.sql" Task="migrate" PreviewOnly="True" />
  </Target>`

then i start command from solution directory `dotnet msbuild ./LearnFluentMigrator/LearnFluentMigrator.csproj  /t:Migrate /p:SolutionDir=$(get-location)`

and i am given this problem

> D:\LearnFluentMigrator\LearnFluentMigrator\LearnFluentMigrator.csproj(76,5): error MSB4062: The "FluentMigrator.MSBuild.Migrate" task could not be loaded from the assembly D:\LearnFluentMigrator\packages\FluentMigrator.1.6.2\tools\FluentMigrator.MSBuild.dll. Could not load file or assembly 'FluentMigrator.MSBuild, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null'. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

it's my packages.config:

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FluentMigrator" version="1.6.2" targetFramework="net452" />
  <package id="FluentMigrator.Tools" version="1.6.2" targetFramework="net452" />
</packages>`

what's problem with FluentMigrator.MSBuild.dll?

**Comment by dmeagor** [comment]
Same problem here.  Just started randomly recently.  possibly after updating to the latest version of Visual Studio

**Comment by escarls** [comment]
@korenb from what you write in the issue, it looks like you're in a .net core project.
FluentMigrator 1.6.2 doesn't support .net core, so that may be the issue.
When I created a .NET core project, I was more or less able to reproduce.
When I did the exact same with a full framework project, the exact same code worked.

**Comment by escarls** [comment]
@dmeagor Do you think that your issue also is related to that you're running this from a .NET core project?
If not, could you give more details so it may be possible to reproduce?

**Comment by fubar-coder** [comment]
The new FluentMigrator.MSBuild package automatically registers the task, but - unless you have all the required assemblies available - it's of limited usefulness.
