### ISSUE TITLE
How to change foreign keys naming convention

### ISSUE THREAD

**Issue by mabead** [fluentmigrator/fluentmigrator#814]
Create.ForeignKeys has two overload:

1. without parameter: uses default naming convention for foreign key
2. with parameter: use foreign key name

Is it possible to change the default naming convention for foreign keys in order to use the first overload and still use a naming scheme that uses my team standards?

**Comment by fubar-coder** [comment]
You can override it by changing `MigrationConventions.GetForeignKeyName` in versions < 2.0 or by providing your own `IForeignKeyConvention` in versions >= 2.0.

**Comment by vincentparrett** [comment]
I'm trying to do this now (porting project to .net core), but I can't see how I provide my IForeignKeyConvention to the runner. 

my runner code looks like this

	public class Runner : Shared.Data.IMigrationRunner
	{
		public void Execute(string database, string connectionString, string fileName, Action<MessageType, string> reportStatus)
		{
			using (var writer = new Writer(fileName, reportStatus))
			{
				var ctx = new RunnerContext(writer);
				ctx.Database = database;
				ctx.Connection = connectionString;

				ctx.Task = "migrate:up";
				ctx.Targets = new string[] { "Continua.Migrations" };

				ctx.PreviewOnly = !string.IsNullOrEmpty(fileName);
				ctx.Timeout = 6000; //40 minutes 

				var executor = new TaskExecutor(ctx);
				executor.Execute();
			}
		}
	}

There just doesn't seem to be anywhere to plug the conventions in.

**Comment by fubar-coder** [comment]
Version 2.0.7 is published

**Comment by ncsmikewoods** [comment]
@fubar-coder Can you expand on what you mean by providing your own IForeignKeyConvention?  I understand that we should be able to extend that and use that to override the DefaultForeignKeyConvention but I don't understand how to configure that.

Where do we feed in our own implementation of that interface?

**Comment by fubar-coder** [comment]
1. You have to implement your own `IConventionSet` (example: see below)
2. Register the `IConventionSet` as singleton: `services.AddSingleton<IConventionSet>(new YourConventionSet())`

# You `IConventionSet` implementation
```cs
    public class YourConventionSet : IConventionSet
    {
        public YourConventionSet()
            : this(new DefaultConventionSet())
        {
        }

        public YourConventionSet(IConventionSet innerConventionSet)
        {
            ForeignKeyConventions = new List<IForeignKeyConvention>()
            {
                /* This is where you do your stuff */
                new YourCustomDefaultForeignKeyNameConvention(),
                innerConventionSet.SchemaConvention,
            };

            ColumnsConventions = innerConventionSet.ColumnsConventions;
            ConstraintConventions = innerConventionSet.ConstraintConventions;
            IndexConventions = innerConventionSet.IndexConventions;
            SequenceConventions = innerConventionSet.SequenceConventions;
            AutoNameConventions = innerConventionSet.AutoNameConventions;
            SchemaConvention = innerConventionSet.SchemaConvention;
            RootPathConvention = innerConventionSet.RootPathConvention;
        }

        /// <inheritdoc />
        public IRootPathConvention RootPathConvention { get; }

        /// <inheritdoc />
        public DefaultSchemaConvention SchemaConvention { get; }

        /// <inheritdoc />
        public IList<IColumnsConvention> ColumnsConventions { get; }

        /// <inheritdoc />
        public IList<IConstraintConvention> ConstraintConventions { get; }

        /// <inheritdoc />
        public IList<IForeignKeyConvention> ForeignKeyConventions { get; }

        /// <inheritdoc />
        public IList<IIndexConvention> IndexConventions { get; }

        /// <inheritdoc />
        public IList<ISequenceConvention> SequenceConventions { get; }

        /// <inheritdoc />
        public IList<IAutoNameConvention> AutoNameConventions { get; }
    }
```

**Comment by igordaiko** [comment]
@fubar-coder where can I register my convention set? As I understand services configure in FluentMigrator.DotNet.Cli.Setup ConfigureService method. How can I override it?

**Comment by fubar-coder** [comment]
It's not picked up by the console runner yet. I'll open a new issue for this problem.

**Comment by fubar-coder** [comment]
I created the issue #916

**Comment by KrisPetkov** [comment]
Hi @fubar-coder 
I have an issue with the naming convention. I have implemented my own IConventionSet class and it is registered as a singleton.
I also have an implementation of IForeignKeyConvention:

```csharp
public class ForeignKeyNameConvention : IForeignKeyConvention
    {
        public IForeignKeyExpression Apply(IForeignKeyExpression expression)
        {
            expression.ForeignKey.Name = GetForeignKeyName(expression.ForeignKey);

            return expression;
        }

        private string GetForeignKeyName(ForeignKeyDefinition foreignKey)
        {
            var fCol = string.Join('_', foreignKey.ForeignColumns);
            var pCol = string.Join('_', foreignKey.PrimaryColumns);

            var keyName = $"FK2_{foreignKey.ForeignTable}_{foreignColumns}_{foreignKey.PrimaryTable}_{primaryColumns}";

            return keyName;
        }
    }
```

But that code and especially the **Apply** method never gets called (I tried with breakpoint to see if it is called). And my custom naming is not applied.
My migration is of type **AutoReversingMigration**
Do you know if something additional needs to be added/applied?

**Comment by KrisPetkov** [comment]
@fubar-coder 
I have some more information:

If I try  to follow your example I'm hitting the following problems:
1. My naming convention has not been applied at all (as I described in my previous post)
2. Getting "A circular dependency was detected for the service of type..." exception

* The above two depends whether I'm going to register it like this (for `1.` problem):

```csharp
services.AddSingleton<IConventionSet, NamingConventionSet>();

services.AddFluentMigratorCore()                 
                 .ConfigureRunner(rb => rb
                    .AddPostgres()
                    .WithGlobalConnectionString(connectionString)
                    .ScanIn(Assembly.GetExecutingAssembly()).For.Migrations());
``` 

* Or like this (for `2.` problem):

```csharp
services.AddFluentMigratorCore()
                 .AddSingleton<IConventionSet, NamingConventionSet>()
                 .ConfigureRunner(rb => rb
                    .AddPostgres()
                    .WithGlobalConnectionString(connectionString)
                    .ScanIn(Assembly.GetExecutingAssembly()).For.Migrations());
```

I managed to resolve the problems if I make the second constructor which takes an argument (from your example) as a `private` constructor. After this change everything works as it suppose to.

Maybe I'm doing something wrong or there is some corner case that I'm hitting but I'll be grateful if you take a look because it's an interesting problem for me and I'll be happy to know the exact reason.

Thank you in advance!

**Comment by jzabroski** [comment]
@KrisPetkov Please open a new issue and I'll investigate.  Please also if you comment on old issues, do so via simply referencing comments in a new issue.  It helps make sure new issues/bugs do not get lost, but also see the linked issues from the new issue.
