### ISSUE TITLE
Have fluentmigrator automatically create database using connection string

### ISSUE THREAD

**Issue by phillijw** [fluentmigrator/fluentmigrator#815]
It would be nice if db could automatically be created if it doesn't exist using the connection string.

**Comment by fubar-coder** [comment]
This change is out of scope for this project - especially when we support idempotent features.

**Comment by JoelLapointe86** [comment]
This is not exactly what you are asking for but have a look at the method **EnsureDatabase** of the Serenity repo. They are using FluentMigrator and create the DB before running migration if the DB doesn't exist.

https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Core/Initialization/DataMigrations.cs

Hope it helps!

**Comment by mridah** [comment]
The link above doesn't work anymore. Does anyone has the code?

**Comment by vadzimdv** [comment]
https://github.com/serenity-is/Serene/blob/master/Serene/Serene.Web/Initialization/DataMigrations.cs

**Comment by vadzimdv** [comment]
> The link above doesn't work anymore. Does anyone has the code?

https://github.com/serenity-is/Serene/blob/master/Serene/Serene.Web/Initialization/DataMigrations.cs

**Comment by 51dario51** [comment]
> > The link above doesn't work anymore. Does anyone has the code?
> 
> https://github.com/serenity-is/Serene/blob/master/Serene/Serene.Web/Initialization/DataMigrations.cs

Looks like this link is broken too. The new one should be the following: https://github.com/serenity-is/serene/blob/master/src/Serene.Web/Initialization/DataMigrations.cs

**Comment by jackalvrus** [comment]
> > > The link above doesn't work anymore. Does anyone has the code?
> > 
> > 
> > https://github.com/serenity-is/Serene/blob/master/Serene/Serene.Web/Initialization/DataMigrations.cs
> 
> Looks like this link is broken too. The new one should be the following: https://github.com/serenity-is/serene/blob/master/src/Serene.Web/Initialization/DataMigrations.cs

And the latest new location is here:

https://github.com/serenity-is/serene/blob/master/src/Serene.Web/Modules/Common/AppServices/DataMigrations.cs

The author has archived the repository as of 29 Oct 2024, so maybe it won't move anymore.

**Comment by bartecargo** [comment]
Broken again; it's probably this one:

https://github.com/serenity-is/Serenity/blob/d390cce61775cc0fcd330f2c43984e9c706a5092/common-features/src/extensions/Modules/MigrationUtils/MigrationUtils.cs#L219
