### ISSUE TITLE
Native support for in-app migration

### ISSUE THREAD

**Issue by FrankV01** [fluentmigrator/fluentmigrator#820]
To me, one of the biggest things missing here is native support for in-app migration during things like app startup or database connection init.

**Comment by MarkEwer** [comment]
I’ve set this up with FluentMigrator on several projects.  It takes a little code, but it’s not that hard.  You can basically just copy over the same code that is used in the command line app and put it in the startup for your app.  Here’s and example:

        #region parameters
        private static string ApplicationContext;
        private static string Connection;
        private static string ConnectionStringConfigPath;
        private static string Namespace;
        private static bool NestedNamespaces;
        private static bool Output;
        private static string OutputFilename;
        private static bool PreviewOnly;
        private static string ProcessorType;
        private static string Profile;
        private static bool ShowHelp;
        private static int Steps;
        private static List<string> Tags = new List<string>();
        private static string TargetAssembly;
        private static string Task;
        private static int Timeout;
        private static bool Verbose;
        private static long Version;
        private static long StartVersion;
        private static bool NoConnection;
        private static string WorkingDirectory;
        private static bool TransactionPerSession;
        private static string ProviderSwitches;
        #endregion parameters

        private static void Up()
        {
            //Path and file name of assembly containing migrations
            TargetAssembly = Assembly.GetExecutingAssembly().FullName;
            //Kind of database server executing against
            ProcessorType = ConfigurationManager.AppSettings.GetValues("ProcessorType").First();
            //Connection string to that database server
            Connection = ConfigurationManager.AppSettings.GetValues("Connection").First();
            //Include migrations in nested namespaces or not
            NestedNamespaces = true;
            //If we should output the generated SQL script to a file or not
            Output = true;
            //Filename to output SQL script to
            OutputFilename = string.Format("Migration_{0}.sql", DateTime.Now.Ticks);
            //Migrate up
            Task = "migrate:up";
            //Version 0 means to run all versions
            Version = 0;
           //logging level
            Verbose = true;
            Execute();

        }

private static void Execute()
        {
            using (var sw = new StreamWriter(OutputFilename))
            {
                var fileAnnouncer = new TextWriterWithGoAnnouncer(sw);
                var consoleAnnouncer = new ConsoleAnnouncer();

                fileAnnouncer.ShowElapsedTime = false;
                fileAnnouncer.ShowSql = true;

                consoleAnnouncer.ShowElapsedTime = Verbose;
                consoleAnnouncer.ShowSql = Verbose;

                var announcer = new CompositeAnnouncer(consoleAnnouncer, fileAnnouncer);

                ExecuteMigrations(announcer);
            }
        }

       private static void ExecuteMigrations(IAnnouncer announcer)
        {
            var RunnerContext = new RunnerContext(announcer)
            {
                Database = ProcessorType,
                Connection = Connection,
                Targets = new string[] { TargetAssembly },
                PreviewOnly = PreviewOnly,
                Namespace = Namespace,
                NestedNamespaces = NestedNamespaces,
                Task = Task,
                Version = Version,
                StartVersion = StartVersion,
                NoConnection = NoConnection,
                Steps = Steps,
                WorkingDirectory = WorkingDirectory,
                Profile = Profile,
                Timeout = Timeout,
                ConnectionStringConfigPath = ConnectionStringConfigPath,
                ApplicationContext = ApplicationContext,
                Tags = Tags,
                TransactionPerSession = TransactionPerSession,
                ProviderSwitches = ProviderSwitches
            };

            new TaskExecutor(RunnerContext).Execute();
        }



________________________________

**Comment by FrankV01** [comment]
I've [accomplished it via this](https://stackoverflow.com/a/10508299/18196); that isn't the point really.  It's to make it native, documented and "officially" part of the product.

**Comment by eloekset** [comment]
I've got a simple one for ASP.NET projects. Searching for FluentMigrator on NuGet gives a lot of hits on runners for various environments. Maybe it would be a good idea to create a github.com/fluentmigrator/runners repository that points to most known open source runners, and then maybe write some missing ones.

**Comment by fubar-coder** [comment]
You can find an example in [samples/FluentMigrator.Example.Migrator/Program.cs](https://github.com/fluentmigrator/fluentmigrator/blob/master/samples/FluentMigrator.Example.Migrator/Program.cs)
