### ISSUE TITLE
Support For Disabling Some Expression

### ISSUE THREAD

**Issue by scokmen** [fluentmigrator/fluentmigrator#822]
Hi,

In some cases, I think disabling some expression would be a nice feature.

For example, in the production database, I want to disable all delete statements.

Thanks.

**Comment by fubar-coder** [comment]
You can do that in 3.0.0 by overriding `DefaultMigrationExpressionValidator.Validate` and checking for the types you want to suppress. Don't forget to call the base implementation of `Validate` to catch all other validation errors.
