### ISSUE TITLE
MySqlGenerator Decimal capacity 19?

### ISSUE THREAD

**Issue by smartmsdn** [fluentmigrator/fluentmigrator#823]
I'm having issue with declaring decimal with capacity more than 19

When doing `.AsDecimal(20,5)` I'm getting the exception "ERROR: Unsupported DbType 'Decimal'"

I'm seeing the `public const int DecimalCapacity = 19;`

According to MySQL documentation [here](https://dev.mysql.com/doc/refman/5.7/en/precision-math-decimal-characteristics.html) the number of maximum range of digit is from 1 to 65.

Is there a reason for this?

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0
