### ISSUE TITLE
Default String length for SqlServer should not be 255

### ISSUE THREAD

**Issue by michaelmalonenz** [fluentmigrator/fluentmigrator#824]
# The Problem: 
specifying a column as a string without a length specified, i.e.
```C#
Create.Column("SomeColumnName").OnTable("SomeTable").AsString();
```
leads me to believe the SqlServer definition for that would be 
```SQL
ALTER TABLE [SomeTable] ADD [SomeColumnName] nvarchar
```

However, it is actually:
```SQL
ALTER TABLE [SomeTable] ADD [SomeColumnName] nvarchar(255)
```

Most of the code looks like it accounts for no length to be specified and will gracefully not add a length, right up until we get to this line:
https://github.com/fluentmigrator/fluentmigrator/blob/f17dca3ba0ada883bf016d7bf297c9e0b8b8bdf7/src/FluentMigrator.Runner/Generators/SqlServer/SqlServer2000TypeMap.cs#L40

Which is where it's defined as being 255 in length.  I couldn't see anywhere in the documentation that specified a default length, which is why I was surprised.  Yes, I can easily work around this by specifying `AsString(int.MaxLength)` but it's a thing I need to remember to do.

**Comment by fubar-coder** [comment]
The behavior is by design. A CLOB (read: `nvarchar(max)`) is usually not what you want, when you want to store a string. 255 was the commonly used max. length for `varchar`.
