### ISSUE TITLE
LoadError: cannot load such file -- albacore 

### ISSUE THREAD

**Issue by astrohart** [fluentmigrator/fluentmigrator#828]
Hi all-

I am running on Windows 7 with a full VS 2017 and all previous versions install, as well as Ruby etc. and all FluentMigrator pre-reqs installed.

I did the following to try and build the nuget:

C:\Users\Brian Hart\Dropbox\Downloads\fluentmigrator-master\fluentmigrator-maste
r>tools\NuGet.exe restore FluentMigrator.sln

C:\Users\Brian Hart\Dropbox\Downloads\fluentmigrator-master\fluentmigrator-maste
r>rake nuget:create_nugets
rake aborted!
LoadError: cannot load such file -- albacore
C:/Users/Brian Hart/Dropbox/Downloads/fluentmigrator-master/fluentmigrator-maste
r/rakefile.rb:1:in `<top (required)>'
(See full trace by running task with --trace)

C:\Users\Brian Hart\Dropbox\Downloads\fluentmigrator-master\fluentmigrator-maste
r>rake nuget:create_nugets --trace
rake aborted!
LoadError: cannot load such file -- albacore
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'

C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'

C:/Users/Brian Hart/Dropbox/Downloads/fluentmigrator-master/fluentmigrator-maste
r/rakefile.rb:1:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in
 `load'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in
 `load_rakefile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:703:i
n `raw_load_rakefile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:104:i
n `block in load_rakefile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:i
n `standard_exception_handling'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:103:i
n `load_rakefile'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:82:in
 `block in run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:i
n `standard_exception_handling'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in
 `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (require
d)>'
C:/Ruby25-x64/bin/rake:23:in `load'
C:/Ruby25-x64/bin/rake:23:in `<main>'

Is there something I am doing wrong?  I have done a 'gem install albacore' prior to running this.

**Comment by escarls** [comment]
The instuctions are a bit weak on how to build the NuGet packages.
So I've changed it a bit in PR #830

**Comment by escarls** [comment]
For your exact case though, even with the changes I did to the PR, it will not work unless you install a complete Ruby development environment, as there are no prebuilt nokogiri gems for windows that works with version 2.5 of Ruby.
If you instead install the latest version 2.4, it should work with my changed instructions and GemFile.lock from PR #830
