### ISSUE TITLE
How to debug a migration within Visual Studio

### ISSUE THREAD

**Issue by mauriciojsola** [fluentmigrator/fluentmigrator#834]
Is there some way to debug the code of a migration from Visual Studio (or from any other way)?
I created a migration which includes some code that is required before executing the migration itself, but for some reason the added code is failing and I don't have a way to debug it. I'd like to add a breakpoint and debug the code.
Actually, I can use Console.WriteLine, but that is not optimal :)
Thanks in advance,
Mauricio

**Comment by fubar-coder** [comment]
The best point to debug migrations is to set breakpoints in the generator for your target database for the interesting expressions, e.g. in `src/FluentMigrator.Runner/Generators/SqlServer/SqlServer2005Generator.cs`, function `string Generate(CreateColumnExpression expression)`.
