### ISSUE TITLE
Update preview to actually have transaction calls

### ISSUE THREAD

**Issue by Vaccano** [fluentmigrator/fluentmigrator#836]
Right now if you generate a preview, it has comments like:

/* Beginning Transaction */

and

/* Committing Transaction */

It would be nice if there was a way to actually output the transaction statements.

**Comment by fubar-coder** [comment]
Not all databases support transaction control using SQL statements. Can you provide the statements for the database you're using?

**Comment by Vaccano** [comment]
`BEGIN TRANSACTION` to start a transaction 
`COMMIT TRANSACTION` to commit the transaction
`ROLLBACK TRANSACTION` to rollback the transaction 

(These are for SQL Server)
