### ISSUE TITLE
Conditions for migrations

### ISSUE THREAD

**Issue by fubar-coder** [fluentmigrator/fluentmigrator#838]
Only run a migration when a given condition is met.

**Comment by poimis** [comment]
I might be interested in implementing this one. Do you have any further requirements or implementation plans for this? Especially, what kind of conditions people are willing to write?

My initial plan for this would be to pass IVersionInfo to IMigrationInformationLoader.LoadMigrations()

Then, I would implement a new interface, say IConstraintAttribute
`[AttributeUsage(AttributeTargets.Class, Inherited = false)]
    public interface IConstraintAttribute
    {
        bool ShouldRun(IVersionInfo currentVersion);
    }`

and then have MigrationInformationLoader check if a migration type has any attribute that implements IConstraintAttribute, then run its (or theirs) ShouldRun method to check whether the migration should be added to the list of migrations to run.

Finally, my need (described in 986) would be fulfilled by this simple attribute
`public class PhasedMigrationAttribute : Attribute, IConstraintAttribute
    {
        private readonly long _minimumVersionToRunAgainst;

        public PhasedMigrationAttribute(long minimumVersionToRunAgainst)
        {
            _minimumVersionToRunAgainst = minimumVersionToRunAgainst;
        }
        public bool ShouldRun(IVersionInfo currentVersion)
        {
            return currentVersion.HasAppliedMigration(_minimumVersionToRunAgainst);
        }
    }`

Any comments? NOTE! I haven't previously contributed to FluentMigrator and lots of it's functions are unknown to me, so I may have well missed something :)

**Comment by fubar-coder** [comment]
I'm not sure if passing the `IVersionInfo` is desired here if we want a generic API and still avoiding a long list of parameters. Maybe `IServiceProvider` would be better? I'm not so sure about the "correct" API.

**Comment by poimis** [comment]
I found class `RunnerOptions` that seems to have all kinds of members that would be of interest when implementing these constraints. Maybe just pass it?
If we need a more generic api, lets have a "MigrationRunContext" that has RunnerOptions as a member.

**Comment by fubar-coder** [comment]
Fixed by #990
