### ISSUE TITLE
Ability to execute user defined operations before or after a migration execution

### ISSUE THREAD

**Issue by fubar-coder** [fluentmigrator/fluentmigrator#839]
This would allow the implementation of a "Database Fix" system.

**Comment by fubar-coder** [comment]
This feature already exists and is called [Maintenance](https://fluentmigrator.github.io/articles/glossary.html#maintenace)

**Comment by poimis** [comment]
> This feature already exists and is called [Maintenance](https://fluentmigrator.github.io/articles/glossary.html#maintenace)

This page would benefit from a a bit more verbose description. What is this Maintenance thing?

**Comment by fubar-coder** [comment]
You're right. This features needs a better description.

This allows one to execute a variation of the migration objects before all/every and after all/every migration. A use case for this is to seed the database after all migrations were run.
