### ISSUE TITLE
Npgsql used version is buggy

### ISSUE THREAD

**Issue by eric-b** [fluentmigrator/fluentmigrator#844]
Hi,

FYI, I encountered a bug with a migration on postgres. When pgsql server raised an exception, sql command hung application side, like if a deadlock happened.

I finally found that it was related to the buggy version of npgsql (2.0.11) referenced by FluentMigrator.Tools (1.6.2).

I updated npgsql to version 3.2.7 and the migration correctly raises the sql exception.

If someone encounter a similar issue, the workaround is to manually replace dll versions next to Migrate.exe file. You also have to modify the Migrate.exe.config file for assemblies bindings. In my case, I had 2 dll to update:

```
   <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Npgsql" publicKeyToken="5d8b90d52f46fda7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.7.0" newVersion="3.2.7.0" />
      </dependentAssembly>
       <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

```

**Comment by fubar-coder** [comment]
Fixed in release/2.0.0, but I'll leave this issue open until 2.0.0 is released.
