### ISSUE TITLE
Oracle Managed DataAccess error with Fluent Migrator

### ISSUE THREAD

**Issue by pittpasc** [fluentmigrator/fluentmigrator#845]
I have a console program in C# with .NET Framework 4.5.2 and FluentMigrator 1.6.2.0 and it worked fine until I've updated my Oracle ManagedDataAccess to the version 12.2.1100

I've got the following error message :
```
-------------------------------------------------------------------------------
=============================== FluentMigrator ================================
-------------------------------------------------------------------------------
Source Code:
  http://github.com/schambers/fluentmigrator
Ask For Help:
  http://groups.google.com/group/fluentmigrator-google-group
-------------------------------------------------------------------------------
[+] Using Database Oracle and Connection String data source=****
!!! Exception has been thrown by the target of an invocation.
!!! The type initializer for 'Oracle.DataAccess.Client.OracleClientFactory' threw an exception.
!!! The provider is not compatible with the version of Oracle client

```
Is there a version of FluentMigrator that is compatible with Framework 4.5.2  and Oracle.ManagedDataAccess 12.2.1100 ?

Thanks for your help
Best Regards

**Comment by escarls** [comment]
What version of ODA did you use before upgrading to 12.2.1100?

**Comment by fubar-coder** [comment]
We use a reflection based approach to load the oracle driver and 1.6.2 didn't try to find / load the managed driver. This may be solved with the release of 2.0.

**Comment by ttallskog** [comment]
Hi,

I am having the same problem.  Using .net 4.7.1 and 12.2.1100. 

This is the command that i run: Migrate.exe --db "Oracle" --conn "DATA SOURCE="xxxx" --assembly "xxxx.dll" --task "migrate:up"

Any idea what can be causing this?
BR

**Comment by fubar-coder** [comment]
Please don't use the `FluentMigrator.Tools`. This package is obsolete. Please use `FluentMigrator.Console` instead.

**Comment by fubar-coder** [comment]
@pittpasc Ok, after using my Google-fu, I found out, that you're using the non-managed driver (`Oracle.DataAccess`. You must use `OracleManaged` instead of `Oracle` as provider. The error message itself comes from the `Oracle.DataAccess` ADO.NET provider, that indicates that the **Oracle client libraries installed on your computer** don't match the version expected by `Oracle.DataAccess`.
