### ISSUE TITLE
Problem with SqlServerCe using 2.02 release

### ISSUE THREAD

**Issue by sthompson32780** [fluentmigrator/fluentmigrator#858]
FluentMigrator requires me to have the runner for SqlServer when using SqlServerCe. Why?

Keep getting an error on use with SqlCeCommand.CommandTimeout does not support non-zero values.

**Comment by fubar-coder** [comment]
It requires the SqlServer runner, because it's derived from it (they share many features).

Regarding the `CommandTimeout` error: That is strange. This shouldn't happen as this is explicitly taken care of. I'll take a look at it.

**Comment by fubar-coder** [comment]
Fix will be in v2.0.3
