### ISSUE TITLE
Bug when using PoundSignSingleLineComment with SqlServer

### ISSUE THREAD

**Issue by kasperbirkelund** [fluentmigrator/fluentmigrator#859]
I'm running a migration script on SqlServer2016. The hardcoded sql uses temp tables which in SqlServer is notated like #myTmpTable. The class PoundSignSingleLineComment though will treat it like a comment and therefore not execute is causing my migrations to fail.

Are there any ways to avoid this 'RangeSearcher' in SqlServer mode?

**Comment by fubar-coder** [comment]
The pound sign should only be recognized at the beginning of a line. Can you show the problematic SQL snippet? I'll upload a hotfix in the next 24 hours.

**Comment by kasperbirkelund** [comment]
Here you are 😃 
select c.*
into #MyTmpTable
from reader.MyTable c

**Comment by kasperbirkelund** [comment]
It works! Thanks for awsomely fast support 😃
