### ISSUE TITLE
Improve install & run wiki pages

### ISSUE THREAD

**Issue by joewarner** [fluentmigrator/fluentmigrator#862]
Sorry to have to ask this but can someone review/revise the sections on "Getting FluentMigrator" and "Migration Runners" in the wiki pages as I'm unable to get the Migration.exe program to build.

I understand that a major part of the problem is that [NuGet is 'broken'](https://github.com/NuGet/Home/issues/4190) insofar as it isn't able to handle DotNetCliToolsPackage's anymore but despite all of the reading I have done around this my .NET experience is insufficient to figure out precisely what I need to do to work around this problem.

I believe what I am missing is

- Specific instructions on how to modify my .csproj file so that it includes what is needed
- How to manually install the FluentMigrator.DotNet.Cli package (which I believe is missing)
- If necessary how to ensure that Migrate.exe is built - as I've never succeeded in doing this I'm unclear whether there are steps missing or not

**Comment by eduprog** [comment]
I use fluentmigrator directly in .Net WinForms and it works 100%. I'll pass you here, the classes I use and also the link I studied to be able to build my classes ok.

To use in my .Net 4.5.2 project, I just used the command
`Install-Package FluentMigrator`
with this command in the Package Manager Console, it installs all required packages.

In this link I found what I needed to be able to run everything according to the classes below.

**The link is in Portuguese, but I hope it helps.**
[http://www.marcelobalexandre.com/blog/2014/10/27/manutencao-de-schema-de-banco-de-dados-com-migrations-em-net/](url)


Well I hope to help and I'm sorry for my English, with the help of google translate!
```

 static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
         UpdateBd.Update();
         }
}

public enum EMigratorEnvironment
    {
        Devel
        Tests,
        production
    } 

public static class UpdateBd
    {
        public static void Update()
        {
            MigrationBd.Migrate(migrationRunner => migrationRunner.MigrateUp(),
                .ConnectionString, EMigratorEnvironment.Devel);
        }
    }

public static class MigrationBd
    {
         
        private class MigrationOptions: IMigrationProcessorOptions
        {
            public bool PreviewOnly { get; set; }
            public int Timeout { get; set; }
            public string ProviderSwitches => throw new NotImplementedException();
        }

        /// <summary>
        /// Executa a migração no bando de dados
        /// </summary>
        /// <param name="migrationRunnerAction"> Tipo de Migração a ser executada. migrationRunner => migrationRunner.MigrateUp() Ugrade banco,  migrationRunner => migrationRunner.MigraDown(1234565676) Downgrade banco</param>
        /// <param name="connectionString">string de conexao</param>
        /// <param name="migratorEnvironment">Motivo da migracao:  EMigratorEnvironment.Desenvolvimento(Desenvolvimento),EMigratorEnvironment.Testes(Teste),EMigratorEnvironment.Producao(Produção)</param>
        public static void Migrate(Action<IMigrationRunner> migrationRunnerAction, string connectionString, EMigratorEnvironment migratorEnvironment)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();

            //var textWriterAnnouncer = new TextWriterAnnouncer(write => GravaLogMigracao(write)); //Linha Original 
            var textWriterAnnouncer = new TextWriterAnnouncer(GravaLogMigracao); // Comando Refatorado Resharper
            var runnerContext = new RunnerContext(textWriterAnnouncer)
            {
                ApplicationContext = migratorEnvironment
            };

            var migrationOptions = new MigracaoOpcoes()
            {
                PreviewOnly = false,
                Timeout = 0
            };

            //Cria o processador de acordo com o Provider, neste Caso Firebird
            /* Modelos Existentes:
             *************************************************************************************
             | PostgresProcessorFactory m = new PostgresProcessorFactory();                      |
             | MySqlProcessorFactory my = new MySqlProcessorFactory();                           |
             | SqlServerProcessorFactory sql = new SqlServerProcessorFactory();                  |
             | OracleProcessorFactory oracle = new OracleProcessorFactory();                     |
             | Db2ProcessorFactory db2 = new Db2ProcessorFactory();                              |
             | HanaProcessorFactory hana = new HanaProcessorFactory();                           |
             | JetProcessorFactory jet = new JetProcessorFactory();                              |
             | SqlServer2000ProcessorFactory sql2000 = new SqlServer2000ProcessorFactory();      |
             | SqlServer2005ProcessorFactory sql2005 = new SqlServer2005ProcessorFactory();      |
             | SqlServer2008ProcessorFactory sql2008 = new SqlServer2008ProcessorFactory();      |
             | SqlServer2012ProcessorFactory sql2012 = new SqlServer2012ProcessorFactory();      |
             | SqlServer2014ProcessorFactory sql2014 = new SqlServer2014ProcessorFactory();      |
             | SQLiteProcessorFactory sqLite = new SQLiteProcessorFactory();                     |
             | FirebirdProcessorFactory firebird = new FirebirdProcessorFactory();               |
             *************************************************************************************/


            FirebirdProcessorFactory processorFactory = new FirebirdProcessorFactory();
            var processor = processorFactory.Create(connectionString, textWriterAnnouncer, migrationOptions);

            var migrationRunner = new MigrationRunner(assembly, runnerContext, processor);
            migrationRunnerAction(migrationRunner);

        }

        /// <summary>
        /// Grava log da Migração para posterior Avaliação, dentro do diretório LogMigracao no diretório raiz da aplicação
        /// </summary>
        /// <param name="log">Nome do Arquivo de Log</param>
        private static void GravaLogMigracao(string log)
        {
            if (!log.Equals("\r\n"))
            {
                log = $"{DateTime.Now:G} - Host: {Environment.UserDomainName}/{Environment.UserName} - {log}";
            }
            string pathLogMigracao = $@"{Application.StartupPath}\LogMigracao";
            string arquivoLogMigracao = "LogMigracaoDados.txt";
            if (!Directory.Exists(pathLogMigracao))
            {
                Directory.CreateDirectory(pathLogMigracao);
            }
            try
            {
                using (StreamWriter w = File.AppendText(pathLogMigracao + "\\" + arquivoLogMigracao))
                {
                    w.Write(log);
                }
            }
            catch (System.Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }

```
**Neste exemplo uso o banco de dados firebird, estou criando a tabela de funcionários
Migration Class Example**:

 ```
 [Migration(201803141106)]
    public class MigracaoFuncionario : Migration
    {
        public override void Up()
        {
            #region FUNCIONARIO
            //Execute.EmbeddedScript("Funcionario.Sql");
            Execute.Sql("CREATE GENERATOR GEN_ID_FUNCIONARIO;");
            Execute.Sql("CREATE TABLE FUNCIONARIO (ID INTEGER NOT NULL," +
                        "NOME VARCHAR(100) DEFAULT NULL COLLATE WIN_PTBR, " +
                        "TELEFONE VARCHAR(10) DEFAULT NULL COLLATE WIN_PTBR, " +
                        "CELULAR VARCHAR(10) DEFAULT NULL COLLATE WIN_PTBR, " +
                        "EMAIL VARCHAR(250) DEFAULT NULL COLLATE WIN_PTBR, " +
                        "COMISSAOVISTA  DECIMAL(15,4) DEFAULT NULL, " +
                        "COMISSAOPRAZO  DECIMAL(15,4) DEFAULT NULL, " +
                        "NIVELAUTORIZACAO CHAR(1) DEFAULT NULL COLLATE WIN_PTBR );");
            Execute.Sql("ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID);");
            Execute.Sql("CREATE INDEX IDX_IDFUNCIONARIO ON FUNCIONARIO (ID);");
              Execute.Sql(@"CREATE OR ALTER TRIGGER BIUD_FUNCIONARIO FOR FUNCIONARIO ACTIVE BEFORE INSERT OR UPDATE OR DELETE POSITION 0 AS " +
                        "begin " +
                        "if (new.ID is null) then " +
                        " new.ID = GEN_ID(GEN_ID_FUNCIONARIO, 1);   " +
                        "end  ;");
            #endregion
        }

        public override void Down()
        {
            Execute.Sql("DROP TRIGGER BIUD_FUNCIONARIO;");
            Execute.Sql("DROP SEQUENCE GEN_ID_FUNCIONARIO;");
            Execute.Sql("DROP TABLE FUNCIONARIO;");
        }
    }
```

**Comment by RobArbor** [comment]
@eduprog Thanks for some samples their are helpful. 

I'm missing in the current documentation how to use the `FluentMigrator.Runner`. For intergrating in my project.

**Comment by joewarner** [comment]
@fubar-coder Ironically right after I posted my question I was reading #860 which, in the end, gave me a big part of my answer.

- I think your answer assumes I am building FluentMigrator, but unless I really need to that wasn't my plan - I just wanted to use the NuGet packages.
- What I learned from #860 is that there is a Migrate.exe in packages\FluentMigrator.Console.2.0.5\tools\net452\x86 and I have been able to use that. (It seems like a bit of a cumbersome way to use it, but it works so I'm happy with that for now. I think my point is that it would be helpful if the Wiki page described either where to find this program or how to "install" it to somewhere more obvious.)
- Since I have found Migrate.exe I'm beginning to think that either references to FluentMigrator.DotNet.Cli are either a bit of a red herring or do something that I simply don't understand. So, absolutely no requirement for me to change my .csproj file in the end.

So, my outstanding questions would be

1. Am I using Migrate.exe the way that is intended. 
2. If so, then I do think that there is a failing in the documentation because I have seen nothing to suggest where I would find this program.

I realise that some of my problems may be due to my lack of experience with .NET, but now that I understand the problem I do still think there is a gap in the documentation.

@eduprog Thanks for making the effort to respond. Your examples are interesting to read (and @RobArbor found them helpful) but not really relevant to what I want to achieve because I specifically wanted to be able to run my migrations from the command line. However, I am much nearer to that goal now, thx.

**Comment by fubar-coder** [comment]
1. Yes, you are using it as inteded.
2. It should be already documented in the Wiki, but I agree that we need a (much) better documentation.

The `FluentMigrator.DotNet.Cli` package (with the `dotnet-fm` tool) is indeed only useful for people using the .NET Core tooling. It is currently only useful in some limited circumstances. Some of the limitations will be lifted as soon as .NET Core CLI and we are supporting the global tools.

I'm glad, that the we (the community) were able to help you!

Please close this issue if all your questions are answered.

**Comment by joewarner** [comment]
I think that we will have to agree to disagree that the Wiki provides sufficient detail on how to locate the Migrate executable but otherwise I am pleased to say that you were able to help me and I will now close this issue. Thx.

**Comment by joewarner** [comment]
Thanks to your help above I got this running on a Windows machine. 

Are there are any special/additional instructions to get this running on MacOS - which is where I would prefer to be running this. I don't seem to have any trouble building fluentmigrator as follows

`dotnet build FluentMigrator.sln`
`    0 Error(s)`

but I am having trouble trying to figure out how to run it. I have a range of Migrate.exe files. Based on what I did on Windows I'd expect this command to work

`dotnet src/FluentMigrator.Console/bin/Debug/net452/Migrate.exe`

but what I get is

`A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/joe/workspace/dotnet/fluentmigrator/src/FluentMigrator.Console/bin/Debug/net452/'.`

I did try the `dotnet publish` command and although it didn't report any errors it didn't write anything to the output directory I specified.

**Comment by fubar-coder** [comment]
TBH: I have no idea and no access to a MacOS machine. The issue dotnet/core#1038 indicates that a `dotnet publish` should be used. I also found RSuter/NSwag#838 where a similar problem was discussed. Those issues may point you in the right direction.

Just an assumption. When you specify a relative output path for `dotnet publish`, then the output path is created below bin/$(Configuration)/... etc.... which caused some confusion for me. Maybe you were hit by the same behavior?

**Comment by joewarner** [comment]
With more reading I found that you have to use something called mono to run the Migrate.exe program. There was nothing wrong with the executable that I had. `dotnet publish` can be used to put it in a more desirable place, but fundamentally is part of the issue/solution.

So, I have finally managed to get it to execute on MacOS. So, I'll close this ticket (again).

**Comment by fubar-coder** [comment]
Good that you found a solution and for letting us know 👍
