### ISSUE TITLE
FluentMigrator Release Plan

### ISSUE THREAD

**Issue by fubar-coder** [fluentmigrator/fluentmigrator#866]
# The Plan (influenced by survey)

1. We release the next version as 3.0
2. It stays mostly API compatible, but parts of the API is marked as deprecated
3. It will be released together with .NET Core CLI 2.1 tooling

# To do until release

1. [Documentation](https://fluentmigrator.github.io) (including upgrade guide)
2. Bug fixes
3. Maybe some database specific enhancements (what's in, is in, what's not, is not, depending on the .NET Core CLI tooling release)

***
# Previous content:
***

# Overview

Please answer [this survey](https://www.surveymonkey.de/r/SHMJMD9) or leave a comment here. Thank you all!

# Information

How should we plan the release?

The current development version contains lots of API changes due to the new support for:

* Microsoft.Extensions.DependencyInjection
* Microsoft.Extensions.Options
* Microsoft.Extensions.Logging

This results in some obsolete API parts with the biggest offender being IRunnerContext (and RunnerContext).

### Pro

* Fine according to SemVer V2, because no legacy API was removed

### Con

* I might've unintentionally removed some legacy API
* Lots of warnings about obsolete members

### Pro

* Breaking changes are expected

### Con

* Maybe too soon after the 2.0.0 release?
* Only structural changes, no big new features

**Comment by jerriep** [comment]
If Option 2 means that there is less code for you to maintain in the future and consequently makes your life as the sole maintainer of this project easier, then, by all means, do that.

I have not used FluentMigrator in a long time, but I was involved in maintaining OSS project previously. So my opinion is based on that experience and obviously does not reflect some (genuine) concerns which actual, current users of the product may have with the second option.

**Comment by fubar-coder** [comment]
Do you think that I should remove the deprecated API for the 3.0 release or instead keep it for 3.0 and remove it in 4.0? I want to give the current users an upgrade path that eases the transition to the new DI-based API.

**Comment by jerriep** [comment]
Oh, I understood that that was the idea of doing a major version jump to 3.0. Otherwise, why do a new major version?

**Comment by sereeth** [comment]
How far are you away from the 3.0 release?  We're looking at using this for migrations but more migrating the content of the database as schema changes happen, which is what a lot of people use migrations for in rails.  Changing the schema is actually only half the story, back-filling tables fixing issues in data is the other.  So, to accomplish this in our code, we'd need to be able to inject our dependencies so that migrations can contain our own classes that might be needed to perform a migration.

Awesome that somebody is bringing .NET into this world, so lacking.

**Comment by fubar-coder** [comment]
The plan is to release 3.0 together with the .NET Core 2.1 release. I *really*, ***really*** hope, that this happens in the same time frame as the [Microsoft build conference](https://www.microsoft.com/build).

Currently, I'm just creating the documentation, and doing some bug-fixes and (maybe) one or two new database-specific features.

Other than that, the current alpha is definitely usable and the [new documentation](https://fluentmigrator.github.io) is already online and there are no API changes planned anymore.

**Comment by fubar-coder** [comment]
The 3.0 beta is out and available via myget: https://www.myget.org/F/fluent-migrator/api/v3/index.json

**Comment by fubar-coder** [comment]
@sereeth .NET Core 2.1 rc1 (with go-live permission) is released - and so is FluentMigrator 3.0.

**Comment by sereeth** [comment]
Thanks
