### ISSUE TITLE
ExecuteSqlScript: doesn't convert directory separators in assembly paths

### ISSUE THREAD

**Issue by joewarner** [fluentmigrator/fluentmigrator#870]
This is a similar problem to #869, but subtly different.

`[+] ExecuteSqlScript /Users/joe/workspace/acdp-database/acdp-database\procedures\System_Create_v1_000.sql`
`!!! Could not find file "/Users/joe/workspace/acdp-database/acdp-database\procedures\System_Create_v1_000.sql"`

The "name" of the script file when it is read from the Assembly can contain a directory separator - in this case the name of the script file is `procedures\System_Create_v1_000.sql`. Unfortunately the directory separator '\\' is not being translated into the '/' character appropriate for Mac.

As with #869 I'm fairly happy to provide a fix but I haven't yet located a suitable point in the code to make this change. If anyone who knows the code better is able to point me in the right direction then that would save me some time.

**Comment by fubar-coder** [comment]
How is the path stored in your assembly source code? You can use one of the following ways to create portable paths:

```c#
Path.Combine("a", "b")
string.Concat("a", Path.DirectorySeparatorChar, "b")
string.Format("a{0}b", Path.DirectorySeparatorChar)
```

Automatic translation of `\\` to `/` shouldn't be necessary and usually creates more harm than good.

**Comment by joewarner** [comment]
User error. Please ignore!
