### ISSUE TITLE
How to get the generated SQL script without changing the database

### ISSUE THREAD

**Issue by saeidjoker** [fluentmigrator/fluentmigrator#872]
This is more of a QUESTION than issue.
I'm trying to create "sql queries" using your AMAZING library.
But I just want to create sql queries not migrating database. Could you please tell me
how can I get only the generated sql query for each Migration class at any time?
I wanna use fluentmigrator as a DDL generator only.

**Comment by reinaldocoelho** [comment]
Hi @saeidjoker .

To write a SQL command you can try this:
`            
Execute.Sql(@"
                UPDATE
	                t
                SET
	                t.Field = 'X'
                FROM
	                table  t
                WHERE
	                t.Id = 2
");
`

Is that your question?
If not, what type of query you want to run, have you an example?

**Comment by fubar-coder** [comment]
Steps:

* Specify that you want an output log file (Migrate.exe, options `-o`)
* *Optional:* Specify a log file name (Migrate.exe, options `--outfile=filename.sql`). If none is specified, the log file is `path-to-assembly.dll.sql`
* Run the migration in preview or connectionless mode
  * "Preview" mode (Migrate.exe, option `-p`)
  * "Connectionless" mode (Migrate.exe, option `--noConnection`)

The difference between those two is, that the preview mode loads the information about the applied migrations from the database, while the latter cannot do this. You can specify a start version for option 2 to work around this limitation.

**Comment by saeidjoker** [comment]
Just wanna thank you for amazingly fast response!!!!!!
THANKS

**Comment by fubar-coder** [comment]
No problem. Please close this issue if your question is answered.
