### ISSUE TITLE
Temp table declaration within script file

### ISSUE THREAD

**Issue by xmark** [fluentmigrator/fluentmigrator#876]
I am trying to use the command line runner for a project of mine, in which I have a C# migration that calls the **Execute.Script** function, which worked fine until I changed the SQL script to contain the declaration of a temp table into the SQL file:

**CREATE table #mergeReportTable ( [Action] [nvarchar](255) NOT NULL, [ItemType] [nvarchar](255) NOT NULL, [Insertions] uniqueidentifier NULL, [Deletions] uniqueidentifier NULL )**

The Migrations now fail with the error:
!!! Incorrect syntax near the keyword 'set'.
Incorrect syntax near the keyword 'END'.

I can assure you the SQL script runs fine when I copy and paste the text into SSMS.

The real clue to the bug is in the output of the Migrate.exe application, the output of the line above looks like this:

**CREATE table**

so it appears that the rest of the line is being treated like a C# comment, not a temp table in SQL.

Is this a known issue?

**Comment by fubar-coder** [comment]
It was already fixed in version 2.0.6, but you may also update your packages to 2.0.7 😁 .

**Comment by xmark** [comment]
Ah, sorry about that, you are right, I just updated and it works fine now. thanks!
