### ISSUE TITLE
Using profiles in 3.x versions

### ISSUE THREAD

**Issue by spindev** [fluentmigrator/fluentmigrator#886]
Hi, we've upgraded from 2.x to 3.x. Everything is running fine except the profiles.

In the documentation I couldn't find a part covering this topic using in-process migration.

            _serviceProvider = new ServiceCollection()
                .AddFluentMigratorCore()
                .ConfigureRunner(
                    builder => builder
                        .AddSqlServer2014()
                        .AddOracleManaged()
                        .WithGlobalConnectionString(connectionString)
                        .WithMigrationsIn(GetType().Assembly)
                )
                .Configure<SelectingGeneratorAccessorOptions>(cfg =>
                {
                    cfg.GeneratorId = dataprovider == Dataprovider.Oracle ? "oraclemanaged" : "sqlserver2014";
                })
                .Configure<RunnerOptions>(cfg => { cfg.Profile = profile; })
                .BuildServiceProvider();

and then

                using (var scope = _serviceProvider.CreateScope())
                {
                    var runner = scope.ServiceProvider.GetRequiredService<IMigrationRunner>();
                    runner.MigrateUp();
                }

The profile doesn't get hit. Any idea what I'm doing wrong? Debugging of the runner shows, that the list of profiles is empty.

Thanks in advance!

**Comment by fubar-coder** [comment]
`WithMigrationsIn` doesn't cover profiles (even though it should).

You can use the following workaround: Remove `WithMigrationsIn` and add the following:

```csharp
    .AddSingleton<IAssemblySourceItem>(() => new AssemblySourceItem(GetType().Assembly));
```

**Comment by spindev** [comment]
Thanks for the fast response.

.AddSingleton<IAssemblySourceItem>(x => new AssemblySourceItem(GetType().Assembly))

Worked!
