### ISSUE TITLE
VersionTable not changed after upgrading to 3.0

### ISSUE THREAD

**Issue by MarcoTUI** [fluentmigrator/fluentmigrator#888]
Hi,
today I upgraded to version 3.0.
now my VersionTable doesn't get updated any longer. Within my migration project I have this class:

    [VersionTableMetaData]
    public class AAInitial : DefaultVersionTableMetaData
    {
        public AAInitial(IConventionSet conventionSet, IOptions<RunnerOptions> runnerOptions)
            : base(conventionSet, runnerOptions)
        {
        }

        public override string SchemaName => "test";
    }

but my VersionTable becomes dbo.VersionTable if it doesn't exist

Best regards
Marco

**Comment by fubar-coder** [comment]
`WithMigrationsIn` doesn't cover version table metadata.

Adding an assembly source for the assembly containing your version table metadata should take care of this problem:

```csharp
    .AddSingleton<IAssemblySourceItem>(() => new AssemblySourceItem(GetType().Assembly));
```

**Comment by MarcoTUI** [comment]
Hi Mark,
thank you very much for your quick answer. This really helped me out. Maybe it is worth updating the documentation or change-list as this is a very different way than it was before?

This is my final approach which updated VersionTableInfo again:

```
private static IServiceProvider CreateServices(Assembly assembly, string connectionString)
        {
            return new ServiceCollection()
                // Add common FluentMigrator services
                .AddFluentMigratorCore()
                .ConfigureRunner(rb => rb
                    // Add SQLite support to FluentMigrator
                    .AddSqlServer2014()
                    // Set the connection string
                    .WithGlobalConnectionString(connectionString)
                    // Define the assembly containing the migrations
                    .WithMigrationsIn(assembly))
                // Enable logging to console in the FluentMigrator way
                .AddLogging(lb => lb.AddFluentMigratorConsole())
                // Add AssemblySourceItem to run VersionTableInfo updates
                .AddSingleton<IAssemblySourceItem>(new AssemblySourceItem(assembly))
                // Build the service provider
                .BuildServiceProvider(false);
        }
```

Best regards
Marco

**Comment by fubar-coder** [comment]
You're right, I'll update the documentation.
Glad that I could help you.
