### ISSUE TITLE
OracleManaged Migrations fail with runtime Exceptions

### ISSUE THREAD

**Issue by cgibbons** [fluentmigrator/fluentmigrator#890]
When trying to migrate an oracle database with version 3.0, runtime exceptions occur.  If using oraclemanaged the following exception occurrs

```text
Unhandled Exception: System.TypeLoadException: Could not load type 'System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at OracleInternal.ConnectionPool.PoolManager`3.CreateNewPRThreadFunc(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

This is using the oracle beta driver that supports dotnet core.

If using the Devart DotConnect driver, it fails because it says it can't find the correct version of Devart.Data, even though I can see it in the output directory.

To repro this is a netcoreapp2.1 project with the following dependencies

```xml
<ItemGroup>
        <!--<PackageReference Include="Oracle.ManagedDataAccess" Version="12.2.1100" />-->
        <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="2.12.0-beta2" />
        <PackageReference Include="FluentMigrator" Version="3.0.0" />
        <PackageReference Include="FluentMigrator.Console" Version="3.0.0" />
        <PackageReference Include="FluentMigrator.Runner" Version="3.0.0" />
        <PackageReference Include="FluentMigrator.Runner.Oracle" Version="3.0.0" />
</ItemGroup>
```

**Comment by cgibbons** [comment]
This can also be recreated following your quickstart guide, but substituting in the oracle libraries instead.

**Comment by cgibbons** [comment]
I've also tried using the devart driver, but it's failing with assembly load exceptions.  Do you want me to file that as a separate bug with repro steps?  Or append it this one?

**Comment by cgibbons** [comment]
@fubar-coder you're right, I substituted the beta driver in place of the managed driver in the code and it runs file.  I'll submit a PR and you can choose to merge it if you'd like.

**Comment by fubar-coder** [comment]
Please file a separate bug. A PR would be welcome. It's good that you were able to solve the problem.

**Comment by cgibbons** [comment]
Here's the PR I've submitted.  I've tested locally and I can now run oracle migrations as a dotnet core application.  https://github.com/fluentmigrator/fluentmigrator/pull/891
