### ISSUE TITLE
Nullable types are not supported in MSBuild runner

### ISSUE THREAD

**Issue by mmiller678** [fluentmigrator/fluentmigrator#892]
I am using the latest version  (v3) of the FluentMigrator.MSBuild package and cannot set the timeout parameter as nullable types are not supported in MSBuild.  Below is the error message:

Error MSB4030: "60000" is an invalid value for the "Timeout" parameter of
the "Migrate" task. The "Timeout" parameter is of type "System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]".

**Comment by fubar-coder** [comment]
It's good to see that the MSBuild runner is still in use. The nullable type is indeed an oversight from my side. I'll release a 3.0.1 tomorrow.

**Comment by mmiller678** [comment]
Great thank you - will test it once I see the release on nuget.

**Comment by fubar-coder** [comment]
3.1.0 has been published to NuGet.org and should be available soon.
