### ISSUE TITLE
Jet Migrations

### ISSUE THREAD

**Issue by sthompson32780** [fluentmigrator/fluentmigrator#894]
Upgrading from 3.0 to 3.1. Followed the migration instructions for 3.0 to 3.1.

Keep getting on running -

Exception thrown: 'System.NullReferenceException' in FluentMigrator.Runner.Core.dll

**Comment by fubar-coder** [comment]
Do you have a test case or a repository where I can reproduce the error?

**Comment by fubar-coder** [comment]
I updated the example application and was unable to see this behaviour.
