### ISSUE TITLE
SqlServer 2017 Support

### ISSUE THREAD

**Issue by WereDev** [fluentmigrator/fluentmigrator#896]
Curious as to when SqlServer 2017 support might be verified.

Thanks.

**Comment by fubar-coder** [comment]
We currently don't use any SQL Server 2017 specific feature, so you can simply use the SQL Server 2016 configuration/support. I guess that we have to just "support" it explicity to avoid confusion in the future. I'm leaving it open for now.

**Comment by WereDev** [comment]
That would be helpful.  I'm am wanting to use this tool at work to replace DbProj migrations, but the powers-that-be said no due to lack of 2017 support.

Thank you!

**Comment by fubar-coder** [comment]
Would it be sufficient when the document states that the SQL Server 2016 mode is compatible with SQL Server 2017?

**Comment by fubar-coder** [comment]
I'll do some tests (running the unit tests against SQL Server 2017) and report back here.

**Comment by WereDev** [comment]
That's awesome!  Thanks!

**Comment by fubar-coder** [comment]
I tested every integration test against SQL Server 2017 Developer and everything works as expected.

**Comment by fubar-coder** [comment]
Documentation will be updated soon.
