### ISSUE TITLE
DB locked exception when manipulating data with nHibernate

### ISSUE THREAD

**Issue by madben2000** [fluentmigrator/fluentmigrator#897]
Since Version 2.0.7, also the latest version 3.1 our Migration is not working anymore.
We are using nHibernate inside migration to initially update the db schema or manipulation data.
With version 1.6.2 everything worked. See below the exception that the database (sqlite) is locked:

Beginning Transaction
ERROR - Unsuccessful: create table ANALYSIS (ANALYSIS_ID  integer primary key autoincrement, NAME TEXT default ''  not null, DESCR TEXT, STATUS_ID INT,unique (NAME), constraint FK_AnalysisToStatus foreign key (STATUS_ID) references STATUS_INFO)
System.Data.SQLite.SQLiteException (0x80004005): database is locked
database is locked
   bei System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   bei System.Data.SQLite.SQLiteDataReader.NextResult()
   bei System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   bei System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   bei System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   bei NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)

How can we solve this problem? Thank you

**Comment by fubar-coder** [comment]
You use NHibernate to create the initial schema and seed the database? Then I suggest that you change the [transaction behavior](https://fluentmigrator.github.io/articles/migration/migration-transaction-behavior.html) of your migration (probably the place where you use NHibernate?) to `None` and let NHibernate use its own transactions.

If you already do this, then it would be helpful to get my hands on an example or unit test where I can test this problem.

**Comment by madben2000** [comment]
We used nHibernate within migrations successfully without touching any transaction behavior before v.2. (for creating the initial schema and so on)
Where there changes which could cause this locking from v.2 on?

**Comment by fubar-coder** [comment]
I'm not aware of such changes, but it sounds plausible ***when*** for some reason NHibernate and FluentMigrator load different SQLite libraries. What changed (since 2.0) was the mechanism to search for those libraries to be accessed through reflection.

**Comment by schambers** [comment]
In an effort to organize existing issues and due to age, this ticket is being closed. If you feel like the issue still applies, please open a new ticket and we'll review for future addition. Thank you!
