### ISSUE TITLE
How can I fix my "No migrations found" error when executing my script.

### ISSUE THREAD

**Issue by CoffeToCodeConverter** [fluentmigrator/fluentmigrator#898]
My solution:
[Solution.zip](https://github.com/fluentmigrator/fluentmigrator/files/2089427/Solution.zip).
When I execute my Migrate.cmd I get "No migrations found". Currently I am using FluentMigrator 3.1.0 and I was following this guide: https://www.codeproject.com/articles/1012802/fluent-migrator-for-database-migration. What do I miss?

**Comment by fubar-coder** [comment]
The migration class must be public.

I'm glad that you found out how to use the latest version. Just some comments:

1. You can use the `nuget.exe` tool (downloadable from [nuget.org](https://www.nuget.org/downloads) to install the console tool with `nuget.exe install FluentMigrator.Console`.
2. Always keep the `FluentMigrator.Console` package (version) in sync with the `FluentMigrator` packages referenced in your project.
3. There's also a quick start guide available from our documentation page: https://fluentmigrator.github.io/articles/quickstart.html
4. Your SQL Server connection string isn't correct. You need (IIRC) a `Server=` at the beginning of the connection string.

A new version 3.1.1 will be available soon with fixed dependencies for the `FluentMigrator.Console` package.
