### ISSUE TITLE
Error: Unable to load the driver. Attempted to load: Oracle.DataAccess.

### ISSUE THREAD

**Issue by CoffeToCodeConverter** [fluentmigrator/fluentmigrator#899]
My solution:
[Solution.zip](https://github.com/fluentmigrator/fluentmigrator/files/2092934/Solution.zip).

This error occurs when I execute Migrate.cmd. I tried to copy Oracle.DataAccess.dll to the FluentMigrator Folder from a nuget package which I included in the solution, but this file was the wrong one.

What am I missing?

**Comment by fubar-coder** [comment]
Did you install the Oracle client on your computer? Did you try the `OracleManaged` database processor?

**Comment by CoffeToCodeConverter** [comment]
I downloaded the instant Client (http://www.oracle.com/technetwork/topics/winx64soft-089540.html).

What do you mean by OracleManaged database processor? I couldn't figure out what you mean by this. 


Many apologies if this is a stupid Question. I am still unexperienced in Terms of databases.

**Comment by fubar-coder** [comment]
No problem. Good that you resolved the problem.
