### ISSUE TITLE
ObjectDisposedException when migrations applying for SQLite database. 

### ISSUE THREAD

**Issue by trueboroda** [fluentmigrator/fluentmigrator#901]
I make web api project on asp.net core 2.1. As database i use SQLite.  I did all as described in docs. And it s produce an Exception when migrations applying. Although the migrations were applied normally. The database and all tables were created successfully. The error occurs when checking connection closing.

net461
Asp.Net Core 2.1
FluentMigrator 3.1.1
System.Data.Sqlite.Core 1.1.0.108

 ```
 public static class MigratorServiceInitializer
    {
        public static IServiceCollection AddFluentMigrator(this IServiceCollection services, Assembly migrationsAssambly)
        {        
            var connectionString = "Data Source=messages_info2.db";
            return services.AddFluentMigratorCore()
                .ConfigureRunner(rb => rb       
                    .AddSQLite()
                    .WithGlobalConnectionString(connectionString)
                    .ScanIn(migrationsAssambly).For.Migrations());
        }
    }
```
 ```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc()
                .AddXmlSerializerFormatters();
            services // Add common FluentMigrator services
                .AddFluentMigrator(typeof(DataBaseManager).Assembly)
                // Enable logging to console in the FluentMigrator way
                .AddLogging(lb => lb.AddFluentMigratorConsole());
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {           
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseMvcWithDefaultRoute();
            //Migration applying
            using (var scope = app.ApplicationServices.CreateScope())
            {
                UpdateDatabase(scope.ServiceProvider);
            }            
        }

        private c void UpdateDatabase(IServiceProvider serviceProvider)
        {
            var runner = serviceProvider.GetRequiredService<IMigrationRunner>();
            runner.MigrateUp();
        }
      
    }

```

> ObjectDisposedException: Доступ к ликвидированному объекту невозможен.
>  Имя объекта: "SQLiteConnection".
> System.Data.SQLite.SQLiteConnection.CheckDisposed()
> System.Data.SQLite.SQLiteConnection.get_State()
> FluentMigrator.Runner.Processors.GenericProcessorBase.EnsureConnectionIsClosed()
> FluentMigrator.Runner.Processors.GenericProcessorBase.Dispose(bool isDisposing)
> Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
> SupportPortal.IntegrationApi.IncomingProxy.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in Startup.cs
> +
>             }            
> Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
> Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by fubar-coder** [comment]
This looks like `Dispose` was called twice on the SQLite processor. Congratulations, you found a bug 👍 . I'll publish a bug-fix release ASAP.

**Comment by fubar-coder** [comment]
I thought about this problem and it might be that there is a problem in your migration too. Can it be that you try to dispose the connection in - for example - an `Execute.WithConnection`?

**Comment by trueboroda** [comment]
I figured it out. The problem was that I used System.Data.Sqlite.Core 1.1.0.108 instead Microsoft.Data.Sqlite. I apologize. You can close this issue.
