### ISSUE TITLE
FluentMigrator.Runner should not depend on all database specific packages

### ISSUE THREAD

**Issue by diegofrata** [fluentmigrator/fluentmigrator#903]
I recently built a library that takes advantage of some stuff in the the FluentMigrator.Runner. Everytime I add this library as dependency to a project the entire Runner gets pulled in with all its dependencies. Basically every release has been a bit of nightmare, because there are so many dependencies.

From what I could see in the source code, there is no real need for it apart from convenience (like adding all databases to the ServiceCollection).

Would it be possible to remove it and have pushed somewhere else, let's say the different runners OR in a separate library that all concrete runners can implement?

**Comment by fubar-coder** [comment]
We did change this already for 4.0 (not released yet), but I don't see how we can make this change for 3.0 without breaking peoples code.

**Comment by diegofrata** [comment]
@fubar-coder in this case I will just wait for it! Is there a timeframe for 4.0?

**Comment by fubar-coder** [comment]
No, not yet. The changes I want for 4.0 are quite huge and I'm currently the only developer/maintainer for this project 😢 .

**Comment by worldbeater** [comment]
Looking forward to resolving this issue.
At least, an early alpha release would be highly appreciated.

**Comment by fubar-coder** [comment]
An alpha version is available on [MyGet](https://www.myget.org/gallery/fluent-migrator). The feed URL is https://www.myget.org/F/fluent-migrator/api/v3/index.json.

**Comment by worldbeater** [comment]
Thanks a lot! Sorry to miss that.

**Comment by lucaritossa** [comment]
> No, not yet. The changes I want for 4.0 are quite huge and I'm currently the only developer/maintainer for this project 😢 .

How could I help you? I'd like to contribute to make this product the best ever!!! 😄

**Comment by mattbrailsford** [comment]
Submitted a fresh PR #1600 to resolve this

**Comment by jzabroski** [comment]
Resolved via @mattbrailsford PR #1600
