### ISSUE TITLE
[Maintanance] BeforeFirst and AfterLast

### ISSUE THREAD

**Issue by alainsch** [fluentmigrator/fluentmigrator#905]
Hi,

feature request for a next version: needed 2 extra types of MigrationStage: .BeforeFirst and .AfterLast

.BeforeFirst = running before the first migration in this run is started. For a new database, this means before the VersionXXX migrations are executed to create the schema, version table, ...

.AfterLast = running always after the last migration in this run is started, even if this last migration is failed

At out company, DDL modifications are protected trough a trigger, so we need to disable this trigger before any DDL modification is done (therefore the .BeforeFirst migration) and always re-enable this trigger, even if a migration is failed (therefore the .AfterLast migration)

Thanks

**Comment by fubar-coder** [comment]
There is already something like `BeforeAll` and `AfterAll`, which should help with your trigger problem. The `BeforeFirst` to create the schema, version table, etc... wouldn't work, because the version table will already be created/queried/used by FluentMigrator.
