### ISSUE TITLE
Broken contributors link in ReadMe

### ISSUE THREAD

**Issue by PoLaKoSz** [fluentmigrator/fluentmigrator#912]
Hi!

I wanted to make a PR to fix this (change the link to [this](../graphs/contributors)) but than I found the `CONTRIBUTORS.md` so now I just wanted to point out this broken link.

> # Contributors
> A [long list](https://github.com/fluentmigrator/fluentmigrator/wiki/ContributorList) of everyone that has contributed to FluentMigrator. Thanks for all the Pull Requests!

**Comment by fubar-coder** [comment]
Thanks for pointing this out, fixed.
