### ISSUE TITLE
SqLite runner creates incorrect datatypes

### ISSUE THREAD

**Issue by schh** [fluentmigrator/fluentmigrator#915]
When i run the following migration:

`Create.Table(Database.AppSettings.TABLE_NAME)`

             .WithColumn(Database.AppSettings.VEHICLEID_COLUMN_NAME)
                    .AsString(Database.AppSettings.VEHICLEID_COLUMN_LENGTH)
                    .NotNullable()
                    .PrimaryKey(Database.AppSettings.PRIMARYKEY_NAME)
                .WithColumn(Database.AppSettings.DRIVERID_COLUMN_NAME)                
                    .AsString()
                    .NotNullable()
                .WithColumn(Database.AppSettings.WEIGHTSYSTEMFILEDIRECTORY_COLUMN_NAME)
                    .AsFixedLengthString(Database.AppSettings.WEIGHTSYSTEMFILEDIRECTORY_COLUMN_LENGTH)
                    .NotNullable()
                .WithColumn(Database.AppSettings.DATABASEINITIATED_COLUMN_NAME)
                    .AsBoolean()
                    .NotNullable();

all AsString() results in TEXT datatype and AsBoolean results in INT. I expected it to create the same datatypes as are created in SqlServer. That is bit for boolean and nvarchar for string.

Runner setup:

`new ServiceCollection()`

                .AddFluentMigratorCore()
                .ConfigureRunner(rb => rb
                    .AddSQLite()
                    .WithGlobalConnectionString(connectionString)
                    .ScanIn(migrationsAssembly).For.Migrations())
                .AddLogging(lb => lb.AddFluentMigratorConsole())
                .BuildServiceProvider();`

**Comment by fubar-coder** [comment]
SQLite only knows INTEGER, TEXT, REAL, BLOB, and NUMERIC. You can find an overview of the types in the [SQLite documentation](https://www.sqlite.org/datatype3.html). Mapping a boolean to an INTEGER vs NUMERIC is just a taste of preference.

**Comment by schh** [comment]
The reason i got confused is that we currently create our SQLite DB with EF.CodeFirst, and the resulting database shows nvarchar, bit etc.

I guess SQLite.CodeFirst uses [SQLite v2](https://www.sqlite.org/datatypes.html) and not V3 wich you linked.

Thanks

**Comment by fubar-coder** [comment]
SQLite v2 is the same in this regard. It maps types like `NVARCHAR(n)` to `TEXT` internally, so there is usually no point in emitting something else than `TEXT` for a text column.

**Comment by schh** [comment]
Ahh ok. Thanks for clearing that up. When i used AsCustom and set NVARCHAR(MAX), then the database did create that so i assumed something was wrong.
