### ISSUE TITLE
Apply migrations that are not present in the database.

### ISSUE THREAD

**Issue by nojaf** [fluentmigrator/fluentmigrator#928]
I was a little surprised that `dotnet-fm migrate -c sqlite up` will create a new database and applies all migrations found in the assembly.

Is there a way of specifying to run migrations that are not present in the database.
Some sort of smart `-t` option?

**Comment by fubar-coder** [comment]
No, that's not supported. The applied migrations are stored (by default) in the `VersionInfo` table. You may add all version numbers to this table that are already applied to avoid re-applying the migrations.
