### ISSUE TITLE
Example on use of LogFileFluentMigratorLoggerOptions

### ISSUE THREAD

**Issue by kasperbirkelund** [fluentmigrator/fluentmigrator#929]
Hi,

I'm setting up an asp.net core 2.1 solution and I want to run migrations during startup. Though I'd like to log all executed sql. Where do I find an example on this?
I'd expect to put this code somewhere: 

```c#
FluentMigratorLoggerOptions options = new LogFileFluentMigratorLoggerOptions()
{
  OutputFileName = "output.sql",
  OutputGoBetweenStatements = true,
  ShowElapsedTime = false,
  ShowSql = true
};
loggerFactory.AddFluentMigratorConsole(options);
```           

My code looks like this:

```c#
CreateWebHostBuilder(args)
  .Build()
  .CreateInitialData()
  .Run();
```

```c#
public static IWebHost CreateInitialData(this IWebHost host)
{
    using (IServiceScope scope = host.Services.CreateScope())
    {
      IMigrationRunner runner = scope.ServiceProvider.GetService<IMigrationRunner>();
      runner.MigrateUp();

      MyContext context = scope.ServiceProvider.GetService<MyContext>();
      DataSeeder.SeedData(context);
    }
  return host;
}
```

**Comment by fubar-coder** [comment]
You can find an example in [src/FluentMigrator.DotNet.Cli/Setup.cs](https://github.com/fluentmigrator/fluentmigrator/blob/d591e6dd2306fcc5ab79032e3fd6f19bafebfa32/src/FluentMigrator.DotNet.Cli/Setup.cs#L60-L68), Lines 60-68.

What happens here is that we add a new `ILoggerProvider` implementation and configure it using the `Microsoft.Extensions.Options`. Please take a look at [Microsoft.Extensions.Logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1) for further information.

You can used `SqlScriptFluentMigratorLoggerProvider` if you want to take a more direct approach.
