### ISSUE TITLE
Example of how to use logging with existing nlog logger

### ISSUE THREAD

**Issue by madben2000** [fluentmigrator/fluentmigrator#930]
In my application I have logging functionality implemented with nlog. How can fluentmigrator (runner) use this Logger instead of  the console logger which is added with .AddLogging(lb => lb.AddFluentMigratorConsole()). I didn't really find any helping examples.
Before v.3 we used TextWriterAnnouncer which now is obsolete.

**Comment by fubar-coder** [comment]
We now use Microsoft. Extensions.Logging and NLog can be integrated with [NLog. Extensions.Logging](https://github.com/NLog/NLog.Extensions.Logging).

**Comment by lucaritossa** [comment]
@madben2000 

- Install **Nlog.Extensions.Logging** via Nuget
- Now you should use the available extended method **AddNLog()**

Here it is:
```c#
.AddLogging(lb => lb.AddNLog())
```
