### ISSUE TITLE
Can't run migration.exe on MVC5

### ISSUE THREAD

**Issue by archer3cl** [fluentmigrator/fluentmigrator#935]
Running the following command
`migrate -conn "Data Source=:memory:" -provider sqlite -assembly "..\..\..\..\ProyectName.Data\bin\Debug\netstandard2.0\ProyectName.Data.dll" --verbose=true -p -profile "Debug"`

from route

`\path-to-my-proyect\packages\FluentMigrator.Console.3.1.3\net461\any`

returns the error

> Could not load file or assembly 'FluentNHibernate, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified

My project has
- asp mvc .net 4.7.1
- FluentNhibernate v2.1.2
- FluentMigrator v3.1.3
- FluentMigrator.Console v3.1.3

What could be the problem?

**Comment by schambers** [comment]
In an effort to organize existing issues and due to age, this ticket is being closed. If you feel like the issue still applies, please open a new ticket and we'll review for future addition. Thank you!
