### ISSUE TITLE
Can't use the Quickstart in Rider with .NET 4.6.1 and C# 6.0

### ISSUE THREAD

**Issue by RaphaelFourdrilis** [fluentmigrator/fluentmigrator#938]
Hi there!

I've been trying to use FluentMigrator in my solution for 2 days now and I can't seem to make it work with .NET 4.6.1 :/ It works out of the box in a dotnetcore projetc though.

Just adding FluentMigrator and FluentMigrator.Runner (both 3.1.3) breaks my compilation in an empty project (containing only the example from the Quickstart guide).

So, just after adding FluentMigrator 3.1.3 from NuGet, then copy pasting the Migration class (just that one,  not the services part) gives this warning:

```
     1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
```

Doing what's recommended by MS solves the warning but doesn't change anything to what comes after.
Then getting FluentMigrator.Runner(.SqlServer in my case, but it pulls everything anyway) and copy pasting the rest of the Quickstart (the part with the ServiceCollection) gives this result:

![image](https://user-images.githubusercontent.com/37067741/47294371-2c3e4f00-d60d-11e8-88c7-78ee31af43e3.png)

Aaaaand yeah, not sure what I did wrong there ...

I've tried pretty much everything I could think of, like removing duplicated references, with one pointing to net461 and the other poiting to netstandard2, tried using packages.config, tried *not* using packages.config ...
The only 'solution' I have is going dotnetcore, which I would love, but the rest of the company / solution can't just jump to dotnetcore instantly, and maintaining two different versions of the framework is something we'd like to avoid.

Does anyone have a clue as to what to do to use FluentMigrator with .NET 4.6.1 ?

**Comment by fubar-coder** [comment]
For .NET 4.6.1, you should use `System.Data.SQLite` instead of `Microsoft.Data.Sqlite`. You can ignore the warning about the `AutoGenerateBindingRedirects`.

**Comment by fubar-coder** [comment]
[TestFluentMigrator-net461.zip](https://github.com/fluentmigrator/fluentmigrator/files/2503244/TestFluentMigrator-net461.zip)

**Comment by RaphaelFourdrilis** [comment]
Hello,

Thanks for the answer, but I get the exact same output with your zip :/

**Comment by RaphaelFourdrilis** [comment]
Note that I obviously changed AddSQLLite to AddSqlServer to fit my needs. So I don't see how changing SQLLite's reference would solve anything :/

**Comment by fubar-coder** [comment]
Sorry, but I cannot reproduce this problem. I tried it with Rider 2018.2.3. The warning is still there, but can be ignored. The program builds and works as expected.

I also added the following line to the first `PropertyGroup` element:

```xml
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
```

Builds without warnings and no errors.

I tested everything on Windows. Maybe you're using Linux?
The last time I've seen all those errors above were when I used .NET Core 1.x or an outdated Visual Studio/NuGet that messed with the `obj\` directory. Removing all `bin\` and `obj\` directories and doing a clean rebuild usually fixed these problems.

**Comment by fubar-coder** [comment]
I just remembered that the same problem might occur when using an old mono version under Linux. HTH

**Comment by fubar-coder** [comment]
AFAIK you *need* the msbuild from VS 2017. It might be sufficient to install the VS 2017 build tools (not the full VS 2017). The build tools are available on this microsoft page: https://go.microsoft.com/fwlink/?linkid=840931 under the "Tools for Visual Studio 2017" category.

**Comment by RaphaelFourdrilis** [comment]
Alright, so, I don't know what went wrong and where, but I just re installed every VS 2015 and VS 2017 component I needed (default install + dotnetcore packages) and without changing anything to my configuration or code, it works fine now.

Again, thanks for taking the time to look into it and sorry for the false alarm. I guess it was some assembly override or some missing files

**Comment by fubar-coder** [comment]
Glad that you resolved it 👍

**Comment by RaphaelFourdrilis** [comment]
Ah, you beat me to it apparently x)

Yes I believe it was indeed the missing build tools from VS 2017.

Thanks again, I guess this is solved then.
Sorry for the inconvenience.

Cheers!
