### ISSUE TITLE
Drop composite index with auto-generated name

### ISSUE THREAD

**Issue by gfgw** [fluentmigrator/fluentmigrator#939]
We have created an index using:
```C#
this.Create
	.Index()
	.OnTable(TableName)
	.OnColumn(Column1).Unique()
	.OnColumn(Column2).Unique();
```

How can we drop this index? Simply replacing Create with Delete, and removing Unique doesn't work:
```C#
this.Delete
	.Index()
	.OnTable(TableName)
	.OnColumn(Column1)
	.OnColumn(Column2);
```

The compiler error message is
> 'IDeleteIndexOptionsSyntax' does not contain a definition for 'OnColumn' and no accessible extension method 'OnColumn' accepting a first argument of type 'IDeleteIndexOptionsSyntax' could be found (are you missing a using directive or an assembly reference?)

**Comment by fubar-coder** [comment]
You may want to use the `OnColumns` extension method.
