### ISSUE TITLE
Is fluentmigrator is supported with MySql 8.0?

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [fluentmigrator/fluentmigrator#951]
Is fluentmigrator is supported with MySql 8.0?

It's not written in this [link](https://fluentmigrator.github.io/articles/faq.html) wants to confirm.

**Comment by fubar-coder** [comment]
It is usable with MySQL 8.0 (even with the new ADO.NET provider), but the new features aren't directly supported which is why it's not in this list.
