### ISSUE TITLE
Update VersionInfoTable when running one specific migration

### ISSUE THREAD

**Issue by RaphaelFourdrilis** [fluentmigrator/fluentmigrator#962]
Hello,

I've been trying to run some specific migration by directly calling `runner.Up(migration)` because I need to be able to run them one by one when needed, not all of the assembly at once, but it doesn't seem to update the `VersionInfoTable`. Is this by design ? How could I achieve the same result without having to scan for all migrations in the assembly ?

Thanks,
Raphael

**Comment by fubar-coder** [comment]
Loading the version information table is seen as an expensive operation which should only be called when absolutely necessary (read: after all migrations have been appied/reverted), so, yes, it's by design.

**Comment by RaphaelFourdrilis** [comment]
Ok, that's what I suspected. But is there no way to force it to still have this behavior when I choose to ? I mean, I could just put one migration by assembly, but that doesn't seem like a good approach.

**Comment by fubar-coder** [comment]
You can do either do a `((MigrationRunner)runner).VersionLoader.LoadVersionInfo();` or you can implement an `IFilteringMigrationSource`.

**Comment by RaphaelFourdrilis** [comment]
Alright, I'll try those. Thanks for your time!
