### ISSUE TITLE
Update rows where a column's value is NULL

### ISSUE THREAD

**Issue by gfgw** [fluentmigrator/fluentmigrator#972]
How can I update rows in a migration, where a specific column has the value NULL? I am trying to change an int column from nullable to not nullable.

I tried `this.Update.Table(tableName).Set(new { Index = -1 }).Where(new { Index = null });`, but that results in a compiler error message `Cannot assign '<null>' to anonymous type property`. I can not find any documentation for the `Where` method.

I also tried `this.Alter.Table(tableName).AlterColumn(columnName).AsInt32().NotNullable().WithDefaultValue(-1).SetExistingRowsTo(-1);`, but that results in a runtime exception:

```System.Exception: 'An error occured executing the following sql:
ALTER TABLE [...] ALTER COLUMN [...] INT NOT NULL
The error was Cannot insert the value NULL into column '...', table '...'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
```
Also I would like to know if there is another way to specify the column name. We have the column names in const string variables, and would like to use the variable name in stead of the actual column name (just like with the table name).

**Comment by fubar-coder** [comment]
IIRC you can use `DbNull.Value` instead of `null`.

**Comment by FantasyOR** [comment]
Try this in migration file     
```c#
    public partial class SomeUpdate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "Delivery",
                keyColumn: "PartnerDeliveryService",
                keyValue: null, 
                column: "PartnerDeliveryService",
                value: "UPS",
                schema: "delivery");
         }
       ...
    }
```

**Comment by jzabroski** [comment]
@FantasyOR - I'm not familiar with the `MigrationBuilder` class. What version of FluentMigrator are you using?
