### ISSUE TITLE
AutoReversingMigration doesn't expose Delete expression root

### ISSUE THREAD

**Issue by CoskunSunali** [fluentmigrator/fluentmigrator#977]
Hi!

The [documentation](https://fluentmigrator.github.io/articles/migration/migration-auto-reversing.html) states that `Delete.ForeignKey` is supported when an auto reversing migration is used.

However, neither [AutoReversingMigration](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator/AutoReversingMigration.cs) not [MigrationBase](https://github.com/fluentmigrator/fluentmigrator/blob/master/src/FluentMigrator/MigrationBase.cs) exposes a `Delete` property of type `IDeleteExpressionRoot`.

This is my first time using FM, am I missing something?

**Comment by fubar-coder** [comment]
The documentation is wrong. `Delete` cannot be reversed automatically, because FluentMigrator doesn't maintain a full schema documentation of the database (unlike - for example - Entity Framework).

**Comment by CoskunSunali** [comment]
Thanks for the insight.
