### ISSUE TITLE
Migration Runner Preview Flag Doesn't Verify Physical Schema

### ISSUE THREAD

**Issue by evancummings** [fluentmigrator/fluentmigrator#979]
When running the migration runner with the preview flag the migration itself isn't verified to be 'good' and reports back a success code - pictured below is a test migration called 061_FAILURE and the left shows the migration with the preview flag and the right shows the actual run, which fails because the schema already exists:

![capture](https://user-images.githubusercontent.com/816653/50707951-a6894780-1030-11e9-8395-4d4d0bc561a5.PNG)

I am trying to run this with the preview flag to confirm schema is valid prior to a deploy task in a CI chain; is this not an appropriate use for the preview flag? If not, how can I verify migrations are valid prior to deployment to make sure that there won't be schema issues after application deployment?

**Comment by fubar-coder** [comment]
The "preview" flag just shows what FluentMigrator would send to the database, not if it would succeed. 

The CI chain should update a temporary database, not production database (of course). Even if it succeeds with the temporary database doesn't mean that it will always succeed with the production database. The only thing you could do is to show an error message and fix this problem.
