### ISSUE TITLE
Cannot find extension method AddFluentMigratorCore

### ISSUE THREAD

**Issue by maxmantz** [fluentmigrator/fluentmigrator#982]
Hi,

I'm trying out this library for my project, but can't get it set up. 

From the samples, I try 
```
var services = new ServiceCollection()
    .AddFluentMigratorCore();
```
My IntelliSense tells me this method is not available and I also couldn't find it in this repo.

I tried this with a console app using .netcoreapp2.2, .netcoreapp2.0, and .NETFramework4.6.1.
My installed nuget packages are
- FluentMigrator (3.1.3),
- FluentMigrator.Runner.SqlServer (3.1.3),
- FluentMigrator.Extensions.SqlServer (3.1.3)

I feel like I'm missing something very simple. Do you know what it could be?

**Comment by fubar-coder** [comment]
You need the package `FluentMigrator.Runner`.

**Comment by maxmantz** [comment]
My mistake for believing tht FluentMigrator.Runner.SqlServer contained FluentMigrator.Runner.
Thanks for the quick reply!

**Comment by Yaro77** [comment]
@maxmantz Same "problem" with PostgreSQL for me. It's really natural to think that FM.Runner.<Db> references FM.Runner.

**Comment by PauloDanielCarneiro** [comment]
I'm with this problem. I'm using postgres database and i put 
```
using FluentMigrator.Runner;
using FluentMigrator.Runner.Initialization;
using FluentMigrator;
```
In the configuration, I used
```
services.AddFluentMigratorCore()
                .ConfigureRunner(rb => rb
                    // Add SQLite support to FluentMigrator
                    .AddPostgres()
                    // Set the connection string
                    .WithGlobalConnectionString(Configuration.GetConnectionString("DefaultConnection"))
                    // Define the assemblies containing the migrations
                    .ScanIn(typeof(CreateApps).Assembly).For.Migrations()
                ).AddLogging(lb => lb
                    .AddFluentMigratorConsole());
```
In configure services. Anyone has an idea about it?

**Comment by fubar-coder** [comment]
Did you install the package `FluentMigrator.Runner`?

**Comment by PauloDanielCarneiro** [comment]
Yes.

**Comment by jzabroski** [comment]
Can you clear your obj and bin directories?

Dll location is driven by MSBuild targets written by Microsoft.

**Comment by rhegner** [comment]
In my scenario I'm only using one specific runner (MySql). So I don't necessarily want to add all the indirect dependencies for the other database types to my project.
It would be nicer to move `AddFluentMigratorCore` to the `FluentMigrator.Runner.Core` or to a new `FluentMigrator.Runner.DependencyInjection` package.

**Comment by mrclayman** [comment]
Why do I need to pull in runners for all database providers just to be able to use `AddFluentMigratorCore`?

**Comment by guangzhengli** [comment]
Same Issue with Postgres for me.  I think most projects only need one database runner dependency.

**Comment by jzabroski** [comment]
We're releasing a version that contains one runner dependency.

**Comment by gpgpublickey** [comment]
The last released version is still not exposing the extension method to avoid all the database dependencies, any ETA ? I guess this issue needs to remain open until get a real release solving the issue

**Comment by jzabroski** [comment]
Hi thank you for your patience. I had to take a break from working on FluentMigrator due to birth of my son but last weekend started working on it again.

**Comment by gpgpublickey** [comment]
> Hi thank you for your patience. I had to take a break from working on FluentMigrator due to birth of my son but last weekend started working on it again.

Congrats! enjoy your time during he is a baby, time passes and they become developers xD

**Comment by apeTim** [comment]
Any updates ??

**Comment by Sherif-Ahmed** [comment]
Any Updates ??

**Comment by jzabroski** [comment]
Update for what?

**Comment by apeTim** [comment]
> Update for what? This is a closed issue.

Update for "We're releasing a version that contains one runner dependency."

**Comment by jzabroski** [comment]
I think I am very close to tagging the 4.0.0 branch now off the master branch.  Just folded in a bunch of stuff from the develop branch including Snowflake support.
