### ISSUE TITLE
General maintenance migrations does not run when using tags

### ISSUE THREAD

**Issue by Jogge** [fluentmigrator/fluentmigrator#983]
We're using tagged migrations based on our customers. I would like to make a general maintenance migration that runs after all other migrations independently of customer (the maintenance migration has no tag). But the migration does not run and is filtered out by this line of code:

https://github.com/fluentmigrator/fluentmigrator/blob/e82aafa20e6dbe3cefa221303fe23cf8bf59fffd/src/FluentMigrator.Runner/MaintenanceLoader.cs#L73

Why is tag required for maintenance migrations, when normal migrations is not required to have tags to run?

**Comment by fubar-coder** [comment]
This was an oversight on my side. My suggestion is to implement your own `IMaintenanceLoader` as workaround. This issue will be fixed in a future release.

**Comment by fubar-coder** [comment]
Fixed by PR #984
