### ISSUE TITLE
Is it possible to find migrations with tags only

### ISSUE THREAD

**Issue by amersi90** [fluentmigrator/fluentmigrator#991]
Hi, I have some migrations without tag attribute. Recently I added two migrations with tags, and tried to run console runner with: ```Migration.exe .... --tag=...```and all migrations showed up in preview mode. 

Is it possible to only run migrations that have the tag specified in runner? Or do all migrations need to have some tag to be able to filter based on tags?

Thanks,

**Comment by fubar-coder** [comment]
All migrations without tags are always included. I guess what you want is to use [profiles](https://fluentmigrator.github.io/articles/profiles.html)?
