### ISSUE TITLE
Initialise at version - is this best practice, if so add to docs, if not help?

### ISSUE THREAD

**Issue by stuartwmurray** [fluentmigrator/fluentmigrator#994]
Hi Guys,

New user here.

I am wiring up a new project with Fluent Migrator and wanted to follow best practices on initializing a database. I understand that creating the database itself is out of the scope of this project. 

This software will be installed on more than one server and needs a self initialization function. The FluentMigrator syntax for migrations is very nice and I would like to use it.

My basic thought process is:
* Have an 'Initialize' migration that I run on a blank database
* Every time there is a schema update required
  * Add a new migration
  * Update the initialization migration to match
* When a new install is deployed: create the database, run the initialize migration, mark the database as having a version greater than the latest migration so that next time we run migrations they are skipped.

I couldn't find anything in the documentation that pointed me in the right direction so this is from poking through the source code. I am mostly looking for validation that this should work, or to be pointed in the right direction. If this could work it would be good to add something similar to the documentation as a 'best practice'.

```
var migrationLoader = this.ServiceProvider.GetRequiredService<IMigrationInformationLoader>();
var versionLoader = this.ServiceProvider.GetRequiredService<IVersionLoader>();

this.Runner.Up(new Migrations.Initialize());

// mark the current version as being after the last migration
long version = migrationLoader.LoadMigrations().Select(x => x.Key).DefaultIfEmpty(0).OrderByDescending(x => x).First();

versionLoader.UpdateVersionInfo(version, $"[[NEW DATABASE CREATED AT VERSION {version}]]");
```

Thanks,
Stuart

**Comment by fubar-coder** [comment]
TBH: It depends on your preference. I usually update the initialization script every "n" versions, when I get the feeling that initializing the database starts taking too much time.

I just do the following:

- Take an empty database
- Apply all migrations
- Create an SQL script (for schema **and** content)

That ensures that FluentMigrator can continue to work as expected without any quirks.
