### ISSUE TITLE
FileLoadException Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by cpistiner** [fluentmigrator/fluentmigrator#998]
I just updated (via NUGET) the version of FluentMigrator from 1.6.2 to 3.1.3 and well in my local environment I have no problems (beyond the necessary adaptations for the version change) when integrating the changes to the server I am receiving the message:

> Initialization method of Infrastructure.Test.Repositories.Persistence.RestoreDB.FixtureSetup class thrown the exception. System.IO.FileLoadException: System.IO.FileLoadException: Unable to load the file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version = 2.0.0.0, Culture = neutral, PublicKeyToken = adb9793829ddae60' or one of its dependencies. The assembly manifest definition does not match the reference to the assembly. (Exception from HRESULT: 0x80131040).

He tried the solution proposed here but it did not work.

What else can I try?

From already thank you very much.

**Comment by fubar-coder** [comment]
You need a binding redirect. I assume that you are using a .NET Framework application?

**Comment by cpistiner** [comment]
> You need a binding redirect. I assume that you are using a .NET Framework application?

I have binding redirect in config's files. 

Yes I'm using .NET Framework, sorry I did not clarify it before. It's an web application with ASPNET MVC.

**Comment by fubar-coder** [comment]
Ok. Do you have a binding redirect for `Microsoft.Extensions.DependencyInjection.Abstractions`?

**Comment by cpistiner** [comment]
Yes I have this:

`<dependentAssembly><assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" /><bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
</dependentAssembly>`

**Comment by fubar-coder** [comment]
Is this binding redirect in the app.config for the application that - when run - throws the exception above?

It seems that you use a test runner (as indicated by the following namespace: `Infrastructure.Test.Repositories.Persistence.RestoreDB.FixtureSetup`). Maybe that runner needs to have this binding redirect.

TBH: It's a mess with .NET Framework. Please think about using `Microsoft.Extensions.DependencyInjection.Abstractions` version 2.0.0 and removing this binding redirect.

**Comment by cpistiner** [comment]
@fubar-coder I understand that everything indicates that it is not a Fluent problem. Thank you very much for all the help given.

I will try these options. Close this issue.

Thanks again,
César
